### PR TITLE
Only send queue invalidation to AS when downlink gets scheduled

### LINKED ISSUE #313: NS warns that session is empty after OTAA join supporting class C
**Summary:** 

NS warns that session is empty after OTAA join.

**Steps to Reproduce:** 

1. Checkout current tip `03696ccb`
2. Start stack; `ttn-lw-stack start`
3. Create device; `ttn-lw-cli dev create test-app simulation --lorawan-version 1.0.2 --lorawan-phy-version 1.0.2-b --frequency-plan-id EU_863_870 --join-eui 4200000000000000 --dev-eui 4200000000000000 --root-keys.app-key.key 42000000000000000000000000000000 --supports-class-c` (note the last flag here – otherwise it doesn't happen)
4. Run the simulator (see https://github.com/johanstokking/mbed-os-lorawan-simulation)
5. Schedule downlink; `mosquitto_pub -h localhost -u test-app -P $APP_API_KEY -d -t 'v3/test-app/devices/simulation/down/push' -m '{"downlinks":[{"f_port":15,"frm_payload":"vu8="}]}'`

**What do you see now?**

NS warns;

```
  WARN Failed to update device in registry      delay=7.289ms device_class=CLASS_C device_uid=test-app.simulation error=error:pkg/networkserver:empty_session (session in empty) start_at=2019-03-19 10:43:49.328041 +0000 UTC
  WARN Task failed                              error=error:pkg/networkserver:empty_session (session in empty) invocation=2 task_id=process_downlink
```

And nothing happens.

Note that the `session` is in fact empty;

```
$ ttn-lw-cli dev get test-app simulation3 --session.dev-addr --supports-class-c
{
  "ids": {
    "device_id": "simulation3",
    "application_ids": {
      "application_id": "test-app"
    },
    "dev_eui": "4200000000000002",
    "join_eui": "4200000000000000"
  },
  "created_at": "2019-03-19T10:45:00.106Z",
  "updated_at": "2019-03-19T10:45:00.106Z",
  "network_server_address": "localhost:1884",
  "application_server_address": "localhost:1884",
  "supports_class_c": true,
  "session": {
    "dev_addr": "00000000",
    "keys": {

    },
    "started_at": "0001-01-01T00:00:00Z"
  }
}
```

**What do you want to see instead?**

Having a session there and working downlink.

@adriansmares confirms the issue by reproduction of the steps above.

**How do you propose to implement this?**

Not sure. The session may not be written back to the registry. No errors or warnings are reported about this though.

**What can you do yourself and what do you need help with?**

Review.

### LINKED ISSUE #416: Queue invalidation is sent when downlink scheduling fails
**Summary:** 

Queue invalidation is sent to Application Server even when the scheduling fails.

**Steps to Reproduce:** 

1. Schedule downlink
2. Let schedule fail (i.e. disconnect gateway, run out of duty-cycle, have conflicts, etc)

**What do you see now?**

AS still gets queue invalidation.

**What do you want to see instead?**

No queue invalidation when scheduling fails.

**How do you propose to implement this?**

Only send queue invalidation when there's a frame counter assigned, i.e. when scheduling succeeded.

**Can you do this yourself and submit a Pull Request?**

Yes, already done in #409

### PR DESCRIPTION
**Pull request by johanstokking**
**Summary:**

Closes #416 

**Changes:**

- NS only sends the queue invalidation to AS when downlink actually gets scheduled
- Extended logging

**Notes for Reviewers:**

- Except for https://github.com/TheThingsNetwork/lorawan-stack/commit/862f06fe69b26f8949f41df3700f6cbdd1a1f155, the changes are only related to extending debug logs
- I have reviewed @rvolosatovs commits already; please sanity check

### CODE REVIEW

File: pkg/gatewayserver/io/io.go [hunk 1]
```diff
@@ -333,6 +333,7 @@ func (c *Connection) SendDown(path *ttnpb.DownlinkPath, msg *ttnpb.DownlinkMessa
 			logger.WithFields(log.Fields(
 				"starts", em.Starts(),
 				"duration", em.Duration(),
+				"raw_payload", msg.RawPayload,
```
Comment (htdvisser) [inline pkg/gatewayserver/io/io.go]: Are you sure we want to log the entire raw payload?

File: pkg/networkserver/downlink.go [hunk 2]
```diff
@@ -142,10 +147,11 @@ func (ns *NetworkServer) generateDownlink(ctx context.Context, dev *ttnpb.EndDev
 	cmdBuf := make([]byte, 0, maxDownLen)
 	for _, cmd := range cmds {
 		var err error
+		logger.WithField("cid", cmd.CID).Debug("Adding MAC command to buffer...")
```
Comment (htdvisser) [inline pkg/networkserver/downlink.go]: This is going to generate multiple log messages for each LoRaWAN message. Are we sure we want this?

File: pkg/networkserver/grpc_gsns.go [hunk 3]
```diff
@@ -359,7 +358,15 @@ func (ns *NetworkServer) handleUplink(ctx context.Context, up *ttnpb.UplinkMessa
 	pld := up.Payload.GetMACPayload()
 
 	logger := log.FromContext(ctx).WithFields(log.Fields(
```
Comment (htdvisser) [inline pkg/networkserver/grpc_gsns.go]: Perhaps we should create a shared func for getting the log fields from a LoRaWAN payload, so that we have consistent log fields across GS/NS/AS.

File: pkg/networkserver/grpc_gsns.go [hunk 4]
```diff
@@ -437,23 +443,30 @@ func (ns *NetworkServer) handleUplink(ctx context.Context, up *ttnpb.UplinkMessa
...
-				WithField("unmarshaled", len(cmds)).
-				WithError(err).
-				Warn("Failed to unmarshal MAC commands")
+			logger.WithFields(log.Fields(
+				"bytes_left", r.Len(),
+				"mac_count", len(cmds),
+			)).WithError(err).Warn("Failed to unmarshal MAC command")
 			break
 		}
+		logger.WithField("cid", cmd.CID).Debug("Read MAC command")
```
Comment (htdvisser) [inline pkg/networkserver/grpc_gsns.go]: This is going to generate multiple log messages for each LoRaWAN message. Are we sure we want this?

File: pkg/networkserver/grpc_gsns.go [hunk 5]
```diff
@@ -437,23 +443,30 @@ func (ns *NetworkServer) handleUplink(ctx context.Context, up *ttnpb.UplinkMessa
...
 
+	logger.Debug("Waiting for deduplication window to close...")
 	select {
 	case <-ctx.Done():
 		return ctx.Err()
 	case <-ns.deduplicationDone(ctx, up):
 	}
 
 	up.RxMetadata = acc.Accumulated()
+	ctx = log.NewContextWithField(ctx, "metadata_count", len(up.RxMetadata))
```
Comment (htdvisser) [inline pkg/networkserver/grpc_gsns.go]: It's cheaper to add the field to the existing logger and then update the context, instead of updating the logger in the context and then getting it from the context.

**Comment by htdvisser** [comment]
@johanstokking can you comment a bit more on _how_ this closes #313? What the issue says about implementation (_"Not sure. The session may not be written back to the registry. No errors or warnings are reported about this though."_) doesn't seem to be related to the changes in this PR.

**Comment by johanstokking** [comment]
@htdvisser issue reference was wrong; fixed that: this closes #416 and #411 closes #313.

Will make logging imperative and see if all logs are necessary still. Note that these changes were actually requested by @rvolosatovs so will decide for him if this is needed.

I think we can be verbose with debug log level; we're not printing that in production, this is very helpful for seeing what is going on and why downlinks are triggered and what MAC commands are sent back and forth, and we do not have a lower log level than debug for this.

**Comment by htdvisser** [comment]
Ok, I'll see if we can replace these kind of debug logs with trace logs in #29
