### PR TITLE
Fix Authorization header decoding

### LINKED ISSUE #6170: Invalid base64 Authorization header causes the webhook form to not load
### Summary

It is possible to create a webhook with an `Authorization` header which causes the webhook settings form to crash.

### Steps to Reproduce

1. Create a webhook with a header with key `Authorization` and value `Basic bXl1c2VyOm15cGFzcw=`
  - This is the encoding of user `myuser` and password `mypass`, which encodes to `bXl1c2VyOm15cGFzcw==`, but I've accidentally deleted a padding `=`.
2. Try to load the webhook.

### Current Result

The form crashes while parsing the `Auhtorization` header, because `btoa` fails on `bXl1c2VyOm15cGFzcw=`.

### Expected Result

The form should load, without parsing the header contents, and a warning should be shown (that the contents of the `Authorization` header cannot be decoded).

### Relevant Logs

_No response_

### URL

_No response_

### Deployment

The Things Stack Enterprise (self-hosted)

### The Things Stack Version

3.25.1

### Client Name and Version

_No response_

### Other Information

_No response_

### Proposed Fix

_No response_

### Contributing

- [X] I can help by doing more research.
- [ ] I can help by implementing a fix after the proposal above is approved.
- [X] I can help by testing the fix before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

### PR DESCRIPTION
**Pull request by ryaplots**
#### Summary

Closes #6170 

#### Changes

- Fix encoding
- Show warning on incorrect encoding

#### Testing

Try to reproduce the error - should not happen.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/webui/console/components/webhook-form/index.js [hunk 1]
```diff
@@ -513,6 +520,16 @@ export default class WebhookForm extends Component {
               />
             </Form.FieldContainer>
           )}
+          {this.state.showDecodeError && (
+            <Notification
+              warning
+              content={
+                'Something went wrong and the contents of the Authorization header could not be decoded.'
```
Comment (kschiffer) [inline pkg/webui/console/components/webhook-form/index.js:533]:
```suggestion
                'The authorization header appears corrupted. Please check whether the encoding is correct or set a new value. Connection attempts with this header will likely fail.'
```

File: pkg/webui/console/components/webhook-form/index.js [hunk 2]
```diff
@@ -370,6 +372,11 @@ export default class WebhookForm extends Component {
     this.setState({ shouldShowCredentialsInput: event.target.checked })
   }
 
+  @bind
+  handleHeadersChange() {
+    this.setState({ showDecodeError: !hasNoEmptyEntry })
+  }
+
```
Comment (kschiffer) [inline pkg/webui/console/components/webhook-form/index.js:385]: Where is this used?

File: pkg/webui/console/components/webhook-form/index.js [hunk 3]
```diff
@@ -293,6 +293,7 @@ export default class WebhookForm extends Component {
       shouldShowCredentialsInput: Boolean(
         initialWebhookValue?.headers?.Authorization?.startsWith('Basic '),
       ),
+      showDecodeError: decodeValues(initialWebhookValue).headers?.Authorization === '',
```
Comment (kschiffer) [inline pkg/webui/console/components/webhook-form/index.js]:
```suggestion
      showDecodeError: decodeValues(initialWebhookValue).headers?.Authorization === null,
```
?

**Review by kschiffer — CHANGES_REQUESTED** [review]

File: pkg/webui/console/components/webhook-form/mapping.js [hunk 4]
```diff
@@ -85,12 +85,20 @@ export const decodeValues = backendValues => {
...
+        formValues._basic_auth_enabled = true
+        formValues._basic_auth_username = decodedCredentials.slice(
+          0,
+          decodedCredentials.indexOf(':'),
+        )
+        formValues._basic_auth_password = decodedCredentials.slice(
+          decodedCredentials.indexOf(':') + 1,
+        )
+      } catch (err) {
+        backendValues.headers.Authorization = null
```
Comment (adriansmares) [inline pkg/webui/console/components/webhook-form/mapping.js]: I think it would be better to leave the original contents intact (i.e.in `base64` format) if possible. The reason being that the user may still want to be able to see his old, perhaps wrong, payload.

File: pkg/webui/console/components/webhook-form/index.js (hunk 2 above)
Comment (ryaplots) [reply pkg/webui/console/components/webhook-form/index.js:385]: It is used [here](https://github.com/TheThingsNetwork/lorawan-stack/blob/a4897719221f849acccaa5f654e156e4faee7e24/pkg/webui/console/components/webhook-form/index.js#L541)

**Review by adriansmares — APPROVED** [review]
Logically looks good to me.

There are some repetitions (`decodeValues(initialWebhookValue)._headers.find(i => i.decodeError)?`, `decodedCredentials.indexOf(':')`, `formValues._headers.find(isBasicAuth)`) which maybe should become variables instead, but I leave the stylistical comments to the frontend team.

**Review by kschiffer — APPROVED** [review]
