### PR TITLE
Set device class to B/C on session confirmation

### LINKED ISSUE #313: NS warns that session is empty after OTAA join supporting class C
**Summary:** 

NS warns that session is empty after OTAA join.

**Steps to Reproduce:** 

1. Checkout current tip `03696ccb`
2. Start stack; `ttn-lw-stack start`
3. Create device; `ttn-lw-cli dev create test-app simulation --lorawan-version 1.0.2 --lorawan-phy-version 1.0.2-b --frequency-plan-id EU_863_870 --join-eui 4200000000000000 --dev-eui 4200000000000000 --root-keys.app-key.key 42000000000000000000000000000000 --supports-class-c` (note the last flag here – otherwise it doesn't happen)
4. Run the simulator (see https://github.com/johanstokking/mbed-os-lorawan-simulation)
5. Schedule downlink; `mosquitto_pub -h localhost -u test-app -P $APP_API_KEY -d -t 'v3/test-app/devices/simulation/down/push' -m '{"downlinks":[{"f_port":15,"frm_payload":"vu8="}]}'`

**What do you see now?**

NS warns;

```
  WARN Failed to update device in registry      delay=7.289ms device_class=CLASS_C device_uid=test-app.simulation error=error:pkg/networkserver:empty_session (session in empty) start_at=2019-03-19 10:43:49.328041 +0000 UTC
  WARN Task failed                              error=error:pkg/networkserver:empty_session (session in empty) invocation=2 task_id=process_downlink
```

And nothing happens.

Note that the `session` is in fact empty;

```
$ ttn-lw-cli dev get test-app simulation3 --session.dev-addr --supports-class-c
{
  "ids": {
    "device_id": "simulation3",
    "application_ids": {
      "application_id": "test-app"
    },
    "dev_eui": "4200000000000002",
    "join_eui": "4200000000000000"
  },
  "created_at": "2019-03-19T10:45:00.106Z",
  "updated_at": "2019-03-19T10:45:00.106Z",
  "network_server_address": "localhost:1884",
  "application_server_address": "localhost:1884",
  "supports_class_c": true,
  "session": {
    "dev_addr": "00000000",
    "keys": {

    },
    "started_at": "0001-01-01T00:00:00Z"
  }
}
```

**What do you want to see instead?**

Having a session there and working downlink.

@adriansmares confirms the issue by reproduction of the steps above.

**How do you propose to implement this?**

Not sure. The session may not be written back to the registry. No errors or warnings are reported about this though.

**What can you do yourself and what do you need help with?**

Review.

### LINKED ISSUE #404: Add downlink task when MAC state device class changes to C
**Summary:** 

Add downlink task automatically when MAC state device class changes to class C and there are application downlink items queued.

**Steps to Reproduce:** 

1. Activate device, `supports-class-c` is off
2. Queue some downlinks
3. Set `mac-state.device-class` to `CLASS_C`

**What do you see now?**

No downlink gets send at that point. The downlink tasks trigger when new downlink gets scheduled.

**What do you want to see instead?**

Downlink queue task starts immediately when class changes.

**How do you propose to implement this?**

When the device class changes and if there's downlink in the queue (or regardless of that), fire the downlink task.

**Can you do this yourself and submit a Pull Request?**

Yes

### PR DESCRIPTION
**Pull request by johanstokking**
**Summary:**

Closes #313 
Closes #404 

**Changes:**

- Do not set class B/C directly on join-accept; the device has to confirm the pending session via an uplink
- On uplink, set the desired device class

### CODE REVIEW

File: pkg/networkserver/grpc_deviceregistry.go [hunk 1]
```diff
@@ -58,11 +58,9 @@ func (ns *NetworkServer) Set(ctx context.Context, req *ttnpb.SetEndDeviceRequest
 	var addDownlinkTask bool
 	dev, err := ns.devices.SetByID(ctx, req.EndDevice.EndDeviceIdentifiers.ApplicationIdentifiers, req.EndDevice.EndDeviceIdentifiers.DeviceID, gets, func(dev *ttnpb.EndDevice) (*ttnpb.EndDevice, []string, error) {
 		if dev != nil {
-			addDownlinkTask = ttnpb.HasAnyField(req.FieldMask.Paths,
-				"mac_state.device_class",
-				"queued_application_downlinks",
-			) && req.EndDevice.MACState.DeviceClass != ttnpb.CLASS_A &&
-				(len(req.EndDevice.QueuedApplicationDownlinks) > 0 || !req.EndDevice.MACState.CurrentParameters.Equal(req.EndDevice.MACState.DesiredParameters))
+			addDownlinkTask = ttnpb.HasAnyField(req.FieldMask.Paths, "mac_state.device_class") &&
```
Comment (htdvisser) [inline pkg/networkserver/grpc_deviceregistry.go]: So we're creating a downlink task if the device class changes from A to something else AND there is existing downlink to send. Why do we no longer consider downlinks added to the queue by the current update (req)?

Comment (johanstokking) [reply pkg/networkserver/grpc_deviceregistry.go]: Because we don't allow setting `application_downlink_queue` through RPC, see also https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/ttnpb/field_mask_validation.go#L490-L561
