### PR TITLE
Broaden the IS password character limits, allow Unicode

### LINKED ISSUE #1223: "Special" password character set is non-extensive and opaque for the user
#### Summary

"Special" password character set is non-extensive and, worst of all, opaque for the user.

https://github.com/TheThingsNetwork/lorawan-stack/blob/7b6050dba6ca1bb546f90570c23402cb059ca0ba/pkg/identityserver/user_registry.go#L84

#### Steps to Reproduce

1. Go to any v3 deployment
2. Attempt to create an account with password 
```
mtMp`2mhbtytvsN?)`Zf(W/]
```

#### What do you see now?

`Should contain at least one special character` error and a major confusion

#### What do you want to see instead?

Successful creation of account or at least error message stating which characters stack expects to be present in the password as "special".

#### Environment

Any

#### How do you propose to implement this?

Either the "special" password character set should be extended, or the "special" character set should be defined clearly, such that users know, which characters we consider "special".

#### Can you do this yourself and submit a Pull Request?

yes

### PR DESCRIPTION
**Pull request by rvolosatovs**
#### Summary

Closes #1223 

#### Changes

- Broaden IS password character limits
- Support Unicode

#### Notes for Reviewers

It's a very small change, but I assigned both @johanstokking and @htdvisser to take look, since it's quite important that we agree on this.
Using unicode characters should not be a problem - it's 2019 already. This also gives a lot of freedom to our users, which I'm sure (at least) some will be happy about.

### CODE REVIEW

File: pkg/identityserver/user_registry.go [hunk 1]
```diff
@@ -77,11 +78,11 @@ func (is *IdentityServer) validatePasswordStrength(ctx context.Context, password
...
 	for _, r := range password {
 		switch {
-		case r >= 'A' && r <= 'Z':
+		case unicode.IsUpper(r):
 			uppercase++
-		case r >= '0' && r <= '9':
+		case unicode.IsDigit(r):
 			digits++
-		case r == '!' || r == '%' || r == '@' || r == '#' || r == '$' || r == '&' || r == '*':
+		case !unicode.IsLetter(r) && !unicode.IsNumber(r):
```
Comment (rvolosatovs) [inline pkg/identityserver/user_registry.go]: This includes category `Z`, separators(e.g. ` `). IMO it makes sense to count space etc. as special, by looking at https://github.com/TheThingsNetwork/lorawan-stack/issues/1223#issuecomment-524226731 seems that @htdvisser as well.

Comment (rvolosatovs) [reply pkg/identityserver/user_registry.go]: Another possiblity is to be more strict and count `S`, `P`, `M`, `Z` here, for example, but IMO the current solution is best.

File: pkg/identityserver/user_registry.go [hunk 2]
```diff
@@ -77,11 +78,11 @@ func (is *IdentityServer) validatePasswordStrength(ctx context.Context, password
 	var uppercase, digits, special int
 	for _, r := range password {
 		switch {
-		case r >= 'A' && r <= 'Z':
+		case unicode.IsUpper(r):
```
Comment (htdvisser) [inline pkg/identityserver/user_registry.go]: This is quite a significant change to our current definition of uppercase letters. Now it would also include letters like `Д` and `𝒬`, which IMO should be considered "special" in passwords.

File: pkg/identityserver/user_registry.go [hunk 3]
```diff
@@ -77,11 +78,11 @@ func (is *IdentityServer) validatePasswordStrength(ctx context.Context, password
...
 			uppercase++
-		case r >= '0' && r <= '9':
+		case unicode.IsDigit(r):
```
Comment (htdvisser) [inline pkg/identityserver/user_registry.go]: Same here, I'm not sure if we should consider `٦` a "digit" or a "special"

File: pkg/identityserver/user_registry.go (hunk 1 above)
Comment (htdvisser) [reply pkg/identityserver/user_registry.go]: We can also just catch all "other" `IsPrint` here.

**Comment by johanstokking** [comment]
Yeah I approved this because it's ultimately the responsibility of the user to come up with a strong password. Administrators set these rules to enforce making passwords hard to guess, and imo if people use their local language chars the same rules apply and things do not become easier to guess.

For simplicity, I would agree with @htdvisser proposal except for explicitly disallowing non-printables; https://github.com/TheThingsNetwork/lorawan-stack/issues/1223#issuecomment-524315248. But it's essentially the same as this, except that we broaden applying our rules to non-latin chars.

File: pkg/identityserver/user_registry.go (hunk 2 above)
Comment (rvolosatovs) [reply pkg/identityserver/user_registry.go]: Why so? Why would we not allow passwords in local languages?
I don't think we should force people to use latin alphabet in passwords, hence I think `Д`, `Ы`, `Ё` etc. are all perfectly valid uppercase characters.

File: pkg/identityserver/user_registry.go (hunk 3 above)
Comment (rvolosatovs) [reply pkg/identityserver/user_registry.go]: If it's "digit enough" for Unicode, it should be "digit enough" for us
