### PR TITLE
Synchronize GPS time via uplink token

### LINKED ISSUE #4823: UDP Gateway drops gps sync on tx event
#### Summary
When the scheduler sends a tx event for a gateway it attempts a time sync using the uplink token.

This clock sync sets the gateway time to nil and then stops class b downlinks until the next uplink.

For busy gateways this may not be evident as they may recieive another uplink before the RX1/RX2 time

#### Steps to Reproduce
1. Connect gateway with gps
2. Run a single node in class b mode

#### What do you see now?
Class B Downlinks fail with `no_gps_sync`

[gps-sync-dropout.txt](https://github.com/TheThingsNetwork/lorawan-stack/files/7473984/gps-sync-dropout.txt)

#### What do you want to see instead?
Absolute time sync stays set and class b traffic is successful

#### Environment

v3.16-dev (1c1a21dbc53d21e9e480dbbdff46aa0f3aa8eb47)

#### How do you propose to implement this?
Quick fix was to hold off a clock sync of the last sync was within 30 seconds. 

```diff
diff --git a/pkg/gatewayserver/scheduling/scheduler.go b/pkg/gatewayserver/scheduling/scheduler.go
index 4a044ccf6..bdf0023a8 100644
--- a/pkg/gatewayserver/scheduling/scheduler.go
+++ b/pkg/gatewayserver/scheduling/scheduler.go
@@ -254,7 +254,7 @@ func (s *Scheduler) syncWithUplinkToken(token *ttnpb.UplinkToken) bool {
        if token.GetServerTime().IsZero() || token.GetConcentratorTime() == 0 {
                return false
        }
-       if lastSync, ok := s.clock.SyncTime(); ok && lastSync.After(token.ServerTime) {
+       if lastSync, ok := s.clock.SyncTime(); ok && lastSync.Add(time.Second*30).After(token.ServerTime) {
                return false
        }
        s.clock.SyncWithGatewayConcentrator(token.Timestamp, token.ServerTime, ConcentratorTime(token.ConcentratorTime))
```

A more robust approach would be to observe the gateway time if it was set on the uplink and then not attempt another sync

#### How do you propose to test this?
Can test patches on existing hardware

#### Can you do this yourself and submit a Pull Request?
@johanstokking @KrishnaIyer @adriansmares?

...

### PR DESCRIPTION
**Pull request by adriansmares**
#### Summary

References https://github.com/TheThingsNetwork/lorawan-stack/issues/2798
Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/4823

#### Changes

- Remove `embed` and `nullable` from `GatewayAntennaIdentifiers` and `UplinkToken`
- Add the gateway absolute time (GPS based) to `ttnpb.UplinkToken`, and make synchronization take it into account
- The Basic Station frontend now uses the reported `GPSTime` in order to compute the gateway time at which an uplink has been received

#### Testing

Unit testing. Will also run a snapshot on `staging1`.

##### Regressions

- The Network Server changes are strictly about `nullable`/`embed`, and I expect that unit tests cover these.
- The Gateway Server changes about GPS time should be covered once again by existing unit tests, and some of the refactoring is based on deduplication (moving time related formulas to `time.go`).

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Review by johanstokking — APPROVED** [review]

File: pkg/gatewayserver/io/ws/lbslns/upstream.go [hunk 1]
```diff
@@ -214,25 +212,19 @@ func (req *JoinRequest) toUplinkMessage(ids ttnpb.GatewayIdentifiers, bandID str
...
-		Rssi:               req.RadioMetaData.UpInfo.RSSI,
-		ChannelRssi:        req.RadioMetaData.UpInfo.RSSI,
-		Snr:                req.RadioMetaData.UpInfo.SNR,
-		AntennaIndex:       uint32(req.RadioMetaData.UpInfo.RCtx),
+	timestamp := TimestampFromXTime(req.RadioMetaData.UpInfo.XTime)
+	tm := TimePtrFromGPSTime(req.UpInfo.GPSTime)
+	up.RxMetadata = []*ttnpb.RxMetadata{
+		{
+			GatewayIdentifiers: ids,
+			Time:               tm,
```
Comment (adriansmares) [inline pkg/gatewayserver/io/ws/lbslns/upstream.go:220]: Note that `up.Settings.Time` and `up.RxMetadata[0].Time` are now always `nil` if no `gpstime` is available, instead of being translations of `RxTime`. 

The reason is that `io.HandleUp` sees `up.Settings.Time` as a source of gateway GPS time, which is incorrect for `RxTime` - `RxTime` is not GPS-sourced, but rather the local system time at receive.

You may argue that 'it's almost as good' (since indeed, it has microsecond precision), but the following issue arises:

The presence of `up.Settings.Time` causes the GS to consider that it has successfully synchronized with gateway absolute time. This would allow something like a class B downlink to take place. The problem is that the transmission acknowledgement (the `dntxed`) does _not_ contain a `RxTime` - only a `gpstime`. This causes the GS to consider once again that the gateway absolute time synchronization has been lost, until the next uplink arrives.

**Comment by adriansmares** [comment]
Since this is closely related to timing and synchronization, I've added a small bugfix for `timesync`, and a scheduler RTT fix (the last 3 commits). I've also been testing this quite rigorously on `staging1`:

Here is a working PPS-based `timesync`:
```
2021-11-07 13:56:13.517 [SYN:INFO] First PPS pulse acquired
2021-11-07 13:56:13.517 [SYN:INFO] Obtained initial PPS offset (125139) - starting timesync with LNS
2021-11-07 13:56:13.532 [SYN:INFO] Time sync: ustime=0xD9E4EA2A utc=0x5D0333D471AD7 gpsOffset=0x0 ppsOffset=125139 syncQual=501
2021-11-07 13:56:13.532 [SYN:INFO] Time sync: MCU/SX130X#0 ustime=0xD9E4E752 xtime=0x88000000658487 pps_xtime=0x880000005D65C8
2021-11-07 13:56:13.533 [SYN:INFO] Time sync: Last PPS     ustime=0xD9E4E752 xtime=0x88000000658487 pps_ustime=0xD9DCC893 pps_xtime=0x880000005D65C8
2021-11-07 13:56:13.567 [SYN:INFO] Timesync with LNS: gpsOffset=0x4B0D4F4A741C0
2021-11-07 13:56:13.567 [SYN:INFO] Time sync: ustime=0xD9E570A2 utc=0x5D0333D47A14F gpsOffset=0x4B0D4F4A741C0 ppsOffset=125139 syncQual=501
2021-11-07 13:56:13.567 [SYN:INFO] Time sync: MCU/SX130X#0 ustime=0xD9E4E752 xtime=0x88000000658487 pps_xtime=0x880000005D65C8
2021-11-07 13:56:13.567 [SYN:INFO] Time sync: Last PPS     ustime=0xD9E4E752 xtime=0x88000000658487 pps_ustime=0xD9DCC893 pps_xtime=0x880000005D65C8
2021-11-07 13:56:13.567 [SYN:INFO] Time ref:  Last PPS     sys->UTC=13:56:13.000000  SX130X->GPS=13:56:31.000000  leaps=18s diff=0
```

And here is a working time transfer-based `timesync`:
```
2021-11-07 14:34:44.033 [SYN:INFO] Server time sync: xtime=0x75000011D68127 gpstime=0x4B0D57E664EEF ppsOffset=80312 gpsOffset=0x4B0D57E664EEF
2021-11-07 14:34:45.402 [SYN:INFO] Changed PPS offset: 80312 => 124796 (delta: 44484)
2021-11-07 14:34:51.431 [SYN:INFO] Time sync: ustime=0x1640D3A93 utc=0x5D033C76F6C97 gpsOffset=0x4B0D57EA357EF ppsOffset=124796 syncQual=264
2021-11-07 14:34:51.431 [SYN:INFO] Time sync: MCU/SX130X#0 ustime=0x163E20DBA xtime=0x750000121D6829 pps_xtime=0x75000012143A6F
2021-11-07 14:34:51.431 [SYN:INFO] Time sync: Last PPS     ustime=0x163E20DBA xtime=0x750000121D6829 pps_ustime=0x163D8E000 pps_xtime=0x75000012143A6F
2021-11-07 14:34:51.431 [SYN:INFO] Time ref:  Last PPS     sys->UTC=14:34:48.000004  SX130X->GPS=14:35:05.999343  leaps=18s diff=-661us
```

**Review by KrishnaIyer — APPROVED** [review]
LGTM

**Review by htdvisser — APPROVED** [review]
Nothing to add.
