### PR TITLE
util: Limit the CFList to 5 frequencies

### LINKED ISSUE #321: Invalid AS923 CFList
**Summary:** 

An error is encountered when a device configured for AS923 is using the V3 stack

**Steps to Reproduce:** 

1. Set the gateway configuration to use AS923
2. Set the device to use AS923
3. Register the gateway and device(OTAA) in a running v3 stack
4. Do a JOIN and you can see from the console log, errors

**What do you see now?**

Here is a link from Andrew Maggio: https://pastebin.com/srFPAR2f

And my stack trace:

```
stack_1      |   INFO Connected                                gateway_eui=3537323931006300 gateway_uid=amigo namespace=gatewayserver/io/udp
stack_1      | runtime error: index out of range
stack_1      | goroutine 526 [running]:
stack_1      | runtime/debug.Stack(0x1d2d660, 0xc00000c020, 0xc000c8ee10)
stack_1      | 	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/debug/stack.go:24 +0xa7
stack_1      | go.thethings.network/lorawan-stack/pkg/rpcserver.New.func1(0x177d980, 0x2b62740, 0xc000a42758, 0x1)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/rpcserver/rpcserver.go:133 +0x9d
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom(0x177d980, 0x2b62740, 0x1a69660, 0xc000c8efd0, 0x0)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/recovery/interceptors.go:47 +0x43
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1(0xc000544a68, 0xc000c90ea0)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/recovery/interceptors.go:21 +0x5f
stack_1      | panic(0x177d980, 0x2b62740)
stack_1      | 	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/panic.go:513 +0x1b9
stack_1      | go.thethings.network/lorawan-stack/pkg/encoding/lorawan.AppendCFList(0xc000efc1e0, 0xd, 0x21, 0x1, 0x0, 0x0, 0x0, 0xc000ede120, 0x2, 0x2, ...)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/encoding/lorawan/messages.go:242 +0x846
stack_1      | go.thethings.network/lorawan-stack/pkg/encoding/lorawan.AppendJoinAcceptPayload(0xc000efc1e0, 0x1, 0x21, 0x0, 0x0, 0x0, 0x5000000000010000, 0xf39b, 0x2, 0x500000000, ...)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/encoding/lorawan/messages.go:310 +0x1ee
stack_1      | go.thethings.network/lorawan-stack/pkg/joinserver.nsJsServer.HandleJoin.func2(0xc000ee86c0, 0xc000ee8480, 0xc0005782a0, 0x7, 0x7, 0xc000ee86c0, 0x0)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/joinserver/grpc_nsjs.go:184 +0x429
stack_1      | go.thethings.network/lorawan-stack/pkg/joinserver/redis.(*DeviceRegistry).SetByEUI.func1(0xc000231440, 0xc000c90628, 0x1)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/joinserver/redis/registry.go:128 +0x191
stack_1      | github.com/go-redis/redis.(*Client).Watch(0xc000850000, 0xc000c90638, 0xc000c90628, 0x1, 0x1, 0x40, 0x18c9a60)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/go-redis/redis@v6.15.1+incompatible/tx.go:45 +0x51
stack_1      | go.thethings.network/lorawan-stack/pkg/joinserver/redis.(*DeviceRegistry).SetByEUI(0xc000246838, 0x1d49100, 0xc000ee7080, 0x241501d07ed5b370, 0x6ee5000000008000, 0xc0005782a0, 0x7, 0x7, 0xc000eda740, 0x203000, ...)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/joinserver/redis/registry.go:106 +0x21f
stack_1      | go.thethings.network/lorawan-stack/pkg/joinserver.nsJsServer.HandleJoin(0xc000132460, 0x1d49100, 0xc000ee7080, 0xc0005781c0, 0xc000132460, 0xc000a44d80, 0xc00068a900)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/joinserver/grpc_nsjs.go:120 +0x678
stack_1      | go.thethings.network/lorawan-stack/pkg/ttnpb._NsJs_HandleJoin_Handler.func1(0x1d49100, 0xc000ee7080, 0x1934ea0, 0xc0005781c0, 0x177b2e0, 0xc000a56e00, 0x42b132, 0xc00068a930)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/ttnpb/joinserver.pb.go:1355 +0x86
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d49100, 0xc000ee7080, 0x1934ea0, 0xc0005781c0, 0x10034c3, 0x1d49100, 0xc000ee6de0, 0x0)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:31 +0x118
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1(0x1d49100, 0xc000ee7080, 0x1934ea0, 0xc0005781c0, 0xc000ee0560, 0xc000eec460, 0x0, 0x0, 0x0, 0x0)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/recovery/interceptors.go:25 +0x97
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d49100, 0xc000ee7080, 0x1934ea0, 0xc0005781c0, 0xc000ee7080, 0x104d11a, 0x181fbe0, 0xc000ee06a0)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:34 +0x9f
stack_1      | go.thethings.network/lorawan-stack/pkg/component.(*Component).ClusterAuthUnaryHook.func1.1(0x1d49100, 0xc000ee6de0, 0x1934ea0, 0xc0005781c0, 0x0, 0xc000224400, 0x0, 0x1)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/component/grpc.go:100 +0x85
stack_1      | go.thethings.network/lorawan-stack/pkg/rpcmiddleware/hooks.UnaryServerInterceptor.func1(0x1d49100, 0xc000ee6de0, 0x1934ea0, 0xc0005781c0, 0xc000ee0560, 0xc000eec460, 0x40a1b3, 0x1798f80, 0x1934ea0, 0x1)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/rpcmiddleware/hooks/hooks.go:132 +0x1ae
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d49100, 0xc000ee6de0, 0x1934ea0, 0xc0005781c0, 0xc0005781c0, 0x1, 0xffffffffffffffff, 0xc000a570b8)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:34 +0x9f
stack_1      | go.thethings.network/lorawan-stack/pkg/rpcmiddleware/validator.UnaryServerInterceptor.func1(0x1d49100, 0xc000ee6de0, 0x1934ea0, 0xc0005781c0, 0xc000ee0560, 0xc000eec460, 0x0, 0x0, 0x1, 0xc000ee7020)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/rpcmiddleware/validator/validator.go:106 +0x12d
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d49100, 0xc000ee6de0, 0x1934ea0, 0xc0005781c0, 0x3, 0x3, 0xc000eda6c0, 0xc000ee6f60)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:34 +0x9f
stack_1      | go.thethings.network/lorawan-stack/pkg/errors.UnaryServerInterceptor.func1(0x1d49100, 0xc000ee6de0, 0x1934ea0, 0xc0005781c0, 0xc000ee0560, 0xc000eec460, 0x186b980, 0x1d32300, 0x1d520a0, 0xc000a57478)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/errors/grpc.go:128 +0x64
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d49100, 0xc000ee6de0, 0x1934ea0, 0xc0005781c0, 0x0, 0x0, 0x0, 0x0)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:34 +0x9f
stack_1      | go.thethings.network/lorawan-stack/pkg/rpcmiddleware/sentry.UnaryServerInterceptor.func1(0x1d49100, 0xc000ee6de0, 0x1934ea0, 0xc0005781c0, 0xc000ee0560, 0xc000eec460, 0xc000ee6f30, 0x3, 0x3, 0x1d520a0)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/rpcmiddleware/sentry/sentry.go:105 +0x67
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d49100, 0xc000ee6de0, 0x1934ea0, 0xc0005781c0, 0x1f, 0xc000eec4b0, 0xc000eda600, 0x13)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:34 +0x9f
stack_1      | github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x1d49100, 0xc000ee6de0, 0x1934ea0, 0xc0005781c0, 0xc000ee0560, 0xc000eec460, 0xc000a575e8, 0x4807c6, 0x5c90ecc4, 0xc400e78)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0xad
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d49100, 0xc000ee6de0, 0x1934ea0, 0xc0005781c0, 0x19d5fed, 0x1f, 0x1d49100, 0xc000ee6de0)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:34 +0x9f
stack_1      | go.thethings.network/lorawan-stack/pkg/rpcmiddleware/rpclog.UnaryServerInterceptor.func1(0x1d49100, 0xc000ee6d20, 0x1934ea0, 0xc0005781c0, 0xc000ee0560, 0xc000eec460, 0x40c498, 0x10, 0xc000edc480, 0x1)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/rpcmiddleware/rpclog/server_interceptors.go:33 +0x108
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d49100, 0xc000ee6d20, 0x1934ea0, 0xc0005781c0, 0x1, 0x1d49100, 0xc000ee6d20, 0xffffffffffffffff)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:34 +0x9f
stack_1      | go.thethings.network/lorawan-stack/pkg/events.UnaryServerInterceptor(0x1d49100, 0xc000ee6c90, 0x1934ea0, 0xc0005781c0, 0xc000ee0560, 0xc000eec460, 0xc000f138d8, 0xc000ee6870, 0x19af57a, 0xa)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/events/correlation_interceptor.go:28 +0x1a4
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d49100, 0xc000ee6c90, 0x1934ea0, 0xc0005781c0, 0x0, 0x1, 0x2bbea00, 0xc000f138e8)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:34 +0x9f
stack_1      | go.thethings.network/lorawan-stack/pkg/rpcmiddleware.RequestIDUnaryServerInterceptor.func1(0x1d49100, 0xc000ee6c90, 0x1934ea0, 0xc0005781c0, 0xc000ee0560, 0xc000eec460, 0xc000224238, 0xc000224238, 0xc000ee6c30, 0xc000ede140)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/rpcmiddleware/request_id.go:40 +0x1c3
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d49100, 0xc000ee6c60, 0x1934ea0, 0xc0005781c0, 0xc000618ae0, 0x1d49100, 0xc000ee6c00, 0xc000544a78)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:34 +0x9f
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware/tags.UnaryServerInterceptor.func1(0x1d49100, 0xc000ee6c00, 0x1934ea0, 0xc0005781c0, 0xc000ee0560, 0xc000eec460, 0xc000615680, 0x1d49100, 0xc000ee6b70, 0x1d49100)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/tags/interceptors.go:21 +0x86
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d49100, 0xc000ee6c00, 0x1934ea0, 0xc0005781c0, 0x20, 0xc000f13a88, 0x40c498, 0x50)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:34 +0x9f
stack_1      | go.thethings.network/lorawan-stack/pkg/rpcmiddleware/fillcontext.UnaryServerInterceptor.func1(0x1d49100, 0xc000ee6b70, 0x1934ea0, 0xc0005781c0, 0xc000ee0560, 0xc000eec460, 0x2b884a0, 0x40c498, 0xc000f13b08, 0x40c498)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/rpcmiddleware/fillcontext/fillcontext.go:34 +0xb3
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x1d49100, 0xc000ee6b70, 0x1934ea0, 0xc0005781c0, 0xc000ee0560, 0xc000ee0580, 0x177cd80, 0x2bbef48, 0x1948840, 0xc000b2e100)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:39 +0x153
stack_1      | go.thethings.network/lorawan-stack/pkg/ttnpb._NsJs_HandleJoin_Handler(0x181bea0, 0xc000132460, 0x1d49100, 0xc000ee6b70, 0xc000eec410, 0xc000618900, 0x0, 0x0, 0xc000b5e5a0, 0x10a)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/ttnpb/joinserver.pb.go:1357 +0x158
stack_1      | google.golang.org/grpc.(*Server).processUnaryRPC(0xc00008b500, 0x1d59ae0, 0xc000a50180, 0xc000b2e100, 0xc0008601e0, 0x2b67560, 0x0, 0x0, 0x0)
stack_1      | 	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:966 +0x4a2
stack_1      | google.golang.org/grpc.(*Server).handleStream(0xc00008b500, 0x1d59ae0, 0xc000a50180, 0xc000b2e100, 0x0)
stack_1      | 	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:1245 +0xd61
stack_1      | google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00016e4d0, 0xc00008b500, 0x1d59ae0, 0xc000a50180, 0xc000b2e100)
stack_1      | 	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:685 +0x9f
stack_1      | created by google.golang.org/grpc.(*Server).serveStreams.func1
stack_1      | 	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:683 +0xa1
stack_1      |  ERROR Finished unary call                      duration=3.0952ms error=error:pkg/rpcserver:rpc_recovered (Internal Server Error) error_correlation_id=d3f3f7c0386f44dc8103e823f3e2d171 error_name=rpc_recovered error_namespace=pkg/rpcserver grpc_code=Internal grpc_method=HandleJoin grpc_service=ttn.lorawan.v3.NsJs namespace=grpc request_id=01D6B1SQKD0BFYJR9ZVKZ7V8GS
stack_1      |   WARN Finished unary call                      duration=4.3273ms error=rpc error: code = Internal desc = error:pkg/rpcserver:rpc_recovered (Internal Server Error) error_correlation_id=d3f3f7c0386f44dc8103e823f3e2d171 error_name=rpc_recovered error_namespace=pkg/rpcserver grpc_code=Internal grpc_method=HandleJoin grpc_service=ttn.lorawan.v3.NsJs namespace=grpc request_id=01D6B1SQKBKHJ8Z7DRGBVV0KF7
stack_1      |   WARN Join Server failed to handle join-request dev_addr=00509BF3 dev_eui=008000000000E56E device_uid=app1.dev1 error=error:pkg/rpcserver:rpc_recovered (Internal Server Error) grpc_method=HandleUplink grpc_service=ttn.lorawan.v3.GsNs join_eui=70B3D57ED0011524 namespace=grpc request_id=01D6B1SQKBKHJ8Z7DRGBVV0KF7
stack_1      |  ERROR Finished unary call                      duration=1.2007407s error=error:pkg/rpcserver:rpc_recovered (Internal Server Error) error_correlation_id=d3f3f7c0386f44dc8103e823f3e2d171 error_name=rpc_recovered error_namespace=pkg/rpcserver grpc_code=Internal grpc_method=HandleUplink grpc_service=ttn.lorawan.v3.GsNs namespace=grpc request_id=01D6B1SQKBKHJ8Z7DRGBVV0KF7
stack_1      |   WARN Finished unary call                      duration=1.2036421s error=rpc error: code = Internal desc = error:pkg/rpcserver:rpc_recovered (Internal Server Error) error_correlation_id=d3f3f7c0386f44dc8103e823f3e2d171 error_name=rpc_recovered error_namespace=pkg/rpcserver grpc_code=Internal grpc_method=HandleUplink grpc_service=ttn.lorawan.v3.GsNs namespace=grpc
stack_1      | runtime error: index out of range
stack_1      |  ERROR Finished unary call                      duration=3.2169ms error=error:pkg/rpcserver:rpc_recovered (Internal Server Error) error_correlation_id=3ea4fc1b21bb456686c36411460812b1 error_name=rpc_recovered error_namespace=pkg/rpcserver grpc_code=Internal grpc_method=HandleJoin grpc_service=ttn.lorawan.v3.NsJs namespace=grpc request_id=01D6B1SRS01BNDGH3W0X6XWT8E
stack_1      | goroutine 546 [running]:
stack_1      | runtime/debug.Stack(0x1d2d660, 0xc00000c020, 0xc000c8ee10)
stack_1      | 	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/debug/stack.go:24 +0xa7
stack_1      | go.thethings.network/lorawan-stack/pkg/rpcserver.New.func1(0x177d980, 0x2b62740, 0x1d2e440, 0xc000f24000)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/rpcserver/rpcserver.go:133 +0x9d
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom(0x177d980, 0x2b62740, 0x1a69660, 0xc000c8efd0, 0x0)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/recovery/interceptors.go:47 +0x43
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1(0xc000544a68, 0xc000c90ea0)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/recovery/interceptors.go:21 +0x5f
stack_1      | panic(0x177d980, 0x2b62740)
stack_1      | 	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/panic.go:513 +0x1b9
stack_1      | go.thethings.network/lorawan-stack/pkg/encoding/lorawan.AppendCFList(0xc0010b56e0, 0xd, 0x21, 0x1, 0x0, 0x0, 0x0, 0xc000edecc0, 0x2, 0x2, ...)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/encoding/lorawan/messages.go:242 +0x846
stack_1      | go.thethings.network/lorawan-stack/pkg/encoding/lorawan.AppendJoinAcceptPayload(0xc0010b56e0, 0x1, 0x21, 0x0, 0x0, 0x0, 0xca00000000010000, 0x8d92, 0x2, 0x500000000, ...)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/encoding/lorawan/messages.go:310 +0x1ee
stack_1      | go.thethings.network/lorawan-stack/pkg/joinserver.nsJsServer.HandleJoin.func2(0xc000f60480, 0xc000f60240, 0xc000579340, 0x7, 0x7, 0xc000f60480, 0x0)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/joinserver/grpc_nsjs.go:184 +0x429
stack_1      | go.thethings.network/lorawan-stack/pkg/joinserver/redis.(*DeviceRegistry).SetByEUI.func1(0xc000231e60, 0xc000c90628, 0x1)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/joinserver/redis/registry.go:128 +0x191
stack_1      | github.com/go-redis/redis.(*Client).Watch(0xc000850000, 0xc000c90638, 0xc000c90628, 0x1, 0x1, 0x40, 0x18c9a60)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/go-redis/redis@v6.15.1+incompatible/tx.go:45 +0x51
stack_1      | go.thethings.network/lorawan-stack/pkg/joinserver/redis.(*DeviceRegistry).SetByEUI(0xc000246838, 0x1d49100, 0xc000f339e0, 0x241501d07ed5b370, 0x6ee5000000008000, 0xc000579340, 0x7, 0x7, 0xc000edba80, 0x203000, ...)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/joinserver/redis/registry.go:106 +0x21f
stack_1      | go.thethings.network/lorawan-stack/pkg/joinserver.nsJsServer.HandleJoin(0xc000132460, 0x1d49100, 0xc000f339e0, 0xc0005792d0, 0xc000132460, 0xc00008be00, 0xc00068a940)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/joinserver/grpc_nsjs.go:120 +0x678
stack_1      | go.thethings.network/lorawan-stack/pkg/ttnpb._NsJs_HandleJoin_Handler.func1(0x1d49100, 0xc000f339e0, 0x1934ea0, 0xc0005792d0, 0x177b2e0, 0xc000a3ce00, 0x42b132, 0xc00068a970)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/ttnpb/joinserver.pb.go:1355 +0x86
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d49100, 0xc000f339e0, 0x1934ea0, 0xc0005792d0, 0x10034c3, 0x1d49100, 0xc000f33920, 0x0)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:31 +0x118
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1(0x1d49100, 0xc000f339e0, 0x1934ea0, 0xc0005792d0, 0xc000ee19a0, 0xc000eed6d0, 0x0, 0x0, 0x0, 0x0)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/recovery/interceptors.go:25 +0x97
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d49100, 0xc000f339e0, 0x1934ea0, 0xc0005792d0, 0xc000f339e0, 0x104d11a, 0x181fbe0, 0xc000ee1a60)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:34 +0x9f
stack_1      | go.thethings.network/lorawan-stack/pkg/component.(*Component).ClusterAuthUnaryHook.func1.1(0x1d49100, 0xc000f33920, 0x1934ea0, 0xc0005792d0, 0x0, 0xc000246b00, 0x0, 0x1)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/component/grpc.go:100 +0x85
stack_1      | go.thethings.network/lorawan-stack/pkg/rpcmiddleware/hooks.UnaryServerInterceptor.func1(0x1d49100, 0xc000f33920, 0x1934ea0, 0xc0005792d0, 0xc000ee19a0, 0xc000eed6d0, 0x40a1b3, 0x1798f80, 0x1934ea0, 0x1)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/rpcmiddleware/hooks/hooks.go:132 +0x1ae
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d49100, 0xc000f33920, 0x1934ea0, 0xc0005792d0, 0xc0005792d0, 0x1, 0xffffffffffffffff, 0xc000a3d0b8)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:34 +0x9f
stack_1      | go.thethings.network/lorawan-stack/pkg/rpcmiddleware/validator.UnaryServerInterceptor.func1(0x1d49100, 0xc000f33920, 0x1934ea0, 0xc0005792d0, 0xc000ee19a0, 0xc000eed6d0, 0xc000f33980, 0x3, 0x3, 0x0)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/rpcmiddleware/validator/validator.go:106 +0x12d
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d49100, 0xc000f33920, 0x1934ea0, 0xc0005792d0, 0x19d60ff, 0xe77738a25f326558, 0xc000eda6c0, 0x0)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:34 +0x9f
stack_1      | go.thethings.network/lorawan-stack/pkg/errors.UnaryServerInterceptor.func1(0x1d49100, 0xc000f33920, 0x1934ea0, 0xc0005792d0, 0xc000ee19a0, 0xc000eed6d0, 0x186b980, 0x1d32300, 0x1d520a0, 0xc000a3d478)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/errors/grpc.go:128 +0x64
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d49100, 0xc000f33920, 0x1934ea0, 0xc0005792d0, 0x0, 0x0, 0x0, 0x0)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:34 +0x9f
stack_1      | go.thethings.network/lorawan-stack/pkg/rpcmiddleware/sentry.UnaryServerInterceptor.func1(0x1d49100, 0xc000f33920, 0x1934ea0, 0xc0005792d0, 0xc000ee19a0, 0xc000eed6d0, 0xc000f33980, 0x3, 0x3, 0x1d520a0)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/rpcmiddleware/sentry/sentry.go:105 +0x67
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d49100, 0xc000f33920, 0x1934ea0, 0xc0005792d0, 0x1f, 0xc000eed720, 0xc000edb9c0, 0x13)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:34 +0x9f
stack_1      | github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x1d49100, 0xc000f33920, 0x1934ea0, 0xc0005792d0, 0xc000ee19a0, 0xc000eed6d0, 0xc000a3d5e8, 0x4807c6, 0x5c90ecc5, 0x18555948)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0xad
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d49100, 0xc000f33920, 0x1934ea0, 0xc0005792d0, 0x19d5fed, 0x1f, 0x1d49100, 0xc000f33920)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:34 +0x9f
stack_1      | go.thethings.network/lorawan-stack/pkg/rpcmiddleware/rpclog.UnaryServerInterceptor.func1(0x1d49100, 0xc000f33860, 0x1934ea0, 0xc0005792d0, 0xc000ee19a0, 0xc000eed6d0, 0x40c498, 0x10, 0xc000edd6a0, 0x1)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/rpcmiddleware/rpclog/server_interceptors.go:33 +0x108
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d49100, 0xc000f33860, 0x1934ea0, 0xc0005792d0, 0x1, 0x1d49100, 0xc000f33860, 0xffffffffffffffff)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:34 +0x9f
stack_1      | go.thethings.network/lorawan-stack/pkg/events.UnaryServerInterceptor(0x1d49100, 0xc000f337d0, 0x1934ea0, 0xc0005792d0, 0xc000ee19a0, 0xc000eed6d0, 0xc00067f8d8, 0xc000f333b0, 0x19af57a, 0xa)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/events/correlation_interceptor.go:28 +0x1a4
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d49100, 0xc000f337d0, 0x1934ea0, 0xc0005792d0, 0x0, 0x1, 0x2bbea00, 0xc00067f8e8)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:34 +0x9f
stack_1      | go.thethings.network/lorawan-stack/pkg/rpcmiddleware.RequestIDUnaryServerInterceptor.func1(0x1d49100, 0xc000f337d0, 0x1934ea0, 0xc0005792d0, 0xc000ee19a0, 0xc000eed6d0, 0xc000246b50, 0xc000246b50, 0xc000f33770, 0xc000edece0)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/rpcmiddleware/request_id.go:40 +0x1c3
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d49100, 0xc000f337a0, 0x1934ea0, 0xc0005792d0, 0xc000618ae0, 0x1d49100, 0xc000f33740, 0xc000544a78)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:34 +0x9f
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware/tags.UnaryServerInterceptor.func1(0x1d49100, 0xc000f33740, 0x1934ea0, 0xc0005792d0, 0xc000ee19a0, 0xc000eed6d0, 0xc000615680, 0x1d49100, 0xc000f336b0, 0x1d49100)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/tags/interceptors.go:21 +0x86
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1d49100, 0xc000f33740, 0x1934ea0, 0xc0005792d0, 0x20, 0xc00067fa88, 0x40c498, 0x50)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:34 +0x9f
stack_1      | go.thethings.network/lorawan-stack/pkg/rpcmiddleware/fillcontext.UnaryServerInterceptor.func1(0x1d49100, 0xc000f336b0, 0x1934ea0, 0xc0005792d0, 0xc000ee19a0, 0xc000eed6d0, 0x2b884a0, 0x40c498, 0xc00067fb08, 0x40c498)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/rpcmiddleware/fillcontext/fillcontext.go:34 +0xb3
stack_1      | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x1d49100, 0xc000f336b0, 0x1934ea0, 0xc0005792d0, 0xc000ee19a0, 0xc000ee19c0, 0x177cd80, 0x2bbef48, 0x1948840, 0xc000b2ff00)
stack_1      | 	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/chain.go:39 +0x153
stack_1      | go.thethings.network/lorawan-stack/pkg/ttnpb._NsJs_HandleJoin_Handler(0x181bea0, 0xc000132460, 0x1d49100, 0xc000f336b0, 0xc000eed680, 0xc000618900, 0x0, 0x0, 0xc000b5efc0, 0x10a)
stack_1      | 	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/ttnpb/joinserver.pb.go:1357 +0x158
stack_1      | google.golang.org/grpc.(*Server).processUnaryRPC(0xc00008b500, 0x1d59ae0, 0xc000a50180, 0xc000b2ff00, 0xc0008601e0, 0x2b67560, 0x0, 0x0, 0x0)
stack_1      | 	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:966 +0x4a2
stack_1      | google.golang.org/grpc.(*Server).handleStream(0xc00008b500, 0x1d59ae0, 0xc000a50180, 0xc000b2ff00, 0x0)
stack_1      | 	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:1245 +0xd61
stack_1      | google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00016e4d0, 0xc00008b500, 0x1d59ae0, 0xc000a50180, 0xc000b2ff00)
stack_1      | 	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:685 +0x9f
stack_1      | created by google.golang.org/grpc.(*Server).serveStreams.func1
stack_1      | 	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:683 +0xa1
stack_1      |   WARN Finished unary call                      duration=4.3417ms error=rpc error: code = Internal desc = error:pkg/rpcserver:rpc_recovered (Internal Server Error) error_correlation_id=3ea4fc1b21bb456686c36411460812b1 error_name=rpc_recovered error_namespace=pkg/rpcserver grpc_code=Internal grpc_method=HandleJoin grpc_service=ttn.lorawan.v3.NsJs namespace=grpc request_id=01D6B1SRRXRX37MZ1FBRJK9EP6
stack_1      |   WARN Join Server failed to handle join-request dev_addr=00CA928D dev_eui=008000000000E56E device_uid=app1.dev1 error=error:pkg/rpcserver:rpc_recovered (Internal Server Error) grpc_method=HandleUplink grpc_service=ttn.lorawan.v3.GsNs join_eui=70B3D57ED0011524 namespace=grpc request_id=01D6B1SRRXRX37MZ1FBRJK9EP6
stack_1      |  ERROR Finished unary call                      duration=1.2029228s error=error:pkg/rpcserver:rpc_recovered (Internal Server Error) error_correlation_id=3ea4fc1b21bb456686c36411460812b1 error_name=rpc_recovered error_namespace=pkg/rpcserver grpc_code=Internal grpc_method=HandleUplink grpc_service=ttn.lorawan.v3.GsNs namespace=grpc request_id=01D6B1SRRXRX37MZ1FBRJK9EP6
stack_1      |   WARN Finished unary call                      duration=1.2042475s error=rpc error: code = Internal desc = error:pkg/rpcserver:rpc_recovered (Internal Server Error) error_correlation_id=3ea4fc1b21bb456686c36411460812b1 error_name=rpc_recovered error_namespace=pkg/rpcserver grpc_code=Internal grpc_method=HandleUplink grpc_service=ttn.lorawan.v3.GsNs namespace=grpc
stack_1      |   WARN Downlink path expired                    gateway_eui=3537323931006300 gateway_uid=amigo namespace=gatewayserver/io/udp
stack_1      |   WARN Connection expired                       gateway_eui=3537323931006300 namespace=gatewayserver/io/udp
stack_1      |   INFO Disconnected                             gateway_eui=3537323931006300 gateway_uid=amigo namespace=gatewayserver/io/udp
```

**What do you want to see instead?**

...

**How do you propose to implement this?**

As suggessted by Hylke, the line pkg/encoding/lorawan/messages.go:242 fails because the message is falling under CFListType = 1 whereas AS923 should have CFListType = 0
...

**Environment:**

Mac OS, Chrome, mDot device running AS923 FW, Gateway running classic packet forwarder. 
...

**What can you do yourself and what do you need help with?**

...

### PR DESCRIPTION
**Pull request by adriansmares**
**Summary:**

Closes #321.

**Changes:**

- Use at most 5 frequencies in the `JoinRequest` CFList

**Notes for Reviewers:**

None.

**Release Notes: _(optional)_**

None.

### CODE REVIEW

File: pkg/frequencyplans/cflist.go [hunk 1]
```diff
@@ -47,6 +47,27 @@ func CFList(fp FrequencyPlan, version ttnpb.PHYVersion) *ttnpb.CFList {
...
+// device does not support CFLists. If the CFList contains more than 5 frequencies,
+// only the first 5 are used.
+func TrimmedCFList(fp FrequencyPlan, version ttnpb.PHYVersion) *ttnpb.CFList {
+	cfList := CFList(fp, version)
+	if cfList == nil {
+		return nil
+	}
+	switch cfList.Type {
+	case ttnpb.CFListType_FREQUENCIES:
+		{
```
Comment (johanstokking) [inline pkg/frequencyplans/cflist.go]: No need for these C-style braces

File: pkg/frequencyplans/cflist.go [hunk 2]
```diff
@@ -47,6 +47,27 @@ func CFList(fp FrequencyPlan, version ttnpb.PHYVersion) *ttnpb.CFList {
...
+// This function returns nil if the CFList could not be computed, or if the
+// device does not support CFLists. If the CFList contains more than 5 frequencies,
+// only the first 5 are used.
+func TrimmedCFList(fp FrequencyPlan, version ttnpb.PHYVersion) *ttnpb.CFList {
+	cfList := CFList(fp, version)
+	if cfList == nil {
+		return nil
+	}
+	switch cfList.Type {
+	case ttnpb.CFListType_FREQUENCIES:
```
Comment (johanstokking) [inline pkg/frequencyplans/cflist.go]: I think this is a perfect case for an if-statement, probably with early exit `return nil`

File: pkg/networkserver/grpc_gsns.go [hunk 3]
```diff
@@ -835,7 +835,7 @@ func (ns *NetworkServer) handleJoin(ctx context.Context, up *ttnpb.UplinkMessage
 	}
 
 	req := &ttnpb.JoinRequest{
-		CFList:             frequencyplans.CFList(*fp, dev.LoRaWANPHYVersion),
+		CFList:             frequencyplans.TrimmedCFList(*fp, dev.LoRaWANPHYVersion),
```
Comment (johanstokking) [inline pkg/networkserver/grpc_gsns.go]: I think you should;
1. Make sure that `resetMACState()` only selects the first five frequencies and puts those in `CurrentParameters`. Leave that function also responsible
2. Use the `CurrentParameters` here in a call to get the `CFList` based on that

Comment (htdvisser) [reply pkg/networkserver/grpc_gsns.go]: I don't agree with @johanstokking's second point. The `CurrentParameters` are a **result** of the CFList, so they shouldn't be input to the function that calculates the CFList.

Why do we need a separate `frequencyplans.TrimmedCFList` func? I don't think there is any "frequencies" CFList than one with max 5 entries, so why not just add this to the normal `CFList` func?

Comment (johanstokking) [reply pkg/networkserver/grpc_gsns.go]: My point is that the magic of selecting _N_ and _which_ N frequencies are part of CFList should be in one place. If we put that in `CFList`, fine, but then we should add an argument to `resetMACState()` saying which are current.

Note that we are talking about the current parameters of the _pending_ session. So that already assumes it's pending, not that it is already current. It will be current once the device confirms the session. So I stand by my point 2.

Comment (htdvisser) [reply pkg/networkserver/grpc_gsns.go]: I'm totally fine with applying CFList to the CurrentParameters of the PendingSession. I'm just saying that these CurrentParameters shouldn't be an input to the CFList calculation function.

File: pkg/frequencyplans/cflist.go [hunk 4]
```diff
@@ -79,5 +79,9 @@ fpChannelsList:
 		cfList.Freq = append(cfList.Freq, uint32(fpChannel.Frequency/100))
```
Comment (johanstokking) [inline pkg/frequencyplans/cflist.go]: Insert after

```go
if len(cfList.Freq) == 5 {
  break
}
```

File: pkg/frequencyplans/cflist.go [hunk 5]
```diff
@@ -77,6 +77,9 @@ fpChannelsList:
 			}
 		}
 		cfList.Freq = append(cfList.Freq, uint32(fpChannel.Frequency/100))
+		if len(cfList.Freq) > 5 {
```
Comment (johanstokking) [inline pkg/frequencyplans/cflist.go]: Please see my previous comment.

This is _after_ adding the fifth, we should break when we're _at_ 5.
