### PR TITLE
Display login error for unapproved users

### LINKED ISSUE #1660: Properly inform console users about unapproved accounts
#### Summary
The console needs to properly react to unapproved users by showing them a notification.

#### Why do we need this?
Currently, the user will just be redirected to the login page after trying to log in.

#### What is already there? What do you see now?
Login page.

#### What is missing? What do you want to see?
A notification about the user account being unapproved (together with some info on how it can be approved)

#### Environment
v.3.3.1 console

#### How do you propose to implement this?
During the login process on the console, after being redirected back from the oauth provider, a request to fetch the user will be made which will get a response like this:
```js
{"code":16,"message":"error:pkg/identityserver:user_requested (user account approval is pending)","details":[{"@type":"type.googleapis.com/ttn.lorawan.v3.ErrorDetails","namespace":"pkg/identityserver","name":"user_requested","message_format":"user account approval is pending","correlation_id":"1a5599e1b8804fd3ae8ab5b21adf108b","code":16}]}
```

We could fetch that message and make sure to redirect to the login page with a state object containing a respective info message. This message can then be displayed inside a notification on the login page.

#### Can you do this yourself and submit a Pull Request?
@pgalic

### PR DESCRIPTION
**Pull request by pgalic96**
#### Summary

This draft PR closes #1660 

#### Changes

- Expand reducer to have a login failure option

#### Notes for Reviewers

- @kschiffer this is a first solution, it's quite hacky since I haven't found the reason why the error gets mapped to response instead of getting caught. This wasn't the problem with other requests and the interceptor didn't interfere before. I understand it is more desired to find another approach but I think this is an isolated issue so it might be good enough.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, database and configuration, according to the stability commitments in `README.md`.
- [x] Testing: The changes are covered with unit tests. The changes are tested manually as well.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/webui/console/store/middleware/logics/init.js [hunk 1]
```diff
@@ -42,7 +42,11 @@ const consoleAppLogic = createRequestLogic({
       try {
         const userId = info.data.oauth_access_token.user_ids.user_id
         const result = await api.users.get(userId)
-        dispatch(user.getUserMeSuccess(result.data))
+        if (result.code === 7) {
```
Comment (htdvisser) [inline pkg/webui/console/store/middleware/logics/init.js]: Shouldn't you be looking at HTTP response codes?

Comment (pgalic96) [reply pkg/webui/console/store/middleware/logics/init.js]: Yep, indeed.
