### PR TITLE
Fix Basic Station CUPS Update-Info Request

### LINKED ISSUE #1313: CUPS update-info returning 403
#### Summary
Submitted as a result of a slack conversation. I've been trying to configure A Kerlink Wirnet Station using `basicstation` to connect to a v3 stack. When the station tries to call `update-info` it errors with 403.

#### Steps to Reproduce

1. Add a new gateway
2. Add a gateway api-key with rights `RIGHT_GATEWAY_ALL`
3. Update the gateway setting `gateway_server_address`, and the attributes `cups-credentials`, `lns-credentials` and `cups-uri`. Not setting these either leads to a different cause of the 403 on the backend or a 500 error.
4. Configure `basicstation` on the gateway setting the authorization header in `cups-boot.key`, the stack uri in `cups-boot.uri` and the stack cert in `cups-boot.trust`
5. Start `basicstation`

#### What do you see now?
The backend logs for the request (these repeat as the gateway retries):
```
INFO Finding gateway... gateway_eui=024B0BFFFE030465 method=POST namespace=web remote_addr=10.15.18.77:13480 request_id=01DKYFYC486KNB1N5QG2KAZT5A url=/update-info
DEBUG Run database query duration=3ms grpc_method=GetIdentifiersForEUI grpc_service=ttn.lorawan.v3.GatewayRegistry namespace=db query=SELECT id, created_at, updated_at, gateway_id, gateway_eui FROM "gateways" WHERE "gateways"."deleted_at" IS NULL AND ((gateway_eui = $1)) ORDER BY "gateways"."id" ASC LIMIT 1 request_id=01DKYFYC49S6RVY3TYXY5R4TSZ rows=1 source=gateway_store.go:117 values=[024B0BFFFE030465]
INFO Finished unary call duration=5.640867ms grpc_method=GetIdentifiersForEUI grpc_service=ttn.lorawan.v3.GatewayRegistry namespace=grpc request_id=01DKYFYC49S6RVY3TYXY5R4TSZ
DEBUG Getting gateway with request credentials gateway_eui=024B0BFFFE030465 gateway_id=gtw-0465 method=POST namespace=web remote_addr=10.15.18.77:13480 request_id=01DKYFYC486KNB1N5QG2KAZT5A url=/update-info
DEBUG Run database query duration=2ms grpc_method=Get grpc_service=ttn.lorawan.v3.GatewayRegistry namespace=db query=SELECT * FROM "api_keys" WHERE ("api_keys"."api_key_id" = $1) ORDER BY "api_keys"."id" ASC LIMIT 1 request_id=01DKYFYC4FMA3WQWDS5S18R5A2 rows=1 source=api_key_store.go:84 values=[AGXRPYACMA7LIPMJQKQ53NQDAC5PNT5HFAJEGXA]
DEBUG Run database query duration=2ms grpc_method=Get grpc_service=ttn.lorawan.v3.GatewayRegistry namespace=db query=SELECT id as uuid, gateway_id as friendly_id FROM "gateways" WHERE (id in ($1)) request_id=01DKYFYC4FMA3WQWDS5S18R5A2 rows=1 source=membership.go:73 values=[1176ce5f-7cca-4a7c-b87d-351f9b83efee]
DEBUG Run database query duration=3ms grpc_method=Get grpc_service=ttn.lorawan.v3.GatewayRegistry namespace=db query=SELECT id, created_at, updated_at, gateway_id, gateway_eui, auto_update, frequency_plan_id, gateway_server_address, update_channel, brand_id, model_id, hardware_version, firmware_version FROM "gateways" WHERE "gateways"."deleted_at" IS NULL AND ((gateway_id = $1) AND (gateway_eui = $2)) ORDER BY "gateways"."id" ASC LIMIT 1 request_id=01DKYFYC4FMA3WQWDS5S18R5A2 rows=1 source=gateway_store.go:117 values=[gtw-0465 024B0BFFFE030465]
DEBUG Run database query duration=3ms grpc_method=Get grpc_service=ttn.lorawan.v3.GatewayRegistry namespace=db query=SELECT * FROM "attributes" WHERE ("entity_id" IN ($1) AND "entity_type" = $2) ORDER BY "attributes"."id" ASC request_id=01DKYFYC4FMA3WQWDS5S18R5A2 rows=3 source=gateway_store.go:117 values=[1176ce5f-7cca-4a7c-b87d-351f9b83efee gateway]
INFO Finished unary call duration=41.106178ms grpc_method=Get grpc_service=ttn.lorawan.v3.GatewayRegistry namespace=grpc request_id=01DKYFYC4FMA3WQWDS5S18R5A2
DEBUG Run database query duration=3ms grpc_method=Update grpc_service=ttn.lorawan.v3.GatewayRegistry namespace=db query=SELECT id, created_at, updated_at, gateway_id, gateway_eui FROM "gateways" WHERE "gateways"."deleted_at" IS NULL AND ((gateway_id = $1) AND (gateway_eui = $2)) ORDER BY "gateways"."id" ASC LIMIT 1 request_id=01DKYFYC6C6FJ5X7DSM8GMXHBM rows=1 source=gateway_store.go:117 values=[gtw-0465 024B0BFFFE030465]
WARN Finished unary call duration=5.596499ms error=error:pkg/auth/rights:insufficient_gateway_rights (insufficient rights for gateway `gtw-0465`) error_correlation_id=1caf5682cad840429e4d0738e3ebfb95 error_name=insufficient_gateway_rights error_namespace=pkg/auth/rights grpc_code=PermissionDenied grpc_method=Update grpc_service=ttn.lorawan.v3.GatewayRegistry namespace=grpc request_id=01DKYFYC6C6FJ5X7DSM8GMXHBM
INFO Request handled duration=74.123482ms error=error:pkg/auth/rights:insufficient_gateway_rights (insufficient rights for gateway `gtw-0465`) method=POST namespace=web remote_addr=10.15.18.77:13480 request_id=01DKYFYC486KNB1N5QG2KAZT5A status=403 url=/update-info
```

#### What do you want to see instead?
`update-info` method should in these circumstances return OK

#### Environment
v3.1.1 of the stack. `basicstation` is running on a Kerlink Wirnet Station. I can provide more info if relevant.

#### Can you do this yourself and submit a Pull Request?
Maybe, but I would need help to work out what actually is going on first.

### PR DESCRIPTION
**Pull request by htdvisser**
#### Summary

This Pull Request refactors the `update-info` handler of Basic Station CUPS and improves its usability (at least a little bit).

Closes #1313

#### Changes

- Basically rewrote the entire flow. 
- Added defaults to GCS config.
- Updated docker-compose accordingly.
- Made it easier to test locally with `--tls.insecure-skip-verify`

#### Notes for Reviewers

Tested this with https://github.com/lorabasics/basicstation/commit/c29b8502f8c715daecec6666835da6e981dc820a

For testing, use the following commands to register the gateway, create the API keys and basicstation config files:

```sh
ttn-lw-cli login

gateway_eui=XXX
gateway_id=yyy
server_host=zzz

export TTN_LW_OAUTH_SERVER_ADDRESS=https://$server_host:8885/oauth
export TTN_LW_IDENTITY_SERVER_GRPC_ADDRESS=$server_host:8884
export TTN_LW_GATEWAY_SERVER_GRPC_ADDRESS=$server_host:8884

ttn-lw-cli gateways create $gateway_id --user-id admin --gateway-eui $gateway_eui --gateway-server-address wss://$server_host:8887

cups_api_key=$(ttn-lw-cli gateways api-keys create $gateway_id --name "CUPS Key" --right-gateway-info --right-gateway-settings-basic)
cups_credentials=$(echo $cups_api_key | jq -r '.key')

lns_api_key=$(ttn-lw-cli gateways api-keys create $gateway_id --name "LNS Key" --right-gateway-info --right-gateway-link)
lns_credentials=$(echo $lns_api_key | jq -r '.key')

ttn-lw-cli gateways update $gateway_id \
  --attributes="lns-credentials=$lns_credentials"

echo -n "https://$server_host:8885" > cups-boot.uri
cat cert.pem > cups-boot.trust
echo -n "" > cups-boot.crt
echo -ne "Authorization: Bearer $cups_credentials\r\n" > cups-boot.key
```

#### Release Notes

- Fixed implementation of CUPS update-info endpoint
- Added `--tls.insecure-skip-verify` to skip certificate chain verification (insecure; for development only).

### CODE REVIEW

File: pkg/basicstation/cups/update_info.go [hunk 1]
```diff
@@ -159,15 +157,57 @@ func (s *Server) UpdateInfo(c echo.Context) error {
...
+		if err != nil {
+			return err
+		}
 	}
-	gtw, err := s.getOrRegisterGateway(ctx, req, authHeader)
 	if err != nil {
 		return err
 	}
 
+	logger = logger.WithField("gateway_uid", unique.ID(ctx, gtw.GatewayIdentifiers))
```
Comment (KrishnaIyer) [inline pkg/basicstation/cups/update_info.go]: Nitpick: You can save locally and re-use the `uid` in `L217`.

File: pkg/basicstation/cups/update_info.go [hunk 2]
```diff
@@ -179,17 +219,37 @@ func (s *Server) UpdateInfo(c echo.Context) error {
 	}
 
 	res := UpdateInfoResponse{}
```
Comment (KrishnaIyer) [inline pkg/basicstation/cups/update_info.go]: Nitpick: IIRC, we preferred `var res UpdateInfoResponse{}`

File: pkg/basicstation/cups/update_info.go [hunk 3]
```diff
@@ -58,90 +60,86 @@ var (
...
-	"attributes",
-	"version_ids",
-	"gateway_server_address",
-	"auto_update",
-	"update_channel",
-	"frequency_plan_id",
-}}
+func getAuthHeader(ctx context.Context) string {
+	if md, ok := metadata.FromIncomingContext(ctx); ok {
+		if authorization := md.Get("authorization"); len(authorization) > 0 {
```
Comment (KrishnaIyer) [inline pkg/basicstation/cups/update_info.go]: `Authorization` right?

Comment (htdvisser) [reply pkg/basicstation/cups/update_info.go]: In gRPC (and http/2) headers are lowercase

File: pkg/basicstation/cups/update_info.go (hunk 2 above)
Comment (htdvisser) [reply pkg/basicstation/cups/update_info.go]: Nope.

Comment (KrishnaIyer) [reply pkg/basicstation/cups/update_info.go]: https://github.com/TheThingsNetwork/lorawan-stack/pull/1077#discussion_r309272681

Comment (KrishnaIyer) [reply pkg/basicstation/cups/update_info.go]: https://github.com/TheThingsNetwork/lorawan-stack/pull/1077#discussion_r309619724

Comment (htdvisser) [reply pkg/basicstation/cups/update_info.go]: 🤦‍♂ I'm always confused with this crap. We really should stop caring so much about equivalent code.

Comment (KrishnaIyer) [reply pkg/basicstation/cups/update_info.go]: I agree with you on this. I'm just repeating what was said to me in my PRs.

Comment (htdvisser) [reply pkg/basicstation/cups/update_info.go]: I'm also fine with making it all more consistent: https://github.com/TheThingsNetwork/lorawan-stack/compare/issue/1313-bs-cups...fix/var-declares

Maybe better to do that in a separate PR then...

Comment (KrishnaIyer) [reply pkg/basicstation/cups/update_info.go]: 👏
