### PR TITLE
Fix pending MAC state import

### LINKED ISSUE #5926: "store error" when importing devices
### Summary

I did an export on TTS-CE of all devices in an application. I then created a new application on a TTS Cloud instance, and imported the json file. 5 of the 22 devices did not import with a "store error".

```
{
  "code": 2,
  "message": "error:pkg/redis:store (store error)",
  "details": [
    {
      "@type": "type.googleapis.com/ttn.lorawan.v3.ErrorDetails",
      "namespace": "pkg/redis",
      "name": "store",
      "message_format": "store error",
      "correlation_id": "6beb7ce9b84e4d1cb21c66561c2d8e2a",
      "code": 2
    }
  ]
}
```

@adriansmares is aware of this, and I provided him with the json to reproduce.

### Steps to Reproduce

1. Use `ttn-lw-migrate` to export all devices in an application.
2. Import into TTS Cloud instance.
3. Sometimes you get this error.

### Current Result

store error

### Expected Result

Devices should import without any error.

### Relevant Logs

_No response_

### URL

_No response_

### Deployment

The Things Stack Cloud

### The Things Stack Version

3.22.2

### Client Name and Version

_No response_

### Other Information

_No response_

### Proposed Fix

_No response_

### Contributing

- [ ] I can help by doing more research.
- [ ] I can help by implementing a fix after the proposal above is approved.
- [ ] I can help by testing the fix before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

### PR DESCRIPTION
**Pull request by adriansmares**
#### Summary

Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/5926

#### Changes

- Fix the behavior of `FieldsWithoutPrefix`, which was causing the import `pending_mac_state` to fail with the very weird `invalid field c_state` error.

#### Testing

Local testing + JSON from the original issue.

##### Regressions

N/A. This was broken completely previously.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/ttnpb/fieldmask_utils.go [hunk 1]
```diff
@@ -267,7 +267,7 @@ func FieldsWithPrefix(prefix string, paths ...string) []string {
 func FieldsWithoutPrefix(prefix string, paths ...string) []string {
 	ret := make([]string, 0, len(paths))
 	for _, p := range paths {
-		if i := strings.Index(p, prefix+"."); i >= 0 {
+		if strings.HasPrefix(p, prefix+".") {
```
Comment (adriansmares) [inline pkg/ttnpb/fieldmask_utils.go:270]: The index of `mac_state.` in `pending_mac_state.` is greater or equal to 0 here, but this is obviously not the intended behavior. 

If we skip `len("mac_state.")` characters from `pending_mac_state`, we have the elusive `c_state` that appears in the error traces.

**Review by johanstokking — APPROVED** [review]
