### PR TITLE
Fix footer layout

### LINKED ISSUE #3851: Footer layout is broken in mobile screen sizes
#### Summary
Recent updates and extensions to the Console/Account App footer introduced some styling issues in mobile screen sizes:
image

#### Steps to Reproduce
1. Go to the Console
2. Enable mobile mode in dev tools
3. Scroll down to see the footer

#### What do you see now?
Jagged layout.

#### What do you want to see instead?
Unjagged layout.

#### How do you propose to implement this?
Use icon only layout for the support button. This will likely do the trick.

#### How do you propose to test this?
Manual testing.

#### Can you do this yourself and submit a Pull Request?
@asmulko

### PR DESCRIPTION
**Pull request by asmulko**
#### Summary

Closes #3851

#### Changes

- Hide support button text for small screen sizes

Before:
before

After:
a1
a2

#### Testing
- Manually tested

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/webui/components/footer/index.js [hunk 1]
```diff
@@ -31,6 +33,10 @@ const m = defineMessages({
   footer: "You are the network. Let's build this thing together.",
 })
 
+const isMinimized =
+  Math.max(document.documentElement.clientWidth || 0, window.innerWidth || 0) <=
```
Comment (bafonins) [inline pkg/webui/components/footer/index.js:37]: `window.innerWidth >= document.documentElement.clientWidth` will always be `true`.
`innerWidth` and `clientWidth` are equal when there is no scrollbar, or `innerWidth > clientWidth` because `clientWidth` accounts for scrollbar and computes only the visible part of the screen (document)

File: pkg/webui/components/footer/index.js [hunk 2]
```diff
@@ -31,6 +33,10 @@ const m = defineMessages({
   footer: "You are the network. Let's build this thing together.",
 })
 
+const isMinimized =
```
Comment (bafonins) [inline pkg/webui/components/footer/index.js]: We can make the `<Link />` component responsive by itself (say via `minimize` prop or something like this).
Another option would be render different version of `<Link.Anchor />` based on screen size via css media queries.

File: pkg/webui/components/footer/index.js [hunk 3]
```diff
@@ -51,12 +57,18 @@ const Footer = ({ className, documentationLink, links, supportLink, onlineStatus
...
+                ? sharedMessages.documentationAbbreviation
+                : sharedMessages.documentation
+            }
+          />
         </Link.Anchor>
       )}
       {supportLink && (
         <Button.AnchorLink
-          message={sharedMessages.getSupport}
+          message={isMinimized ? null : sharedMessages.getSupport}
```
Comment (kschiffer) [inline pkg/webui/components/footer/index.js]:
```suggestion
          message={isMinimized ? undefined : sharedMessages.getSupport}
```

This will make the button use the correct styling for only icon buttons.

File: pkg/webui/components/footer/index.js (hunk 2 above)
Comment (kschiffer) [reply pkg/webui/components/footer/index.js]: I agree. We usually don't do responsive styling programmatically, unless forced to. You can use a combination of attached classnames and rendering different elements and show/hide them based on screen size (using css media queries).

File: pkg/webui/components/footer/index.js [hunk 4]
```diff
@@ -51,12 +57,18 @@ const Footer = ({ className, documentationLink, links, supportLink, onlineStatus
       <span className={style.version}>v{process.env.VERSION}</span>
       {documentationLink && (
         <Link.Anchor className={style.documentation} secondary href={documentationLink} external>
-          <Message content={sharedMessages.documentation} />
+          <Message
+            content={
+              isMinimized && supportLink
+                ? sharedMessages.documentationAbbreviation
+                : sharedMessages.documentation
```
Comment (kschiffer) [inline pkg/webui/components/footer/index.js]: Let's not use an abbreviation here. It might work in English but might be troublesome in other languages. Let's instead hide the version tag. Use a tight media query for this so it only get's hidden when it becomes necessary.

**Review by kschiffer — CHANGES_REQUESTED** [review]

**Review by bafonins — CHANGES_REQUESTED** [review]
Please center the icon
Screenshot 2021-03-02 at 17 08 37
Screenshot 2021-03-02 at 17 08 45

File: pkg/webui/components/button/index.js [hunk 5]
```diff
@@ -69,7 +71,11 @@ const buttonChildren = props => {
   ) : (
     <>
       {icon ? <ButtonIcon icon={icon} type="left" /> : null}
-      {message ? <Message content={message} /> : null}
+      {message ? (
+        <span className={style.linkButtonMessage}>
```
Comment (bafonins) [inline pkg/webui/components/button/index.js]: Do you really need this wrapping `span`?

```js
<Message className={style.linkButtonMessage} content={message} />
```

should work just fine

**Review by bafonins — APPROVED** [review]

File: pkg/webui/components/button/index.js [hunk 6]
```diff
@@ -227,6 +229,8 @@ const commonPropTypes = {
   autoFocus: PropTypes.bool,
   /** A message to be evaluated and passed to the <button /> element. */
   title: PropTypes.message,
+  /** A flag specifying whether the button `message` should be responsive. */
+  minimize: PropTypes.bool,
```
Comment (kschiffer) [inline pkg/webui/components/button/index.js]:
```suggestion
  /** A flag specifying whether the button `message` should be responsive. */
  responsiveLabel: PropTypes.bool,
```

**Review by kschiffer — APPROVED** [review]
