### PR TITLE
Fix application uplinks queue memory usage

### LINKED ISSUE #2908: Per-application uplink queue buffer size
#### Summary

Use the configured buffer size as a max cutoff point, but trim Redis streams to only store non-processed uplinks.
Note, we have a stream per-application
Refs #2904 

#### Why do we need this?

To minimize memory usage for things we don't need to store

#### What is already there? What do you see now?

Currently all applications use the same configurable constant uplink queue buffer size

#### What is missing? What do you want to see?

Perhaps a more reasonable approach would actually be to have an absolute cap on this and dynamically adjust it at runtime.

#### Environment

production

#### How do you propose to implement this?

 maintain the amount of enqueued uplinks and amount of processed uplinks and set stream size to `min(bufferSize, enqueued-processed)` or simply delete the processed entries, but I'm not sure of what the implications of this are on performance - we need to research and profile this. Redis streams are an append-only data structure - so if e.g. the cap is 20k, then we would store last 20k uplinks per application regardless of whether they are processed or not and that's not ideal.

#### How do you propose to test this?

integration testing

#### Can you do this yourself and submit a Pull Request?

yes

### PR DESCRIPTION
**Pull request by rvolosatovs**
#### Summary

Closes #2908

#### Changes

- Delete processed application uplinks from queues
- Categorize application uplink streams, store at most 1 invalidation and store join-accepts separately. Thanks @adrian for the suggestion.
- ~Read at most 1 uplink from queue - this ensures maximum fail-safety and minimizes allocations in NS.~ Store the last invalidation FCnt per-device UID and avoid sending invalidations with FCnt lower than that value

#### Testing

Unit testing, test with a class c device

##### Regressions

From https://redis.io/commands/xdel:
> Eventually if all the entries in a macro-node are marked as deleted, the whole node is destroyed and the memory reclaimed. This means that if you delete a large amount of entries from a stream, for instance more than 50% of the entries appended to the stream, the memory usage per entry may increment, since what happens is that the stream will start to be fragmented. However the stream performances will remain the same.

The memory usage may slightly increase for a while, but I believe it will fix our issues after that

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/networkserver/redis/application_uplink_queue.go [hunk 1]
```diff
@@ -61,9 +69,26 @@ func (q *ApplicationUplinkQueue) Add(ctx context.Context, ups ...*ttnpb.Applicat
...
 
+		var (
+			streamID             string
+			maxLen, maxLenApprox int64
+		)
+		switch up.Up.(type) {
+		case *ttnpb.ApplicationUp_JoinAccept:
+			streamID = q.uidJoinAcceptKey(uid)
+			maxLenApprox = q.maxLen
+		case *ttnpb.ApplicationUp_DownlinkQueueInvalidated:
```
Comment (adriansmares) [inline pkg/networkserver/redis/application_uplink_queue.go:77]: I don't think this is ok. We cannot coalesce this per application, since we may have multiple devices in the same app.  We'll still have to keep the limit here, but that's fine since we now `XDEL`.

File: pkg/networkserver/redis/application_uplink_queue.go [hunk 2]
```diff
@@ -61,9 +69,26 @@ func (q *ApplicationUplinkQueue) Add(ctx context.Context, ups ...*ttnpb.Applicat
...
+		default:
+			streamID = q.uidGenericUplinkKey(uid)
+			maxLenApprox = q.maxLen
+		}
+
 		if err = q.redis.XAdd(&redis.XAddArgs{
-			Stream:       q.uidUplinkKey(uid),
-			MaxLenApprox: q.maxLen,
+			Stream:       streamID,
+			MaxLen:       maxLen,
```
Comment (adriansmares) [inline pkg/networkserver/redis/application_uplink_queue.go]: Is it valid to specify both ? As far as I know the command syntax is to add `~` when you want to approximate, so how would specifying both work ?

File: pkg/networkserver/redis/application_uplink_queue.go (hunk 1 above)
Comment (rvolosatovs) [reply pkg/networkserver/redis/application_uplink_queue.go:77]: Ah yes indeed, good point!

File: pkg/networkserver/redis/application_uplink_queue.go (hunk 2 above)
Comment (rvolosatovs) [reply pkg/networkserver/redis/application_uplink_queue.go]: One of them is always zero (a.k.a unspecified in Go semantics)

**Review by johanstokking — APPROVED** [review]

**Comment by johanstokking** [comment]
Please wait for @adriansmares

**Review by adriansmares — APPROVED** [review]
