### PR TITLE
CLI create user config dir if missing

### LINKED ISSUE #2355: Snap generating config file fails because of missing directory.
#### Summary

`ttn-lw-cli use <host> --user`  fails when CLI is installed using snap.

#### Steps to Reproduce

1. `sudo snap install ttn-lw-stack`
2. `ttn-lw-stack.ttn-lw-cli use localhost --user`

#### What do you see now?

```
 $ ttn-lw-stack.ttn-lw-cli use localhost --user
error:cmd/ttn-lw-cli/commands:fail_write (failed to write `HOME/snap/ttn-lw-stack/181/.config/.ttn-lw-cli.yml`)
    file=HOME/snap/ttn-lw-stack/181/.config/.ttn-lw-cli.yml
--- open HOME/snap/ttn-lw-stack/181/.config/.ttn-lw-cli.yml: no such file or directory
```

This happens because there is no directory `.config` directory inside the snap folder. If you create the directory by hand then it works.

#### What do you want to see instead?

The command to succeed (somehow)

#### Environment

3.7.0

#### How do you propose to implement this?

Two ideas:

- Create the destination directory if it does not exist already (not in favor of this one)
- When running in snap, add an extra default config file path `$SNAP_USER_COMMON` (which would be `HOME/snap/ttn-lw-stack/common`). Also, write configuration file there instead of the user config dir, which changes in every revision.

#### Can you do this yourself and submit a Pull Request?

yes, but let's discuss what's best first @htdvisser, @rvolosatovs

### PR DESCRIPTION
**Pull request by neoaggelos**
#### Summary

Closes #2355 

#### Changes

- Create user config directory if it does not exist, so that the config file generation does not fail.

#### Notes for Reviewers

Do we need a flag for disable this? e.g. `--no-make-dirs`

#### Checklist

- [X] Scope: The referenced issue is addressed, there are no unrelated changes.
- [X] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md`. The target branch is set to `master` if the changes are fully compatible with existing API, database, configuration and CLI.
- [X] Testing: The changes are covered with unit tests. The changes are tested manually as well.
- [X] Documentation: Relevant documentation is added or updated.
- [X] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [X] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: cmd/ttn-lw-cli/commands/use.go [hunk 1]
```diff
@@ -78,6 +78,12 @@ var (
 					if err != nil {
 						return "", err
 					}
+					if _, err := os.Stat(dir); os.IsNotExist(err) {
+						if err = os.MkdirAll(dir, 0775); err != nil {
```
Comment (htdvisser) [inline cmd/ttn-lw-cli/commands/use.go:82]: Isn't 775 a bit too open? 755 would be sufficient, right?

File: cmd/ttn-lw-cli/commands/use.go [hunk 2]
```diff
@@ -78,6 +78,12 @@ var (
...
+							return "", err
+						}
+						logger.Infof("Created missing directory %s", dir)
+					}
```
Comment (rvolosatovs) [inline cmd/ttn-lw-cli/commands/use.go:86]: Let's just keep it simple:
```suggestion
					if err = os.MkdirAll(dir, 0775); err != nil {
						return "", err
					}
```

From https://golang.org/pkg/os/#MkdirAll
> If path is already a directory, MkdirAll does nothing and returns nil.
