### PR TITLE
Fix DeviceTimeAns timestamp not corresponding to the specification

### LINKED ISSUE #5586: DeviceTimeAns timestamp is not corresponding to the specification
### Summary

References https://github.com/TheThingsNetwork/lorawan-stack/issues/2471
References https://github.com/TheThingsNetwork/lorawan-stack/pull/2478
References https://github.com/TheThingsNetwork/lorawan-stack/issues/5585

The Network Server should not use the Network Server receive time as a response to `DeviceTimeReq`, but instead the timestamp of the end of the transmission.

### Current Situation

The Network Server received timestamp is used:

https://github.com/TheThingsNetwork/lorawan-stack/blob/70d88dd86a9b17bf8faf1bbea6961d6c5d3f2ae7/pkg/networkserver/mac/device_time.go#L34-L43

The standard is both misleading and clear regarding this in both the 1.0.3 and 1.0.4 specification:
image

I think that https://github.com/TheThingsNetwork/lorawan-stack/issues/2471 is caused by the phrasing of 'current Network time', but the below sentence (GPS time at the end of the transmission) should be hopefully clearer.

### Why do we need this? Who uses it, and when?

We need this for proper class B support.

### Proposed Implementation

This requires https://github.com/TheThingsNetwork/lorawan-stack/issues/5585 first.

I think we need the following fallback system:
1. In the presence of a `settings.gps_time` field, use that.
2. If not found, walk through the `rx_metadata` slice and use the first `gps_time` found.
3. If not found, use the Network Server receive time.

I think that option 2 can become more sophisticated later on, but for now this should suffice.

cc @johanstokking 

Edit:
Also https://github.com/TheThingsNetwork/lorawan-stack/pull/2478/files#diff-9ba913e113eb0e0a51b8c6b091c237d7af5d797e29720b3fea84410ece5a99c5L666-L671 should be reverted, as the handler should run after deduplication.

### Contributing

- [X] I can help by doing more research.
- [X] I can help by implementing the feature after the proposal above is approved.
- [X] I can help by testing the feature before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

### PR DESCRIPTION
**Pull request by happyRip**
#### Summary

Closes #5586 

#### Changes

- Improved [HandleDeviceTimeReq](https://github.com/TheThingsNetwork/lorawan-stack/blob/70d88dd86a9b17bf8faf1bbea6961d6c5d3f2ae7/pkg/networkserver/mac/device_time.go#L34-L43) timestamp
- Reverted the change that made the MAC handler run before the deduplication occurred

#### Testing

- Added test cases regarding the improvement

##### Regressions

n/a

#### Notes for Reviewers

nil

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/networkserver/mac/device_time.go [hunk 1]
```diff
@@ -33,11 +35,27 @@ var (
...
 	}, nil
 }
+
+func messageTimestamp(msg *ttnpb.UplinkMessage) *pbtypes.Timestamp {
+	var ts *pbtypes.Timestamp
+	for _, md := range msg.RxMetadata {
+		if t := md.GpsTime; t != nil {
+			return t
+		}
+		if ts == nil && md.Time != nil {
```
Comment (adriansmares) [inline pkg/networkserver/mac/device_time.go]: This should be `md.ReceivedAt`, and the tests should be updated.

`md.Time` is the timestamp from the gateway with undefined accuracy, so using it is not ideal.

**Review by adriansmares — APPROVED** [review]
