### PR TITLE
Handle stack config in forms in the Console

### LINKED ISSUE #4631: Remove irrelevant fields in JS-only deployments in the Console
#### Summary
In JS-only deployments, when registering new devices or gateways, the forms will ask to select a frequency plan, when such information is not relevant when registering the on the IS and JS only.

#### Steps to Reproduce
1. Go to the Console of a JS-only deployment of the Stack, e.g. https://sandbox.join.cloud.thethings.industries/console
2. Create a new end device or gateway
3. See the frequency plan selector being displayed with a warning that FPs cannot be retrieved
4. In some occasions the device cannot be registered at all, since the FP field is marked as required

#### What do you see now?
Irrelevant fields being displayed that are also causing errors (#4522)

#### What do you want to see instead?
All fields that do not relate to the IS or JS being hidden and also not marked as required

#### How do you propose to implement this?
It is necessary to go through the forms of end devices and gateways and making sure that such fields are removed based on the stack config. The broader issue is that we still render many fields that are related to a stack component, regardless of whether that component is active or not.
I think it's OK to do this iteratively but to start with JS-only scenarios.

#### How do you propose to test this?
End-to-end tests will be a good helper in this situation since it allows us to inject stack configuration easily to test different scenarios.

#### Can you do this yourself and submit a Pull Request?
I think @bafonins is more suited to this. Pushing this to 3.15.1 because I think there are some low-hanging fruits to start with.

### PR DESCRIPTION
**Pull request by bafonins**
#### Summary

Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/4631

#### Changes

- Hide certain fields based on stack configuration in device add form (manual and repository)
- Hide certain fields based on stack configuration gateway form
- Expand section in manual device add form on required fields
- Extend e2e tests

#### Testing

Manual + e2e

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/webui/console/views/device-add/manual/form/form.js [hunk 1]
```diff
@@ -182,21 +182,23 @@ const ManualForm = props => {
...
-        { context: validationContext },
-      ),
-    [jsEnabled, nsEnabled, validationContext],
-  )
+  const initialValues = React.useMemo(() => {
+    const initialActivationMode = jsEnabled
+      ? ACTIVATION_MODES.OTAA
+      : nsEnabled
+      ? ACTIVATION_MODES.ABP
+      : ACTIVATION_MODES.NONE
```
Comment (kschiffer) [inline pkg/webui/console/views/device-add/manual/form/form.js:190]: The manual form does not allow setting no activation mode anymore. I guess in this special case we need to make it available as checkbox option.

**Review by kschiffer — APPROVED** [review]
