### PR TITLE
gs: Get fallback frequency plan ID from server context

### LINKED ISSUE #1027: Basic Station frontend does not use fallback FrequencyPlan ID
#### Summary

Basic Station frontend does not use fallback FrequencyPlan ID when it's configured.

#### Steps to Reproduce

1. Set env `TTN_LW_GS_BASIC_STATION_FALLBACK_FREQUENCY_PLAN_ID=EU_863_870`.
2. Connect an unregistered gateway

#### What do you see now?

- Gateway connection dropped.

#### What do you want to see instead?

- Gateway connected using the fallback frequency.

#### Environment

Latest master.

#### How do you propose to implement this?

- Copy the fallback frequencyplan id from server context to request context.

#### Can you do this yourself and submit a Pull Request?

yup.

### PR DESCRIPTION
**Pull request by KrishnaIyer**
#### Summary

Closes #1027 

#### Changes

- Copy the fallback frequency plan id from server context to request context.

### CODE REVIEW

File: pkg/gatewayserver/io/basicstationlns/basicstationlns.go [hunk 1]
```diff
@@ -170,6 +171,12 @@ func (s *srv) handleTraffic(c echo.Context) error {
 		ctx = metadata.NewIncomingContext(s.ctx, md)
 	}
 
+	// If a fallback frequency is defined, inject it into the request context.
```
Comment (johanstokking) [inline pkg/gatewayserver/io/basicstationlns/basicstationlns.go]: Wrong comment

File: pkg/gatewayserver/io/basicstationlns/basicstationlns.go [hunk 2]
```diff
@@ -170,6 +171,12 @@ func (s *srv) handleTraffic(c echo.Context) error {
...
+	fallback, ok := frequencyplans.FallbackIDFromContext(s.ctx)
+	if ok {
```
Comment (johanstokking) [inline pkg/gatewayserver/io/basicstationlns/basicstationlns.go]: No need for change, but we put this stuff on a single line
