### PR TITLE
Return plaintext values for update gateway

### LINKED ISSUE #4066: LNS Auth field in the Gateway Settings page displays garbage value
#### Summary

LNS Auth field in the Gateway Settings page displays garbage value

#### Steps to Reproduce

1. Update the LBS LNS Key or clear it.
2. Press Save changes

image

#### What do you see now?

Some garbage value is printed.

#### What do you want to see instead?

Print the LNS Key value (if set) or be empty.

#### Environment

```
tts v3.12.0
```

#### How do you propose to implement this?

Should be something in the type conversion. This was actually tested in the original PR; https://github.com/TheThingsNetwork/lorawan-stack/pull/4011

But there might have been a regression introduced.

#### How do you propose to test this?

Run the stack and test this.

#### Can you do this yourself and submit a Pull Request?

Yes

### PR DESCRIPTION
**Pull request by KrishnaIyer**
#### Summary

Closes #4066 

#### Changes

- Return plaintext values of secrets set in `UpdateGateway`.
- Remove unused error message.

#### Testing

Local stack

Screenshot 2021-07-05 at 11 27 16

##### Regressions

Don't expect any since I don't expect clients to use the encrypted value that this RPC used to return for anything.

#### Notes for Reviewers

@htdvisser If there's a prettier way to do this, let me know.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/identityserver/gateway_registry.go [hunk 1]
```diff
@@ -464,6 +467,7 @@ func (is *IdentityServer) updateGateway(ctx context.Context, req *ttnpb.UpdateGa
 			return nil, err
 		} else if req.LBSLNSSecret != nil {
 			value := req.LBSLNSSecret.Value
+			ptLBSLNSSecret = req.LBSLNSSecret.Value
```
Comment (htdvisser) [inline pkg/identityserver/gateway_registry.go:470]: Shouldn't this just replace the `value` above?

Same question for the other secrets below.

**Review by htdvisser — APPROVED** [review]
lgtm

File: pkg/identityserver/gateway_registry.go (hunk 1 above)
Comment (KrishnaIyer) [reply pkg/identityserver/gateway_registry.go:470]: No because the `value` gets overwritten by the encrypted secret if an encryption key is defined.

**Review by kschiffer — APPROVED** [review]
