### PR TITLE
Check if peers are available before using them

### LINKED ISSUE #1231: Stack panic when IS is not available
#### Summary

Stack panics and exits with code `2` when IS not available

#### Steps to Reproduce

1. `stack start ns as gs`
2. Generate some traffic e.g. by using simulator

#### What do you see now?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x16608e4]

goroutine 99 [running]:
go.thethings.network/lorawan-stack/pkg/gatewayserver.(*GatewayServer).getRegistry(0xc0004611a0, 0x23a6d20, 0xc00136c8a0, 0x0, 0xc00136c8a0, 0x0)
        /home/rvolosatovs/src/go.thethings.network/lorawan-stack/pkg/gatewayserver/gatewayserver.go:72 +0x84
go.thethings.network/lorawan-stack/pkg/gatewayserver.(*GatewayServer).FillGatewayContext(0xc0004611a0, 0x23a6d20, 0xc00136c8a0, 0x0, 0x0, 0xc001350600, 0xc000000000, 0xc001310d00, 0xc001310d18, 0xc0002c0bd0, ...)
        /home/rvolosatovs/src/go.thethings.network/lorawan-stack/pkg/gatewayserver/gatewayserver.go:246 +0x126
go.thethings.network/lorawan-stack/pkg/gatewayserver/io/udp.(*srv).connect(0xc0006e63c0, 0x23a6d20, 0xc00136c7e0, 0x0, 0x0, 0x0, 0x0)
        /home/rvolosatovs/src/go.thethings.network/lorawan-stack/pkg/gatewayserver/io/udp/udp.go:202 +0x416
go.thethings.network/lorawan-stack/pkg/gatewayserver/io/udp.(*srv).handlePackets(0xc0006e63c0)
        /home/rvolosatovs/src/go.thethings.network/lorawan-stack/pkg/gatewayserver/io/udp/udp.go:171 +0x325
created by go.thethings.network/lorawan-stack/pkg/gatewayserver/io/udp.Start
        /home/rvolosatovs/src/go.thethings.network/lorawan-stack/pkg/gatewayserver/io/udp/udp.go:101 +0x225
exit status 2
```

#### What do you want to see instead?

Log error, stating what went wrong and no panic.

#### Environment

Any

#### How do you propose to implement this?

If IS is the cause for this - check if IS is present, if not - log the error and stop execution of RPC. At a later stage we could buffer these by storing in e.g. Redis until the IS is up. Similar to what is going to happen for #560 

#### Can you do this yourself and submit a Pull Request?

Probably, but I guess @johanstokking or @KrishnaIyer can take over this?
@johanstokking I will asign you for now, please change assignment if/as required

### PR DESCRIPTION
**Pull request by adriansmares**
#### Summary

Closes #1231

#### Changes

- Check in `pkg/*/cups` if the peers are available.
- Check in GS if the peers are available.
- Refactor `Cluster.GetPeer`, `Cluster.GetPeers` and `Peer.Conn` to also return an error. Always take into account that if a peer is available, it doesn't necessary mean that the connection will be available as well.
- Add `Cluster.GetPeerConn` that combines `Cluster.GetPeer` and `Peer.Conn` due to popular usage.

#### Notes for Reviewers

None.

### CODE REVIEW

File: pkg/basicstation/cups/server.go [hunk 1]
```diff
@@ -106,18 +106,28 @@ func (s *Server) getAuth(ctx context.Context, eui types.EUI64, auth string) grpc
 	return s.component.WithClusterAuth()
 }
 
-func (s *Server) getRegistry(ctx context.Context, ids *ttnpb.GatewayIdentifiers) ttnpb.GatewayRegistryClient {
+var errESUnavailable = errors.DefineUnavailable("entity_registry_unavailable", "Entity Registry unavailable for gateway_id `{gateway_id}`")
```
Comment (johanstokking) [inline pkg/basicstation/cups/server.go]: - `errERPeerUnavailable` or `errEntityRegistryPeerUnavailable`
- no code names in human friendly error messages (i.e. no `gateway_id` but `gateway`)
- always UIDs in error messages, so `{gateway_uid}` or `{uid}` here

File: pkg/basicstation/cups/server.go [hunk 2]
```diff
@@ -106,18 +106,28 @@ func (s *Server) getAuth(ctx context.Context, eui types.EUI64, auth string) grpc
...
+	}
+	if peer := s.component.GetPeer(ctx, ttnpb.ClusterRole_ENTITY_REGISTRY, ids); peer != nil {
+		return ttnpb.NewGatewayRegistryClient(peer.Conn()), nil
 	}
-	return ttnpb.NewGatewayRegistryClient(s.component.GetPeer(ctx, ttnpb.ClusterRole_ENTITY_REGISTRY, ids).Conn())
+	return nil, errESUnavailable.WithAttributes("gateway_id", ids.GetGatewayID())
 }
 
-func (s *Server) getAccess(ctx context.Context, ids *ttnpb.GatewayIdentifiers) ttnpb.GatewayAccessClient {
+var errAUnavailable = errors.DefineUnavailable("access_unavailable", "Access unavailable for gateway_id `{gateway_id}`")
```
Comment (johanstokking) [inline pkg/basicstation/cups/server.go]: Suggesting `errAccessPeerUnavailable` here

Comment (johanstokking) [reply pkg/basicstation/cups/server.go]: Idem about other points

File: pkg/gatewayconfigurationserver/gatewayconfigurationserver.go [hunk 3]
```diff
@@ -77,11 +78,17 @@ func New(c *component.Component, conf *Config) (*GatewayConfigurationServer, err
 	return gcs, nil
 }
 
+var errESUnavailable = errors.DefineUnavailable("entity_registry_unavailable", "Entity Registry unavailable for gateway_id `{gateway_id}`")
```
Comment (johanstokking) [inline pkg/gatewayconfigurationserver/gatewayconfigurationserver.go]: Idem

File: pkg/gatewayserver/gatewayserver.go [hunk 4]
```diff
@@ -65,11 +65,16 @@ type GatewayServer struct {
 	connections sync.Map
 }
 
-func (gs *GatewayServer) getRegistry(ctx context.Context, ids *ttnpb.GatewayIdentifiers) ttnpb.GatewayRegistryClient {
+var errESUnavailable = errors.DefineUnavailable("entity_registry_unavailable", "Entity Registry unavailable for gateway_id `{gateway_id}`")
```
Comment (johanstokking) [inline pkg/gatewayserver/gatewayserver.go]: Idem

File: pkg/thethingsgateway/cups/server.go [hunk 5]
```diff
@@ -63,11 +63,16 @@ type Server struct {
 	config Config
 }
 
-func (s *Server) getRegistry(ctx context.Context, ids *ttnpb.GatewayIdentifiers) ttnpb.GatewayRegistryClient {
+var errESUnavailable = errors.DefineUnavailable("entity_registry_unavailable", "Entity Registry unavailable for gateway_id `{gateway_id}`")
```
Comment (johanstokking) [inline pkg/thethingsgateway/cups/server.go]: Idem

File: pkg/basicstation/cups/server.go [hunk 6]
```diff
@@ -106,18 +107,34 @@ func (s *Server) getAuth(ctx context.Context, eui types.EUI64, auth string) grpc
...
+func (s *Server) getRegistry(ctx context.Context, ids *ttnpb.GatewayIdentifiers) (ttnpb.GatewayRegistryClient, error) {
 	if s.registry != nil {
-		return s.registry
+		return s.registry, nil
+	}
+	if peer := s.component.GetPeer(ctx, ttnpb.ClusterRole_ENTITY_REGISTRY, ids); peer != nil {
+		return ttnpb.NewGatewayRegistryClient(peer.Conn()), nil
+	}
+	if ids != nil {
+		return nil, errERPeerUnavailable.WithAttributes("gateway_uid", unique.ID(ctx, ids))
```
Comment (johanstokking) [inline pkg/basicstation/cups/server.go]: In fact, `unique.ID()` may still panic if `ids != nil`; it needs the primary identifiers (`GatewayID`); if only `ids.EUI` is set, there's still a panic.

Maybe just remove the attribute

File: pkg/basicstation/cups/server.go [hunk 7]
```diff
@@ -106,18 +107,34 @@ func (s *Server) getAuth(ctx context.Context, eui types.EUI64, auth string) grpc
...
 	}
-	return ttnpb.NewGatewayRegistryClient(s.component.GetPeer(ctx, ttnpb.ClusterRole_ENTITY_REGISTRY, ids).Conn())
+	return nil, errERPeerUnavailable
```
Comment (johanstokking) [inline pkg/basicstation/cups/server.go]: If you keep the attribute, you need to define a different error here without the gateway UID

Again I think it's easier to remove the attribute

File: pkg/applicationserver/applicationserver.go [hunk 8]
```diff
@@ -432,8 +432,12 @@ func (as *ApplicationServer) fetchAppSKey(ctx context.Context, ids ttnpb.EndDevi
 		SessionKeyID: sessionKeyID,
 		DevEUI:       *ids.DevEUI,
 	}
-	if js := as.GetPeer(ctx, ttnpb.ClusterRole_JOIN_SERVER, ids); js != nil {
-		res, err := ttnpb.NewAsJsClient(js.Conn()).GetAppSKey(ctx, req, as.WithClusterAuth())
+	if js, _ := as.GetPeer(ctx, ttnpb.ClusterRole_JOIN_SERVER, ids); js != nil {
```
Comment (htdvisser) [inline pkg/applicationserver/applicationserver.go]: Why not use `err` here?

File: pkg/basicstation/cups/server.go [hunk 9]
```diff
@@ -106,18 +106,38 @@ func (s *Server) getAuth(ctx context.Context, eui types.EUI64, auth string) grpc
...
+	cc, err := peer.Conn()
+	if err != nil {
+		return nil, errERPeerUnavailable.WithCause(err)
 	}
-	return ttnpb.NewGatewayRegistryClient(s.component.GetPeer(ctx, ttnpb.ClusterRole_ENTITY_REGISTRY, ids).Conn())
+	return ttnpb.NewGatewayRegistryClient(cc), nil
 }
 
-func (s *Server) getAccess(ctx context.Context, ids *ttnpb.GatewayIdentifiers) ttnpb.GatewayAccessClient {
+var errAccessPeerUnavailable = errors.DefineUnavailable("access_unavailable", "Access unavailable")
```
Comment (htdvisser) [inline pkg/basicstation/cups/server.go]: This error description may be a bit confusing

File: pkg/applicationserver/applicationserver.go (hunk 8 above)
Comment (johanstokking) [reply pkg/applicationserver/applicationserver.go]: Yeah better to check here if `err == nil`

File: pkg/joinserver/grpc_deviceregistry.go [hunk 10]
```diff
@@ -72,7 +73,10 @@ func (srv jsEndDeviceRegistryServer) Get(ctx context.Context, req *ttnpb.GetEndD
 		dev.RootKeys = &ttnpb.RootKeys{
 			RootKeyID: rootKeysEnc.GetRootKeyID(),
 		}
-		cs := srv.JS.GetPeer(ctx, ttnpb.ClusterRole_CRYPTO_SERVER, dev.EndDeviceIdentifiers)
+		var cc *grpc.ClientConn
+		if cs, _ := srv.JS.GetPeer(ctx, ttnpb.ClusterRole_CRYPTO_SERVER, dev.EndDeviceIdentifiers); cs != nil {
```
Comment (rvolosatovs) [inline pkg/joinserver/grpc_deviceregistry.go]: error handling missing

File: pkg/joinserver/joinserver.go [hunk 11]
```diff
@@ -354,7 +354,10 @@ func (js *JoinServer) HandleJoin(ctx context.Context, req *ttnpb.JoinRequest) (r
 				return nil, nil, errGenerateSessionKeyID
 			}
 
-			cs := js.GetPeer(ctx, ttnpb.ClusterRole_CRYPTO_SERVER, dev.EndDeviceIdentifiers)
+			var cc *grpc.ClientConn
+			if cs, _ := js.GetPeer(ctx, ttnpb.ClusterRole_CRYPTO_SERVER, dev.EndDeviceIdentifiers); cs != nil {
```
Comment (rvolosatovs) [inline pkg/joinserver/joinserver.go]: IDEM

File: pkg/networkserver/downlink_internal_test.go [hunk 12]
```diff
@@ -99,12 +99,12 @@ func TestProcessDownlinkTask(t *testing.T) {
...
 		return test.AssertClusterGetPeerRequestSequence(ctx, getPeerCh,
-			[]cluster.Peer{
-				nil,
-				peer124,
-				peer124,
-				peer3,
-				peer124,
+			[]test.ClusterGetPeerResponse{
+				{Peer: nil, Error: fmt.Errorf("peer not found")},
+				{Peer: peer124, Error: nil},
```
Comment (rvolosatovs) [inline pkg/networkserver/downlink_internal_test.go]: No need to set `nil`

File: pkg/networkserver/downlink_internal_test.go [hunk 13]
```diff
@@ -99,12 +99,12 @@ func TestProcessDownlinkTask(t *testing.T) {
...
 		a := assertions.New(t)
 		return test.AssertClusterGetPeerRequestSequence(ctx, getPeerCh,
-			[]cluster.Peer{
-				nil,
-				peer124,
-				peer124,
-				peer3,
-				peer124,
+			[]test.ClusterGetPeerResponse{
+				{Peer: nil, Error: fmt.Errorf("peer not found")},
```
Comment (rvolosatovs) [inline pkg/networkserver/downlink_internal_test.go]: `errors.New` is good enough here

File: pkg/networkserver/grpc_gsns.go [hunk 14]
```diff
@@ -923,8 +924,12 @@ func (ns *NetworkServer) newDevAddr(context.Context, *ttnpb.EndDevice) types.Dev
 
 func (ns *NetworkServer) sendJoinRequest(ctx context.Context, ids ttnpb.EndDeviceIdentifiers, req *ttnpb.JoinRequest) (*ttnpb.JoinResponse, error) {
 	logger := log.FromContext(ctx)
-	if js := ns.GetPeer(ctx, ttnpb.ClusterRole_JOIN_SERVER, ids); js != nil {
-		resp, err := ttnpb.NewNsJsClient(js.Conn()).HandleJoin(ctx, req, ns.WithClusterAuth())
+	var cc *grpc.ClientConn
+	if js, _ := ns.GetPeer(ctx, ttnpb.ClusterRole_JOIN_SERVER, ids); js != nil {
```
Comment (rvolosatovs) [inline pkg/networkserver/grpc_gsns.go]: IDEM

File: pkg/networkserver/grpc_gsns_test.go [hunk 15]
```diff
@@ -1018,7 +1019,10 @@ func TestHandleUplink(t *testing.T) {
 						a.So(role, should.Equal, ttnpb.ClusterRole_JOIN_SERVER) &&
 						a.So(ids, should.Resemble, getDevice.EndDeviceIdentifiers)
 				},
-					nil,
+					test.ClusterGetPeerResponse{
+						Peer:  nil,
```
Comment (rvolosatovs) [inline pkg/networkserver/grpc_gsns_test.go]: IDEM

File: pkg/networkserver/grpc_gsns_test.go [hunk 16]
```diff
@@ -1128,7 +1132,10 @@ func TestHandleUplink(t *testing.T) {
...
```
Comment (rvolosatovs) [inline pkg/networkserver/grpc_gsns_test.go]: IDEM

File: pkg/networkserver/grpc_gsns_test.go [hunk 17]
```diff
@@ -1128,7 +1132,10 @@ func TestHandleUplink(t *testing.T) {
...
+						Error: fmt.Errorf("peer not found"),
```
Comment (rvolosatovs) [inline pkg/networkserver/grpc_gsns_test.go]: IDEM

File: pkg/networkserver/networkserver_flow_test.go [hunk 18]
```diff
@@ -71,9 +71,12 @@ func AssertSetDevice(ctx context.Context, conn *grpc.ClientConn, getPeerCh <-cha
...
 			return a.So(role, should.Equal, ttnpb.ClusterRole_ACCESS) && a.So(ids, should.BeNil)
 		},
-		NewISPeer(ctx, &test.MockApplicationAccessServer{
-			ListRightsFunc: test.MakeApplicationAccessListRightsChFunc(listRightsCh),
-		}),
+		test.ClusterGetPeerResponse{
+			Peer: NewISPeer(ctx, &test.MockApplicationAccessServer{
+				ListRightsFunc: test.MakeApplicationAccessListRightsChFunc(listRightsCh),
+			}),
+			Error: nil,
```
Comment (rvolosatovs) [inline pkg/networkserver/networkserver_flow_test.go]: IDEM

File: pkg/networkserver/networkserver_flow_test.go [hunk 19]
```diff
@@ -657,7 +669,10 @@ func handleOTAAClassA868FlowTest1_0_2(ctx context.Context, reg DeviceRegistry, t
 						GatewayID: "test-gtw-3",
 					})
 			},
-			gsPeer,
+			test.ClusterGetPeerResponse{
+				Peer:  gsPeer,
+				Error: nil,
```
Comment (rvolosatovs) [inline pkg/networkserver/networkserver_flow_test.go]: IDEM

File: pkg/joinserver/grpc_deviceregistry.go (hunk 10 above)
Comment (johanstokking) [reply pkg/joinserver/grpc_deviceregistry.go]: CS is optional

File: pkg/joinserver/joinserver.go (hunk 11 above)
Comment (johanstokking) [reply pkg/joinserver/joinserver.go]: IDEM

File: pkg/networkserver/grpc_gsns.go (hunk 14 above)
Comment (johanstokking) [reply pkg/networkserver/grpc_gsns.go]: OK, so related to the above. Should we:

1. Not bother about an error if the peer is not required
2. Check explicitly for `errors.IsNotFound()` and skip if we don't need it, and return an error on anything else?

File: pkg/joinserver/grpc_deviceregistry.go (hunk 10 above)
Comment (rvolosatovs) [reply pkg/joinserver/grpc_deviceregistry.go]: Still - it has to at least be logged as debug

File: pkg/networkserver/grpc_gsns.go (hunk 14 above)
Comment (rvolosatovs) [reply pkg/networkserver/grpc_gsns.go]: I vote for 2.

File: pkg/joinserver/grpc_deviceregistry.go (hunk 10 above)
Comment (johanstokking) [reply pkg/joinserver/grpc_deviceregistry.go]: CS unavailability is normal flow, especially in open source.

As mentioned below, if we log anything, it should be if `!errors.IsNotFound(err)` because not-found is as much happy flow as found

File: pkg/joinserver/grpc_deviceregistry.go [hunk 20]
```diff
@@ -72,7 +74,10 @@ func (srv jsEndDeviceRegistryServer) Get(ctx context.Context, req *ttnpb.GetEndD
 		dev.RootKeys = &ttnpb.RootKeys{
 			RootKeyID: rootKeysEnc.GetRootKeyID(),
 		}
-		cc, _ := srv.JS.GetPeerConn(ctx, ttnpb.ClusterRole_CRYPTO_SERVER, dev.EndDeviceIdentifiers)
+		cc, err := srv.JS.GetPeerConn(ctx, ttnpb.ClusterRole_CRYPTO_SERVER, dev.EndDeviceIdentifiers)
+		if err != nil {
+			logger.WithError(err).Debug("Crypto Server connection is not available")
```
Comment (johanstokking) [inline pkg/joinserver/grpc_deviceregistry.go]: OK so two things about this;

- Only log this if `!errors.IsNotFound(err)`
- I think it's a good practice to deliberately set `cc = nil` because imo the return values are undefined if `err != nil`

File: pkg/networkserver/grpc_gsns.go [hunk 21]
```diff
@@ -923,8 +923,11 @@ func (ns *NetworkServer) newDevAddr(context.Context, *ttnpb.EndDevice) types.Dev
 
 func (ns *NetworkServer) sendJoinRequest(ctx context.Context, ids ttnpb.EndDeviceIdentifiers, req *ttnpb.JoinRequest) (*ttnpb.JoinResponse, error) {
 	logger := log.FromContext(ctx)
-	if js := ns.GetPeer(ctx, ttnpb.ClusterRole_JOIN_SERVER, ids); js != nil {
-		resp, err := ttnpb.NewNsJsClient(js.Conn()).HandleJoin(ctx, req, ns.WithClusterAuth())
+	cc, err := ns.GetPeerConn(ctx, ttnpb.ClusterRole_JOIN_SERVER, ids)
+	if err != nil && !errors.IsNotFound(err) {
```
Comment (johanstokking) [inline pkg/networkserver/grpc_gsns.go]: `errPeerEmptyTarget` is not a `NotFound` but is not reason to exit the whole join flow here. That should gracefully go to interop

Comment (johanstokking) [reply pkg/networkserver/grpc_gsns.go]: @rvolosatovs please advise here

Comment (rvolosatovs) [reply pkg/networkserver/grpc_gsns.go]: Indeed, just log the error at error level, do not return here.
