### PR TITLE
Fix redundant header fetching on device search

### LINKED ISSUE #1910: Extend store logic for search results
#### Summary
We need to change the way we handle search results in our redux store. Currently, we treat search request just like regular list requests.

#### Why do we need this?
- The `totalCount` prop we're using will be affected by search requests, resulting in the UI showing wrong values for the total number of entities
- Search requests will trigger a `fetching` toggle for the `GET_*_LIST` actions, resulting in some elements rendering a loading spinner when they don't actually have to

#### What is already there? What do you see now?
- Current state of the store which includes the new pagination logic

#### What is missing? What do you want to see?
A distinction of `LIST_*` and `SEARCH_*` requests

#### Environment
Console @ v3.5.0

#### How do you propose to implement this?
Cannot think this through in detail right now, but maybe adding a `filteredIds` to the pagination store, which will hold the currently filtered entities.

#### Can you do this yourself and submit a Pull Request?
Yes but @bafonins feel free to take over

### PR DESCRIPTION
**Pull request by pgalic96**
#### Summary

Relevant issue #1910 (not closing the issue itself, but the discussion in the issue, also I think separating search and list requests is not necessary)

#### Changes

- Create new redux request `getApplicationDeviceCount` and new store variable `applicationDeviceCount`
- Use `applicationDeviceCount` in application overview header instead of `totalCount` obtained via `getDeviceList` request
- also removed `selectDeviceFetching` selector from the application overview page since it's not relevant for the device count anymore

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, database and configuration, according to the stability commitments in `README.md`.
- [x] Testing: The changes are covered with unit tests. The changes are tested manually as well.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/webui/console/views/application/index.js [hunk 1]
```diff
@@ -79,6 +80,7 @@ import PropTypes from '../../../lib/prop-types'
     loadData: id => {
       dispatch(getApplication(id, 'name,description'))
       dispatch(getApplicationsRightsList(id))
+      dispatch(getApplicationDeviceCount(id))
```
Comment (bafonins) [inline pkg/webui/console/views/application/index.js]: This call is only relevant if the user goes to the overview page. In case the user has no rights to view the devices the request will result in a redundant request with `403` code. We can detect this beforehand.

You can move this call to the application overview page, something like this:
```diff
@ pkg/webui/console/views/application-overview/connect.js:28 @ import {
  selectCollaboratorsTotalCount,
  selectCollaboratorsFetching,
} from '../../store/selectors/collaborators'
+ import { getApplicationDeviceCount } from '../../store/actions/applications'
import { selectApiKeysTotalCount, selectApiKeysFetching } from '../../store/selectors/api-keys'
import { getCollaboratorsList } from '../../store/actions/collaborators'
import { getApiKeysList } from '../../store/actions/api-keys'
@ pkg/webui/console/views/application-overview/connect.js:85 @ const mapDispatchToProps = dispatch => ({
    mayViewApplicationCollaborators,
    mayViewApplicationApiKeys,
    mayViewApplicationLink,
+   mayViewDevices,
    appId,
  ) {
    if (mayViewApplicationCollaborators) dispatch(getCollaboratorsList('application', appId))
    if (mayViewApplicationApiKeys) dispatch(getApiKeysList('application', appId))
    if (mayViewApplicationLink) dispatch(getApplicationLink(appId))
+    if (mayViewDevices) dispatch(getApplicationDeviceCount(appId))
  },
})

@ pkg/webui/console/views/application-overview/connect.js:104 @ const mergeProps = (stateProps, dispatchProps, ownProps) => ({
      stateProps.mayViewApplicationCollaborators,
      stateProps.mayViewApplicationApiKeys,
      stateProps.mayViewApplicationLink,
+     stateProps.mayViewDevices,
      stateProps.appId,
    ),
})
```
