### PR TITLE
Sleep before retrying uplink sending in flow test

### LINKED ISSUE #2143: NS flaky test
#### Summary

NS flaky test

#### Steps to Reproduce

1. Run Travis
2. 🙏

[log.txt](https://github.com/TheThingsNetwork/lorawan-stack/files/4325142/log.txt)

#### What do you see now?

Flaky

#### What do you want to see instead?

No flaky

#### Environment

Travis on `linux/386`

#### How do you propose to implement this?

Regression since #2110 ?

Need higher timeouts?

#### Can you do this yourself and submit a Pull Request?

No

### PR DESCRIPTION
**Pull request by rvolosatovs**
#### Summary

Closes #2143 

#### Changes

- Fix the flaky test fix

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, database and configuration, according to the stability commitments in `README.md`.
- [x] Testing: The changes are covered with unit tests. The changes are tested manually as well.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [ ] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/networkserver/networkserver_flow_test.go [hunk 1]
```diff
@@ -628,6 +628,7 @@ func handleClassAOTAAEU868FlowTest1_0_2(ctx context.Context, conn *grpc.ClientCo
 					return
 				}
 				t.Log("Uplink handling failed with a not-found error. The join-accept was scheduled, but the new device state most probably had not been written to the registry on time, retry.")
+				time.Sleep(test.Delay)
```
Comment (rvolosatovs) [inline pkg/networkserver/networkserver_flow_test.go]: This gives some time for the NS to actually write the device before retrying the same thing.
In single-threaded environments this would definitely cause problems, which may be the case in CI.
