### PR TITLE
Update gateway location handling fixes

### LINKED ISSUE #2008: Allow gateway location to be updated from status messages once per connection
#### Summary

With #1999 all gateways with `update_location_from_status` have their location updated (debounced) everytime a new status message arrives  This creates unnecessary load on the stack

#### Why do we need this?

Even with a 1 hour debounce time, with 10K+ gateways this is ~ 3 updates on the database per second. Most of those updates are also useless, since the majority of the gateways does not move.

#### What is already there? What do you see now?

All gateways are updated even when their location does not change, spawning of many go-routines that do not do anything useful.

#### What is missing? What do you want to see?

Ability to opt out of unnecessary location updates per gateway
#### Environment

3.5.3 dev

#### How do you propose to implement this?

An option (configurable per gateway) to only update the gateway location once per connection. Afterwards, we can cleanup all relevant goroutines. This would greatly lower the amount of updates required on the database.

#### Can you do this yourself and submit a Pull Request?

Yes

### PR DESCRIPTION
**Pull request by neoaggelos**
#### Summary

Closes #2008 

#### Changes

- Set gateway location even if there were no locations previously set
- Do not perform any updates if location has not changed

#### Notes for Reviewers

...

#### Checklist

- [X] Scope: The referenced issue is addressed, there are no unrelated changes.
- [X] Compatibility: The changes are backwards compatible with existing API, database and configuration, according to the stability commitments in `README.md`.
- [X] Testing: The changes are covered with unit tests. The changes are tested manually as well.
- [X] Documentation: Relevant documentation is added or updated.
- [X] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [X] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/gatewayserver/gatewayserver.go [hunk 1]
```diff
@@ -717,11 +717,22 @@ func (gs *GatewayServer) handleLocationUpdates(conn connectionEntry) {
 			status, _, ok := conn.StatusStats()
 			locations := status.AntennaLocations
 			antennas := conn.Gateway().Antennas
-			if ok && len(locations) > 0 && len(antennas) > 0 {
-				// TODO: Handle multiple antenna locations (https://github.com/TheThingsNetwork/lorawan-stack/issues/2006).
-				locations[0].Source = ttnpb.SOURCE_GPS
-				antennas[0].Location = *locations[0]
+			if len(conn.Gateway().Antennas) == 0 {
```
Comment (johanstokking) [inline pkg/gatewayserver/gatewayserver.go]: nit; `len(antennas)`

File: pkg/gatewayserver/gatewayserver.go [hunk 2]
```diff
@@ -717,11 +717,22 @@ func (gs *GatewayServer) handleLocationUpdates(conn connectionEntry) {
...
+				conn.Gateway().Antennas = []ttnpb.GatewayAntenna{
+					{
+						Location: ttnpb.Location{},
```
Comment (johanstokking) [inline pkg/gatewayserver/gatewayserver.go]: Are we now always setting an empty location?

Comment (neoaggelos) [reply pkg/gatewayserver/gatewayserver.go]: Changed to only adding an empty antenna if the status message has a location set.

File: pkg/gatewayserver/gatewayserver.go [hunk 3]
```diff
@@ -713,11 +713,19 @@ func (gs *GatewayServer) handleLocationUpdates(conn connectionEntry) {
...
+				if len(antennas) == 0 {
+					// Add an antenna if none are present
+					conn.Gateway().Antennas = []ttnpb.GatewayAntenna{{}}
+					antennas = conn.Gateway().Antennas
+				}
+				locations[0].Source = ttnpb.SOURCE_REGISTRY
+				if antennas[0].Location.Equal(*locations[0]) {
+					break
+				}
+				antennas[0].Location = *locations[0]
```
Comment (johanstokking) [inline pkg/gatewayserver/gatewayserver.go]: So now the location is set to registry, but these are GPS values, right?

Comment (neoaggelos) [reply pkg/gatewayserver/gatewayserver.go]: This is actually because the location from the registry never stores location source. https://github.com/TheThingsNetwork/lorawan-stack/blob/6a873f552411bb41ecffb91e46041dbc6982b46c/pkg/identityserver/store/types.go#L124-L131

So using SOURCE_GPS as a source not only has no effect, it will also cause the equality check below to fail because of the difference in location sources.

Fixing that requires a database migration (adding a `Source` to `GatewayAntenna` ORM model. Creating a pull request for that.

Comment (neoaggelos) [reply pkg/gatewayserver/gatewayserver.go]: Reverted change to ttnpb.SOURCE_GPS.

Comment (johanstokking) [reply pkg/gatewayserver/gatewayserver.go]: Why do we depend on what IS stores exactly? Isn't this just about checking if the location doesn't change at the GS level, before it updates it in IS?

Comment (neoaggelos) [reply pkg/gatewayserver/gatewayserver.go]: The change is checked at the GS level. But location equality check also includes the location source, and that is always hard-coded to `SOURCE_REGISTRY` for gateway locations from the IS at the moment. This only really effects the first status message received (because the initial location on GS is the one retrieved from IS). Discussion is in #2245, not sure if we really care about it.

File: pkg/gatewayserver/gatewayserver.go [hunk 4]
```diff
@@ -709,6 +709,11 @@ func (gs *GatewayServer) updateConnStats(conn connectionEntry) {
 	}
 }
 
+func sameLocation(A, B ttnpb.Location) bool {
```
Comment (johanstokking) [inline pkg/gatewayserver/gatewayserver.go]: lowerCamelCase for arguments (or vars for that matter)

File: pkg/gatewayserver/gatewayserver.go [hunk 5]
```diff
@@ -709,6 +709,11 @@ func (gs *GatewayServer) updateConnStats(conn connectionEntry) {
...
+	return A.Latitude == B.Latitude && A.Longitude == B.Longitude &&
```
Comment (johanstokking) [inline pkg/gatewayserver/gatewayserver.go]: These are floating points; we probably need a very small delta that is allowed

File: pkg/gatewayserver/gatewayserver.go [hunk 6]
```diff
@@ -733,11 +738,19 @@ func (gs *GatewayServer) handleLocationUpdates(conn connectionEntry) {
 			status, _, ok := conn.StatusStats()
 			locations := status.AntennaLocations
 			antennas := conn.Gateway().Antennas
```
Comment (johanstokking) [inline pkg/gatewayserver/gatewayserver.go]: I don't think we really need `locations` and `antennas` anymore

Comment (neoaggelos) [reply pkg/gatewayserver/gatewayserver.go]: Removed them, using `status.AntennaLocations` and `conn.Gateway().Antennas` directly.
