### PR TITLE
Secure in-process loopback gRPC connection (#711)

### LINKED ISSUE #711: Loopback connection is considered insecure
#### Summary

The loopback connection is not considered secure by gRPC, resulting in errors when sending credentials on it (`transport: cannot send secure credentials on an insecure connection`).

#### Steps to Reproduce

1. Start the stack
2. Connect an authenticated gateway to the GS

#### What do you see now?

Reported by [Matthew Dean on Slack](https://thethingsnetwork.slack.com/team/UHQUKH6NA):

```
stack_1      |   WARN Finished unary call                      duration=48.909µs error=rpc error: code = Unauthenticated desc = transport: cannot send secure credentials on an insecure connection grpc_code=Unauthenticated grpc_method=Get grpc_service=ttn.lorawan.v3.GatewayRegistry namespace=grpc
stack_1      |   WARN Failed to setup connection               error=error:unknown:unknown (transport: cannot send secure credentials on an insecure connection) namespace=gatewayserver/io/mqtt remote_addr=X.X.X.X:35175
```

#### What do you want to see instead?

It shouldn't complain about this

#### Environment

v3.0.3

#### How do you propose to implement this?

- either we make the loopback connection use transport security, or
- we tell gRPC to consider the loopback connection secure

#### Can you do this yourself and submit a Pull Request?

Sure.

Until this is resolved the recommended workaround is using the `grpc.allow-insecure-for-credentials` flag.

### PR DESCRIPTION
**Pull request by htdvisser**
#### Summary

This Pull Requests implements an in-process loopback connection (which is obviously as secure as it gets) and faking transport security on top of it.

Refs #711

#### Changes

- Use an in-process listener and dialer for the gRPC loopback conn
- Adapt tests so that they no longer require us to allow credentials on insecure connections.

#### Notes for Reviewers

I'll create an issue for unit-testing this entire package.

### CODE REVIEW

File: pkg/networkserver/networkserver_flow_test.go [hunk 1]
```diff
@@ -171,18 +171,10 @@ func handleOTAAClassA868FlowTest1_0_2(ctx context.Context, reg DeviceRegistry, t
 		component.MustNew(
 			test.GetLogger(t),
 			&component.Config{
-				ServiceBase: config.ServiceBase{
-					GRPC: config.GRPC{
-						AllowInsecureForCredentials: true,
-					},
-				},
+				ServiceBase: config.ServiceBase{},
```
Comment (rvolosatovs) [inline pkg/networkserver/networkserver_flow_test.go]: Just make this `&component.Config{}`

**Comment by htdvisser** [comment]
I'm afraid I was a bit too enthousiastic here. The GS and AS tests don't actually use the loopback conn, but `grpc.Dial(` to the component and mocks themselves, so I could only adapt the NS test.

Furthermore, this does not yet fully resolve #711, because the GS and AS use `cluster.GetPeer`, which also does its own dialing. I'll see if we can use the loopback connection for the `self` peer in the `cluster` package.
