### PR TITLE
Fix gateway concentrator clock roll over

### LINKED ISSUE #2581: Basic Station Integration: Spurious xtime jumps
#### Summary
For background on `xtime` and its handling in lorawan-stack read issue #1709.
Spurious 2**32-jumps of the `xtime` value sent to the gateway in the `dnmsg` message can be observed. This permanently puts gateway and server out of sync. As a consequence, downlinks scheduled based on the wrong xtime value are rejected by the Gateway because they are too far in the future. 

#### Steps to Reproduce

1. Start a gateway process and schedule a first downlink before the first 32 bit rollover.
2. Schedule another downlink some time after the first one, but still before the first 32 bit rollover.

#### What do you see now?
The first downlink has correct xtime. For the second downlink the `xtime` value is 2**32 larger than expected. Here is a concrete example:

```
<CONCENTRATOR START>
  "updf" xtime=00e1000000721200 (0)
...
  "updf" xtime=00e10000049e2b28 (0)
  "updf" xtime=00e100000536c120 (0)
 "dnmsg" xtime=00e100000536c120 (1) < -- first downlink OK
  "updf" xtime=00e1000005cf6b00 (0)
...
  "updf" xtime=00e100002b5c4050 (0)
  "updf" xtime=00e100002bf4d668 (0)
 "dnmsg" xtime=00e100012bf4d668 (1) < -- second downlink xtime offset by 2**32
  "updf" xtime=00e100002c8d6c40 (0)
 "dnmsg" xtime=00e100012c8d6c40 (1) < -- all following downlinks offset by 2**32
  "updf" xtime=00e100002d260220 (0)     /
 "dnmsg" xtime=00e100012d260220 (1) < -´
...
```

Here is the complete station.log:
[station.log](https://github.com/TheThingsNetwork/lorawan-stack/files/4667368/station.log)

The xtime log can be extracted from it like this
```bash
head -n 300 station.log  | sed -n 's/[^{]*\({.*}\).*/\1/p' | jq -cr '[.msgtype, (select(.msgtype == "updf") | .upinfo.xtime), (select(.msgtype == "dnmsg") | .xtime ) ,.RxDelay ] | @csv' | awk -F, '{ printf "%8.8s xtime=%016lx (%1d)\n", $1, $2, $3 }'
```

I suspect the issue is rooted in the tracking of 32 bit rollovers of `xtime`. In this particular case apparently a 32 bit rollover was assumed to have happened some time between `0x00000536c120` and `0x00002bf4d668` (~11 minutes).

#### What do you want to see instead?

The class A downlink `xtime` should not be offset by 2**32 to the corresponding uplink.

#### Environment
Basic Station 2.0.4
TTN community network

### PR DESCRIPTION
**Pull request by johanstokking**
#### Summary

Closes #2581
References #1707

#### Changes

- Synchronize concentrator timestamp when uplink messages arrive out-of-order
- Work-around for Basic Station gateways sending uplink frames with no `xtime` (https://github.com/lorabasics/basicstation/issues/74)

#### Testing

Unit testing, see test case for #2581

##### Regressions

Not expected

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/gatewayserver/scheduling/clock.go [hunk 1]
```diff
@@ -59,10 +59,13 @@ func (c *RolloverClock) SyncTime() (time.Time, bool) {
 // Sync synchronizes the clock with the given concentrator timestamp and the server time.
 func (c *RolloverClock) Sync(timestamp uint32, server time.Time) ConcentratorTime {
 	rollovers := int64(c.absolute/ConcentratorTime(time.Microsecond)) >> 32
-	if passed := int64(timestamp) - int64(c.relative); passed < 0 {
+	// If the new timestamp is lower, it is considered a roll over if it advanced more than 25%.
```
Comment (KrishnaIyer) [inline pkg/gatewayserver/scheduling/clock.go:62]: Nit; 
```
// If the new timestamp is lower, it is considered a roll over if the difference is more than 25%.
```

File: pkg/gatewayserver/io/basicstationlns/basicstationlns.go [hunk 2]
```diff
@@ -435,6 +431,11 @@ func (s *srv) handleTraffic(c echo.Context) (err error) {
 				logger.WithError(err).Debug("Failed to parse join-request message")
 				return err
 			}
+			// TODO: Remove (https://github.com/lorabasics/basicstation/issues/74)
```
Comment (adriansmares) [inline pkg/gatewayserver/io/basicstationlns/basicstationlns.go:434]: This probably has to stay here even after 74 is going to be solved, since it's basically guaranteed that gateway vendors won't upgrade right away.

**Review by adriansmares — APPROVED** [review]

File: pkg/gatewayserver/io/basicstationlns/basicstationlns.go (hunk 2 above)
Comment (johanstokking) [reply pkg/gatewayserver/io/basicstationlns/basicstationlns.go:434]: Yep, I'm afraid so indeed.

File: pkg/gatewayserver/scheduling/clock.go (hunk 1 above)
Comment (KrishnaIyer) [reply pkg/gatewayserver/scheduling/clock.go:62]: Also isn't 25% a lot? We tolerate a drift of up to 17.9 mins?

Comment (johanstokking) [reply pkg/gatewayserver/scheduling/clock.go:62]: > ```
> // If the new timestamp is lower, it is considered a roll over if the difference is more than 25%.
> ```

On a scale of 0-9, going from 8 to 1, is "the difference" 7 or 3? We're specifically testing if the value advanced more than X, so the 3.

Comment (johanstokking) [reply pkg/gatewayserver/scheduling/clock.go:62]: > Also isn't 25% a lot? We tolerate a drift of up to 17.9 mins?

It's pretty arbitrary but this is what we ended up with choosing in an offline discussion with @htdvisser

Comment (htdvisser) [reply pkg/gatewayserver/scheduling/clock.go:62]: The idea behind that 25% was that it is also the margin for FCnt rollovers in earlier LoRaWAN versions (MAX_FCNT_GAP).

Comment (KrishnaIyer) [reply pkg/gatewayserver/scheduling/clock.go:62]: Yeah ok sounds good. A small note would've been useful.
