### PR TITLE
Publish Tx Ack failure result as string

### LINKED ISSUE #4336: Improvise debug details of the gs.down.tx.fail event
#### Summary
The “value” in the data object of the `gs.down.tx.fail` event currently doesn’t provide useful information to know/identify the cause of the failure.
Ref: https://github.com/TheThingsIndustries/lorawan-stack-support/issues/457

#### Steps to Reproduce
....

#### What do you see now?
The value in the data object of the `gs.down.tx.fail` event corresponds to the “Result” enum: https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.13.1/api/messages.proto#L153-L163

#### What do you want to see instead?
It should give the information on the cause for the downlink failure.

#### Environment
TTS V3.13.2

#### How do you propose to implement this?
...

#### How do you propose to test this?
...
#### Can you do this yourself and submit a Pull Request?
No, @KrishnaIyer

### PR DESCRIPTION
**Pull request by KrishnaIyer**
#### Summary

Closes #4336 

#### Changes

- Use the `.String()` method of the result in the event.

#### Testing

Local

##### Regressions

NA

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/gatewayserver/observability.go [hunk 1]
```diff
@@ -334,6 +334,6 @@ func registerSuccessDownlink(ctx context.Context, gtw *ttnpb.Gateway, protocol s
 }
 
 func registerFailDownlink(ctx context.Context, gtw *ttnpb.Gateway, ack *ttnpb.TxAcknowledgment, protocol string) {
-	events.Publish(evtTxFailureDown.NewWithIdentifiersAndData(ctx, gtw, ack.Result))
```
Comment (adriansmares) [inline pkg/gatewayserver/observability.go:337]: Can we add `result` as a label to `downlinkTxFailed` and record the result please ?

**Review by adriansmares — APPROVED** [review]

File: pkg/gatewayserver/observability.go (hunk 1 above)
Comment (KrishnaIyer) [reply pkg/gatewayserver/observability.go:337]: Yeah I thought of that but then we add potentially 8 new series of data and we've never really used this for debugging. Doesn't hurt I guess.

Comment (adriansmares) [reply pkg/gatewayserver/observability.go:337]: It would be nice for https://github.com/TheThingsNetwork/lorawan-stack/issues/18

File: pkg/gatewayserver/observability.go [hunk 2]
```diff
@@ -202,7 +202,7 @@ var gsMetrics = &messageMetrics{
 			Name:      "downlink_tx_failed_total",
 			Help:      "Total number of unsuccessfully emitted downlinks",
 		},
-		[]string{protocol},
+		[]string{protocol, "result"},
```
Comment (adriansmares) [inline pkg/gatewayserver/observability.go:205]: Nit: constant like `host` or `protocol`.

**Review by adriansmares — APPROVED** [review]

File: pkg/gatewayserver/observability.go (hunk 2 above)
Comment (KrishnaIyer) [reply pkg/gatewayserver/observability.go:205]: Technically we use those constants for repeated labels.
