### PR TITLE
dcs: Remap error codes from TTJS

### LINKED ISSUE #7045: Map error codes from The Things Join Server
### Summary

The Things Join Server returns various error codes which The Things Stack should understand better to improve the user experience.

### Current Situation

Currently, when the device's claim authentication code (owner token) is wrong, TTJS returns 403 that is passed through to the client (Console), which suggests the user to sign-in again. Instead, this occassion should be mapped to 500 because it is bad configuration.

### Why do we need this? Who uses it, and when?

We need not to confuse users to sign in again if server-to-server authentication failed or if a claim code is wrong.

### Proposed Implementation

TTJS returns:

- 401 if not authenticated as an AS = bad config, internal server error
- 400 if the DevEUI is malformatted = client error, internal server error
- 400 if the claim request is malformatted = client error, internal server error
- 403 if the authenticated AS is not the AS in the claim request = client error, internal server error
- 403 if the owner token is wrong

I.e. TTS cannot simply map a status code to another one, as some are reused (as they should be). Most notably, the last 403 is relevant to the end user, while the others are all bad config and should return 500.

The only way to implement this is to test the error message that TTJS returns. If it is 403 and the message is `claim failed with given owner token`, it should be mapped to 400 (Bad request) and the others should be 500 (Internal server error).

### Contributing

- [X] I can help by doing more research.
- [X] I can help by implementing the feature after the proposal above is approved.
- [X] I can help by testing the feature before it's released.

### Validation

- [ ] The feature is tested in a staging environment.
- [ ] The feature is documented in [The Things Stack Documentation](https://www.thethingsindustries.com/docs/)

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

### PR DESCRIPTION
**Pull request by halimi**
#### Summary

Closes #7045 

HTTP error codes coming from the JS passed through to the client. These error codes are not relevant to the clients and sometimes they are confusing e.g. wrong owner token results 403 forbidden but it should be just 400 bad request. To not confuse the client we remapped some of the error codes.

#### Changes

This change remaps the error code from TTJS.
 - HTTP error code 400 bad request and 401 unauthorized to 500 internal server error
 - HTTP error code 403 forbidden to 400 bad request

##### Steps

Try to register a device with a wrong authentication code and you should get error 400 bad request instead of 403 forbidden.

##### Results

Registering a device with wrong authentication code results error code 400.

##### Regressions

Some of the error codes have been changed.

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Testing: The steps/process to test this feature are clearly explained including testing for regressions.
- [ ] Infrastructure: If infrastructural changes (e.g., new RPC, configuration) are needed, a separate issue is created in the infrastructural repositories.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [ ] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Review by johanstokking — COMMENTED** [review]
@halimi this does not implement the proposal of https://github.com/TheThingsNetwork/lorawan-stack/issues/7045, e.g. it cannot be simply be mapping error codes as some status codes mean two different things where we'd need to check the error message.

**Comment by halimi** [comment]
@johanstokking you are right, I will change it to check the error message. Is the error message `claim failed with given owner token` in the proposal correct? I cannot find it in the code.

**Comment by johanstokking** [comment]
> @johanstokking you are right, I will change it to check the error message. Is the error message `claim failed with given owner token` in the proposal correct? I cannot find it in the code.

It comes from here: https://github.com/TheThingsIndustries/lorawan-join-server/blob/master/src/core/controller.ts#L486-L488.

The response will be a JSON message `{"message":"claim failed with given owner token"}` with status code 403. That needs to be mapped to 400 bad request. The others should become 500. So check if the `Content-Type` is `application/json`, then unmarshal JSON into a struct with `Message string `json:"message"` and then check the string. Ideally add a comment on the aforementioned line in TTJS to not change the error message because clients depend on it.

A small nit comment is that `errBadRequest` should really be `InvalidArgument` to make it clearer for our future selves. Because `Internal` gets mapped to 500 via gRPC Web, meaning that returning `errBadRequest` in code results in 500 for the client. That is hard to debug.

**Comment by halimi** [comment]
@johanstokking thank you for clarifying what is the join server and where the error comes from. Now it make more sense.
The error message is already unmarshaled so now I'm checking the message and based on that returning back with a different error code.

I agree to name an internal server error as `errBadRequest` is a bad idea and makes our life harder later, I've changed it back and created a new `errInternalError`.

File: pkg/deviceclaimingserver/enddevices/ttjsv2/util_test.go [hunk 1]
```diff
@@ -170,7 +170,7 @@ func (srv *mockTTJS) handleClaim(w http.ResponseWriter, r *http.Request) { //nol
 		}
 
 		if dev.claimAuthenticationCode != req.OwnerToken {
-			writeResponse(w, http.StatusUnauthorized, "Owner token mismatch")
+			writeResponse(w, http.StatusForbidden, "claim failed with given owner token")
```
Comment (halimi) [inline pkg/deviceclaimingserver/enddevices/ttjsv2/util_test.go:173]: @johanstokking to trigger the error `claim failed with given owner token` means sending a wrong token or it should be able to authenticate with the token just the actual claiming should fail?

File: pkg/deviceclaimingserver/enddevices/ttjsv2/ttjs.go [hunk 2]
```diff
@@ -177,10 +178,13 @@ func (c *TTJS) Claim(ctx context.Context, joinEUI, devEUI types.EUI64, claimAuth
...
 	case http.StatusBadRequest:
-		return errBadRequest.WithAttributes("message", errResp.Message)
+		return errInternalError.WithAttributes("message", errResp.Message)
 	case http.StatusNotFound:
 		return errDeviceNotProvisioned.WithAttributes("dev_eui", devEUI)
 	case http.StatusForbidden:
+		if errResp.Message == "claim failed with given owner token" {
+			return errBadRequest.WithAttributes("message", errResp.Message)
+		}
 		return errDeviceAccessDenied.WithAttributes("dev_eui", devEUI)
```
Comment (johanstokking) [inline pkg/deviceclaimingserver/enddevices/ttjsv2/ttjs.go]: In the case that the "claim failed with given owner token", that is when we want to convey a 400 with an informative message to the user.

So while the error code is good (400), you should basically return `errDeviceAccessDenied` that has error code 400 (not 500).

If it returns 403 but the message is different, return `errInternalError`.

Essentially, there is no `errBadRequest` here anymore. You can remove it. Run `tools/bin/mage go:messages js:translations` to get rid of the messages everywhere (otherwise CI will complain).

File: pkg/deviceclaimingserver/enddevices/ttjsv2/util_test.go (hunk 1 above)
Comment (johanstokking) [reply pkg/deviceclaimingserver/enddevices/ttjsv2/util_test.go:173]: See below

File: pkg/deviceclaimingserver/enddevices/ttjsv2/ttjs.go (hunk 2 above)
Comment (halimi) [reply pkg/deviceclaimingserver/enddevices/ttjsv2/ttjs.go]: I've changed it and now it returns `errDeviceAccessDenied` with error code 400 when the message is "claim failed with given owner token" and with `errInternalError` in other cases.

There is still one place where we use `errBadRequest` when the batch unclaim list is empty https://github.com/TheThingsNetwork/lorawan-stack/blob/e2b9df1f1c3e1a8ecaefc4fc15a8640f9fc5f13b/pkg/deviceclaimingserver/enddevices/ttjsv2/ttjs.go#L338

I've added the new `errInternalError` to the translations.

**Review by johanstokking — APPROVED** [review]

File: pkg/deviceclaimingserver/enddevices/ttjsv2/ttjs.go (hunk 2 above)
Comment (johanstokking) [reply pkg/deviceclaimingserver/enddevices/ttjsv2/ttjs.go]: OK, this is good now.

File: pkg/deviceclaimingserver/enddevices/ttjsv2/ttjs.go [hunk 3]
```diff
@@ -108,10 +108,11 @@ var (
 	errBadRequest           = errors.DefineInvalidArgument("bad_request", "bad request", "message")
 	errDeviceNotProvisioned = errors.DefineNotFound("device_not_provisioned", "device with EUI `{dev_eui}` not provisioned") //nolint:lll
 	errDeviceNotClaimed     = errors.DefineNotFound("device_not_claimed", "device with EUI `{dev_eui}` not claimed")
-	errDeviceAccessDenied   = errors.DefinePermissionDenied("device_access_denied", "access to device with `{dev_eui}` denied: device is already claimed or the owner token is invalid") //nolint:lll
-	errUnauthenticated      = errors.DefineUnauthenticated("unauthenticated", "unauthenticated")
+	errDeviceAccessDenied   = errors.DefineInvalidArgument("device_access_denied", "access to device with `{dev_eui}` denied: device is already claimed or the owner token is invalid") //nolint:lll
+	errUnauthenticated      = errors.DefineInternal("unauthenticated", "unauthenticated")
```
Comment (KrishnaIyer) [inline pkg/deviceclaimingserver/enddevices/ttjsv2/ttjs.go]: I think this is a mistake. This should be reverted since we have a dedicated internal error `errInternalError`.

**Review by KrishnaIyer — CHANGES_REQUESTED** [review]

File: pkg/deviceclaimingserver/enddevices/ttjsv2/ttjs.go (hunk 3 above)
Comment (johanstokking) [reply pkg/deviceclaimingserver/enddevices/ttjsv2/ttjs.go]: So if our client is unauthenticated, it is an internal configuration error.

Comment (halimi) [reply pkg/deviceclaimingserver/enddevices/ttjsv2/ttjs.go]: Should I use `errInternalError` instead of `errUnauthenticated` to make it clear that will produce an "internal error" with error code 500  or should I leave it like this to produce "unauthenticated" error with error code 500?

Comment (johanstokking) [reply pkg/deviceclaimingserver/enddevices/ttjsv2/ttjs.go]: I think it is okay like this. We return an internal error, but the reason is that TTS is not authenticated with TTJS. So we see the right error in the logs and we see the right error in the response.

Comment (KrishnaIyer) [reply pkg/deviceclaimingserver/enddevices/ttjsv2/ttjs.go]: This isn't great for readability but this is fine as it is.

**Review by KrishnaIyer — APPROVED** [review]

File: pkg/deviceclaimingserver/enddevices/ttjsv2/ttjs.go (hunk 3 above)
Comment (johanstokking) [reply pkg/deviceclaimingserver/enddevices/ttjsv2/ttjs.go]: @halimi okay can you rename this to `errCredentials` instead?

Comment (halimi) [reply pkg/deviceclaimingserver/enddevices/ttjsv2/ttjs.go]: Sure, done.

File: pkg/deviceclaimingserver/enddevices/ttjsv2/ttjs.go [hunk 4]
```diff
@@ -109,7 +109,7 @@ var (
 	errDeviceNotProvisioned = errors.DefineNotFound("device_not_provisioned", "device with EUI `{dev_eui}` not provisioned") //nolint:lll
 	errDeviceNotClaimed     = errors.DefineNotFound("device_not_claimed", "device with EUI `{dev_eui}` not claimed")
 	errDeviceAccessDenied   = errors.DefineInvalidArgument("device_access_denied", "access to device with `{dev_eui}` denied: device is already claimed or the owner token is invalid") //nolint:lll
-	errUnauthenticated      = errors.DefineInternal("unauthenticated", "unauthenticated")
+	errCredentials          = errors.DefineInternal("unauthenticated", "unauthenticated")
```
Comment (johanstokking) [inline pkg/deviceclaimingserver/enddevices/ttjsv2/ttjs.go]:
```suggestion
	errCredentials          = errors.DefineInternal("credentials", "invalid credentials")
```

Comment (johanstokking) [reply pkg/deviceclaimingserver/enddevices/ttjsv2/ttjs.go]: And run `tools/bin/mage go:messages js:translations`

Comment (halimi) [reply pkg/deviceclaimingserver/enddevices/ttjsv2/ttjs.go]: Sorry, I forgot to rewrite the message but now I did. Thanks for the suggestion.

**Review by johanstokking — APPROVED** [review]

**Comment by KrishnaIyer** [comment]
@halimi: For future reference, we don't use `Closes` for issues, unless they don't require testing and/or are small fixes. this way the issue stays open and we only close it after it's tested in staging.

**Comment by halimi** [comment]
> @halimi: For future reference, we don't use `Closes` for issues, unless they don't require testing and/or are small fixes. this way the issue stays open and we only close it after it's tested in staging.

Understood, I will keep in mind, thank you.
