### PR TITLE
Display event error payloads

### LINKED ISSUE #1963: Event error payloads are not shown
#### Summary

Event error payloads are not shown

#### Steps to Reproduce

1. Subscribe to gateway or application events in the Console
2. Observe failure or packet drop events; they are not shown
3. Subscribe to the same events in CLI; they are shown

#### What do you see now?

Console doesn't show error payloads:

Screenshot 2020-02-07 at 13 32 10

#### What do you want to see instead?

Error payloads, like CLI:

```json
{
  "name": "gs.up.drop",
  "time": "2020-02-07T12:30:40.588851469Z",
  "identifiers": [
    {
      "gateway_ids": {
        "gateway_id": "kerlink-ifemtocell",
        "eui": "7276FF003903007D"
      }
    }
  ],
  "data": {
    "@type": "type.googleapis.com/ttn.lorawan.v3.ErrorDetails",
    "namespace": "pkg/gatewayserver",
    "name": "host_handle",
    "message_format": "host `{host}` failed to handle message",
    "attributes": {
        "host": "cluster"
      },
    "cause": {
      "namespace": "pkg/networkserver",
      "name": "device_not_found",
      "message_format": "device not found",
      "correlation_id": "df971dc6e7c5402596576816401ade98",
      "code": 5
    },
    "code": 5
  },
  ...
}
```

#### Environment

Console

#### How do you propose to implement this?

- Remove a filter somewhere that suppresses error payloads (?)
- Render the error nicely. Would be nice to show a tree of causes

#### Can you do this yourself and submit a Pull Request?

Can review

### PR DESCRIPTION
**Pull request by pgalic96**
#### Summary

Closes #1963 

#### Changes

- Add the logic for displaying event data to all event component types
- Add the `ErrorMessage` case for displaying event data

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, database and configuration, according to the stability commitments in `README.md`.
- [ ] Testing: The changes are covered with unit tests. The changes are tested manually as well.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/webui/components/event/types/format-message.js [hunk 1]
```diff
@@ -12,7 +12,7 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
-import { getEventDataType } from '..'
+import { getEventDataType } from '.'
 
 const formatMessageData = function(data) {
```
Comment (bafonins) [inline pkg/webui/components/event/types/format-message.js]: Please move this utility to `.../components/event/types/index.js`

File: CHANGELOG.md [hunk 2]
```diff
@@ -9,6 +9,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 ### Added
 
+- Display of error payloads in console event log
```
Comment (johanstokking) [inline CHANGELOG.md]: Add empty line after
