### PR TITLE
Fix camera switching for ios, android and desktop

### LINKED ISSUE #6529: Switch camera button during device onboarding via mobile doesn't work
### Summary

Switch camera button during device onboarding via mobile doesn't work.
Ref: https://github.com/TheThingsNetwork/lorawan-stack/pull/6500

### Steps to Reproduce

See https://github.com/TheThingsIndustries/lorawan-stack-support/issues/991#issuecomment-1710017134. 
I have also tested this with an iPhone 12 Pro with Safari and Firefox.

### Current Result

The switch camera button doesn't do anything visible on clicks.

### Expected Result

The button should cycle through the cameras. 
Since this is used by users to onboard devices, we need the users to be able to use the rear camera of their mobile phones. 
The good thing is that I have consistently seen that it always shows the primary (rear) camera. 
If we can somehow guarantee that this works, we don't even need to cycle I think.

### Relevant Logs

```shell
See https://github.com/TheThingsIndustries/lorawan-stack-support/issues/991#issuecomment-1710017134
```

### URL

_No response_

### Deployment

The Things Stack Open Source (self-hosted)

### The Things Stack Version

3.27.2

### Client Name and Version

```shell
iPhone Pro with Firefox and Safari.
```

### Other Information

_No response_

### Proposed Fix

_No response_

### Contributing

- [ ] I can help by doing more research.
- [ ] I can help by implementing a fix after the proposal above is approved.
- [X] I can help by testing the fix before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

### PR DESCRIPTION
**Pull request by mjamescompton**
#### Summary

Closes #6529

#### Changes

- Refactor Video component and separate into `Camera`, `Stream`, `Video`  components.
- Only display video stream based on `videoinput` with a `deviceID`

#### Testing

Testing
Log in the console on a mobile device
Go to register end device
Click on scan end device QR code
See the switch button at the bottom of the video
Click and see the camera changing

##### Regressions

...

#### Notes for Reviewers

I have separated this component into `Camera`, `Stream`, `Video`. I did this so that we would completely re render the `Stream`, `Video` components when a user selects another a new camera.

## Problem 1 -  samsung galaxy s20

The main discovery while testing was that on many devices (iPhone and some android) `navigator.mediaDevices.enumerateDevices()` was only able to show an empty videoinput object until the user gives permission to view the full list. 

The problem with some android devices was that this stack overflow snippet we where using would assume that all android devices would have a device Id on page load.

```
const videoMode =
        cameras.length > 1
          ? ua.indexOf('safari') !== -1 && ua.indexOf('chrome') === -1
            ? { facingMode: { exact: 'environment' } }
            : { deviceId: rearCamera.deviceId }
          : { facingMode: 'environment' }
``` 

When we would request the back camera using the following we would get an empty device id which would then tell the phone to use its default camera, which in this case was the face camera. 
```
  let rearCamera = cameras.find(device => device.label.toLowerCase().includes('back'))
```

## Problem 2 - Android error on camera switch.

We where not using 

```
if (stream) {
      stream.getTracks().forEach(track => {
        track.stop()
      })
    }
```
When switching cameras, so the previous camera feed was still active and this would cause an error on some android phone.

## Problem 3 - iPhone

I think the root of the problem here was the amount of videoinputs on the newer iphones 
 
WhatsApp Image 2023-11-07 at 14 09 20

When testing I believe we where just cycling through different back cameras making it seem it was not changing. This lead to us going down a rabbit whole where we ended up with no switching at all.

The switch button would not show on first render as at that point we did not have permission to view the list of cameras.

## General Solution

As device Id is the only consistent way of identify the cameras, I have rebuilt this element to only display the video to the user once we have a deviceId

so the idea is that we request the back camera using the following

```
const userStream = await navigator.mediaDevices.getUserMedia({
  video: { facingMode: 'environment' },
})
```

This snippet seem to work generally across devices to return the back camera. 
This requests permission to use the cameras and so gives us access to all camera data
At this point nothing is displayed to the user but using this stream we can get the deviceID for the camera the phone as assumed as back camera.

We then re-render the Stream component with a deviceId which displays Videos component to the user.

We now have a list of all devices for the switch button to use to change devices. Depending on the label names we either switch between cameras named `back` or `front` or we cycle through all the camera (This allows us to also cycle between multiple cameras on desktop for example if you using an external webcam ). As iPhone label names are pretty clean and consistent this means we should not cycle through all the different types of back cameras.

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] The steps/process to test this feature are clearly explained including testing for regressions.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [ ] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/webui/components/qr/input/video/index.js [hunk 1]
```diff
@@ -28,97 +28,165 @@ const m = defineMessages({
...
+
+    if (videoTracks.length > 0) {
+      const { deviceId } = videoTracks[0].getSettings()
+      setDeviceId(deviceId)
+    }
+  }, [])
+
+  useEffect(() => {
+    setDeviceTypes()
+  }, [setDeviceTypes])
```
Comment (kschiffer) [inline pkg/webui/components/qr/input/video/index.js]: Somewhat redundant.
```suggestion
  useEffect(() => {
        setHasFrontCamera(cameras.some(device => device.label.toLowerCase().includes('front')))
        setHasBackCamera(cameras.some(device => device.label.toLowerCase().includes('back')))
  }, [cameras])
```

File: pkg/webui/components/qr/input/video/index.js [hunk 2]
```diff
@@ -28,97 +28,165 @@ const m = defineMessages({
...
+    const enumerateDevices = await navigator.mediaDevices.enumerateDevices()
+    const videoInputs = enumerateDevices.filter(device => device.kind === 'videoinput')
+
+    if (videoInputs.length !== cameras.length) {
+      setCameras(videoInputs)
     }
-  }, [devices.length])
+  }, [cameras])
+
+  const setDeviceIdFromStream = useCallback(async userStream => {
```
Comment (kschiffer) [inline pkg/webui/components/qr/input/video/index.js]:
```suggestion
  const setDeviceIdFromStream = useCallback(userStream => {
```

File: pkg/webui/components/qr/input/video/index.js [hunk 3]
```diff
@@ -28,97 +28,165 @@ const m = defineMessages({
...
+  )
+}
+
+Camera.propTypes = {
+  onRead: PropTypes.func.isRequired,
+  setCapture: PropTypes.func.isRequired,
+  setError: PropTypes.func.isRequired,
+  stream: PropTypes.shape({
+    active: PropTypes.bool,
+  }),
```
Comment (kschiffer) [inline pkg/webui/components/qr/input/video/index.js]: Is this used?

File: pkg/webui/components/qr/input/video/index.js [hunk 4]
```diff
@@ -28,97 +28,165 @@ const m = defineMessages({
...
   useEffect(() => {
-    getDevices()
     getStream()
-    return () => {
-      if (stream) {
-        stream.getTracks().map(t => t.stop())
-      }
-    }
-  }, [devices, getDevices, getStream, stream])
+  }, [getStream])
```
Comment (kschiffer) [inline pkg/webui/components/qr/input/video/index.js]: Just use `useEffect()` directly without wrapping around `useCallback()`.

File: pkg/webui/components/qr/input/video/index.js [hunk 5]
```diff
@@ -28,97 +28,165 @@ const m = defineMessages({
...
+Stream.propTypes = {
+  deviceId: PropTypes.string,
+  getDevices: PropTypes.func.isRequired,
+  onRead: PropTypes.func.isRequired,
+  setCapture: PropTypes.func.isRequired,
+  setDeviceIdFromStream: PropTypes.func.isRequired,
+  setError: PropTypes.func.isRequired,
+  stream: PropTypes.shape({
+    active: PropTypes.bool,
+  }),
```
Comment (kschiffer) [inline pkg/webui/components/qr/input/video/index.js]: Is this used?

**Review by kschiffer — CHANGES_REQUESTED** [review]
Nice drill-through. See my remarks.

File: pkg/webui/components/qr/input/video/index.js (hunk 4 above)
Comment (mjamescompton) [reply pkg/webui/components/qr/input/video/index.js]: I don't think that will work because of the `async`

Comment (kschiffer) [reply pkg/webui/components/qr/input/video/index.js]:
```js
useEffect(() => {
  const asyncStuff = async () => {
    // Do async stuff
  }
  
  asyncStuff()
}, […])
```

**Review by kschiffer — APPROVED** [review]
Thanks! See my last remark.
