### PR TITLE
Fix byte input value change

### LINKED ISSUE #1336: Incomplete byte input not changing value
#### Summary

Partially filled byte input does not update its value when the cursor is placed after the inputs mask.

byte-input-blocked

#### Steps to Reproduce

1. Input hex chars such that there are placeholder characters left
2. Move cursor after the last placeholder char and continue typing
3. See no changes

#### What do you see now?

Input being blocked

#### What do you want to see instead?

Cursor should be placed right after the last non-placolder char

#### Environment

browser (console) 3.1.2

#### How do you propose to implement this?

Most probably something is wrong in how the inputs mask is handled

#### Can you do this yourself and submit a Pull Request?

Yes, but feel free to reassign

### PR DESCRIPTION
**Pull request by bafonins**
#### Summary

References https://github.com/TheThingsNetwork/lorawan-stack/issues/2605
Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/1336

#### Changes

- Check for cursor position and explicitly process input character when cursor position is outside of the input mask.
- Add `id` prop to `<JoinEuiPrefixesInput />` component.
- Add `id` prop to `<DevAddrInput />` component.

#### Testing

Tested byte input with various values for `min`, `max` and `showPerChar` props.

##### Regressions

Byte input value handling

#### Notes for Reviewers

As mentioned in https://github.com/TheThingsNetwork/lorawan-stack/issues/1336 ignoring inputs when cursor is outside of the input mask is expected behavior of `react-text-mask`. However, this is blocking issue for using cypress `type()`.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/webui/components/input/byte.js [hunk 1]
```diff
@@ -147,10 +147,28 @@ export default class ByteInput extends React.Component {
...
+
+    // Check if the value already has length equal to `max`.
+    const isValueMaxLength = value.length === normalizedMax * 2
+    // Check if the cursor is placed after the last placeholder chararcter.
+    const isCursorAfterMask = evt.target.selectionStart === normalizedMax * 3 - 1
+
+    if (!isValueMaxLength && isCursorAfterMask && data !== null) {
+      const hexMatch = data.match(hex)
+      if (hexMatch !== null) {
+        value += hexMatch[0]
```
Comment (kschiffer) [inline pkg/webui/components/input/byte.js:164]: Let's then also set the cursor position back to the end of the current incomplete value.

**Review by kschiffer — APPROVED** [review]

File: pkg/webui/components/input/byte.js (hunk 1 above)
Comment (bafonins) [reply pkg/webui/components/input/byte.js:164]: Well, this is how it works now:
ezgif com-video-to-gif

Tested in chrome/firefox and safari.
