### PR TITLE
Wrap type unmarshaling errors

### LINKED ISSUE #4500: confusing error message if dev-eui is too short
#### Summary

There is no check on the length of the dev-eui. 
Instead a technical error is shown: 
  
`error:pkg/types:invalid_length (invalid slice length)`

This error doesn't show which parameter is wrong.

#### Steps to Reproduce

run
`ttn-lw-cli end-devices create a b --net-id 000013 --join-eui 0000000000000000 --dev-eui 123456789012`

#### What do you see now?

`error:pkg/types:invalid_length (invalid slice length)`
#### What do you want to see instead?

`dev-eui is too short, must be 8 bytes (16 characters in hex)`

#### Environment

```
# ttn-lw-cli version
The Things Network Command-line Interface: ttn-lw-cli
Version:             3.14.1
Build date:          2021-08-06T11:08:04Z
Git commit:          0be1360d5
Go version:          go1.16.7
OS/Arch:             linux/amd64
```

#### How do you propose to implement this?

The parameter length should be checked before running in a invalid slice length error

#### How do you propose to test this?

It can be tested easily (as I did to produced the bug)

#### Can you do this yourself and submit a Pull Request?

I haven't programmed in go yet. I think someone who knows the code can do this easily. I just want to create this bug because I spend some time figuring out what is wrong. I think this should be addressed so others don't fall in the same pit.

### PR DESCRIPTION
**Pull request by htdvisser**
#### Summary

This pull request adds some error definitions so that we can better wrap type unmarshaling errors.

Instead of

```
error:pkg/types:invalid_length (invalid slice length)
```

you'll now see

```
error:cmd/ttn-lw-cli/commands:invalid_join_eui (invalid JoinEUI)
--- error:pkg/types:invalid_eui (invalid EUI)
--- error:pkg/types:invalid_length (invalid length: want 8 bytes, got 3)
```

Closes #4500

#### Changes

- Added some errInvalidTypeName errors
- Replaced bare `return err` with `return errInvalidTypeName.WithCause(err)`

#### Testing

CLI, existing tests should cover the rest.

#### Notes for Reviewers

...

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: cmd/ttn-lw-cli/commands/end_devices.go [hunk 1]
```diff
@@ -426,10 +429,10 @@ var (
 						return err
 					}
 					if err := macVersion.UnmarshalText([]byte(s)); err != nil {
-						return err
+						return errInvalidMACVersion.WithCause(err)
 					}
 					if err := macVersion.Validate(); err != nil {
-						return errInvalidMACVerson
+						return errInvalidMACVersion
```
Comment (adriansmares) [inline cmd/ttn-lw-cli/commands/end_devices.go]: `WithCause` here too

File: cmd/ttn-lw-cli/commands/simulate.go [hunk 2]
```diff
@@ -468,11 +468,11 @@ var (
 			}
 
 			if err := uplinkParams.LoRaWANVersion.Validate(); err != nil {
-				return errInvalidMACVerson
+				return errInvalidMACVersion
```
Comment (adriansmares) [inline cmd/ttn-lw-cli/commands/simulate.go]: `WithCause` here too, and bellow.

**Review by adriansmares — APPROVED** [review]
