### PR TITLE
Use Backend Interfaces Result objects

### LINKED ISSUE #908: Invalid Result field type in Backend Interfaces
#### Summary

Invalid Result field type in Backend Interfaces

Reported by @brocaar

#### Steps to Reproduce

1. Send valid `JoinReq` message to Join Server
2. Receive `JoinAns` and observe `Result` field

#### What do you see now?

`"Result": "Success"`

#### What do you want to see instead?

Should be a Result Object:

Screenshot 2019-07-02 at 13 37 37

#### How do you propose to implement this?

Change structs

#### Can you do this yourself and submit a Pull Request?

Yes

### PR DESCRIPTION
**Pull request by johanstokking**
#### Summary

Closes #908 

#### Changes

- Use Result Object
- Return non-internal error cause in `Description`
- Add testing

### CODE REVIEW

File: pkg/component/interop_test.go [hunk 1]
```diff
@@ -158,6 +164,6 @@ func TestInteropTLS(t *testing.T) {
 		if !a.So(json.NewDecoder(res.Body).Decode(&msg), should.BeNil) {
 			t.FailNow()
 		}
-		a.So(msg.Result, should.Equal, interop.ResultUnknownSender)
+		a.So(msg.Result.ResultCode, should.Equal, interop.ResultUnknownSender)
```
Comment (rvolosatovs) [inline pkg/component/interop_test.go]: I'd prefer asserting `msg.Result` or even the whole `msg` via `should.Resemble` to ensure nothing is missed, but that's personal preference I guess.

File: pkg/interop/errors.go [hunk 2]
```diff
@@ -48,26 +48,32 @@ var (
...
 // ErrorHandler is an echo.HTTPErrorHandler.
 func ErrorHandler(err error, c echo.Context) {
 	if httpErr, ok := err.(*echo.HTTPError); ok {
 		c.JSON(httpErr.Code, httpErr.Message)
 		return
 	}
 
-	result := ResultOther
-	statusCode := http.StatusInternalServerError
+	result, statusCode, description := ResultOther, http.StatusInternalServerError, ""
```
Comment (rvolosatovs) [inline pkg/interop/errors.go]: :frowning_face: 
This refactoring does not seem to help readability, please consider just declaring an additional `var description string` below the previous lines

File: pkg/interop/errors_test.go [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+	"testing"
+
+	echo "github.com/labstack/echo/v4"
+	"github.com/smartystreets/assertions"
+	"go.thethings.network/lorawan-stack/pkg/errors"
+	"go.thethings.network/lorawan-stack/pkg/util/test/assertions/should"
+)
+
+func TestErrorHandler(t *testing.T) {
+	errTest := errors.DefineInvalidArgument("test", "test error")
```
Comment (rvolosatovs) [inline pkg/interop/errors_test.go]: This will `panic` if another test in this package defines an error with the same ID.
Minor issue, but consider renaming this to something unique across package, e.g. `test-error-handler` ?

File: pkg/interop/interop_test.go [hunk 4]
```diff
@@ -69,7 +69,7 @@ func TestServeHTTP(t *testing.T) {
 				}
 				var msg ErrorMessage
 				err := json.NewDecoder(res.Body).Decode(&msg)
-				return a.So(err, should.BeNil) && a.So(msg.Result, should.Equal, ResultUnknownSender)
+				return a.So(err, should.BeNil) && a.So(msg.Result.ResultCode, should.Equal, ResultUnknownSender)
```
Comment (rvolosatovs) [inline pkg/interop/interop_test.go]: IDEM

File: pkg/interop/errors.go (hunk 2 above)
Comment (htdvisser) [reply pkg/interop/errors.go]: On one hand I agree that this isn't perfect. `""` signals that it's explicitly `""`, while declaring a `var description string` signals that we'll assign it later. However, I don't think this is important enough to fix. We all understand what's going on.
