### PR TITLE
Redirect logged in user when trying to access Create Account page

### LINKED ISSUE #1030: User can open create account page while logged in
#### Summary

If user is logged in, they can still open the create account page and create a new account, which results in a newly created account being the one that is logged in. This is not intended I believe and leads to confusion.

#### Steps to Reproduce

1. Log into `oauth` client
2. Go to url `/oauth/register`
3. Create account

#### What do you see now?

Create account form

#### What do you want to see instead?

Redirect to for example, `/oauth`.

#### Environment

Latest master

#### How do you propose to implement this?

Add check if the user is already logged in and redirect

#### Can you do this yourself and submit a Pull Request?

I can do it

cc @kschiffer @bafonins

### PR DESCRIPTION
**Pull request by pgalic96**
#### Summary

- closes #1030 

#### Changes

- Add check if the user object is present and if it is return `Redirect` component that returns to `/oauth`

### CODE REVIEW

File: pkg/webui/oauth/views/create-account/index.js [hunk 1]
```diff
@@ -91,16 +93,20 @@ const getSuccessMessage = function (state) {
   }
 }
 
-@connect(null, {
+
```
Comment (bafonins) [inline pkg/webui/oauth/views/create-account/index.js]: redundant new line

File: pkg/webui/oauth/views/create-account/index.js [hunk 2]
```diff
@@ -138,6 +144,29 @@ export default class CreateAccount extends React.PureComponent {
...
+          <Message content={sharedMessages.loading} />
+        </Spinner>
+      )
+    }
+
+    if (Boolean(user)) {
+      return (
+        <Redirect
+          to={{
+            pathname: `${env.app_root}`,
```
Comment (bafonins) [inline pkg/webui/oauth/views/create-account/index.js]:
```suggestion
            pathname: env.app_root,
```
