### PR TITLE
Change location propType

### LINKED ISSUE #1291: Fix prop-types issue in oauth app
#### Summary

Prop type validation show errors in the oauth app

#### Steps to Reproduce

1. Navigate to the oauth app
2. See the error in the dev tools console

#### What do you see now?

Screenshot 2019-09-03 at 11 04 03

#### What do you want to see instead?

No errors

#### Environment

browser (oauth)

#### How do you propose to implement this?

Adapt prop-types

#### Can you do this yourself and submit a Pull Request?

Can review

### PR DESCRIPTION
**Pull request by pgalic96**
#### Summary

Closes #1291 

#### Changes

- since `location` is an object, change `propType` of `location` to object instead of string

### CODE REVIEW

File: pkg/webui/oauth/views/login/index.js [hunk 1]
```diff
@@ -60,7 +60,6 @@ const appRoot = selectApplicationRootPath()
 @bind
 export default class OAuth extends React.PureComponent {
   static propTypes = {
-    location: PropTypes.string.isRequired,
```
Comment (bafonins) [inline pkg/webui/oauth/views/login/index.js]: It is used in the component: https://github.com/TheThingsNetwork/lorawan-stack/blob/8cd545e3df2299019599b4fd52ca62f7c04c414d/pkg/webui/oauth/views/login/index.js#L77

Comment (pgalic96) [reply pkg/webui/oauth/views/login/index.js]: ah yeah, will update

File: pkg/webui/oauth/views/login/index.js [hunk 2]
```diff
@@ -60,7 +60,7 @@ const appRoot = selectApplicationRootPath()
...
+    location: PropTypes.object.isRequired,
```
Comment (bafonins) [inline pkg/webui/oauth/views/login/index.js]: we dont use the `object` prop type

File: pkg/webui/oauth/views/login/index.js [hunk 3]
```diff
@@ -60,10 +60,14 @@ const appRoot = selectApplicationRootPath()
 @bind
 export default class OAuth extends React.PureComponent {
   static propTypes = {
-    location: PropTypes.string.isRequired,
+    location: PropTypes.location,
```
Comment (bafonins) [inline pkg/webui/oauth/views/login/index.js]: is should be required. see `L95`, `L102`

Comment (pgalic96) [reply pkg/webui/oauth/views/login/index.js]: I updated it, the reason why I put it as not required because sometimes `location.state` was undefined so wanted to define a default prop for it. This works fine as well.

**Comment by bafonins** [comment]
@pgalic96 can we merge this?

**Comment by pgalic96** [comment]
@bafonins solved the conflicts and waiting for travis to pass
