### PR TITLE
Fix GatewayServer MQTTv2 support

### LINKED ISSUE #255: Gateway Server panic on v2 FromDownlink
**Summary:** 

The Gateway Server panics upon converting a downlink to the v2 MQTT format.

**Steps to Reproduce:** 

1. Connect a gateway using MQTT in the v2 format
2. Send a join-request from a device to the gateway
3. The GatewayServer panics on [format_protobufv2.go#L74](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/gatewayserver/io/mqtt/format_protobufv2.go#L74)

**What do you see now?**

A panic since the `Payload` field of the `ttnpb.DownlinkMessage` is `nil`, so the `if` statement dereferences nil.

**What do you want to see instead?**

No panic.

**How do you propose to implement this?**

Converting `Payload` to `GetPayload()` in both appearances fixed this during the test

**Environment:**

Branch `feature/68-gateway-endpoints`, but this matters only for testing.

**What can you do yourself and what do you need help with?**

I can create the issue and provide the diff I've used to fix this:

```diff
--- a/pkg/gatewayserver/io/mqtt/format_protobufv2.go
+++ b/pkg/gatewayserver/io/mqtt/format_protobufv2.go
@@ -71,7 +71,7 @@ func (protobufv2) FromDownlink(down *ttnpb.DownlinkMessage) ([]byte, error) {
                return nil, errNotScheduled
        }
        lorawan := &legacyttnpb.LoRaWANTxConfiguration{}
-       if pld, ok := down.Payload.Payload.(*ttnpb.Message_MACPayload); ok {
+       if pld, ok := down.GetPayload().GetPayload().(*ttnpb.Message_MACPayload); ok {
                lorawan.FCnt = pld.MACPayload.FHDR.FCnt
        }
        switch dr := settings.DataRate.Modulation.(type) {
```

### LINKED ISSUE #256: GatewayServer does not pass the GatewayID on uplink in v2 MQTT
**Summary:** 

The Gateway Server expects the v2 uplink that is sent using v2 MQTT to contain the `GatewayID` inside the `RxMetadata`, but The Things Gateway is not sending it.

In the v2 bridge, the `GatewayID` is manually injected ([see here](https://github.com/TheThingsNetwork/gateway-connector-bridge/blob/master/backend/mqtt/mqtt.go#L247)).

**Steps to Reproduce:** 

1. Connect a gateway using the v2 MQTT protocol.
2. Receive an uplink from the said gateway.

**What do you see now?**

```
  INFO Finished unary call                      duration=293.035µs error=error:unknown:unknown (invalid field RxMetadata.GatewayIdentifiers.GatewayID: value '' must be a string conforming to regex "^[a-z0-9](?:[-]?[a-z0-9]){2,}$") error_correlation_id=f8436fa2456e43f79354959eb4b29014 grpc_code=InvalidArgument grpc_method=HandleUplink grpc_service=ttn.lorawan.v3.GsNs namespace=grpc request_id=01D59WVC2WZFMW8BJ4QMG0BG3D
 DEBUG Finished unary call                      duration=2.797977ms error=rpc error: code = InvalidArgument desc = error:unknown:unknown (invalid field RxMetadata.GatewayIdentifiers.GatewayID: value '' must be a string conforming to regex "^[a-z0-9](?:[-]?[a-z0-9]){2,}$") error_correlation_id=f8436fa2456e43f79354959eb4b29014 grpc_code=InvalidArgument grpc_method=HandleUplink grpc_service=ttn.lorawan.v3.GsNs namespace=grpc
 DEBUG Dropping message                         dev_eui=0004A30B001C17E8 error=error:unknown:unknown (invalid field RxMetadata.GatewayIdentifiers.GatewayID: value '' must be a string conforming to regex "^[a-z0-9](?:[-]?[a-z0-9]){2,}$") gateway_uid=gtw-test join_eui=0000000000000001 namespace=gatewayserver/io/mqtt remote_addr=192.168.0.230:62877
``` 
Which occurs since the uplink does not contain a valid `GatewayID`.

**What do you want to see instead?**

The `GatewayID` should be filled.

**How do you propose to implement this?**

Either changing the `Format` interface to pass the `*ttnpb.Gateway` in `ToUplink` (uglier), or manually set it inside `deliver`.

**Environment:**

Branch `feature/68-gateway-endpoints` in order to connect a The Things Gateway to v3.

**What can you do yourself and what do you need help with?**

I can create the issue and review + test the fix.

### PR DESCRIPTION
**Pull request by adriansmares**
**Summary:**

Closes #255 .
Closes #256.

**Changes:**

- Use payload getters when formatting the v2 downlink in the MQTT frontend.
- Manually inject the gateway ID in the uplinks during parsing.

### CODE REVIEW

File: pkg/gatewayserver/io/mqtt/format.go [hunk 1]
```diff
@@ -25,7 +25,7 @@ type Format interface {
 	topics.Layout
 
 	FromDownlink(down *ttnpb.DownlinkMessage) ([]byte, error)
-	ToUplink(message []byte) (*ttnpb.UplinkMessage, error)
+	ToUplink(message []byte, gatewayID string) (*ttnpb.UplinkMessage, error)
```
Comment (johanstokking) [inline pkg/gatewayserver/io/mqtt/format.go]: - `ids ttnpb.GatewayIdentifiers`
- add to others as well, although they're noop

Comment (johanstokking) [reply pkg/gatewayserver/io/mqtt/format.go]: Second point here not addressed

Comment (adriansmares) [reply pkg/gatewayserver/io/mqtt/format.go]: Fixed now - didn't understand the request initially.
