### PR TITLE
Lock based concurrency

### LINKED ISSUE #2696: Lock-based concurrency in registries
#### Summary

Replaces #33 
Lock values in registries on SET.

#### Why do we need this?

To ensure correctness and optimal performance.

#### What is already there? What do you see now?

In all registries except NS(after #2662) we use optimistic concurrency, where the modified keys are `WATCH`'ed and in case the transaction fails, we simply fail it without retrying.
In #2662 an efficient Redis mutex lock implementation is added. It is essentially a drop-in replacement for `redis.Watch`. The implementation only locks 1 key, but can be extended to support multiple easily if there's a use case for it.

#### What is missing? What do you want to see?

Use `redis.LockedWatch` from #2662 (and, perhaps, lock other important keys depending on the implementation) to avoid possibility of transaction failure and remove the need for retrying transactions. Failed transactions in this case represent an implementation error.
Regarding the "transaction failures only happen in NS" or "the request count is small enough, that such issues rarely happen"(e.g. for JS) argument: concurrency-induced transaction failures shall not be possible. The overhead of locking is extremely small and so there's no reason not to do it.
At scale it ensures performance (versus the optimistic concurrency and retry solution) and correctness. At small scale it ensures correctness and has a negligible effect on performance.
Consider the case where the device would be updated in JS registry at the same time a join-request arrives - perfect example of a component, where clashes are very rare - with current implementation one of the operations would fail, but there's no reason for that to happen. Even though it's improbable for this to happen - it *can* happen and the more customers we have, the higher possibility of such. Even accidental concurrent set to a registry is a possible occasion and we can easily handle this case gracefully and give the user expected output instead of failing.

Please also see table at https://redislabs.com/ebook/part-2-core-concepts/chapter-6-application-components-in-redis/6-2-distributed-locking/6-2-4-fine-grained-locking/

#### How do you propose to implement this?

Use `redis.LockedWatch`, go through each implementation probably adding additional locking logic. See #2662 for an example of NS part.

#### How do you propose to test this?

Integration testing, flow tests

#### Can you do this yourself and submit a Pull Request?

yes

### PR DESCRIPTION
**Pull request by adriansmares**
#### Summary

Closes #2696 

#### Changes

- Add lock based concurrency to registries where optimistic concurrency was used
  - What this means in general is that we moved from `Watch` to `LockedWatch`, which wraps `Watch` with a mutex 
  - This has the same pattern:
    - Add `LockTTL` and mutex / entropy source
    - Ensure `Init` is called before the registry is used
    - Use `ttnredis.LockedWatch` instead of simple `Watch`
- Lock (mutex) TTL has been standardized to 10 seconds
  - The previous 1 second TTL has been a bit too optimistic for high load environments

#### Testing

Unit testing covers this.

##### Regressions

If I did something wrong, this may deadlock. With that being said, I'm pretty optimistic.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/networkserver/redis/registry.go [hunk 1]
```diff
@@ -905,10 +903,6 @@ func (r *DeviceRegistry) SetByID(ctx context.Context, appID ttnpb.ApplicationIde
 				}
 				if pb.JoinEui != nil && pb.DevEui != nil {
 					ek := r.euiKey(*pb.JoinEui, *pb.DevEui)
-
```
Comment (adriansmares) [inline pkg/networkserver/redis/registry.go:908]: This was slightly overzealous. In theory it is safe, since the order of acquiring locks is `uidKey`, followed by `euiKey`, but unlocking the mutex is problematic (cannot be done using `tx`, because that would unlock it too soon, cannot be done with `p`, since then it wouldn't be unlocked if the transaction fails).

This can be fixed (create a function outside of the transaction and `defer` that) but it's quite ugly and doesn't protect much.

File: pkg/joinserver/redis/registry.go [hunk 2]
```diff
@@ -313,10 +331,15 @@ func (r *DeviceRegistry) SetByEUI(ctx context.Context, joinEUI types.EUI64, devE
...
+	lockerID, err := ttnredis.GenerateLockerID(r.entropy, r.entropyMu)
+	if err != nil {
+		return nil, err
+	}
+
 	defer trace.StartRegion(ctx, "set end device by eui").End()
 
 	var pb *ttnpb.ContextualEndDevice
-	err := r.Redis.Watch(ctx, func(tx *redis.Tx) error {
+	err = ttnredis.LockedWatch(ctx, r.Redis, ek, lockerID, r.LockTTL, func(tx *redis.Tx) error {
```
Comment (adriansmares) [inline pkg/joinserver/redis/registry.go:333]: We lock only in `SetByEUI`, but not in `SetByID` due to the way the keys work: you need to know the UID in order to find out the EUI, and vice versa. This means that you need to acquire the locks in a different order based on the call site, which is a textbook deadlock.

We can live with locking only `SetByEUI`, since that endpoint is the one that is hit the most (since most JS communication is based on EUIs, not device IDs).

File: pkg/applicationserver/io/pubsub/redis/registry.go [hunk 3]
```diff
@@ -52,7 +56,21 @@ func applyPubSubFieldMask(dst, src *ttnpb.ApplicationPubSub, paths ...string) (*
...
-	Redis *ttnredis.Client
+	Redis   *ttnredis.Client
+	LockTTL time.Duration
+
+	entropyMu *sync.Mutex
+	entropy   io.Reader
+}
+
+// Init initializes the PubSubRegistry.
+func (r *PubSubRegistry) Init(ctx context.Context) error {
```
Comment (johanstokking) [inline pkg/applicationserver/io/pubsub/redis/registry.go:60]: Is it not feasible to turn this in a `New()` that returns an initialized `PubSubRegistry`?

File: pkg/redis/redis.go [hunk 4]
```diff
@@ -983,6 +985,18 @@ outer:
 	}
 }
 
+// GenerateLockerID generates a unique locker ID from the provided entropy source.
+// The mutex is acquired and held during entropy extraction.
+func GenerateLockerID(entropy io.Reader, mu *sync.Mutex) (string, error) {
+	mu.Lock()
+	defer mu.Unlock()
+	lockID, err := ulid.New(ulid.Timestamp(time.Now()), entropy)
```
Comment (johanstokking) [inline pkg/redis/redis.go]: This adds quite some synchronization. Is this faster than using `crypto/rand` and not lock?

File: pkg/applicationserver/io/pubsub/redis/registry.go (hunk 3 above)
Comment (adriansmares) [reply pkg/applicationserver/io/pubsub/redis/registry.go:60]: It's slightly awkward because the structs are already exposed, so you can construct the object without `New`. At least `Init` signals that you need to call `Init` first.

File: pkg/redis/redis.go (hunk 4 above)
Comment (adriansmares) [reply pkg/redis/redis.go]: This is a carry over from the NS implementation, in order to ensure that we don't accidentally generate the same locker ID for two separate goroutines / processes. I'll think of a benchmark.

Edit: Actually yeah, I think `rand.Reader` is fine.

**Review by johanstokking — APPROVED** [review]
What happens if the callback panics that does the actual work? There's no panic recovery in `LockedWatch` – does Redis do the magic?

**Comment by adriansmares** [comment]
> 
> 
> What happens if the callback panics that does the actual work? There's no panic recovery in `LockedWatch` – does Redis do the magic?

The panic is propagated through the stack, while the mutex is unlocked:
https://github.com/TheThingsNetwork/lorawan-stack/blob/8c3891a18b9f42dbadb5763bdda39a1c6c2c067e/pkg/redis/redis.go#L811-L815

**Review by htdvisser — APPROVED** [review]
Code-owned part lgtm.

**Review by KrishnaIyer — APPROVED** [review]
