### PR TITLE
gs: Fix parsing of reserved DataRate indexes

### LINKED ISSUE #1090: Fix Parsing of Reserved DataRate Indexes
#### Summary

Fix Parsing of Reserved DataRate Indexes.

#### Steps to Reproduce

1. Connect a US Basic station Gateway to the stack
2. Check Gateway Logs.

#### What do you see now?

Data Rate indexes that are reserved are over written with the next values in the slice.

```
2019-08-01 13:15:59.803 [S2E:VERB]   DR0  SF10/BW125
2019-08-01 13:15:59.805 [S2E:VERB]   DR1  SF9/BW125
2019-08-01 13:15:59.807 [S2E:VERB]   DR2  SF8/BW125
2019-08-01 13:15:59.811 [S2E:VERB]   DR3  SF7/BW125
2019-08-01 13:15:59.816 [S2E:VERB]   DR4  SF8/BW500
2019-08-01 13:15:59.833 [S2E:VERB]   DR5  SF12/BW500
2019-08-01 13:15:59.838 [S2E:VERB]   DR6  SF11/BW500
2019-08-01 13:15:59.843 [S2E:VERB]   DR7 SF10/BW500
2019-08-01 13:15:59.848 [S2E:VERB]   DR8 SF9/BW500
2019-08-01 13:15:59.852 [S2E:VERB]   DR9 SF8/BW500
2019-08-01 13:15:59.857 [S2E:VERB]   DR10 SF7/BW500
2019-08-01 13:15:59.866 [S2E:VERB]   DR11 FSK
2019-08-01 13:15:59.866 [S2E:VERB]   DR12 FSK
2019-08-01 13:15:59.866 [S2E:VERB]   DR13 FSK
2019-08-01 13:15:59.862 [S2E:VERB]   DR14 FSK
2019-08-01 13:15:59.866 [S2E:VERB]   DR15 FSK
```

#### What do you want to see instead?

Reserved fields are left as default value (`FSK` for Basic Station).

```
2019-08-01 13:15:59.803 [S2E:VERB]   DR0  SF10/BW125
2019-08-01 13:15:59.805 [S2E:VERB]   DR1  SF9/BW125
2019-08-01 13:15:59.807 [S2E:VERB]   DR2  SF8/BW125
2019-08-01 13:15:59.811 [S2E:VERB]   DR3  SF7/BW125
2019-08-01 13:15:59.816 [S2E:VERB]   DR4  SF8/BW500
2019-08-01 13:15:59.821 [S2E:VERB]   DR5  FSK
2019-08-01 13:15:59.825 [S2E:VERB]   DR6  FSK
2019-08-01 13:15:59.829 [S2E:VERB]   DR7  FSK
2019-08-01 13:15:59.833 [S2E:VERB]   DR8  SF12/BW500
2019-08-01 13:15:59.838 [S2E:VERB]   DR9  SF11/BW500
2019-08-01 13:15:59.843 [S2E:VERB]   DR10 SF10/BW500
2019-08-01 13:15:59.848 [S2E:VERB]   DR11 SF9/BW500
2019-08-01 13:15:59.852 [S2E:VERB]   DR12 SF8/BW500
2019-08-01 13:15:59.857 [S2E:VERB]   DR13 SF7/BW500
2019-08-01 13:15:59.862 [S2E:VERB]   DR14 FSK
2019-08-01 13:15:59.866 [S2E:VERB]   DR15 FSK
```

#### Environment

`ttn-lw-stack v3.1.0`

#### How do you propose to implement this?

Easy peasy. Simple one line fix.

#### Can you do this yourself and submit a Pull Request?

Yes

### PR DESCRIPTION
**Pull request by KrishnaIyer**
#### Summary

Closes #1090

#### Changes

- Increment loop variable when empty DRs are encountered in `band.DataRates`.

### CODE REVIEW

File: pkg/gatewayserver/io/basicstationlns/messages/util.go [hunk 1]
```diff
@@ -114,11 +114,10 @@ func getDataRatesFromBandID(id string) (DataRates, error) {
 			loraDR.GetSpreadingFactor()
 			drs[i][0] = int(loraDR.GetSpreadingFactor())
 			drs[i][1] = int(loraDR.GetBandwidth() / 1000)
-			i++
 		} else if fskDR := dr.Rate.GetFSK(); fskDR != nil {
 			drs[i][0] = 0 // must be set to 0 for FSK, the BW field is ignored.
-			i++
 		}
+		i++
```
Comment (htdvisser) [inline pkg/gatewayserver/io/basicstationlns/messages/util.go]: Now you can just as well use `for i, dr := range`

**Comment by htdvisser** [comment]
Maybe also add a test case
