### PR TITLE
Fix RTT handling for LBS gateways

### LINKED ISSUE #3515: Revisit RTT calculation for LBS gateways
#### Summary

Revisit RTT calculation for LBS gateways

#### Why do we need this?

We use the LBS `RefTime` parameter returned by the gateway to calculate RTT. This may have issues or the way we are using it is incorrect (under certain conditions).

#### What is already there? What do you see now?

We use the LBS `RefTime` to calculate RTT. It's definition;
> The RefTime field is calculated from the last received MuxTime, adjusted by the time interval on the router between the arrival of MuxTime and the sending of RefTime. Since downlink traffic is less frequent than uplink messages, it is likely that a MuxTime may be reused to construct multiple RefTime fields. This means that round-trip measurements are composed of the latency of the last downlink message and the most recent uplink message.

There are 2 (potential) issues using a time managed by the gateway
1. We don't exactly know what happens in case of infrequent downlinks. Specifically this;
> This means that round-trip measurements are composed of the latency of the last downlink message and the most recent uplink message.

The way I read it, the gateway will internally offset these values and return a sane RefTime but I don't really know.

2. If the gateway's internal clock is faulty/out of sync, it's possible we measure very large values of RTT and hence never use this gateway for downlinks.

#### What is missing? What do you want to see?

That we are able to account for this.

#### Environment

`v3.10 and LBS gateways`

#### How do you propose to implement this?

Should we perhaps Calculate RTT only for TxAcks and use the server time as reference (like UDP)?

#### How do you propose to test this?

UT + Gateway testing

#### Can you do this yourself and submit a Pull Request?

Yup but let's discuss.

### PR DESCRIPTION
**Pull request by KrishnaIyer**
#### Summary

Closes #3515 

Moved `timesync` message support to #3546 

#### Changes

- Measure RTT only for valid TxAcks.
- Add sanity check for round trip time
- Update tests

#### Testing

UT (testing on gateway ongoing)

##### Regressions

Traffic test on physical gateways should cover regressions.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/gatewayserver/gatewayserver.go [hunk 1]
```diff
@@ -270,8 +270,9 @@ func New(c *component.Component, conf *Config, opts ...Option) (gs *GatewayServe
 		listenerConfig listenerConfig
 	}{
 		{
-			Name:      "basicstation",
-			Formatter: lbslns.NewFormatter(),
+			Name: "basicstation",
+			// TODO: Add to config in v3.11 (https://github.com/TheThingsNetwork/lorawan-stack/issues/3548)
+			Formatter: lbslns.NewFormatter(10 * time.Second),
```
Comment (johanstokking) [inline pkg/gatewayserver/gatewayserver.go]: Please carefully read the compatibility commitment. This is not necessary

**Review by johanstokking — COMMENTED** [review]
This is not making the LNS implementation more maintainable.

If we only care about measuring RTTs on downlink, why not just put the `MuxTime` in the downlink message, and observe `RefTime` in TX ack?

Then remove RTT stuff from join-request and uplink data frame and only sync concentrator time there.

**Comment by KrishnaIyer** [comment]
> This is not making the LNS implementation more maintainable.

I've simplified the implementation significantly. 

> If we only care about measuring RTTs on downlink, why not just put the MuxTime in the downlink message, and observe RefTime in TX ack?

Yes this is what I do. The `MuxTime` needs to be stored somewhere to fetch on the next `TxAck` and check. Originally, I put that in the session state. Now I fetch that from the downlink tokens.

> Then remove RTT stuff from join-request and uplink data frame and only sync concentrator time there.

Yes this is also what I do. Please see
https://github.com/TheThingsNetwork/lorawan-stack/blob/7f4a72efe19967f85312dd16a710226a45d11a8a/pkg/gatewayserver/io/ws/lbslns/upstream.go#L444
https://github.com/TheThingsNetwork/lorawan-stack/blob/7f4a72efe19967f85312dd16a710226a45d11a8a/pkg/gatewayserver/io/ws/lbslns/upstream.go#L498
https://github.com/TheThingsNetwork/lorawan-stack/blob/7f4a72efe19967f85312dd16a710226a45d11a8a/pkg/gatewayserver/io/ws/lbslns/upstream.go#L525

File: pkg/gatewayserver/io/ws/lbslns/upstream.go [hunk 2]
```diff
@@ -407,16 +407,25 @@ func (updf *UplinkDataFrame) FromUplinkMessage(up *ttnpb.UplinkMessage, bandID s
...
+	logger := log.FromContext(ctx)
+	sec, nsec := math.Modf(conf.RefTime)
+	refTime := time.Unix(int64(sec), int64(nsec*1e9))
+	var (
+		cids  []string
+		ok    bool
+		txAck *ttnpb.TxAcknowledgment
+		delta time.Duration
+	)
+	if cids, delta, ok = tokens.Get(uint16(conf.Diid), refTime); ok {
```
Comment (johanstokking) [inline pkg/gatewayserver/io/ws/lbslns/upstream.go]: Downlink tokens work with server time

File: pkg/gatewayserver/io/ws/lbslns/upstream.go [hunk 3]
```diff
@@ -407,16 +407,25 @@ func (updf *UplinkDataFrame) FromUplinkMessage(up *ttnpb.UplinkMessage, bandID s
...
+		txAck = &ttnpb.TxAcknowledgment{
+			CorrelationIDs: cids,
+			Result:         ttnpb.TxAcknowledgment_SUCCESS,
+		}
 	} else {
-		logger := log.FromContext(ctx)
 		logger.WithField("diid", conf.Diid).Debug("Tx acknowledgement either does not correspond to a downlink message or arrived too late")
 	}
-	return &txAck
+	return txAck, delta
```
Comment (johanstokking) [inline pkg/gatewayserver/io/ws/lbslns/upstream.go]: `delta` is undefined here

File: pkg/gatewayserver/io/ws/lbslns/upstream.go [hunk 4]
```diff
@@ -512,28 +522,35 @@ func (f *lbsLNS) HandleUp(ctx context.Context, raw []byte, ids ttnpb.GatewayIden
...
+
 		session := ws.SessionFromContext(ctx)
 		session.DataMu.Lock()
 		session.Data = State{
 			ID: int32(txConf.XTime >> 48),
 		}
 		session.DataMu.Unlock()
-		recordTime(txConf.RefTime, txConf.XTime, receivedAt)
+
+		if delta > f.maxRoundTripDelay {
```
Comment (johanstokking) [inline pkg/gatewayserver/io/ws/lbslns/upstream.go:537]: The server time minus `RefTime` _is_ the delta.

`RefTime` is in the server time domain as it's sent as `MuxTime`.

Why are downlink tokens used for this?

File: pkg/gatewayserver/io/ws/lbslns/upstream.go [hunk 5]
```diff
@@ -432,6 +441,7 @@ func (f *lbsLNS) HandleUp(ctx context.Context, raw []byte, ids ttnpb.GatewayIden
 	))
 
 	recordTime := func(refTime float64, xTime int64, server time.Time) {
+		// Set refTime to 0 to skip recording RTT
```
Comment (johanstokking) [inline pkg/gatewayserver/io/ws/lbslns/upstream.go]: I don't really like this but ok

File: pkg/gatewayserver/io/ws/lbslns/upstream.go [hunk 6]
```diff
@@ -431,11 +431,13 @@ func (f *lbsLNS) HandleUp(ctx context.Context, raw []byte, ids ttnpb.GatewayIden
 		"upstream_type", typ,
 	))
 
-	recordTime := func(refTime float64, xTime int64, server time.Time) {
-		sec, nsec := math.Modf(refTime)
-		if sec != 0 {
-			ref := time.Unix(int64(sec), int64(nsec*1e9))
-			conn.RecordRTT(server.Sub(ref), server)
+	recordTime := func(recordRTT bool, refTime float64, xTime int64, server time.Time) {
+		if recordRTT {
```
Comment (johanstokking) [inline pkg/gatewayserver/io/ws/lbslns/upstream.go:435]: 🙏

File: pkg/gatewayserver/io/ws/lbslns/upstream.go [hunk 7]
```diff
@@ -446,6 +448,11 @@ func (f *lbsLNS) HandleUp(ctx context.Context, raw []byte, ids ttnpb.GatewayIden
 		)
 	}
 
+	getTimeFromFloat64 := func(timeInFloat float64) time.Time {
```
Comment (johanstokking) [inline pkg/gatewayserver/io/ws/lbslns/upstream.go]: Probably declare this in the package with `(time.Time, bool)` returns

File: pkg/gatewayserver/io/ws/lbslns/upstream.go [hunk 8]
```diff
@@ -431,11 +431,13 @@ func (f *lbsLNS) HandleUp(ctx context.Context, raw []byte, ids ttnpb.GatewayIden
...
 	))
 
-	recordTime := func(refTime float64, xTime int64, server time.Time) {
-		sec, nsec := math.Modf(refTime)
-		if sec != 0 {
-			ref := time.Unix(int64(sec), int64(nsec*1e9))
-			conn.RecordRTT(server.Sub(ref), server)
+	recordTime := func(recordRTT bool, refTime float64, xTime int64, server time.Time) {
+		if recordRTT {
+			sec, nsec := math.Modf(refTime)
```
Comment (johanstokking) [inline pkg/gatewayserver/io/ws/lbslns/upstream.go]: And use here

**Review by adriansmares — COMMENTED** [review]
Nothing to add.

File: CHANGELOG.md [hunk 9]
```diff
@@ -26,6 +25,9 @@ For details about compatibility between different releases, see the **Commitment
 
 ### Fixed
 
+- RTT recording for LBS gateways.
+    The maximum round trip delay for RTT calculation is configurable via `--gs.basic-station.max-valid-round-trip-delay`.
```
Comment (htdvisser) [inline CHANGELOG.md]: This newline+indent has no effect. Just keep it on one line.

**Review by htdvisser — APPROVED** [review]
Config changes LGTM.

**Review by johanstokking — APPROVED** [review]
