### PR TITLE
Set DevEui field in LBS downlink to a non-zero value

### LINKED ISSUE #4085: Transmit confirmation event for LBS gateways in Gateway live data
#### Summary
As per the earlier insights from the [#253](https://github.com/TheThingsIndustries/lorawan-stack-support/issues/253#issuecomment-747599562),
RTT is only recorded on successful TxACK messages for downlinks (always for UDP and from v3.10.4 [for LBS](https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.10/CHANGELOG.md#3104---2020-12-08) ).

We believe for the above to happen there must be a `gs.down.tx.success` for the LBS gateways right after `gs.down.send` upon the transmit confirmation. Ref: https://doc.sm.tc/station/tcproto.html#transmit-confirmation

#### Steps to Reproduce

1. Register an end-device and LBS based Gateway in TTS Console.
2. Schedule a `downlink`.
3. You could see the `successful scheduled data downlink` event in the end-device i.e., `ns.down.data.schedule.success`
4. Navigate to the gateway live data, we can only see `gs.down.send` event but no Ack message/event i.e., `gs.down.tx.success`

#### Why do we need this?
To understand the scheduled downlink status from the Gateways via the Gateway live data.

#### What is already there? What do you see now?
- For UDP gateways, there is the `gs.down.send` and `gs.down.tx.success` events upon successful downlink.
```
{
  "name": "gs.down.send",
  "time": "2021-04-22T13:36:23.973621056Z",
  "identifiers": [
    {
      "gateway_ids": {
        "gateway_id": "",
        "eui": ""
      }
    }
  ],
  "data": {
    "@type": "type.googleapis.com/ttn.lorawan.v3.DownlinkMessage",
    "raw_payload": "",
    "request": {
      "class": "CLASS_C",
      "downlink_paths": [
        {
          "uplink_token": "ChoKGAoMbXVsdGl0ZWNoLTAxEggAgAAAoAA2iBDs2pEQGgwIzPeFhAYQ+Pan+gIg4Nutin4="
        }
      ],
      "rx2_data_rate_index": 3,
      "rx2_frequency": "869525000",
      "frequency_plan_id": "EU_863_870_TTN"
    },
    "correlation_ids": [
      "as:downlink:01F3WWQGMH38HE64K4X33BF0CZ",
      "ns:downlink:01F3WWQGV6J6DVXDC68WP7SH2V",
      "rpc:/ttn.lorawan.v3.AppAs/DownlinkQueueReplace:55770fa5-a8b3-4d3a-9174-7e9673048594",
      "gs:conn:01F3WWP7CD9AMAM6ASA8K0HKDX",
      "rpc:/ttn.lorawan.v3.NsGs/ScheduleDownlink:01F3WWQGX59PEK02RCV8B0WVYK"
    ]
  },
  "correlation_ids": [
    "gs:conn:01F3WWP7CD9AMAM6ASA8K0HKDX",
    "rpc:/ttn.lorawan.v3.NsGs/ScheduleDownlink:01F3WWQGX59PEK02RCV8B0WVYK"
  ],
  "origin": "ip-10-23-13-196.eu-west-1.compute.internal",
  "context": {
    "tenant-id": ""
  },
  "visibility": {
    "rights": [
      "RIGHT_GATEWAY_TRAFFIC_READ"
    ]
  },
{
  "name": "gs.down.tx.success",
  "time": "2021-04-22T13:36:29.678398322Z",
  "identifiers": [
    {
      "gateway_ids": {
        "gateway_id": "",
        "eui": ""
      }
    }
  ],
  "correlation_ids": [
    "gs:conn:01F3WWP7CD9AMAM6ASA8K0HKDX",
    "gs:tx_ack:01F3WWQPFE4KRY9Y0CZZXQX9TR"
  ],
  "origin": "ip-10-23-13-196.eu-west-1.compute.internal",
  "context": {
    "tenant-id": ""
  },
  "visibility": {
    "rights": [
      "RIGHT_GATEWAY_TRAFFIC_READ"
    ]
  },
  "unique_id": "01F3WWQPFE23D83DYTPE30YH3Y"
}
```
- In the LoRa Basics Station gateways, we can see a successful scheduled downlink in the console live data, but couldn’t see the `gs.down.tx.success` event in the gateway events.
```
{
  "name": "gs.down.send",
  "time": "2021-04-21T02:41:00.814069747Z",
  "identifiers": [
    {
      "gateway_ids": {
        "gateway_id": "",
        "eui": ""
      }
    }
  ],
  "data": {
    "@type": "type.googleapis.com/ttn.lorawan.v3.DownlinkMessage",
    "raw_payload": "",
    "request": {
      "class": "CLASS_C",
      "downlink_paths": [
        {
          "uplink_token": "ChkKFwoLdHRpZy0wMDIyMjISCFigy//+gAyxEPyfs+oBGgwIs6H+gwYQ1d3Q0AMg4OCxoKcO"
        }
      ],
      "rx2_data_rate_index": 3,
      "rx2_frequency": "869525000",
      "frequency_plan_id": "EU_863_870_TTN"
    },
    "correlation_ids": [
      "as:downlink:01F3S4TR5B0YT80DEQV3P70DA4",
      "ns:downlink:01F3S4TRC9YX4NJN18FSX9HX36",
      "rpc:/ttn.lorawan.v3.AppAs/DownlinkQueueReplace:d9a6c4ab-9429-4442-a3ff-d073348627ca",
      "gs:conn:01F3S4BE8GZDJV8ZY2Y5P6TMAY",
      "rpc:/ttn.lorawan.v3.NsGs/ScheduleDownlink:01F3S4TRC9W35N379V52CB7YF4"
    ]
  },
  "correlation_ids": [
    "gs:conn:01F3S4BE8GZDJV8ZY2Y5P6TMAY",
    "rpc:/ttn.lorawan.v3.NsGs/ScheduleDownlink:01F3S4TRC9W35N379V52CB7YF4"
  ],
  "origin": "ip-10-23-15-98.eu-west-1.compute.internal",
  "context": {
    "tenant-id": ""
  },
  "visibility": {
    "rights": [
      "RIGHT_GATEWAY_TRAFFIC_READ"
    ]
  },
  "unique_id": "01F3S4TRCERT7YPZPTFA84YWJS"
}
```
#### What do you want to see instead?
`gs.down.tx.success` event for LBS based gateway

#### Environment:
TTSC v3.12.1

#### How do you propose to implement this?
...

#### How do you propose to test this?
...

#### Can you do this yourself and submit a Pull Request?
No

### PR DESCRIPTION
**Pull request by KrishnaIyer**
#### Summary

Closes #4085 

#### Changes

- Set `DevEui` to `0000000000000001`. This is necessary to get Transmit Confirmation messages.
- Update tests
- Remove some unused definitions.

#### Testing

Locally tested with a TTIG and an Uno
TxConf

##### Regressions

Don't think there's any

#### Notes for Reviewers

The reasoning was discussed offline with the LBS protocol experts and documented here; https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/447

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Review by adriansmares — APPROVED** [review]

File: pkg/gatewayserver/io/ws/lbslns/downstream.go [hunk 1]
```diff
@@ -88,8 +85,8 @@ func (f *lbsLNS) FromDownlink(ctx context.Context, uid string, down ttnpb.Downli
 	// Estimate the xtime based on the timestamp; xtime = timestamp - (rxdelay). The calculated offset is in microseconds.
 	dnmsg.XTime = xTime - int64(dnmsg.RxDelay*int(time.Second/time.Microsecond))
 
-	// This field is not used but needs to be defined for the station to parse the json.
-	dnmsg.DevEUI = "00-00-00-00-00-00-00-00"
+	// This field is not used but needs to be defined for the station to parse the json and should be non-zero for the station to return tx confirmations.
+	dnmsg.DevEUI = "00-00-00-00-00-00-00-01"
```
Comment (johanstokking) [inline pkg/gatewayserver/io/ws/lbslns/downstream.go:89]: WTF, really?

So is the DevEUI used as primary key somehow? What if there are multiple confirmed data downlink messages sent by the same gateway, all waiting for a confirmation?

**Review by johanstokking — APPROVED** [review]

File: pkg/gatewayserver/io/ws/lbslns/downstream.go (hunk 1 above)
Comment (adriansmares) [reply pkg/gatewayserver/io/ws/lbslns/downstream.go:89]: `DevEUI` and `Diid`, but indeed, silly.

Comment (KrishnaIyer) [reply pkg/gatewayserver/io/ws/lbslns/downstream.go:89]: Yup. I've summarized the behaviour here; https://www.thethingsindustries.com/docs/reference/lbs-implementation-guide/implementation-details/#use-of-deveui-field-in-downlink-messages
