### PR TITLE
Return registry error cause code

### LINKED ISSUE #2940: AppSKey not recovered via interop
#### Summary

AppSKey is not recovered via interop

#### Steps to Reproduce

1. Setup stack the usual way
2. Register device on external Join Server
3. Unlink AS
4. Activate device
5. Link AS
6. Send uplink message

#### What do you see now?

AS doesn't recover the AppSKey from the JS via interop

```json
{
  "name": "as.up.data.drop",
  "time": "<snip>",
  "identifiers": [
    {
      "device_ids": {
        "device_id": "<snip>",
        "application_ids": {
          "application_id": "<snip>"
        },
        "dev_eui": "<snip>",
        "join_eui": "70B3D57ED0000000",
        "dev_addr": "270000<snip>"
      }
    }
  ],
  "data": {
    "@type": "type.googleapis.com/ttn.lorawan.v3.ErrorDetails",
    "namespace": "pkg/applicationserver",
    "name": "app_s_key",
    "message_format": "failed to get AppSKey",
    "cause": {
      "namespace": "pkg/joinserver",
      "name": "registry_operation",
      "message_format": "registry operation failed",
      "correlation_id": "90e316b18fd74b488ef8d5d0dd0c2cec",
      "cause": {
        "namespace": "pkg/redis",
        "name": "not_found",
        "message_format": "entity not found",
        "code": 5
      },
      "code": 13
    },
    "code": 13
  },
  "correlation_ids": [
    "<snip>"
  ],
  "origin": "<snip>",
  "context": {
    "tenant-id": "<snip>"
  },
  "visibility": {
    "rights": [
      "RIGHT_APPLICATION_TRAFFIC_READ"
    ]
  }
}

```

#### What do you want to see instead?

AppSKey recovery via JS interop

#### Environment

3.8.6

#### How do you propose to implement this?

The error code is not checked correctly; returned code is `Internal` while AS would go to JS via interop if it were `NotFound`.

#### How do you propose to test this?

See reproduction steps

#### Can you do this yourself and submit a Pull Request?

Already working on it

### PR DESCRIPTION
**Pull request by johanstokking**
#### Summary

Closes #2940

#### Changes

- JS now returns the registry error cause's code instead of `Internal` (13). This is useful for clients to act on whether the entity exists in the registry, for example
- AS contacts interop JS when the cluster-local JS reported not found (no functional change, but now it works)
- Error comparison now doesn't take code into account if any is `Unknown`

#### Testing

Unit tests

##### Regressions

Clients relying on `Internal` code from JS device registry operations break.

#### Notes for Reviewers

@htdvisser please check `pkg/errors`

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md`. The target branch is set to `master` if the changes are fully compatible with existing API, database, configuration and CLI.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/errors/comparison.go [hunk 1]
```diff
@@ -29,7 +31,7 @@ func Resemble(a, b error) bool {
 	if !ok {
 		return false
 	}
-	return ttnA.Code() == ttnB.Code() &&
+	return (ttnA.Code() == uint32(codes.Unknown) || ttnB.Code() == uint32(codes.Unknown) || ttnA.Code() == ttnB.Code()) &&
```
Comment (htdvisser) [inline pkg/errors/comparison.go:34]: I don't really understand this. It shouldn't be possible to define an error with the same name in the same namespace, but give it a different code.

Comment (johanstokking) [reply pkg/errors/comparison.go:34]: The big question is: should https://github.com/TheThingsNetwork/lorawan-stack/pull/2941/files#diff-4ba598240540ba3699477b82237d81b5R59 `BeTrue` or `BeFalse`. I think it makes more sense for this to be true.

Comment (htdvisser) [reply pkg/errors/comparison.go:34]: Okay. Then maybe we should just only compare the namespace and name.

Comment (johanstokking) [reply pkg/errors/comparison.go:34]: Also fine with me
