### PR TITLE
Display backend error details in console

### LINKED ISSUE #1319: Improve error rendering in Web UI
#### Summary

We need to improve how errors are rendered in the web UI.

#### Why do we need this?

Right now they're not informative enough.

#### What is already there? What do you see now?

Creating an entity (in this case an organization) with an invalid ID returns the following error stack in the CLI:

```
error:pkg/errors:validation (invalid `organization`: embedded message failed validation)
    name=CreateOrganizationRequestValidationError
    reason=embedded message failed validation
    field=organization
    correlation_id=ff913a0396cc4b109c869cf4d172c62d
--- error:pkg/errors:validation (invalid `ids`: embedded message failed validation)
    field=ids
    name=OrganizationValidationError
    reason=embedded message failed validation
--- error:pkg/errors:validation (invalid `organization_id`: value does not match regex pattern "^[a-z0-9](?:[-]?[a-z0-9]){2,}$")
    reason=value does not match regex pattern "^[a-z0-9](?:[-]?[a-z0-9]){2,}$"
    field=organization_id
    name=OrganizationIdentifiersValidationError
```

but the console only shows

Screenshot 2019-09-05 at 11 44 45

#### What is missing? What do you want to see?

I'd like to see what caused the error.

#### How do you propose to implement this?

Look at the `cause` field in the response:

```json
{
  "code": 3,
  "message": "error:pkg/errors:validation (invalid `organization`: embedded message failed validation)",
  "details": [
    {
      "@type": "type.googleapis.com/ttn.lorawan.v3.ErrorDetails",
      "namespace": "pkg/errors",
      "name": "validation",
      "message_format": "invalid `{field}`: {reason}",
      "attributes": {
        "field": "organization",
        "name": "CreateOrganizationRequestValidationError",
        "reason": "embedded message failed validation"
      },
      "correlation_id": "eefb90988c284758956cc3585218ea7f",
      "cause": {
        "namespace": "pkg/errors",
        "name": "validation",
        "message_format": "invalid `{field}`: {reason}",
        "attributes": {
          "field": "ids",
          "name": "OrganizationValidationError",
          "reason": "embedded message failed validation"
        },
        "cause": {
          "namespace": "pkg/errors",
          "name": "validation",
          "message_format": "invalid `{field}`: {reason}",
          "attributes": {
            "field": "organization_id",
            "name": "OrganizationIdentifiersValidationError",
            "reason": "value does not match regex pattern \"^[a-z0-9](?:[-]?[a-z0-9]){2,}$\""
          },
          "code": 3
        },
        "code": 3
      },
      "code": 3
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by pgalic96**
#### Summary

Closes #1319 

#### Changes

- Change message rendering in `Notification` component
- Create new `ErrorNotification` component that wraps `Notification`
- Add new `Details` component that displays error details if available
- Update existing `Notification` components

### CODE REVIEW

File: pkg/webui/components/error-notification/story.js [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+const m = defineMessages({
+  problem: 'We got a problem here!',
+  lengthyProblem:
+    'We got a problem here! And the description is quite lengthy as well, which can sometimes be a problem.',
+})
+storiesOf('Notification/ErrorNotification', module).add('Error', () => (
+  <div>
+    <ErrorNotification title="example message title" content={m.problem} />
+    <ErrorNotification content={m.problem} />
+    <ErrorNotification
```
Comment (kschiffer) [inline pkg/webui/components/error-notification/story.js]: Let's pass a realistic error object here.
