### PR TITLE
Prevent users from submitting zero or empty security keys in the Console

### LINKED ISSUE #4539: Prevent users from submitting zero or empty security keys
#### Summary
It is currently possible to submit the general settings form for ABP devices with empty security keys. This causes an [avoidable error](https://sentry.io/organizations/the-things-industries/issues/2298261705) when submitting the form.

#### Steps to Reproduce

1. Create an ABP device with MAC Version `1.1.0`
2. Go to the general settings form of the new device
3. Expand the network layer settings
4. Remove a security key (e.g. `FNwkSIntKey`, or any other key). Alternatively, enter an all-zero key.
5. Submit the form and observe the error
> invalid value of field `session.keys.f_nwk_s_int_key.key`

#### What do you see now?
Missing validation of required field (the field is also not marked as required)

#### What do you want to see instead?
- Field being marked as required
- Form validation catching empty or all-zero key values before submit

#### How do you propose to implement this?
- Update validation schema of the network layer form
- Add required prop to field

#### How do you propose to test this?
E2E

#### Can you do this yourself and submit a Pull Request?
@bafonins

### PR DESCRIPTION
**Pull request by bafonins**
#### Summary

Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/4539

<details>
<summary>Screenshots</summary>

Screenshot 2021-08-18 at 13 37 47
Screenshot 2021-08-18 at 13 37 37

</details>

#### Changes

- Move validation for form values to respective sections in the device general settings page.
- Fix and improve validation for session keys

#### Testing

manual

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/webui/console/views/device-general-settings/network-server-form/index.js [hunk 1]
```diff
@@ -111,12 +111,19 @@ const NetworkServerForm = React.memo(props => {
...
 
       setError('')
       try {
         // Always submit current `mac_settings` values to avoid overwriting nested entries.
-        await onSubmit({ ...updatedValues, mac_settings: castedValues.mac_settings })
+        await onSubmit({
+          ...updatedValues,
+          mac_settings: castedValues.mac_settings,
+          session: { ...updatedValues.session, keys: castedValues.session.keys },
+        })
```
Comment (kschiffer) [inline pkg/webui/console/views/device-general-settings/network-server-form/index.js]: It's currently not possible to remove an existing key (by removing the value and submitting it as emtpy), since `diff()` will not include such keys.

**Review by kschiffer — CHANGES_REQUESTED** [review]

**Comment by kschiffer** [comment]
While testing, I saw that the AppSKey inside the application layer form needs the same fix wrt zero values.

**Comment by kschiffer** [comment]
Also, just to make sure: Is it correct that `SNwkSIntKey` and `NwkSEncKey` should be removable? @johanstokking

**Comment by johanstokking** [comment]
> Also, just to make sure: Is it correct that `SNwkSIntKey` and `NwkSEncKey` should be removable? @johanstokking

In LoRaWAN 1.0, they don't exist. In LoRaWAN 1.1, they do and are required.

**Review by kschiffer — CHANGES_REQUESTED** [review]
The `AppSKey` should also not allow zero values:
image

Otherwise LGTM

**Review by kschiffer — APPROVED** [review]
