### PR TITLE
Check expiration of Rx windows in class A downlink

### LINKED ISSUE #389: Avoid Rx1 in class B/C when it's clearly too late
**Summary:** 

Network Server always attempts Rx1 in class B/C, even when the last Rx1 opportunity is long gone. This is not strictly a bug but it is a costly (PP-PB-PP-)GS roundtrip.

**Steps to Reproduce:** 

1. Start stack
2. Join device
3. Switch to class C
4. Send class A uplink message. Wait a while
5. Send class C downlink message

**What do you see now?**

An attempt in Rx1;

```
 DEBUG Adding downlink task...                  device_class=CLASS_C device_uid=test-app.test-sim grpc_method=DownlinkQueuePush grpc_service=ttn.lorawan.v3.AsNs namespace=grpc queue_length=1 request_id=01D72Y01QM0XB6QKQSEKFDGAWW start_at=2019-03-28 19:56:27.27871 +0000 UTC
  INFO Finished unary call                      duration=28.215618ms grpc_method=DownlinkQueuePush grpc_service=ttn.lorawan.v3.AsNs namespace=grpc request_id=01D72Y01QM0XB6QKQSEKFDGAWW
 DEBUG Finished unary call                      duration=28.734412ms grpc_method=DownlinkQueuePush grpc_service=ttn.lorawan.v3.AsNs namespace=grpc request_id=01D72Y01P96Z03M3HRD64WRF9H
  INFO Finished unary call                      duration=75.204974ms grpc_method=DownlinkQueuePush grpc_service=ttn.lorawan.v3.AppAs namespace=grpc request_id=01D72Y01P96Z03M3HRD64WRF9H
 DEBUG Processing downlink task...              device_uid=test-app.test-sim start_at=2019-03-28 19:56:27.27871 +0000 UTC started_at=2019-03-28 19:56:27.285835 +0000 UTC
 DEBUG transport: loopyWriter.run returning. connection error: desc = "transport is closing" namespace=grpc
 DEBUG Generated downlink                       ack=false device_uid=test-app.test-sim f_cnt=8 f_pending=false f_port=15 m_type=UNCONFIRMED_DOWN mac_count=0 payload_length=15 started_at=2019-03-28 19:56:27.285835 +0000 UTC
 DEBUG Scheduling downlink...                   attempt_rx1=true attempt_rx2=false device_class=CLASS_C device_uid=test-app.test-sim downlink_class=CLASS_A downlink_type=data path_count=1 rx1_delay=5 rx1_frequency=868100000 started_at=2019-03-28 19:56:27.285835 +0000 UTC
 DEBUG Attempting to schedule downlink on gateway class=CLASS_A gateway_eui=00800000A0000DB4 gateway_uid=eui-00800000a0000db4 namespace=gatewayserver/io/udp
 DEBUG Attempting to schedule downlink in receive window class=CLASS_A data_rate=5 frequency=868100000 gateway_eui=00800000A0000DB4 gateway_uid=eui-00800000a0000db4 namespace=gatewayserver/io/udp rx_window=1
 DEBUG Failed to schedule downlink in Rx window class=CLASS_A data_rate=5 error=error:pkg/gatewayserver/scheduling:too_late (too late to transmission scheduled time (delta is `-13.661161781s`)) frequency=868100000 gateway_eui=00800000A0000DB4 gateway_uid=eui-00800000a0000db4 namespace=gatewayserver/io/udp rx_window=1
 DEBUG Attempting to schedule downlink in receive window class=CLASS_A data_rate=0 frequency=0 gateway_eui=00800000A0000DB4 gateway_uid=eui-00800000a0000db4 namespace=gatewayserver/io/udp rx_window=2
 DEBUG Failed to schedule on path               error=error:pkg/gatewayserver/io:tx_schedule (failed to schedule) gateway_uid=eui-00800000a0000db4 grpc_method=ScheduleDownlink grpc_service=ttn.lorawan.v3.NsGs namespace=grpc request_id=01D72Y01SGTHPMAJ0WSCQBD308
  WARN Finished unary call                      duration=412.673µs error=error:pkg/gatewayserver:schedule (failed to schedule) error_correlation_id=91c807bd1d44488d8f6f70597a60a986 error_name=schedule error_namespace=pkg/gatewayserver grpc_code=Aborted grpc_method=ScheduleDownlink grpc_service=ttn.lorawan.v3.NsGs namespace=grpc request_id=01D72Y01SGTHPMAJ0WSCQBD308
  WARN Finished unary call                      duration=7.779368ms error=rpc error: code = Aborted desc = error:pkg/gatewayserver:schedule (failed to schedule) error_correlation_id=91c807bd1d44488d8f6f70597a60a986 error_name=schedule error_namespace=pkg/gatewayserver grpc_code=Aborted grpc_method=ScheduleDownlink grpc_service=ttn.lorawan.v3.NsGs namespace=grpc
  WARN All Gateway Servers failed to schedule downlink attempt_rx1=true attempt_rx2=false device_class=CLASS_C device_uid=test-app.test-sim downlink_class=CLASS_A downlink_type=data error_0=error:pkg/gatewayserver:schedule (failed to schedule) rx1_delay=5 rx1_frequency=868100000 started_at=2019-03-28 19:56:27.285835 +0000 UTC
```

See the GS reported "too late" explanation: `delta is `-13.661161781s`.

**What do you want to see instead?**

Avoid Rx1 in class B/C when it's clearly too late.

**How do you propose to implement this?**

Since upstream and downstream flows are nicely separated and we allow late downlink scheduling based on an uplink message, I think we need the NS to make a guess whether the Rx1 opportunity is gone.

**Can you do this yourself and submit a Pull Request?**

Review and test.

### LINKED ISSUE #396: Use of application class B/C settings in Rx 1
**Summary:** 

Use of application class B/C settings in Rx 1. These are only applicable to Rx 2; there is no uplink token so GS does not have the required timestamp.

**Steps to Reproduce:** 

1. Schedule class C application downlink with `class_b_c` settings without `absolute_time`

**What do you see now?**

NS attempt to schedule in Rx 1

**What do you want to see instead?**

- No attempt to schedule in Rx 1; this is Rx 2 only
- The fixed downlink path is optional; if those are not specified, the downlink path from recent uplink messages should be taken

**How do you propose to implement this?**

Remove scheduling in NS.

**Can you do this yourself and submit a Pull Request?**

Yes, at least a proposal

### PR DESCRIPTION
**Pull request by johanstokking**
**Summary:**

Closes #389 
Closes #396 

**Changes:**

- Check whether the Rx windows have not expired, according to NS server-time

**Notes for Reviewers:**

This does not account for NS-GS latency and GS scheduling delay. Future work documented in #399

### CODE REVIEW

File: pkg/networkserver/downlink.go [hunk 1]
```diff
@@ -676,6 +718,9 @@ func (ns *NetworkServer) processDownlinkTask(ctx context.Context) error {
 
 					default:
 						// Data downlink for Class B/C in Rx1
+						req.Rx1Delay = dev.MACState.CurrentParameters.Rx1Delay
+						req.Rx1Frequency = rx1Freq
```
Comment (htdvisser) [inline pkg/networkserver/downlink.go]: Why don't we also use `downlinkPathsForClassA` for Rx1 of a Class B/C device?

Comment (johanstokking) [reply pkg/networkserver/downlink.go]: Good call. Was planning on fixing that in #396 but will apply in this PR.

Comment (johanstokking) [reply pkg/networkserver/downlink.go]: https://github.com/TheThingsNetwork/lorawan-stack/pull/410/commits/783b87b66d6c3568e98243a9dfda21bf92cb541d
