### PR TITLE
Application Server garbage collection

### LINKED ISSUE #2735: Pub/sub error for non-existent application
#### Summary

I did some pub/sub testing, and created a couple applications and nats/mqtt pub/sub integrations in them. I deleted the apps, but in the console, I'm still getting weird integration errors for non-existent apps:

```
WARN Integration failed                       application_uid=my-new-application error=nats: no servers available for connection namespace=applicationserver/io/pubsub pub_sub_id=test
```

But the app "my-new-application" doesn't exist and I have no integrations in any other app

Screenshot 2020-06-15 at 13 00 03

Screenshot 2020-06-15 at 13 00 09

#### Steps to Reproduce

I'm not 100% sure this is what happened, but I can send any logs or anything else that might be useful as well

1. Create an app
2. Create a pub/sub nats integration
3. Delete the app

#### What do you see now?

```
WARN Integration failed                       application_uid=my-new-application error=nats: no servers available for connection namespace=applicationserver/io/pubsub pub_sub_id=test
```

#### Environment

Mac OS X, running dev stack

#### Can you do this yourself and submit a Pull Request?

No

### PR DESCRIPTION
**Pull request by pgalic96**
#### Summary

Closes #2735
References #14 

#### Changes

- Add `as-db cleanup` command
- Add `Range` to registry interfaces and redis implementation
- Add IS store methods for fetching all applications / devices

#### Testing

To be added, that is why I am making this a draft PR

##### Regressions

This is a new command with new functionality, if the complements are not correctly calculated we can delete live data.

#### Notes for Reviewers

Looking for some feedback on implementation while I am writing tests. I am also still trying to find the right level of abstraction (how to structure the cleaners across various registries in interface).

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: cmd/ttn-lw-stack/commands/as_db.go [hunk 1]
```diff
@@ -0,0 +1,141 @@
...
+	asiopsredis "go.thethings.network/lorawan-stack/v3/pkg/applicationserver/io/pubsub/redis"
+	"go.thethings.network/lorawan-stack/v3/pkg/applicationserver/io/web"
+	asiowebredis "go.thethings.network/lorawan-stack/v3/pkg/applicationserver/io/web/redis"
+	asredis "go.thethings.network/lorawan-stack/v3/pkg/applicationserver/redis"
+	"go.thethings.network/lorawan-stack/v3/pkg/identityserver/store"
+	"go.thethings.network/lorawan-stack/v3/pkg/redis"
+	"go.thethings.network/lorawan-stack/v3/pkg/ttnpb"
+)
+
+func toApplicationSet(list []*ttnpb.ApplicationIdentifiers) (set map[*ttnpb.ApplicationIdentifiers]struct{}) {
```
Comment (adriansmares) [inline cmd/ttn-lw-stack/commands/as_db.go]: These sets should have unique identifiers in them, not pointers to identifiers. The pointers won't even compare correctly (https://play.golang.org/p/gzaizaea0JV)

File: cmd/ttn-lw-stack/commands/as_db.go [hunk 2]
```diff
@@ -0,0 +1,141 @@
...
+	asDBCleanupCommand = &cobra.Command{
+		Use:   "cleanup",
+		Short: "Clean stale Application Server application data",
+		RunE: func(cmd *cobra.Command, args []string) error {
+			if config.Redis.IsZero() {
+				panic("Only Redis is supported by this command")
+			}
+
+			logger.Info("Connecting to Identity Server database...")
+			db, err := store.Open(ctx, config.IS.DatabaseURI)
```
Comment (adriansmares) [inline cmd/ttn-lw-stack/commands/as_db.go]: This will work in deployments where the Identity Server is local, but not in the ones where it is remote. I think we will have to add this method as an RPC that uses cluster authentication.

The component stores are fine (you may assume that you can just open them via Redis).

File: pkg/applicationserver/io/web/redis/registry.go [hunk 3]
```diff
@@ -53,6 +53,10 @@ type WebhookRegistry struct {
 	Redis *ttnredis.Client
 }
 
+func (r *WebhookRegistry) allKey(ctx context.Context) string {
```
Comment (adriansmares) [inline pkg/applicationserver/io/web/redis/registry.go]: This key/index does not exist right now, so you will either need a migration or to actually scan the database.

Checkout how `ns-db` does this here:
https://github.com/TheThingsNetwork/lorawan-stack/blob/865c1a18686d1c1d9d93240e5bf539db2b6fd7df/cmd/ttn-lw-stack/commands/ns_db.go#L49
https://github.com/TheThingsNetwork/lorawan-stack/blob/865c1a18686d1c1d9d93240e5bf539db2b6fd7df/cmd/ttn-lw-stack/commands/redis.go#L73

File: cmd/ttn-lw-stack/commands/as_db.go (hunk 2 above)
Comment (pgalic96) [reply cmd/ttn-lw-stack/commands/as_db.go]: I would say then this whole `as_db` command should be part of an AS RPC that is invoked from somewhere else. If we need to use cluster auth, we will have to do this procedure where we have access to the component and the running cluster.

But then do we invoke this as part of `ttn-lw-cli`? Or do we enhance `as_db` with an ability to attach to the current running component / cluster ?

**Comment by pgalic96** [comment]
@adriansmares I moved the `ns_db` range implementation to redis, and used it to do the scanning, seems to work. Let me know if you like this implementation. Will re-request review as a notification, no rush since it's not a live PR yet.

File: cmd/ttn-lw-stack/commands/as_db.go [hunk 4]
```diff
@@ -0,0 +1,138 @@
...
+	"go.thethings.network/lorawan-stack/v3/pkg/applicationserver/io/web"
+	asiowebredis "go.thethings.network/lorawan-stack/v3/pkg/applicationserver/io/web/redis"
+	asredis "go.thethings.network/lorawan-stack/v3/pkg/applicationserver/redis"
+	"go.thethings.network/lorawan-stack/v3/pkg/identityserver/store"
+	"go.thethings.network/lorawan-stack/v3/pkg/redis"
+	"go.thethings.network/lorawan-stack/v3/pkg/ttnpb"
+)
+
+func toApplicationSet(list []*ttnpb.ApplicationIdentifiers) (set map[ttnpb.ApplicationIdentifiers]struct{}) {
+	set = make(map[ttnpb.ApplicationIdentifiers]struct{})
```
Comment (adriansmares) [inline cmd/ttn-lw-stack/commands/as_db.go]: This is still not ideal - using the structs as keys is not really allowed (if you check the actual struct you will see some `XXX_*` fields in there which are filled by marshallers and will cause equality checks to fail).

I'd still recommend to use strings and `unique.ID` + contexts.

**Comment by adriansmares** [comment]
> @adriansmares I moved the `ns_db` range implementation to redis, and used it to do the scanning, seems to work. Let me know if you like this implementation. Will re-request review as a notification, no rush since it's not a live PR yet.

The range implementation is much better - it's fine to continue with this.

File: cmd/ttn-lw-stack/commands/as_db.go (hunk 2 above)
Comment (adriansmares) [reply cmd/ttn-lw-stack/commands/as_db.go]: Pinging @htdvisser @johanstokking for thoughts on this. Making it an AS RPC would cause the performance of that particular AS instance to plummet most likely, which is why I preferred to have this range process separate from the real components, but at the same time calling the IS from a `-db` command is also not ideal either.

File: api/application_services.proto [hunk 5]
```diff
@@ -119,6 +119,8 @@ service ApplicationRegistry {
       post: "/applications/{application_id}/dev-eui"
     };
   };
+
+  rpc ListAll(google.protobuf.Empty) returns (ListAllApplicationsResponse);
```
Comment (htdvisser) [inline api/application_services.proto]: 1. Without pagination this really isn't going to scale in large networks, so I think we should use that.
2. Can't we use the existing `List` RPC? That already says that _If no user or organization is given, this returns the applications the caller has access to_, so we could make that return everythin if it's called with cluster auth.

File: api/end_device_services.proto [hunk 6]
```diff
@@ -96,6 +96,8 @@ service EndDeviceRegistry {
       delete: "/applications/{application_ids.application_id}/devices/{device_id}"
     };
   };
+
+  rpc ListAll(google.protobuf.Empty) returns(ListAllEndDevicesResponse);
```
Comment (htdvisser) [inline api/end_device_services.proto]: There's no way this is going to scale. We can't return hundreds of thousands of end devices in a single response.

**Review by htdvisser — COMMENTED** [review]
Maybe `as-db` isn't the right place for this, and we should instead put it under some "batch" or "background job" command. But I don't have anything against making RPC calls from a background job.

This is still a bit race-y. On large databases, this command will take quite a long time, so if someone creates a new application between our IS call and our database range, we may accidentally delete it. Maybe it would be better to _first_ range over our own database, and then ask the IS if the application is in the deleted-but-too-late-to-be-restored window.

**Comment by pgalic96** [comment]
I removed some required fields from application and end device protos, I guess that would mean that this PR can land in 3.16 only.

**Comment by htdvisser** [comment]
I'm not sure. It doesn't look like a breaking change actually.

In any case, this isn't going to land in v3.15.1, so changing the milestone.

File: cmd/ttn-lw-stack/commands/as_db.go [hunk 7]
```diff
@@ -0,0 +1,176 @@
...
+			return nil, nil, err
+		}
+		clusterOpts = append(clusterOpts, cluster.WithTLSConfig(tls))
+	}
+	c, err := cluster.New(ctx, &config.Cluster, clusterOpts...)
+	if err != nil {
+		return nil, nil, err
+	}
+	c.Join()
+	time.Sleep(20 * time.Millisecond)
```
Comment (adriansmares) [inline cmd/ttn-lw-stack/commands/as_db.go]: I think this is slightly optimistic, and instead we should look a couple of times the `GetPeerConn` (+delay).

File: cmd/ttn-lw-stack/commands/as_db.go [hunk 8]
```diff
@@ -0,0 +1,176 @@
...
+		if err := tlsConf.Client.ApplyTo(tls); err != nil {
+			return nil, nil, err
+		}
+		clusterOpts = append(clusterOpts, cluster.WithTLSConfig(tls))
+	}
+	c, err := cluster.New(ctx, &config.Cluster, clusterOpts...)
+	if err != nil {
+		return nil, nil, err
+	}
+	c.Join()
```
Comment (adriansmares) [inline cmd/ttn-lw-stack/commands/as_db.go]: Don't forget to check the error, and maybe defer a `Leave`.

File: cmd/ttn-lw-stack/commands/as_db.go [hunk 9]
```diff
@@ -0,0 +1,176 @@
...
+	}
+	asDBCleanupCommand = &cobra.Command{
+		Use:   "cleanup",
+		Short: "Clean stale Application Server application data",
+		RunE: func(cmd *cobra.Command, args []string) error {
+			if config.Redis.IsZero() {
+				panic("Only Redis is supported by this command")
+			}
+			// Initialize AS registry cleaners (together with their local app/dev sets).
+			logger.Info("Initiating pubsub client")
```
Comment (adriansmares) [inline cmd/ttn-lw-stack/commands/as_db.go]: Try to be consistent with PubSub - I think we used `PubSub` everywhere.

File: cmd/ttn-lw-stack/commands/as_db.go [hunk 10]
```diff
@@ -0,0 +1,176 @@
...
+				}
+				pageCounter++
+			}
+			// Cleanup data from AS registries.
+			logger.Info("Cleaning pub sub registry")
+			err = pubsubCleaner.CleanData(ctx, deviceIdentityServerSet)
+			if err != nil {
+				return err
+			}
+			logger.Info("Cleaning app packages registry")
```
Comment (adriansmares) [inline cmd/ttn-lw-stack/commands/as_db.go]: `app packages` -> `application packages`

File: pkg/applicationserver/cleanup.go [hunk 11]
```diff
@@ -0,0 +1,67 @@
...
+	)
+	return err
+}
+
+func (cleaner *RegistryCleaner) DeleteComplement(ctx context.Context, devSet map[string]struct{}) error {
+	for ids := range devSet {
+		devIds, err := unique.ToDeviceID(ids)
+		if err != nil {
+			return err
+		}
```
Comment (adriansmares) [inline pkg/applicationserver/cleanup.go:49]: Use `unique.WithContext` afterwards.
```
	ctx := ctx
	ctx, err = unique.WithContext(ctx, uid)
	if err != nil {
		return nil, err
	}
```
In order to fill the context with the unique data. This should be done after each `unique.ToDeviceID`.

**Review by adriansmares — COMMENTED** [review]
Looks pretty good, but I would love to somehow see a testing procedure for this.

**Comment by pgalic96** [comment]
Regarding testing; Mock response from IS, populating registries with extra application data, running the command and checking what's left in registries would be a good test, the problem is that some/most of these registries do not test the underlying registry interface methods but the tests are tied to the RPC's which this command is not using. Will setup some new test procedures.

File: pkg/unique/unique.go [hunk 12]
```diff
@@ -41,6 +41,10 @@ func ID(ctx context.Context, id ttnpb.IDStringer) (res string) {
 	return res
 }
 
+func GenericID(ctx context.Context) (res string) {
```
Comment (htdvisser) [inline pkg/unique/unique.go]: This is missing godoc.

File: pkg/identityserver/application_registry.go [hunk 13]
```diff
@@ -213,9 +228,12 @@ func (is *IdentityServer) listApplications(ctx context.Context, req *ttnpb.ListA
 		return nil, err
 	}
 
-	for i, app := range apps.Applications {
-		if rights.RequireApplication(ctx, *app.GetIds(), ttnpb.RIGHT_APPLICATION_INFO) != nil {
-			apps.Applications[i] = app.PublicSafe()
+	// If request comes from cluster, skip trimming of application info.
+	if !clusterAuth {
```
Comment (htdvisser) [inline pkg/identityserver/application_registry.go:244]: Should we at least restrict the field mask for cluster auth?

Like we do in `updateEndDevice` (`end_device_registry.go`)

File: pkg/identityserver/application_registry.go [hunk 14]
```diff
@@ -156,29 +157,36 @@ func (is *IdentityServer) getApplication(ctx context.Context, req *ttnpb.GetAppl
...
 	var includeIndirect bool
-	if req.Collaborator == nil {
-		authInfo, err := is.authInfo(ctx)
-		if err != nil {
-			return nil, err
+	var clusterAuth bool
+	// If request comes from cluster (list all applications), skip caller rights check.
+	if clusterauth.Authorized(ctx) == nil && req.Collaborator == nil {
+		clusterAuth = true
+		ctx = store.WithSoftDeleted(ctx, false)
```
Comment (htdvisser) [inline pkg/identityserver/application_registry.go]: Shouldn't the caller decide this?

File: cmd/ttn-lw-stack/commands/as_db.go [hunk 15]
```diff
@@ -0,0 +1,207 @@
...
+	pbtypes "github.com/gogo/protobuf/types"
+	"github.com/spf13/cobra"
+	"go.thethings.network/lorawan-stack/v3/pkg/applicationserver/io/web"
+	"go.thethings.network/lorawan-stack/v3/pkg/cluster"
+	"go.thethings.network/lorawan-stack/v3/pkg/ttnpb"
+	"go.thethings.network/lorawan-stack/v3/pkg/unique"
+	"google.golang.org/grpc"
+)
+
+func NewClusterComponentConnection(ctx context.Context, config Config, role ttnpb.ClusterRole) (*grpc.ClientConn, cluster.Cluster, error) {
```
Comment (htdvisser) [inline cmd/ttn-lw-stack/commands/as_db.go]: - Missing godoc (also the funcs below)
- This looks like it can / will be used by other commands than as-db, so should it be in another file?

File: cmd/ttn-lw-stack/commands/as_db.go [hunk 16]
```diff
@@ -0,0 +1,207 @@
...
+	return deviceIdentityServerSet, nil
+}
+
+var (
+	// Define limit for pagination (maximum defined in protos).
+	limit = uint32(1000)
+	// Max retries to join cluster
+	maxRetries = 5
+	// Delay between retries to join cluster
+	delay       = 500
```
Comment (htdvisser) [inline cmd/ttn-lw-stack/commands/as_db.go]: Why isn't this a time.Duration?

File: cmd/ttn-lw-stack/commands/as_db.go [hunk 17]
```diff
@@ -0,0 +1,207 @@
...
+	}
+	return nil, nil, err
+}
+
+func FetchIdentityServerApplicationSet(ctx context.Context, client ttnpb.ApplicationRegistryClient, clusterAuth grpc.CallOption) (map[string]struct{}, error) {
+	applicationIdentityServerSet := make(map[string]struct{})
+	pageCounter := uint32(1)
+	// Iterate over application list paginated requests and add them to the IS app map.
+	for {
+		res, err := client.List(ctx, &ttnpb.ListApplicationsRequest{
```
Comment (htdvisser) [inline cmd/ttn-lw-stack/commands/as_db.go]: Should we add a little delay so that we won't hit the rate limit?

File: cmd/ttn-lw-stack/commands/as_db.go [hunk 18]
```diff
@@ -0,0 +1,207 @@
...
+	}
+	return applicationIdentityServerSet, nil
+}
+
+func FetchIdentityServerEndDeviceSet(ctx context.Context, client ttnpb.EndDeviceRegistryClient, clusterAuth grpc.CallOption) (map[string]struct{}, error) {
+	deviceIdentityServerSet := make(map[string]struct{})
+	pageCounter := uint32(1)
+	// Iterate over application list paginated requests and add them to the IS app map.
+	for {
+		res, err := client.List(ctx, &ttnpb.ListEndDevicesRequest{
```
Comment (htdvisser) [inline cmd/ttn-lw-stack/commands/as_db.go]: Should we add a little delay so that we won't hit the rate limit?

File: cmd/ttn-lw-stack/commands/as_db.go [hunk 19]
```diff
@@ -0,0 +1,207 @@
...
+			}
+			// Create cluster and grpc connection with identity server.
+			conn, cl, err := NewClusterComponentConnection(ctx, *config, ttnpb.ClusterRole_ENTITY_REGISTRY)
+			if err != nil {
+				return err
+			}
+			defer func() {
+				logger.Debug("Leaving cluster...")
+				if err := cl.Leave(); err != nil {
+					logger.WithError(err).Error("Could not leave cluster")
```
Comment (htdvisser) [inline cmd/ttn-lw-stack/commands/as_db.go:73]: You may want to `return` after this.

File: cmd/ttn-lw-stack/commands/as_db.go [hunk 20]
```diff
@@ -0,0 +1,207 @@
...
+				}
+			}
+			return nil
+		},
+	}
+)
+
+func init() {
+	Root.AddCommand(asDBCommand)
+	asDBCommand.AddCommand(asDBCleanupCommand)
```
Comment (htdvisser) [inline cmd/ttn-lw-stack/commands/as_db.go:157]: Should we perhaps add a `--dry-run` flag as well, so that we can see what the command plans to do?

File: pkg/applicationserver/cleanup.go [hunk 21]
```diff
@@ -0,0 +1,71 @@
...
+
+import (
+	"context"
+
+	"go.thethings.network/lorawan-stack/v3/pkg/cleanup"
+	"go.thethings.network/lorawan-stack/v3/pkg/ttnpb"
+	"go.thethings.network/lorawan-stack/v3/pkg/unique"
+)
+
+type RegistryCleaner struct {
```
Comment (htdvisser) [inline pkg/applicationserver/cleanup.go:26]: Missing godoc. Also on the funcs below.

File: cmd/ttn-lw-stack/commands/as_db.go [hunk 22]
```diff
@@ -0,0 +1,207 @@
...
+			client := ttnpb.NewApplicationRegistryClient(conn)
+			applicationIdentityServerSet, err := FetchIdentityServerApplicationSet(ctx, client, cl.Auth())
+			if err != nil {
+				return err
+			}
+			devClient := ttnpb.NewEndDeviceRegistryClient(conn)
+			deviceIdentityServerSet, err := FetchIdentityServerEndDeviceSet(ctx, devClient, cl.Auth())
+			if err != nil {
+				return err
+			}
```
Comment (htdvisser) [inline cmd/ttn-lw-stack/commands/as_db.go]: I've said before that I think it's dangerous to do it this way, because we may delete things that were created while command runs.

Comment (pgalic96) [reply cmd/ttn-lw-stack/commands/as_db.go]: This is done after the local sets are computed (`RangeToLocalSet`). If there are extra applications created they will be part of the IS set but not of the local sets (unless there is a following flow: app `app-x` data created in AS -> local set in AS computed -> IS set computed -> application `app-x` created in IS . I think this state is probably unreachable, but please confirm this.

Comment (htdvisser) [reply cmd/ttn-lw-stack/commands/as_db.go]: Ah sorry, I now see that that's hidden in those `NewXXXCleaner` funcs.

File: pkg/identityserver/application_registry.go (hunk 14 above)
Comment (pgalic96) [reply pkg/identityserver/application_registry.go]: Should we reuse the `deleted` field in case of cluster auth, i.e. if its set we add `WithSoftDeleted(ctx, false)`? The only concern with this is that it is slightly different than what this field is indicating right now (`store.WithSoftDeleted(ctx, true)`). Otherwise we would need to introduce a new request field which breaks the compatibility commitment.

Comment (pgalic96) [reply pkg/identityserver/application_registry.go]: It wouldn't necessarily break the compatibility commitment if its just a new field, but what I wanted to say is that we have `deleted` field which indicates whether we want to **only** include deleted entities and now it seems like a very hacky approach to add another field like `merge_deleted_and_non_deleted` which wouldn't break compatibility commitment but wouldn't make sense if we can just refactor this to `deleted` and `deleted_only` fields.

File: pkg/applicationserver/io/packages/redis/registry.go [hunk 23]
```diff
@@ -82,6 +83,10 @@ func (r *ApplicationPackagesRegistry) Init(ctx context.Context) error {
 	return nil
 }
 
+func (r *ApplicationPackagesRegistry) allKey(ctx context.Context) string {
```
Comment (adriansmares) [inline pkg/applicationserver/io/packages/redis/registry.go]: Remove this

**Review by adriansmares — APPROVED** [review]
Reviewed `pkg/applicationserver` and the `cmd` changes. They look good.

I'd recommend a `rebase` + `autosquash` and then a review from @johanstokking.

**Comment by pgalic96** [comment]
will wait for approval from @htdvisser before squashing

**Comment by htdvisser** [comment]
No, please go ahead with rebase and history cleanup. I'll review after.

**Comment by pgalic96** [comment]
done

**Review by htdvisser — APPROVED** [review]
Code-owned files LGTM

File: cmd/ttn-lw-stack/commands/as_db.go [hunk 24]
```diff
@@ -0,0 +1,148 @@
...
+	"go.thethings.network/lorawan-stack/v3/pkg/ttnpb"
+)
+
+var (
+	// Define limit for pagination (maximum defined in protos).
+	limit = uint32(1000)
+	// Max retries to join cluster
+	maxRetries = 5
+	// Delay between retries to join cluster
+	delay       = time.Duration(500) * time.Millisecond
```
Comment (johanstokking) [inline cmd/ttn-lw-stack/commands/as_db.go]: These are declared in `cmd/ttn-lw-stack/commands` but they seem very specific to a particular (set of) command(s).

If this is not configurable via flags or a config file, why are they declared at this level and why aren't they consts?

File: cmd/ttn-lw-stack/commands/utils.go [hunk 25]
```diff
@@ -0,0 +1,129 @@
...
+	c, err := cluster.New(ctx, &config.Cluster, clusterOpts...)
+	if err != nil {
+		return nil, nil, err
+	}
+	if err := c.Join(); err != nil {
+		return nil, nil, err
+	}
+	var cc *grpc.ClientConn
+	for i := 0; i < maxRetries; i++ {
+		time.Sleep(delay)
```
Comment (johanstokking) [inline cmd/ttn-lw-stack/commands/utils.go:55]: So this is not obvious that these symbols are just for this use case. There can be so many things to retry or delay.

Take as function parameters maybe?

File: cmd/ttn-lw-stack/commands/utils.go [hunk 26]
```diff
@@ -0,0 +1,129 @@
...
+			return nil, err
+		}
+		for _, app := range res.Applications {
+			applicationIdentityServerSet[unique.ID(ctx, app.GetIds())] = struct{}{}
+		}
+		if len(res.Applications) < int(limit) {
+			break
+		}
+		pageCounter++
+		time.Sleep(paginationDelay)
```
Comment (johanstokking) [inline cmd/ttn-lw-stack/commands/utils.go:85]: Is this against rate limiting or flattening the load curve? I guess that rate limiting is off for cluster auth, so I presume the latter?

File: cmd/ttn-lw-stack/commands/utils.go [hunk 27]
```diff
@@ -0,0 +1,129 @@
...
+		cc, err = c.GetPeerConn(ctx, role, nil)
+		if err == nil {
+			return cc, c, nil
+		}
+	}
+	return nil, nil, err
+}
+
+// FetchIdentityServerApplicationSet returns the set of all non-expired applications in the Identity Server.
+func FetchIdentityServerApplicationSet(ctx context.Context, client ttnpb.ApplicationRegistryClient, clusterAuth grpc.CallOption) (map[string]struct{}, error) {
```
Comment (johanstokking) [inline cmd/ttn-lw-stack/commands/utils.go]: Why are we returning a set if the caller is likely only interested in a slice of unique identifiers?

File: pkg/applicationserver/cleanup.go [hunk 28]
```diff
@@ -0,0 +1,75 @@
...
+	err := cleaner.DevRegistry.Range(ctx, []string{"ids"}, func(ctx context.Context, ids ttnpb.EndDeviceIdentifiers, dev *ttnpb.EndDevice) bool {
+		cleaner.LocalSet[unique.ID(ctx, ids)] = struct{}{}
+		return true
+	},
+	)
+	return err
+}
+
+// DeleteComplement deletes registry application data of all devices in the device set.
+func (cleaner *RegistryCleaner) DeleteComplement(ctx context.Context, devSet map[string]struct{}) error {
```
Comment (johanstokking) [inline pkg/applicationserver/cleanup.go]: Why take a map here?

File: pkg/identityserver/application_registry.go (hunk 13 above)
Comment (johanstokking) [reply pkg/identityserver/application_registry.go:244]: Is this addressed?

**Review by johanstokking — COMMENTED** [review]
Only checked CLI and AS. Comments are mostly code quality related, functionality looks otherwise good!

File: cmd/ttn-lw-stack/commands/utils.go (hunk 26 above)
Comment (pgalic96) [reply cmd/ttn-lw-stack/commands/utils.go:85]: Yes indeed, I will change this to a flag parameter so we can see what works best.

File: pkg/identityserver/application_registry.go (hunk 13 above)
Comment (pgalic96) [reply pkg/identityserver/application_registry.go:244]: Yes, see https://github.com/TheThingsNetwork/lorawan-stack/pull/4653/files#diff-0a302077283e72a9d2eea5fc0ceaf857f4e7c6afe47a86eac138b5d5318722faR164

File: cmd/ttn-lw-stack/commands/as_db.go (hunk 24 above)
Comment (pgalic96) [reply cmd/ttn-lw-stack/commands/as_db.go]: I hardcoded `limit` as its obvious we want to fetch large batches in this method. I moved `maxRetries` and `delay` as function parameters (and scoped them to the `as_db` function) I don't think these two params need to be configurable, it is used only for obtaining peer connection.

File: cmd/ttn-lw-stack/commands/utils.go [hunk 29]
```diff
@@ -0,0 +1,121 @@
...
+			ApplicationIds: nil,
+			FieldMask:      &pbtypes.FieldMask{Paths: []string{"ids"}},
+			Limit:          uint32(1000),
+			Page:           pageCounter,
+		}, clusterAuth)
+		if err != nil {
+			return nil, err
+		}
+		deviceList = append(deviceList, res.EndDevices...)
+		if len(res.EndDevices) < 1000 {
```
Comment (johanstokking) [inline cmd/ttn-lw-stack/commands/utils.go]: I don't think this is correct. The limit is really a limit; "not more than", not necessarily "exactly". Do we have this logic in other places as well?

The preferred approach would be breaking the loop when the received item count is zero or when the total received item count equals or exceeds the total indicated in the response. That value is in a response header though, not in `res`.

Also, limits are defined as consts but there's a literal used in this function twice.

File: cmd/ttn-lw-stack/commands/utils.go [hunk 30]
```diff
@@ -0,0 +1,121 @@
...
+	return deviceList, nil
+}
+
+func setToArray(set map[string]struct{}) []string {
+	keys := make([]string, len(set))
+	i := 0
+	for k := range set {
+		keys[i] = k
+		i++
+	}
```
Comment (johanstokking) [inline cmd/ttn-lw-stack/commands/utils.go:121]:
```suggestion
	keys := make([]string, 0, len(set))
	for k := range set {
		keys = append(keys, k)
	}
```

File: pkg/applicationserver/cleanup.go [hunk 31]
```diff
@@ -0,0 +1,81 @@
...
+
+// CleanData cleans registry device data.
+func (cleaner *RegistryCleaner) CleanData(ctx context.Context, isSet map[string]struct{}) error {
+	complement := cleanup.ComputeSetComplement(isSet, cleaner.LocalSet)
+	devIds := make([]string, len(complement))
+	i := 0
+	for id := range complement {
+		devIds[i] = id
+		i++
+	}
```
Comment (johanstokking) [inline pkg/applicationserver/cleanup.go:75]:
```suggestion
	devIds := make([]string, 0, len(complement))
	for id := range complement {
		devIds = append(devIds, id)
	}
```

**Review by johanstokking — APPROVED** [review]

**Comment by johanstokking** [comment]
Approved with comments. The small code changes aren't strictly necessary but if you address them, please address in all places.

Not sure if this pagination thing needs to be addressed; @htdvisser any opinion on this? We don't want to break the loop too early.

File: cmd/ttn-lw-stack/commands/utils.go (hunk 30 above)
Comment (pgalic96) [reply cmd/ttn-lw-stack/commands/utils.go:121]: I was actually looking into this and this is what I got from the stack overflow thread:

```
In most situations it probably won't make much of a difference, but it's not much more work,
 and in my tests (using a map with 1,000,000 random int64 keys and then generating the array
 of keys ten times with each method), 
it was about 20% faster to assign members of the array directly than to use append.

Although setting the capacity eliminates reallocations, 
append still has to do extra work to check if you've reached capacity on each append.
```

Comment (pgalic96) [reply cmd/ttn-lw-stack/commands/utils.go:121]: Might be relevant if we do operations with 100,000 + keys

Comment (johanstokking) [reply cmd/ttn-lw-stack/commands/utils.go:121]: Ah, ok, thanks for sharing

File: cmd/ttn-lw-stack/commands/utils.go [hunk 32]
```diff
@@ -0,0 +1,123 @@
...
+	"crypto/tls"
+	"time"
+
+	pbtypes "github.com/gogo/protobuf/types"
+	"go.thethings.network/lorawan-stack/v3/pkg/cluster"
+	"go.thethings.network/lorawan-stack/v3/pkg/ttnpb"
+	"google.golang.org/grpc"
+)
+
+const defaultPaginationDelay = 1000
```
Comment (johanstokking) [inline cmd/ttn-lw-stack/commands/utils.go]: Limit, right?

**Review by johanstokking — APPROVED** [review]

File: cmd/ttn-lw-stack/commands/utils.go (hunk 32 above)
Comment (pgalic96) [reply cmd/ttn-lw-stack/commands/utils.go]: ah yeah
