### PR TITLE
Only publish MAC downlink events on success

### LINKED ISSUE #789: Duplicate events
#### Summary

NS publishes an event whenever a MAC command is added to a buffer(in `generateDownlink`), however that does not equate to NS actually scheduling the MAC command. Additionally, the downlink may be generated twice (e.g. in case Rx1 is not possible for Class C device)

#### Steps to Reproduce

1. Look at the source

#### What do you see now?

Duplicate/inapplicable events

#### What do you want to see instead?

Non-duplicate, applicable events

#### How do you propose to implement this?

Return a slice of events from `generateDownlink`

#### Can you do this yourself and submit a Pull Request?

yes

### PR DESCRIPTION
**Pull request by rvolosatovs**
#### Summary

Closes #789 

#### Changes

- Only publish MAC downlink events on successful scheduling
- Fix invalid CIDs used for `RejoinParamSetupReq` and `PingSlotReq` MAC commands
- Wrap multiple return values of MAC enqueuers into a struct

#### Notes for Reviewers

Tested on metal

### CODE REVIEW

File: pkg/networkserver/mac_adr_param_setup.go [hunk 1]
```diff
@@ -60,23 +64,37 @@ func enqueueADRParamSetupReq(ctx context.Context, dev *ttnpb.EndDevice, maxDownL
...
+			"ack_delay_exponent", req.ADRAckDelayExponent,
+		)).Debug("Enqueued ADRParamSetupReq")
+		return []*ttnpb.MACCommand{
+				req.MACCommand(),
+			},
+			1,
+			[]events.DefinitionDataClosure{
+				evtEnqueueADRParamSetupRequest.BindData(req),
+			},
+			true
```
Comment (johanstokking) [inline pkg/networkserver/mac_adr_param_setup.go]: This looks a bit weird on my screen

Comment (rvolosatovs) [reply pkg/networkserver/mac_adr_param_setup.go]: Putting it all on 1 line is even worse IMO.
I tried different layouts, but in the end I couldn't find a way to make it look nice - so I went for clarity. Please open a technical debt issue if you think it's necessary to do something about this.
