### PR TITLE
Fix content flashing in console overview

### LINKED ISSUE #2218: Console overview page content flashing
#### Summary

The overview page changes its title/choosers content when the page loaded:
overview-flashing

#### Steps to Reproduce

1. Go to the overview page and refresh
2. See titles/choosers change

When throttling network requests it becomes even worse

#### What do you see now?

Content changing while the page is available

#### What do you want to see instead?

No content changes

#### Environment

v3.6.2	

#### Can you do this yourself and submit a Pull Request?

@kschiffer @pgalic96

### PR DESCRIPTION
**Pull request by pgalic96**
#### Summary

Closes #2218

#### Changes

- Pass `_BASE` actions instead of general actions to fetching selector

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, database and configuration, according to the stability commitments in `README.md`.
- [x] Testing: The changes are covered with unit tests. The changes are tested manually as well.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/webui/console/views/overview/index.js [hunk 1]
```diff
@@ -77,7 +77,7 @@ const componentMap = {
     return {
       applicationCount: selectApplicationsTotalCount(state),
       gatewayCount: selectGatewaysTotalCount(state),
-      fetching: createFetchingSelector([GET_APPS_LIST, GET_GTWS_LIST])(state),
+      fetching: createFetchingSelector([GET_APPS_LIST_BASE, GET_GTWS_LIST_BASE])(state),
```
Comment (bafonins) [inline pkg/webui/console/views/overview/index.js]: Please move it outside of `connect` so the function is not created any time the store gets updated.

```js
const overviewFetchingSelector = createFetchingSelector([GET_APPS_LIST_BASE, GET_GTWS_LIST_BASE])
```

and then simply use it

File: pkg/webui/console/store/selectors/fetching.js [hunk 2]
```diff
@@ -21,8 +21,8 @@ const selectFetchingEntry = (state, id) => selectFetchingStore(state)[id] || fal
 /**
  * @example
  * const selectFetching = createFetchingSelector([
- * 'GET_ENTITY_LIST',
- * 'SEARCH_ENTITY_LIST'
+ * 'GET_ENTITY_LIST_BASE',
+ * 'SEARCH_ENTITY_LIST_BASE'
```
Comment (kschiffer) [inline pkg/webui/console/store/selectors/fetching.js:25]: The old example is actually correct. What you mean is:
```suggestion
 * GET_ENTITY_LIST_BASE,
 * SEARCH_ENTITY_LIST_BASE
```

**Comment by pgalic96** [comment]
@kschiffer I added webfontloader as per your instructions, I don't observe text flashing anymore but please double check this.

File: pkg/webui/oauth.js [hunk 3]
```diff
@@ -25,6 +26,12 @@ import Init from './lib/components/init'
 
 import createStore from './oauth/store'
 
+WebFont.load({
```
Comment (kschiffer) [inline pkg/webui/oauth.js:29]: While this fixes the issue of FUOT, it is not what we want, since the webfontloader will load the font from Google. Since we need to support offline mode, we need to continue fetching the font as a local asset.

Comment (kschiffer) [reply pkg/webui/oauth.js:29]: After researching about this for a little more, I found this:
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display

If that works then it should be the way to go.

**Comment by pgalic96** [comment]
@kschiffer `fallback` seems as a prefered option which somewhat reduces FOUT but also does not limit accessibility. I have tested it and don't observe both FOUT and FOIT.

File: pkg/webui/styles/fonts.styl [hunk 4]
```diff
@@ -66,5 +70,6 @@
   font-family: 'Material Icons'
   font-style: normal
   font-weight: 400
+  font-display: fallback
```
Comment (kschiffer) [inline pkg/webui/styles/fonts.styl:73]:
```suggestion
  font-display: block
```
For icons, I think this is the better option. It's better not showing anything than the unstyled, lengthy icon ids.
