### PR TITLE
Account for NbTrans in ADR loss rate calculation

### LINKED ISSUE #269: Incorrect loss calculation for ADR
**Summary:** 

The loss calculation function that we use for calculating the NbTrans parameter of  ADR is incorrect if the current NbTrans is greater than 1.

**Steps to Reproduce:** 

1. Consider https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/networkserver/adr.go#L160-L170: `lossRate := float32(up.Payload.GetMACPayload().FHDR.FCnt-ups[0].Payload.GetMACPayload().FHDR.FCnt-uint32(len(ups))) /
float32(up.Payload.GetMACPayload().FHDR.FCnt-ups[0].Payload.GetMACPayload().FHDR.FCnt)`
2. Assume that the EndDevice has NbTrans=2, the history is [1,1,2,2,3,3,4,4,5,5] and the current FCnt is 6.
3. The `lossRate` will become `float32(uint32(6)-uint32(1)-uint32(10)) /
float32(uint32(6)-uint32(1))`

**What do you see now?**

The `lossRate` is something like `8.589935e+08` (because of the uint32 going "negative") while the `lossRate` should have been `0`.

**What do you want to see instead?**

The loss function should keep into account the current NbTrans of the EndDevice.

**How do you propose to implement this?**

- Make the loss function depend on the nbTrans.
- Don't consider the first and last fCnt (because their duplicates may fall outside the window)
- Count missing fCnts in the middle
- I think we can assume that all devices increment by 1, but I do know that there are some non-compliant devices on v2 that sometimes increment by 1000, so we may want to return a loss of 0 if we see unrealistic values.

```go
func loss(fCnts []uint32, nbTrans int) int { ... }

// Zero loss because we have everything:
a.So(loss([]uint32{11, 12, 13}, 1), should.Equal, 0)
a.So(loss([]uint32{11, 11, 12, 12, 13, 13}, 2), should.Equal, 0)
a.So(loss([]uint32{11, 11, 11, 12, 12, 12, 13, 13, 13}, 3), should.Equal, 0)

// Zero loss because we don't know how many duplicates fall outside the window:
a.So(loss([]uint32{11, 12, 12, 13}, 2), should.Equal, 0)
a.So(loss([]uint32{11, 11, 12, 12, 12, 13, 13}, 3), should.Equal, 0)
a.So(loss([]uint32{11, 12, 12, 12, 13}, 3), should.Equal, 0)

// Loss:
a.So(loss([]uint32{11, 13}, 1), should.Equal, 1)
a.So(loss([]uint32{11, 14}, 1), should.Equal, 2)
a.So(loss([]uint32{11, 13, 15}, 1), should.Equal, 2)

a.So(loss([]uint32{11, 11, 12, 13, 13}, 2), should.Equal, 1)
a.So(loss([]uint32{11, 12, 13}, 2), should.Equal, 1) // All we know is that we miss the second 12.

// etc.
```

**What can you do yourself and what do you need help with?**

In v2 I simply removed the entire loss calculation in https://github.com/TheThingsNetwork/ttn/pull/758 until we have a better function for it. Hopefully @rvolosatovs can come up with something that works well.

### PR DESCRIPTION
**Pull request by rvolosatovs**
**Summary:**

Closes #269 

**Changes:**

- Account for `NbTrans` when counting loss rate of packets for ADR
- Reset `RecentADRUplinks` on each ADR parameter change
- Fix `UseADR` handling

**Release Notes: _(optional)_**

- Improved ADR algorithm performance

### CODE REVIEW

File: pkg/networkserver/adr.go [hunk 1]
```diff
@@ -85,6 +85,48 @@ func deviceADRMargin(dev *ttnpb.EndDevice, defaults ttnpb.MACSettings) float32 {
...
+		case fCnt:
+			fCntTrans++
+
+		default:
+			if fCntTrans < nbTrans {
+				d := nbTrans - fCntTrans
+				lost += d
+				n += d
+			}
+			d := (v - fCnt - 1) * nbTrans
```
Comment (htdvisser) [inline pkg/networkserver/adr.go]: This goes wrong on an FCnt reset, right? Or do we clear recent uplinks on reset?

File: pkg/networkserver/adr.go [hunk 2]
```diff
@@ -157,13 +199,11 @@ func adaptDataRate(dev *ttnpb.EndDevice, fps *frequencyplans.Store, defaults ttn
...
-		case lossRate < 0.05:
+		switch r := lossRate(dev.MACState.CurrentParameters.ADRNbTrans, ups...); {
+		case r < 0.05:
 			dev.MACState.DesiredParameters.ADRNbTrans = 1 + dev.MACState.DesiredParameters.ADRNbTrans/3
-		case lossRate < 0.10:
-		case lossRate < 0.30:
+		case r < 0.10:
+		case r < 0.30:
 			dev.MACState.DesiredParameters.ADRNbTrans = 2 + dev.MACState.DesiredParameters.ADRNbTrans/2
 		default:
```
Comment (htdvisser) [inline pkg/networkserver/adr.go]: How about adding a filter for unrealistic values (and just use NbTrans=1 for those)? For example, we see ABP devices that increment a persistent FCnt by 1000 on every power cycle (because they don't want to persist the actual FCnt). We don't want to send all of those to NbTrans=3.

File: pkg/networkserver/adr.go (hunk 1 above)
Comment (rvolosatovs) [reply pkg/networkserver/adr.go]: This will be done in #505
