### PR TITLE
Fix HTTP Error code conversion

### LINKED ISSUE #1014: Error 401 returned from backend with wrong error code
#### Summary

When making api requests without access token and cokie, an error `401` unauthenticated is returned. However when trying to recognize the error using grpc or http codes, the error wasn't recognized. Upon inspection it was found that the grpc code returned is 2, which is unknown error.

#### Steps to Reproduce

1. Make request without access token or cookie (for example, log out in one console tab, and open Gateway list in another console tab)
2. Observe response from the server

#### What do you see now?

```
{  
  "code":2,
  "message":"error:pkg/errors/web:http (HTTP error: code=401, message=You are not logged in)",
  "details":[  
    {  
      "@type":"type.googleapis.com/ttn.lorawan.v3.ErrorDetails",
      "namespace":"pkg/errors/web",
      "name":"http",
      "message_format":"HTTP error: {message}",
      "attributes":{  
        "message":"code=401, message=You are not logged in"
      }
    }
  ]
}
```
#### What do you want to see instead?

The correct grpc code should be 16

#### How do you propose to implement this?

Intercept this error somewhere in backend and set the correct error code

#### Can you do this yourself and submit a Pull Request?

I can do it, but maybe its faster if @htdvisser looks at it (if time allows)

### PR DESCRIPTION
**Pull request by htdvisser**
#### Summary

This Pull Request fixes the conversion from Echo errors to TTN errors.

Additionally it turns the particular errors mentioned in #1014 into TTN errors.

Resolves #1014 	

#### Changes

- Fixed conversion from Echo errors to TTN errors
- Changed errors used in Console OAuth flow

#### Release Notes

- Fixed an issue where incorrect error codes were returned from the console's OAuth flow.

### CODE REVIEW

**Comment by htdvisser** [comment]
TODO: cleanup frontend/sdk code cc: @pgalic96

**Comment by pgalic96** [comment]
https://github.com/TheThingsNetwork/lorawan-stack/blob/feature/971-reset-password-ui/pkg/webui/lib/errors/utils.js#L58-L62

File: pkg/webui/lib/errors/utils.js [hunk 1]
```diff
@@ -118,9 +118,6 @@ export const isPermissionDeniedError = error => (
  */
 export const isUnauthenticatedError = error => (
   grpcStatusCode(error) === 16
```
Comment (pgalic96) [inline pkg/webui/lib/errors/utils.js]: Should we have this as well as in `404` error?
```suggestion
  grpcStatusCode(error) === 16 || httpStatusCode(error) === 401
```

Comment (htdvisser) [reply pkg/webui/lib/errors/utils.js]: We could do that, but then we should do the same for `isInternalError`, `isAlreadyExistsError` and `isPermissionDeniedError`.

File: pkg/console/cookie_auth.go [hunk 2]
```diff
@@ -45,27 +45,22 @@ type authCookie struct {
...
 func (console *Console) getAuthCookie(c echo.Context) (authCookie, error) {
 	value := authCookie{}
 	ok, err := console.AuthCookie().Get(c, &value)
 	if err != nil {
 		return authCookie{}, err
 	}
-
 	if !ok {
-		return authCookie{}, echo.NewHTTPError(http.StatusUnauthorized, "You are not logged in")
+		return authCookie{}, echo.NewHTTPError(http.StatusBadRequest, "No auth cookie")
```
Comment (bafonins) [inline pkg/console/cookie_auth.go]: Should this return `401` instead of `400`? 
This rollbacks changes made in https://github.com/TheThingsNetwork/lorawan-stack/pull/1007

Comment (htdvisser) [reply pkg/console/cookie_auth.go]: Ok

File: pkg/webui/lib/errors/utils.js (hunk 1 above)
Comment (htdvisser) [reply pkg/webui/lib/errors/utils.js]: Done.

File: pkg/console/cookie_auth.go (hunk 2 above)
Comment (htdvisser) [reply pkg/console/cookie_auth.go]: Done.
