### PR TITLE
Overriding desired MAC parameters and defaults

### LINKED ISSUE #60: Add some desired MAC parameters to MAC settings with opinionated defaults
**Summary:** 

Add some desired MAC parameters to the end device's MAC settings with opinionated defaults.

**Why do we need this?**

1. For users to configure custom desired MAC parameters for each end device. This may be based on what's configured in the device repository
2. To fall back to sane defaults that we have identified based on progressive insight running LoRaWAN public and private networks

**What is already there? What do you see now?**

We currently allow a few MAC settings, like `use_adr`, `adr_margin`, `class_b_timeout`, etc.

**What is missing? What do you want to see?**

We need to support at least the following settings:

- `rx1_delay`; defaults to 5 seconds
- `rx2_data_rate_index`; defaults to what is in the frequency plan
- `rx2_frequency`; defaults to what is in the frequency plan

**How do you propose to implement this?**

The above fields to be added to the `MACSettings`, and set as desired parameters on device reset.

Note that the current parameters stay the band defaults, per spec. This means that we stay compliant with devices that have not received desired parameters yet (i.e. ABP devices).

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/1544 by @johanstokking

### LINKED ISSUE #104: Set OTAA devices and specify DevAddr, AppSKey, NwkSKey, FCntUp, FCntDown
**Summary:** 
ability to update or create OTAA devices and specify DevAddr, AppSKey, NetSKey, FcntUp, FnctDown in addition to DevEUI, JoinEUI and AppKey using the cli

**Why do we need this?**
We need to transfer existing devices that have already joined other Network Servers (ttnv2 and others) to ttnv3. Rejoining is not an option since those devices are on the field. We have session keys for those devices and up / down counters

**What is already there? What do you see now?**
ttn-lw-cli devices update and create are there, but the option --session.dev_addr= does not seem to update the registry. I still got "WARN No device matched DevAddr". In addition, --session.keys.app-s-key.key does not work (value not saved). bug?

**What is missing? What do you want to see?**
ttn-lw-cli devices update work as we have with ttnv2: 
ttnctl devices set xxx --override --dev-addr xxx --nwk-s-key xxx --app-s-key xxx --fcnt-up  nnn --fcnt-down  nnn

**How do you propose to implement this?**
not sure. is updating the session the right thing to do?

**Environment:**
lorawan-stack on a linux server.

**What can you do yourself and what do you need help with?**
Test any fix or workaround or try to fix with guidance

### LINKED ISSUE #105: Configure NetID for OTAA and ABP generated DevAddr
**Summary:** 
I haven't seen a way to configure the NetID on the NS. I may have missed something stupid

**Why do we need this?**
Unless I missed something, by default the NetId is zero. Devices are registered in the 0x00/0x01 address range. We need a way to configure the NetId to set a LoRaWAN NetId. Ideally, it should be configurable.

**What is already there? What do you see now?**
I haven't seen anything

**What is missing? What do you want to see?**
configure the netid as an env variable or in the config file.

**How do you propose to implement this?**
use standard config

**Environment:**
lorawan-stack on a linux server

**What can you do yourself and what do you need help with?**

### LINKED ISSUE #144: Make less assumptions about devices, BE compatibility
**Summary:** 

In current implementation NS assumes that `EndDevice.DefaultMACParameters` always contains a valid `MACParameters` device can be reset to, but that's not always the case.
2019-02-14-14 25 28-screenshot
As can be seen in Backend Interfaces spec, `DeviceProfile` contains optional fields, which NS assumes to be always set to valid values.
Instead of using a `DefaultMACParameters` field, `MACSettings` should contain the optional fields from `DeviceProfile` and on reset, NS should use these values with the fallback to NS defaults(#101)/band defaults.

**Why do we need this?**

To be compliant with Backend Interfaces and make less assumptions about devices

**What is already there? What do you see now?**

Assumption, that `DefaultMACParameters` contains a valid `MACParameters`

**What is missing? What do you want to see?**

Various overrides in `MACSettings`. We should not modify the `MACParameters` message, as that should stay internal for NS use only.

**How do you propose to implement this?**

Add the fields from `DeviceProfile` to `MACSettings` in a similar manner as #101, remove `DefaultMACParameters`, add `MACSettings` to `EndDeviceVersion`

### LINKED ISSUE #159: segmentation violation ns on downlink to ABP device downlink.go l 167
**Summary:** 
registered a device as an ABP device (--supports-join=false).
ns crashes on downlink

exit status 2

**Steps to Reproduce:** 
register a device on the ns that is already on the field:

go run ./cmd/ttn-lw-cli devices create test dev2 --defaults=true \
--supports-join=false \
--join-eui=70B3D59520000000 --dev-eui=A81758FFFE032277 \
--root-keys.root-key-id=dev2 \
--root-keys.app-key.key=4F939595CE83288AFEF81BD881C3C36E \
--session.dev-addr=010B600C \
--session.keys.app-s-key.key=A15BEF4A3233274AE917E4AFB19055F2 \
--session.keys.f-nwk-s-int-key.key=9E2FB61D7310C9279886DB79FA52F9F4 \
--lorawan-version=1.0.2 --lorawan-phy-version=1.0.2-b \
--frequency-plan-id EU_863_870 \
--mac-settings.use-adr=true \
--resets-f-cnt=false \
--resets-join-nonces=false \
--session.last-f-cnt-up=45872 \
--session.last-n-f-cnt-down=1880 \
--uses-32-bit-f-cnt=true

**What do you see now?**
ns crash on downlink.go l 167:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x215c15c]

goroutine 219 [running]:
go.thethings.network/lorawan-stack/pkg/networkserver.generateDownlink(0x28f7a20, 0xc000eba600, 0xc0002dc6c0, 0xe60019, 0xc000168070, 0x28f7a20, 0xc000eba5a0, 0x3, 0x0, 0xc00023a560, ...)
	/Users/pdubois/lorawan-stack/pkg/networkserver/downlink.go:167 +0xafc

**What do you want to see instead?**
ns handling gacefully uplink and downlink.

**How do you propose to implement this?**
on line 167, EndDeviceIdentifiers is nil. 
i think the create command does not create the dev ids:

go run ./cmd/ttn-lw-cli devices get test dev2 --session
{
  "ids": {
    "device_id": "dev2",
    "application_ids": {
      "application_id": "test"
    }
  },
....

**Environment:**
macOS, but crashes also on Centos and Ubuntu.

**What can you do yourself and what do you need help with?**

### PR DESCRIPTION
**Pull request by rvolosatovs**
**Summary:**

References #5 
Closes #60 
Closes #104 
Closes #105 
Closes #144 
Closes #159 

**Changes:**

- Add all optional fields from Backend Interfaces `DeviceProfile` as well as additional MAC parameters to `MACSettings`
- Ensure device API is aligned with `DeviceProfile ` from Backend Interfaces
- Make `MACSettings` optional
- Allow specifying NS-wide default `MACSettings` to fallback to if not defined by the device
- Update protoc image version (requires https://github.com/TheThingsIndustries/protoc-gen-fieldmask/pull/20)
- Set `RxDelay` to `5s` by default
- Move defaults from CLI to NS
- Validate the devices on create, ensure the session/MAC state are valid
- Allow specifying `session` for OTAA devices(#104)
- Fix panic reported in #104 and #159 (missing fieldpaths are the reason, of course)
- Remove `DefaultMACParameters`

**Notes for Reviewers:**

Other MAC parameters, if required, will be added in another PR - please create an issue
I tested this with a Class C device in a simulator

**Release notes:**
Backwards-incompatible API and DB-model changes were introduced. Any created devices need to be recreated.

### CODE REVIEW

File: pkg/networkserver/utils.go [hunk 1]
```diff
@@ -160,6 +160,9 @@ outerDown:
 	dev.MACState.DesiredParameters.UplinkDwellTime = fp.DwellTime.GetUplinks()
 	dev.MACState.DesiredParameters.DownlinkDwellTime = fp.DwellTime.GetDownlinks()
 
+	// TODO: Apply NS-wide default (https://github.com/TheThingsIndustries/lorawan-stack/issues/1544)
+	dev.MACState.DesiredParameters.Rx1Delay = ttnpb.RX_DELAY_5
```
Comment (johanstokking) [inline pkg/networkserver/utils.go]: This has to come from config. No magic numbers in code please.

File: pkg/networkserver/downlink.go [hunk 2]
```diff
@@ -124,6 +138,7 @@ func generateDownlink(ctx context.Context, dev *ttnpb.EndDevice, maxDownLen, max
 		fPending = fPending || !ok
 	}
 	cmds = append(cmds, dev.MACState.PendingRequests...)
+	logger.WithField("cmds", cmds).Debug("ADDED MAC")
```
Comment (johanstokking) [inline pkg/networkserver/downlink.go]: Casing

File: pkg/networkserver/grpc_gsns.go [hunk 3]
```diff
@@ -713,10 +715,10 @@ func (ns *NetworkServer) handleUplink(ctx context.Context, up *ttnpb.UplinkMessa
 
 // newDevAddr generates a DevAddr for specified EndDevice.
 func (ns *NetworkServer) newDevAddr(context.Context, *ttnpb.EndDevice) types.DevAddr {
-	nwkAddr := make([]byte, types.NwkAddrLength(ns.NetID))
+	nwkAddr := make([]byte, types.NwkAddrLength(ns.netID))
```
Comment (johanstokking) [inline pkg/networkserver/grpc_gsns.go]: Please file and issue and TODO here that we generate `DevAddr` from a `DevAddrPrefix`, which falls back to the `NetID`. But in clustered NS, we're using a subset of the `NetID`.

**Comment by rvolosatovs** [comment]
Looks like our config package does not support custom types:
```
panic: config: cannot work with "types.NetID" in configuration at name "ns.net_id"

goroutine 1 [running]:
go.thethings.network/lorawan-stack/pkg/config.(*Manager).setDefaults(0xc000646680, 0x15c1f8d, 0x2, 0xc0000ffb00, 0x188a820, 0xc000586d30)
        /home/rvolosatovs/src/go.thethings.network/lorawan-stack/pkg/config/config.go:485 +0x2f85
go.thethings.network/lorawan-stack/pkg/config.(*Manager).setDefaults(0xc000646680, 0x0, 0x0, 0xc0000ffb00, 0x188a040, 0xc000586800)
        /home/rvolosatovs/src/go.thethings.network/lorawan-stack/pkg/config/config.go:483 +0xaed
go.thethings.network/lorawan-stack/pkg/config.Initialize(0x1967804, 0xc, 0x195e875, 0x6, 0x188a040, 0xc000586800, 0x2bc6cd0, 0x2, 0x2, 0xc000586800)
        /home/rvolosatovs/src/go.thethings.network/lorawan-stack/pkg/config/config.go:151 +0x450
go.thethings.network/lorawan-stack/pkg/config.InitializeWithDefaults(0x1967804, 0xc, 0x195e875, 0x6, 0x188a040, 0xc000586800, 0x0, 0x0, 0x0, 0x19674e0)
        /home/rvolosatovs/src/go.thethings.network/lorawan-stack/pkg/config/config.go:188 +0x144
exit status 2
```
I will address this next week

File: pkg/networkserver/config.go [hunk 4]
```diff
@@ -28,6 +29,8 @@ type Config struct {
 	DeduplicationWindow time.Duration          `name:"deduplication-window" description:"Time window during which, duplicate messages are collected for metadata"`
 	CooldownWindow      time.Duration          `name:"cooldown-window" description:"Time window starting right after deduplication window, during which, duplicate messages are discarded"`
 	DownlinkPriorities  DownlinkPriorityConfig `name:"downlink-priorities" description:"Downlink message priorities"`
+	NetID               types.NetID            `name:"net_id" description:"NetID of this Network Server"`
+	DefaultMACSettings  *ttnpb.MACSettings     `name:"mac_defaults" description:"Default MAC settings to use if not specified for device"`
```
Comment (johanstokking) [inline pkg/networkserver/config.go]: - Does it add any value to make this nullable?
- Please add sane defaults in the `cmd/internal` package

File: pkg/networkserver/downlink.go (hunk 2 above)
Comment (rvolosatovs) [reply pkg/networkserver/downlink.go]: Whoops, shouldn't have been added

**Comment by johanstokking** [comment]
@rvolosatovs 

>Looks like our config package does not support custom types

It does support some, indeed `types.NetID` should be added.

File: api/end_device.proto [hunk 5]
```diff
@@ -175,18 +176,30 @@ message EndDeviceVersion {
 }
 
 message MACSettings {
-  bool use_adr = 1 [(gogoproto.customname) = "UseADR"];
+  google.protobuf.BoolValue use_adr = 1 [(gogoproto.customname) = "UseADR"];
```
Comment (htdvisser) [inline api/end_device.proto]: Although this doesn't break existing JSON API, this is not binary compatible with our existing protos, so existing databases and existing clients/servers may become incompatible.

File: api/end_device.proto [hunk 6]
```diff
@@ -175,18 +176,30 @@ message EndDeviceVersion {
...
   // The ADR margin tells the network server how much margin it should add in ADR requests.
   // A bigger margin is less efficient, but gives a better chance of successful reception.
-  uint32 adr_margin = 2 [(gogoproto.customname) = "ADRMargin"];
+  google.protobuf.FloatValue adr_margin = 2 [(gogoproto.customname) = "ADRMargin"];
```
Comment (htdvisser) [inline api/end_device.proto]: Although this doesn't break existing JSON API, this is not binary compatible with our existing protos, so existing databases and existing clients/servers may become incompatible.

File: api/end_device.proto [hunk 7]
```diff
@@ -175,18 +176,30 @@ message EndDeviceVersion {
...
+  google.protobuf.Duration class_b_timeout = 3 [(gogoproto.stdduration) = true];
   // Deadline for the device to respond to requests from the Network Server.
-  google.protobuf.Duration class_c_timeout = 4 [(gogoproto.stdduration) = true, (gogoproto.nullable) = false];
+  google.protobuf.Duration class_c_timeout = 4 [(gogoproto.stdduration) = true];
   // The interval after which a DevStatusReq MACCommand shall be sent.
-  google.protobuf.Duration status_time_periodicity = 5 [(gogoproto.stdduration) = true, (gogoproto.nullable) = false];
+  google.protobuf.Duration status_time_periodicity = 5 [(gogoproto.stdduration) = true];
   // Number of uplink messages after which a DevStatusReq MACCommand shall be sent.
-  uint32 status_count_periodicity = 6;
+  google.protobuf.UInt32Value status_count_periodicity = 6;
```
Comment (htdvisser) [inline api/end_device.proto]: Although this doesn't break existing JSON API, this is not binary compatible with our existing protos, so existing databases and existing clients/servers may become incompatible.

File: api/end_device.proto (hunk 5 above)
Comment (htdvisser) [reply api/end_device.proto]: Also, I don't know how the CLI's flag handling will work for this. We may have to write some logic for these wrappers (I can do that if needed). Also below

File: pkg/networkserver/config.go [hunk 8]
```diff
@@ -19,15 +19,23 @@ import (
...
-	DownlinkPriorities  DownlinkPriorityConfig `name:"downlink-priorities" description:"Downlink message priorities"`
+	Devices                       DeviceRegistry         `name:"-"`
+	DownlinkTasks                 DownlinkTaskQueue      `name:"-"`
+	DeduplicationWindow           time.Duration          `name:"deduplication-window" description:"Time window during which, duplicate messages are collected for metadata"`
+	CooldownWindow                time.Duration          `name:"cooldown-window" description:"Time window starting right after deduplication window, during which, duplicate messages are discarded"`
+	DownlinkPriorities            DownlinkPriorityConfig `name:"downlink-priorities" description:"Downlink message priorities"`
+	NetID                         types.NetID            `name:"net_id" description:"NetID of this Network Server"`
+	DefaultADRMargin              *float32               `name:"default-adr-margin" description:"The default margin Network Server should add in ADR requests if not configured in device's MAC settings"`
```
Comment (htdvisser) [inline pkg/networkserver/config.go]: We could also put these in a `Defaults` struct inside the `Config` struct

File: api/end_device.proto (hunk 6 above)
Comment (rvolosatovs) [reply api/end_device.proto]: We did not release the `3.0.0` yet, so non-backwards compatible changes should be fine

File: pkg/networkserver/config.go (hunk 8 above)
Comment (rvolosatovs) [reply pkg/networkserver/config.go]: Originally I used `MACSettings` directly for this, but it did not work well with the CLI.
I don't think we should redefine `MACSettings` here

File: cmd/ttn-lw-cli/internal/util/flags.go [hunk 9]
```diff
@@ -23,6 +23,7 @@ import (
 	"time"
 
 	"github.com/gogo/protobuf/proto"
+	"github.com/gogo/protobuf/types"
```
Comment (rvolosatovs) [inline cmd/ttn-lw-cli/internal/util/flags.go]: We import this package as `pbtypes` @htdvisser

Comment (htdvisser) [reply cmd/ttn-lw-cli/internal/util/flags.go]: Only if we already import `go.thethings.network/lorawan-stack/pkg/types`

**Comment by rvolosatovs** [comment]
Blocking #104

**Comment by rvolosatovs** [comment]
@johanstokking @htdvisser any update on this?

**Comment by htdvisser** [comment]
You didn't request my review, so I only commented on the API things that I noticed. I'll remove my review request. If you do want a full review from me, please re-request.

**Comment by rvolosatovs** [comment]
@htdvisser I made a bunch more changes from #144  here, since I was modifying `MACSettings` anyway.
Please make a full review.
Also note that I added more `*Value` messages in `MACSettings`, so there are some ugly flags in CLI again
2019-02-15-14 35 31-screenshot
Please fix that

**Comment by rvolosatovs** [comment]
Setting priority to high, since we need this to make the first release

File: api/end_device.proto [hunk 10]
```diff
@@ -80,12 +81,18 @@ message MACParameters {
   DataRateIndex rx2_data_rate_index = 11;
   // Frequency for Rx2 (Hz).
   uint64 rx2_frequency = 12;
+  // Maximum uplink duty cycle (of all channels).
+  AggregatedDutyCycle max_duty_cycle = 13;
```
Comment (rvolosatovs) [inline api/end_device.proto]: No functional changes in this message, moved things around for better allignment with `MACSettings` and clarity

File: api/end_device.proto [hunk 11]
```diff
@@ -175,18 +173,79 @@ message EndDeviceVersion {
...
+    PingSlotPeriod value = 1;
+  }
+  message AggregatedDutyCycleValue {
+    AggregatedDutyCycle value = 1;
+  }
+  message RxDelayValue {
+    RxDelay value = 1;
+  }
+
+  // Maximum delay for the device to answer a MAC request or a confirmed downlink frame.
```
Comment (rvolosatovs) [inline api/end_device.proto]: Field order here is aligned with `DeviceProfile`

File: api/end_device.proto [hunk 12]
```diff
@@ -175,18 +173,79 @@ message EndDeviceVersion {
...
+  // Must be set if the device supports class B.
```
Comment (rvolosatovs) [inline api/end_device.proto]: @htdvisser @johanstokking do we need to enforce this? BE says we should, but it looks like we could also just use a NS default?

File: api/end_device.proto [hunk 13]
```diff
@@ -175,18 +173,79 @@ message EndDeviceVersion {
...
+  PingSlotPeriodValue ping_slot_periodicity = 2;
+  // Data rate index of the class B ping slot.
+  // Must be set if the device supports class B.
+  DataRateIndexValue ping_slot_data_rate_index = 3;
+  // Frequency of the class B ping slot (Hz).
+  // Must be set if the device supports class B.
+  uint64 ping_slot_frequency = 4;
+
+  // Maximum delay for the device to answer a MAC request or a confirmed downlink frame.
+  // Must be set if the device supports class C.
```
Comment (rvolosatovs) [inline api/end_device.proto]: @htdvisser @johanstokking do we need to enforce this? BE says we should, but it looks like we could also just use a NS default?

File: api/end_device.proto [hunk 14]
```diff
@@ -175,18 +173,79 @@ message EndDeviceVersion {
...
+  // Must be set if the device is ABP.
+  google.protobuf.UInt32Value rx1_data_rate_offset = 7;
+  // Data rate index for Rx2.
+  // Must be set if the device is ABP.
+  DataRateIndexValue rx2_data_rate_index = 8;
+  // Frequency for Rx2 (Hz).
+  // Must be set if the device is ABP.
+  uint64 rx2_frequency = 9;
+  // List of factory-preset frequencies.
+  // Must be set if the device is ABP.
```
Comment (rvolosatovs) [inline api/end_device.proto]: @htdvisser @johanstokking do we need to enforce this? BE says we should, but it looks like we could also just use the band default?

File: api/end_device.proto [hunk 15]
```diff
@@ -175,18 +173,79 @@ message EndDeviceVersion {
...
+  repeated uint64 factory_preset_frequencies = 10;
+
+  // Maximum uplink duty cycle (of all channels).
+  AggregatedDutyCycleValue max_duty_cycle = 11;
+
+  // Whether the device supports 32-bit frame counters.
+  // Must be set if the device MAC version is 1.0.
```
Comment (rvolosatovs) [inline api/end_device.proto]: @htdvisser @johanstokking do we need to enforce this? BE says we should, but it looks like we could also just use a NS default? I believe we don't break anything if we just always assume 32-bit counters?

**Comment by htdvisser** [comment]
I agree that we can relax the BE requirements and fallback to defaults if they are not set.

I'm currently working on other things myself, so if you want to make the CLI nicer for the wrapper types, you can see how I did it for the google wrappers in https://github.com/TheThingsNetwork/lorawan-stack/pull/101/commits/d12117d011b73e8279698113f3af58a9c29ffa86. Should just be a bit of copy-pasting.

File: pkg/networkserver/downlink.go [hunk 16]
```diff
@@ -49,6 +48,18 @@ type DownlinkTaskQueue interface {
 
 var errNoDownlink = errors.Define("no_downlink", "no downlink to send")
 
+const DefaultClassCTimeout = 15 * time.Second
+
+func deviceClassCTimeout(dev *ttnpb.EndDevice, defaults ttnpb.MACSettings) time.Duration {
```
Comment (htdvisser) [inline pkg/networkserver/downlink.go]: I like this better than how you do it in adr

File: pkg/networkserver/errors.go [hunk 17]
```diff
@@ -35,13 +35,11 @@ var (
...
 	errFCntTooHigh               = errors.DefineInvalidArgument("f_cnt_too_high", "FCnt is too high")
 	errGatewayServerNotFound     = errors.DefineNotFound("gateway_server_not_found", "Gateway Server not found")
-	errInvalidADRMargin          = errors.DefineInvalidArgument("adr_margin", "invalid ADR margin")
 	errInvalidChannelIndex       = errors.DefineInvalidArgument("channel_index", "invalid channel index")
-	errInvalidClassBTimeout      = errors.DefineInvalidArgument("class_b_timeout", "invalid class B timeout")
-	errInvalidClassCTimeout      = errors.DefineInvalidArgument("class_c_timeout", "invalid class C timeout")
 	errInvalidConfiguration      = errors.DefineInvalidArgument("configuration", "invalid configuration")
 	errInvalidDataRate           = errors.DefineInvalidArgument("data_rate", "invalid data rate")
 	errInvalidFieldMask          = errors.DefineInvalidArgument("field_mask", "invalid field mask")
+	errInvalidFieldValue         = errors.DefineInvalidArgument("field_value", "invalid value of field `{field}`")
```
Comment (htdvisser) [inline pkg/networkserver/errors.go]: These kind of changes should result in changes in `messages.json`, but I don't see anything in this PR. Also, Travis doesn't complain about it, so please check that.

**Comment by rvolosatovs** [comment]
@htdvisser https://github.com/TheThingsNetwork/lorawan-stack/pull/101/commits/5c93eeb51e0c6ffc51b4dfc8ce45035e42a10855 should fix it

File: pkg/networkserver/config.go (hunk 8 above)
Comment (johanstokking) [reply pkg/networkserver/config.go]: `Defaults` doesn't have to be `MACSettings`. I'm strongly in favor of introducing a struct for this.

File: pkg/networkserver/downlink.go [hunk 18]
```diff
@@ -267,16 +286,21 @@ outer:
 		return nil, nil, errUnknownSNwkSIntKey
 	}
 	if dev.Session.SNwkSIntKey.KEKLabel != "" {
```
Comment (johanstokking) [inline pkg/networkserver/downlink.go]: Use `cryptoutil.UnwrapAES128Key()`; does exactly this

File: pkg/networkserver/grpc_deviceregistry.go [hunk 19]
```diff
@@ -45,82 +46,206 @@ func (ns *NetworkServer) Set(ctx context.Context, req *ttnpb.SetEndDeviceRequest
...
+			"mac_state.current_parameters",
+			"mac_state.desired_parameters",
+			"queued_application_downlinks",
+		)
+	}
+
 	var addDownlinkTask bool
-	dev, err := ns.devices.SetByID(ctx, req.Device.EndDeviceIdentifiers.ApplicationIdentifiers, req.Device.EndDeviceIdentifiers.DeviceID, req.FieldMask.Paths, func(dev *ttnpb.EndDevice) (*ttnpb.EndDevice, []string, error) {
-		paths := req.FieldMask.Paths
+	dev, err := ns.devices.SetByID(ctx, req.Device.EndDeviceIdentifiers.ApplicationIdentifiers, req.Device.EndDeviceIdentifiers.DeviceID, gets, func(dev *ttnpb.EndDevice) (*ttnpb.EndDevice, []string, error) {
```
Comment (johanstokking) [inline pkg/networkserver/grpc_deviceregistry.go]: Q; why is `SetByID()` not taking `ttnpb.EndDeviceIdentifiers`?

File: pkg/networkserver/grpc_deviceregistry.go [hunk 20]
```diff
@@ -45,82 +46,206 @@ func (ns *NetworkServer) Set(ctx context.Context, req *ttnpb.SetEndDeviceRequest
...
+				"session",
+			); err != nil {
+				return nil, nil, errInvalidFieldMask.WithCause(err)
+			}
+
+			addDownlinkTask = ttnpb.HasAnyField(req.FieldMask.Paths,
+				"mac_state.device_class",
+				"queued_application_downlinks",
+			) && req.Device.MACState.DeviceClass != ttnpb.CLASS_A &&
+				(len(req.Device.QueuedApplicationDownlinks) > 0 || !req.Device.MACState.CurrentParameters.Equal(req.Device.MACState.DesiredParameters))
```
Comment (johanstokking) [inline pkg/networkserver/grpc_deviceregistry.go]: Please make this statement readable

File: pkg/networkserver/grpc_deviceregistry.go [hunk 21]
```diff
@@ -45,82 +46,206 @@ func (ns *NetworkServer) Set(ctx context.Context, req *ttnpb.SetEndDeviceRequest
...
+		if ttnpb.HasAnyField(req.FieldMask.Paths, "session.keys.s_nwk_s_int_key.kek_label") && (req.Device.Session == nil || len(req.Device.Session.SessionKeys.GetSNwkSIntKey().GetKEKLabel()) == 0) {
+			return nil, nil, errInvalidFieldValue.WithAttributes("field", "session.keys.s_nwk_s_int_key.kek_label")
+		}
+		if ttnpb.HasAnyField(req.FieldMask.Paths, "session.keys.nwk_s_enc_key.key") && (req.Device.Session == nil || len(req.Device.Session.SessionKeys.GetNwkSEncKey().GetKey()) == 0) {
+			return nil, nil, errInvalidFieldValue.WithAttributes("field", "session.keys.nwk_s_enc_key.key")
+		}
+		if ttnpb.HasAnyField(req.FieldMask.Paths, "session.keys.nwk_s_enc_key.kek_label") && (req.Device.Session == nil || len(req.Device.Session.SessionKeys.GetNwkSEncKey().GetKEKLabel()) == 0) {
+			return nil, nil, errInvalidFieldValue.WithAttributes("field", "session.keys.nwk_s_enc_key.kek_label")
+		}
+		if ttnpb.HasAnyField(req.FieldMask.Paths, "session.keys.app_s_key.key") && (req.Device.Session == nil || len(req.Device.Session.SessionKeys.GetAppSKey().GetKey()) == 0) {
```
Comment (johanstokking) [inline pkg/networkserver/grpc_deviceregistry.go]: What is `app_s_key` doing here?

File: pkg/networkserver/grpc_deviceregistry.go [hunk 22]
```diff
@@ -45,82 +46,206 @@ func (ns *NetworkServer) Set(ctx context.Context, req *ttnpb.SetEndDeviceRequest
...
+			); err != nil {
+				return nil, nil, errInvalidFieldMask.WithCause(err)
+			}
 		}
 
 		if req.Device.SupportsJoin {
-			return &req.Device, paths, nil
+			var hasSession bool
+			for _, p := range sets {
+				if p == "session" || strings.HasPrefix(p, "session.") {
```
Comment (johanstokking) [inline pkg/networkserver/grpc_deviceregistry.go]: Don't we have a helper for this?

File: pkg/networkserver/grpc_gsns.go [hunk 23]
```diff
@@ -277,20 +297,25 @@ outer:
...
 			)
 		} else {
 			if dev.matchedSession.SNwkSIntKey == nil || len(dev.matchedSession.SNwkSIntKey.Key) == 0 {
-				logger.Warn("Device missing SNwkSIntKey in registry")
+				logger.Warn("Device missing SNwkSIntKey in registry, skipping...")
 				continue
 			}
 
 			var sNwkSIntKey types.AES128Key
 			if dev.matchedSession.SNwkSIntKey.KEKLabel != "" {
```
Comment (johanstokking) [inline pkg/networkserver/grpc_gsns.go]: See above

File: pkg/networkserver/mac_dev_status.go [hunk 24]
```diff
@@ -27,10 +27,30 @@ var (
...
+	if dev.GetMACSettings().GetStatusTimePeriodicity() != nil {
+		tp = *dev.MACSettings.StatusTimePeriodicity
+	} else if defaults.StatusCountPeriodicity != nil {
+		tp = *defaults.StatusTimePeriodicity
+	}
+
+	if cp == 0 && tp == 0 ||
+		dev.LastDevStatusReceivedAt != nil &&
+			(cp == 0 || dev.MACState.LastDevStatusFCntUp+cp > dev.Session.LastFCntUp) &&
+			(tp == 0 || dev.LastDevStatusReceivedAt.Add(tp).After(time.Now())) {
```
Comment (johanstokking) [inline pkg/networkserver/mac_dev_status.go]: I'm fine with multiple if-statements for readability. The compiler optimizes that away anyway.

File: pkg/networkserver/grpc_deviceregistry.go (hunk 22 above)
Comment (rvolosatovs) [reply pkg/networkserver/grpc_deviceregistry.go]: Unfortunately not, I tried using `ttnpb.HasAnyField(sets, "session")`, but that caused bugs (https://github.com/TheThingsNetwork/lorawan-stack/issues/104#issuecomment-465074076)
We need to check if `sets` contains any or all of `session` fields, this was the easiest way to do this and it looked like this feature is not required by other components, so I did not add a helper for it. I was also confused about how to name the function, since we already have `HasAnyField`.

File: pkg/networkserver/mac_dev_status.go (hunk 24 above)
Comment (rvolosatovs) [reply pkg/networkserver/mac_dev_status.go]: I extracted `cp == 0 && tp == 0`, I don't really see how I can further improve readability by using multiple `if` statements. I tried `switch`, but that does not help

File: pkg/networkserver/grpc_deviceregistry.go (hunk 19 above)
Comment (rvolosatovs) [reply pkg/networkserver/grpc_deviceregistry.go]: We already discussed this before.
Consistency with `GetByEUI`(in NS and JS) and `SetByEUI`(in JS) and being explicit.

File: pkg/networkserver/grpc_deviceregistry.go (hunk 20 above)
Comment (rvolosatovs) [reply pkg/networkserver/grpc_deviceregistry.go]: What would be "readable" in this case and what makes this not readable?
Can you make a suggestion?(ctrl+g)

Comment (johanstokking) [reply pkg/networkserver/grpc_deviceregistry.go]: That, or variables and a nice logical expression.

File: pkg/networkserver/grpc_deviceregistry.go (hunk 19 above)
Comment (johanstokking) [reply pkg/networkserver/grpc_deviceregistry.go]: I don't agree and I don't see the issues you mention.

The `*ByEUI` version is clear and is not related.

I'm suggesting this also to align with AS, which does exactly this. See [here](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/applicationserver/registry.go#L30-L33).

File: pkg/networkserver/grpc_deviceregistry.go (hunk 20 above)
Comment (johanstokking) [reply pkg/networkserver/grpc_deviceregistry.go]: But I'm also fine leaving it this way.

File: pkg/networkserver/grpc_deviceregistry.go (hunk 22 above)
Comment (johanstokking) [reply pkg/networkserver/grpc_deviceregistry.go]: You can invert it; `ttnpb.HasAnyField([]string{"session"}, sets...)`

File: pkg/networkserver/grpc_deviceregistry.go (hunk 19 above)
Comment (rvolosatovs) [reply pkg/networkserver/grpc_deviceregistry.go]: Please create an issue and let's work/discuss this there. It's out of scope of this PR.
