### PR TITLE
Various Device creation fixes in JS SDK

### LINKED ISSUE #566: Fix key generation for Devices in JS SDK after api changes
**Summary:** 
#519 changed the way AES128Keys were encoded in the API. The SDK still uses a base64 encoding for the keys it is generating itself. This needs to be fixed.

**Steps to Reproduce:** 
1. Create a device using the SDK with the new API, using the `setDefaults` option
2. Get an error message from the backend stating something like `invalid slice length`

**What do you see now?**
Errors when creating devices using AES128Key in hex notation

**What do you want to see instead?**
No errors when creating a device.

**Environment:**
JS SDK in node or browser

**How do you propose to implement this?**
Changing the random byte generators to hex encoding

**Can you do this yourself and submit a Pull Request?**
Yes.

### LINKED ISSUE #567: Prevent JS rpc calls in SDK Device creation with ABP
**Summary:** 
The JS SDK currently tries to query the JoinServer even when `supports_join` is off (ABP enabled).

**Steps to Reproduce:** 
1. Create a Device using the JS SDK with the `abp` option to true
2. Get an error from the backend (`no JoinEUI specified`) after the SDK tried to query the JoinServer rpc
3. Device creation fails

**What do you see now?**
Device creation failing when `abp` is enabled

**What do you want to see instead?**
Device creation running through without calling JS rpcs

**Environment:**
JS SDK on node and browser

**How do you propose to implement this?**
Adding a simple condition to the path splitter that will disregard JS paths when `supports_join` is true

**Can you do this yourself and submit a Pull Request?**
Yes.

### LINKED ISSUE #568: Use available browser or node implementation of URL in JS SDK
**Summary:** 
The JS SDK currently uses `import { URL } from 'url'` to handle URL values. This will however only work in node environments. In browsers, `window.URL` should be used instead.

**Steps to Reproduce:** 
1. Do any Device service function in the JS SDK using the browser
2. Get an error message, originating from the fact that `url` cannot be imported in the browser

**What do you see now?**
Errors on Device creation in browser

**What do you want to see instead?**
No errors

**Environment:**
JS SDK in browser

**How do you propose to implement this?**
Simply use `window.URL` when `URL` is unavailable

**Can you do this yourself and submit a Pull Request?**
Yes.

### PR DESCRIPTION
**Pull request by kschiffer**
**Summary:**
Closes #566 
Closes #567 
Closes #568

Referencing #332 

**Changes:**
- Change encoding of keys to hex in device key generation
- Fix usage of `URL` class in browsers
- Prevent rpc calls to JS when the device has `supports_join` set to `false`
- Fix faulty composition of default values with provided values

**Notes for Reviewers:**
It's a couple of quick fixes. See the respective issues. These are all necessary for #332 to work properly.

**Release Notes: _(optional)_**
- Change encoding of keys to hex in device key generation (JS SDK)
- Fix usage of `URL` class in browsers (JS SDK)
- Prevent rpc calls to JS when the device has `supports_join` set to `false` (JS SDK)
- Fix faulty composition of default values with provided values during device creation (JS SDK)

### CODE REVIEW

File: sdk/js/src/service/devices/index.js [hunk 1]
```diff
@@ -183,12 +188,13 @@ class Devices {
 
   async create (applicationId, device, { abp = false, setDefaults = true, withRootKeys = false } = {}) {
     let dev = device
+    const Url = URL ? URL : window.URL
```
Comment (bafonins) [inline sdk/js/src/service/devices/index.js]:
```suggestion
    const Url = window.URL ? window.URL : URL
```

Comment (kschiffer) [reply sdk/js/src/service/devices/index.js]: This would error in NodeJS. Why do you want it changed?

Comment (kschiffer) [reply sdk/js/src/service/devices/index.js]: Will merge now, pls open an issue if I missed something here.
