### PR TITLE
console: Allow dynamic frequencies and hide desired fields

### LINKED ISSUE #5893: End device settings when using multicast/abp
### Summary

> When using multicast, I shouldn’t see any desired settings because desired settings are not applicable in multicast (there are no uplinks in multicast, so you cannot edit any parameters). The ping slot frequency of 0 is not visible, same for maximum duty cycle. And the beacon frequency is not allowed to be zero, while a zero ping slot frequency is not sent to the server. 

Also `0` should be a valid ping slot and beacon frequency in the device advanced settings (meaning automatic).

### Steps to Reproduce

Use US915 FSB2, Multicast, class B and see the end device settings panel.

### Current Result

Many irrelevant fields when using multicast.

### Expected Result

Only relevant fields should be editable.

### Relevant Logs

_No response_

### URL

_No response_

### Deployment

The Things Stack Open Source (self-hosted)

### The Things Stack Version

3.22.1

### Client Name and Version

_No response_

### Other Information

_No response_

### Proposed Fix

As proposed before by @johanstokking we should add a `macspec` module that can provide relevant constaints for a particular band and RP version. Such module can than be used by the Console to determine whether fields should be rendered or not.

### Contributing

- [X] I can help by doing more research.
- [X] I can help by implementing a fix after the proposal above is approved.
- [X] I can help by testing the fix before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

### PR DESCRIPTION
**Pull request by kschiffer**
#### Summary
Fixes #5893

#### Changes

- Allow setting `0` as a frequency value for ping slot and beacon frequency (meaning dynamic frequency)
- Hide desired MAC fields when using multicast end devices

#### Testing

Manual testing.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/webui/console/components/mac-settings-section/index.js [hunk 1]
```diff
@@ -513,26 +529,27 @@ const MacSettingsSection = props => {
...
-            name="mac_settings.desired_adr_ack_delay_exponent"
-            component={Select}
-            options={adrAckDelayOptions}
-            tooltipId={tooltipIds.ADR_ACK_DELAY}
-            fieldWidth="xs"
-          />
-        </>
-      )}
+      {isNewLorawanVersion &&
+        !isMulticast(
```
Comment (mjamescompton) [inline pkg/webui/console/components/mac-settings-section/index.js]: This is not a function

Comment (mjamescompton) [reply pkg/webui/console/components/mac-settings-section/index.js]: Error on expanding network layer on device general settings

File: pkg/webui/console/views/device-general-settings/network-server-form/validation-schema.js [hunk 2]
```diff
@@ -134,33 +135,26 @@ const validationSchema = Yup.object()
 
         return schema.shape({
           beacon_frequency: Yup.lazy(frequency => {
```
Comment (mjamescompton) [inline pkg/webui/console/views/device-general-settings/network-server-form/validation-schema.js]: frequency is declared but never read

File: pkg/webui/console/views/device-general-settings/network-server-form/validation-schema.js [hunk 3]
```diff
@@ -134,33 +135,26 @@ const validationSchema = Yup.object()
...
-              Yup.passValues(sharedMessages.validateNumberGte),
+            return Yup.number().test(
+              'is-valid-freq',
+              sharedMessages.validateFreqDynamic,
+              dynamicFrequencyTest,
             )
-
-            return schema
           }),
           desired_beacon_frequency: Yup.lazy(frequency => {
```
Comment (mjamescompton) [inline pkg/webui/console/views/device-general-settings/network-server-form/validation-schema.js]: frequency is declared but never read

**Review by mjamescompton — CHANGES_REQUESTED** [review]

**Review by ryaplots — APPROVED** [review]
lgtm
