### PR TITLE
Restore downlink queue on join-accept

### LINKED ISSUE #402: Downlink queue is reset on join-accept
**Summary:** 

Regression since #400; any items in the downlink queue are lost when the device joins.

**Steps to Reproduce:** 

1. Activate the device
2. Schedule a few downlink messages
3. List the queued messages; they're there
4. Reset the device for a rejoin
5. List the queued messages; they're gone

**What do you see now?**

Downlink queue is reset on rejoin.

**What do you want to see instead?**

The downlink queue to be preserved. In V3, we consider the application downlink queue independent of underlying network session.

For some use cases, however, a device reset may make any scheduled items in the downlink queue void. Since with closing this issue, the V3 behavior will be to preserve items in the queue, applications become responsible for clearing the queue.

**How do you propose to implement this?**

On join-accept, then NS gives the queue to AS, store the items as-is back in NS.

**Can you do this yourself and submit a Pull Request?**

Yes

### PR DESCRIPTION
**Pull request by johanstokking**
**Summary:**

Replaces #403 
Closes #402 

**Changes:**

- Restores downlink queue in original session
- Added test case for recalculation

### CODE REVIEW

File: pkg/applicationserver/applicationserver.go [hunk 1]
```diff
@@ -437,6 +442,18 @@ func (as *ApplicationServer) handleJoinAccept(ctx context.Context, ids ttnpb.End
 				StartedAt: time.Now().UTC(),
 			}
 			mask = append(mask, "pending_session")
+			if !joinAccept.PendingSession && len(joinAccept.InvalidatedDownlinks) > 0 {
+				// The Network Server reset the downlink queue as the new security session invalidated it.
+				// The invalidated downlink queue is passed as part of the join-accept and the Application Server should recalculate it.
+				// This changes the LastAFCntDown in the session, so it should be run as part of the transaction.
+				logger := logger.WithField("count", len(joinAccept.InvalidatedDownlinks))
+				logger.Debug("Recalculating downlink queue to restore downlink queue on join")
+				if err := as.recalculateDownlinkQueue(ctx, dev, previousSession, joinAccept.InvalidatedDownlinks, 1, link); err != nil {
```
Comment (htdvisser) [inline pkg/applicationserver/applicationserver.go]: Why start with FCnt 1? Shouldn't we start with 0?
