### PR TITLE
Remove hardcoded app root paths

### LINKED ISSUE #727: Replace hard-coded console routes with APP_ROOT config value
#### Summary
We currently still use hard coded `console` values inside routes, when these should be replaced with the `window.APP_ROOT` value to enable configurations with root URI other than `console`.

#### Steps to Reproduce
1. Configure the stack to have a `--console.mount` other than `console`
2. See the console not working

#### What do you see now?
Console not working when the mount is different than `console`

#### What do you want to see instead?
Console working regardless.

#### Environment
Console in browser.

#### How do you propose to implement this?
Replace all occurrences of `console` inside routes (and similar props) with `window.APP_ROOT`

#### Can you do this yourself and submit a Pull Request?
Yes but help welcome.

### PR DESCRIPTION
**Pull request by kschiffer**
#### Summary
Closes #727.

#### Changes
- Move environment mapper to own module and use snakeCase
- Refactor env prop references accordingly
- Change routing to use  the `app_root` as `basename`
- Refactor all routes accordingly
- Both for oauth and console app
- Various related minor fixes and improvements
- Remove unnecessary env context provider, introduced by cc @pgalic96 (see [here](https://github.com/TheThingsNetwork/lorawan-stack/commit/59d6efde5b1b494504c7d32b8d41a8702c60f099))

#### Notes for Reviewers
Obviously a lot of refactoring here, so maybe better to go commit by commit. The new approach using `basename` saves us a lot of referencing `env.appRoot`. Please check this also by changing the mount path of the console.

#### Release Notes
- Fixed console handling of configured mount paths other than `/console`

### CODE REVIEW

File: pkg/webui/components/header/index.js [hunk 1]
```diff
@@ -123,11 +96,11 @@ Header.propTypes = {
    * @param {boolean} exact - Flag identifying whether the path should be matched exactly
    */
   navigationEntries: PropTypes.arrayOf(PropTypes.shape({
-    path: PropTypes.string.isRequired,
+    path: PropTypes.string,
```
Comment (bafonins) [inline pkg/webui/components/header/index.js]: `<NavigationBar />` requires this entry

File: pkg/webui/console/views/application-add/index.js [hunk 2]
```diff
@@ -94,7 +94,7 @@ export default class Add extends React.Component {
         })
 
       const { ids: { application_id }} = result
-      dispatch(push(`/console/applications/${application_id}`))
+      dispatch(push(`/applications/${application_id}`))
```
Comment (bafonins) [inline pkg/webui/console/views/application-add/index.js]: since you are doing this to other files, move this to `matchDispatchToProps`

File: pkg/webui/console/views/application-collaborator-edit/index.js [hunk 3]
```diff
@@ -72,7 +72,7 @@ import api from '../../api'
     dispatch(getApplicationCollaborator(appId, collaboratorId, isUser))
   },
   redirectToList (appId) {
-    dispatch(replace(`/console/applications/${appId}/collaborators`))
+    dispatch(replace(`/applications/${appId}/collaborators`))
```
Comment (bafonins) [inline pkg/webui/console/views/application-collaborator-edit/index.js]: since you are doing this to other files, move this to `matchDispatchToProps`

File: pkg/webui/console/views/application-integration-add/index.js [hunk 4]
```diff
@@ -54,7 +54,7 @@ export default class ApplicationIntegrationAdd extends Component {
   handleSubmitSuccess () {
     const { dispatch, appId } = this.props
 
-    dispatch(push(`/console/applications/${appId}/integrations`))
+    dispatch(push(`/applications/${appId}/integrations`))
```
Comment (bafonins) [inline pkg/webui/console/views/application-integration-add/index.js]: since you are doing this to other files, move this to `matchDispatchToProps`

File: pkg/webui/console/views/gateway-api-key-add/index.js [hunk 5]
```diff
@@ -73,7 +73,7 @@ export default class GatewayApiKeyAdd extends React.Component {
   handleApprove () {
     const { dispatch, gtwId } = this.props
 
-    dispatch(replace(`/console/gateways/${gtwId}/api-keys`))
+    dispatch(replace(`/gateways/${gtwId}/api-keys`))
```
Comment (bafonins) [inline pkg/webui/console/views/gateway-api-key-add/index.js]: since you are doing this to other files, move this to `matchDispatchToProps`

File: pkg/webui/console/views/gateway-collaborator-edit/index.js [hunk 6]
```diff
@@ -90,7 +90,7 @@ import api from '../../api'
 
   return (
     <Breadcrumb
-      path={`/console/gateways/${gtwId}/collaborators/${collaboratorId}/edit`}
+      path={`/gateways/${gtwId}/collaborators/${collaboratorId}/edit`}
```
Comment (bafonins) [inline pkg/webui/console/views/gateway-collaborator-edit/index.js]:
```suggestion
      path={`/gateways/${gtwId}/collaborators/${collaboratorId}`}
```

File: pkg/webui/oauth/views/create-account/index.js [hunk 7]
```diff
@@ -114,7 +114,7 @@ export default class CreateAccount extends React.PureComponent {
         user: { ids: { user_id }, ...rest },
       })
 
-      push('/oauth/login', {
+      push('/login', {
```
Comment (bafonins) [inline pkg/webui/oauth/views/create-account/index.js]: see `L134`

File: pkg/webui/console/views/application-collaborator-edit/index.js (hunk 3 above)
Comment (kschiffer) [reply pkg/webui/console/views/application-collaborator-edit/index.js]: This is already in map dispatch to props.

File: pkg/webui/components/header/index.js [hunk 8]
```diff
@@ -20,46 +20,19 @@ import NavigationBar from '../navigation/bar'
...
   handleLogout = () => null,
-  dropdownItems = defaultDropdownItems(handleLogout),
-  navigationEntries = defaultNavigationEntries,
+  dropdownItems,
+  navigationEntries,
   user,
   searchable,
   handleSearchRequest = () => null,
   anchored = false,
+  appRoot,
```
Comment (bafonins) [inline pkg/webui/components/header/index.js]: not used

File: pkg/webui/console/views/app/index.js [hunk 9]
```diff
@@ -35,41 +35,42 @@ import style from './app.styl'
...
-                  <Route path={`${env.app_root}/login`} component={Login} />
-                  <Route path={env.app_root} component={Landing} />
-                </Switch>
-              </div>
-            </main>
-            <Footer className={style.footer} />
-          </div>
-        </ErrorView>
-      </EnvProvider>
+      <ErrorView ErrorComponent={FullViewError}>
```
Comment (bafonins) [inline pkg/webui/console/views/app/index.js]: The header links do not use `basename` when the `<FullViewError />` is rendered

File: pkg/webui/console/views/app/index.js [hunk 10]
```diff
@@ -35,41 +35,42 @@ import style from './app.styl'
...
+        <div className={style.app}>
+          <IntlHelmet
+            titleTemplate={`%s - ${siteTitle ? `${siteName} - ` : ''}${siteName}`}
+            defaultTitle={siteName}
+          />
+          <div id="modal-container" />
+          <Header className={style.header} appRoot={appRoot} />
```
Comment (bafonins) [inline pkg/webui/console/views/app/index.js]:
```suggestion
          <Header className={style.header} />
```

File: pkg/webui/components/header/index.js [hunk 11]
```diff
@@ -112,21 +84,21 @@ Header.propTypes = {
   dropdownItems: PropTypes.arrayOf(PropTypes.shape({
     title: PropTypes.message.isRequired,
     icon: PropTypes.string,
-    path: PropTypes.string.isRequired,
+    path: PropTypes.string,
```
Comment (bafonins) [inline pkg/webui/components/header/index.js]: it is `required` in `<NavigationBar/>` and the app crashes if you dont pass an entry without the `path` entry

Comment (kschiffer) [reply pkg/webui/components/header/index.js]: These are the proptypes for the dropdown items, they aren't even passed to the `<NavigationBar>`.

Comment (kschiffer) [reply pkg/webui/components/header/index.js]: In general, we can improve our recurring proptypes by referencing them rather than redefining. Also this particular one should be solved rather like this:
```js
PropTypes.arrayOf(
    PropTypes.oneOfType([
      PropTypes.shape({
        title: PropTypes.message.isRequired,
        icon: PropTypes.string,
        path: PropTypes.string,
        action: PropTypes.func.isRequired,
      }),
      PropTypes.shape({
        title: PropTypes.message.isRequired,
        icon: PropTypes.string,
        path: PropTypes.string.isRequired,
        action: PropTypes.func,
      }),
    ])
  ).isRequired,
```

However, fixing this here would be too out of scope for this PR. I'll create an issue.
