### PR TITLE
Fix error handling of event streams

### LINKED ISSUE #932: Console does not show error if events stream gets refused
#### Summary

During today's demo we found that the console doesn't show any error if the events stream gets refused (for the user not having sufficient rights).

#### Steps to Reproduce

1. Assume application `foo`
2. Give non-admin user `bar` `right_application_info` on application `foo`
3. As user `bar` look at the events widget on the overview page of application `foo`

#### What do you see now?

Nothing in the UI, but the development tools do show a 403 for the events call.

#### What do you want to see instead?

Ideally events flowing of course, which will be taken care of by #869, but if a user doesn't have sufficient rights to see events, I'd like to see an error in the UI.

#### How do you propose to implement this?

Show an error if the event stream 403's

#### Can you do this yourself and submit a Pull Request?

Nope, no idea where to start. Assigning to @bafonins, who can reassign if he things someone else should do this.

### PR DESCRIPTION
**Pull request by kschiffer**
#### Summary
Closes #932 and a general issue on event streams that caused errors for opening streams to be swallowed.

#### Changes
- Modify stream logic in JS SDK to await the initial request result of the stream endpoint enabling proper catching of errors
- Fix request logic middleware to call `done()` when the stream closes
- Pass stream errors to the `<EventSubscription />` via the error selector
- Add display logic for event stream errors
- Extend error proptype to accept `code` and `grpc_code` property
- Some related refactoring of `propTypes` and `defaultProps` into class statics

#### Notes for Reviewers
I think it's better to use async/await to the extent possible in `sdk/js/src/api/stream.js`, so we can await the initial request and react on errors, before returning the channel. The old implementation failed to catch/handle the error that was thrown in these cases. 

#### Release Notes
- Fixed an issue that resulted in some event errors not being shown in the console

### CODE REVIEW

**Comment by bafonins** [comment]
please assign me when it ready for review

File: pkg/webui/console/store/middleware/logics/events.js [hunk 1]
```diff
@@ -68,31 +67,42 @@ const createEventsConnectLogics = function (
...
           channel.on('start', () => dispatch(startEventsSuccess(id)))
           channel.on('event', message => dispatch(getEventSuccess(id, message)))
-          channel.on('error', error => dispatch(getEventFailure(id, error)))
+          channel.on('error', function (error) {
+            const status = selectEntityEventsStatus(getState(), id)
+            if (status === CONNECTION_STATUS.CONNECTING) {
+              dispatch(startEventsFailure(id, error))
+              done()
+            } else {
+              dispatch(getEventFailure(id, error))
```
Comment (bafonins) [inline pkg/webui/console/store/middleware/logics/events.js]: if we stick to this implementation, should `done()` be called here as well?

Comment (kschiffer) [reply pkg/webui/console/store/middleware/logics/events.js]: Not sure about this. The way I see it, an error during retrieval of an event does not necessarily mean that the stream has closed altogether.

File: sdk/js/src/api/stream/stream.js [hunk 2]
```diff
@@ -96,6 +97,10 @@ export default async function (payload, url) {
           notify(listeners[EVENTS.ERROR], error)
           listeners = null
         })
+    }).catch(function (error) {
```
[the remark this answers is not in the document]
Comment (kschiffer) [reply sdk/js/src/api/stream/stream.js]: If we don't add this, the error will be swallowed, because it occurs in a promise that runs after the subscription object has been returned.

What other implementation do you suggest?

[the remark this answers is not in the document]
Comment (kschiffer) [reply sdk/js/src/api/stream/stream.js]: I've tried several implementations here:
- Awaiting the initial request ⟶ makes us lose the start event (which I think is not an issue, is also similar to how [`nes`](https://github.com/hapijs/nes#client-1) works)
- Exposing an `open()` function to the returned subscription object, to be able to open the stream after the handlers have been set ⟶ messes up our SDK API
- Using current implementation with added catch block ⟶ makes `error` event ambiguous (event error, or stream start error)

File: pkg/webui/console/store/middleware/logics/events.js (hunk 1 above)
Comment (bafonins) [reply pkg/webui/console/store/middleware/logics/events.js]: https://github.com/TheThingsNetwork/lorawan-stack/pull/974/files#diff-1ef843661c3cb6cc93d5f07c76d59dd8R97

Comment (kschiffer) [reply pkg/webui/console/store/middleware/logics/events.js]: Indeed. It should call `done()` then.

File: sdk/js/src/api/stream/stream.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (bafonins) [reply sdk/js/src/api/stream/stream.js]: 1. https://gist.github.com/bafonins/1a8d3f7840652fb1e5756c69d3a14df6 - something like this, can add some `async/await` to make it prettier. note, it doesnt really matter where you call the `open()` method (before/after adding listeners). dont really this approach.
2. https://gist.github.com/bafonins/2e60e9f28b5fd13b7c9aecf67348e74f - `resolve/reject` based on `fetch` result and propagate errors to the user 
3. add `.catch` to the `fetch` request and notify listeners on `events.error`, but then we have to clearly separate errors caused by reading chunked data and errors caused by failed `fetch`.

File: pkg/webui/console/store/middleware/logics/events.js [hunk 3]
```diff
@@ -68,31 +67,42 @@ const createEventsConnectLogics = function (
...
 
         try {
           channel = await onEventsStart([ id ])
+
           channel.on('start', () => dispatch(startEventsSuccess(id)))
           channel.on('event', message => dispatch(getEventSuccess(id, message)))
-          channel.on('error', error => dispatch(getEventFailure(id, error)))
+          channel.on('error', function (error) {
+            const status = selectEntityEventsStatus(getState(), id)
+            if (status === CONNECTION_STATUS.CONNECTING) {
```
Comment (bafonins) [inline pkg/webui/console/store/middleware/logics/events.js]: see https://github.com/TheThingsNetwork/lorawan-stack/pull/974/files#r304372739, if you decide to go with option 3, then it would be nice to move this to selectors, something like `selectEventsStreamConnected`, etc.

File: sdk/js/src/api/stream/stream.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (kschiffer) [reply sdk/js/src/api/stream/stream.js]: Took inspiration from your approaches to implement it in a way that will allow us to await the request (like my first bullet point) without losing the `start` event.

This allows us to keep the original usage of the stream in the event logic.

**Comment by kschiffer** [comment]
> Also, I noticed some prop-types related errors in the console if passing just regular Error object to the <ErrorMessage/> components

Yeah, this is a separate issue that I would like to solve in a different issue/PR.
