### PR TITLE
Fix editorconfig errors

### LINKED ISSUE #2723: Update EditorConfig
#### Summary

Code in the repo does not comply with EditorConfig present.
We should update the config to exclude e.g. `LICENSE` etc

#### Why do we need this?

To run https://github.com/jedmao/eclint on CI and ensure code is compliant

#### What is already there? What do you see now?

`.editorconfig`, which does not correctly describe the formatting expected in the repo

#### What is missing? What do you want to see?

Necessary additions to `.editorconfig`

#### How do you propose to implement this?

Update `.editorconfig`

#### How do you propose to test this?

CI should pass

#### Can you do this yourself and submit a Pull Request?

yes

### PR DESCRIPTION
**Pull request by rvolosatovs**
#### Summary

Closes #2723 

#### Changes

- Run `eclint fix` (NOTE, that by some reason binary files are modified as well, but that seems to be a bug in the tool)
- Fix some issues not catched by `eclint fix`
- Update `.editorconfig`:
	- max length limit is not respected basically anywhere, so just remove it for now.
	- add proper exclusion rules

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md`. The target branch is set to `master` if the changes are fully compatible with existing API, database, configuration and CLI.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: cmd/ttn-lw-cli/commands/end_device_templates.go [hunk 1]
```diff
@@ -347,9 +347,9 @@ mapping many end device templates with a generic template.
 Typical use cases are:
 
 1. Assigning identifiers from a mapping file to device templates matching on
-   mapping key.
+	mapping key.
```
Comment (johanstokking) [inline cmd/ttn-lw-cli/commands/end_device_templates.go]: What’s the change here; spaces to tabs? That’s gonna break here; this is alignment for CLI

File: cmd/ttn-lw-cli/commands/end_devices.go [hunk 2]
```diff
@@ -923,11 +923,11 @@ the device ID.
 
 This command may take end device identifiers from stdin.`,
 		Example: `To generate a QR code for a single end device:
-  ttn-lw-cli end-devices generate-qr app1 dev1
+	ttn-lw-cli end-devices generate-qr app1 dev1
```
Comment (johanstokking) [inline cmd/ttn-lw-cli/commands/end_devices.go]: I think this is fine in places like this

File: doc/themes/the-things-stack/layouts/shortcodes/tts.html [hunk 3]
```diff
@@ -1 +1 @@
-The Things Stack
\ No newline at end of file
+The Things Stack
```
Comment (johanstokking) [inline doc/themes/the-things-stack/layouts/shortcodes/tts.html]: Does this go well?

**Comment by rvolosatovs** [comment]
> There’s a `doc/.config.toml.swp` checked in; that doesn’t seem necessary
> 
> Can we make this part of CI?

This is usually handled by `.gitignore`, but we can add a CI check as well. Please file an issue.

File: doc/data/api/ttn.lorawan.v3/enums.yml [hunk 4]
```diff
@@ -252,71 +252,71 @@ DownlinkPathConstraint:
   values:
   - name: DOWNLINK_PATH_CONSTRAINT_NONE
     comment: |2
-       Indicates that the gateway can be selected for downlink without constraints by the Network Server.
+      Indicates that the gateway can be selected for downlink without constraints by the Network Server.
```
Comment (johanstokking) [inline doc/data/api/ttn.lorawan.v3/enums.yml]: This is generated; is the generation fixed as well?

Comment (htdvisser) [reply doc/data/api/ttn.lorawan.v3/enums.yml]: Yeah this is indeed generated. I'll take a look at the generator.

File: pkg/applicationserver/applicationserver_test.go [hunk 5]
```diff
@@ -110,23 +110,23 @@ func TestApplicationServer(t *testing.T) {
...
-          parameter: encoder.js`),
+	'1.0':
+		- firmware_version: 1.1
+			payload_format:
+				up:
+					type: javascript
+					parameter: decoder.js
+				down:
+					type: javascript
+					parameter: encoder.js`),
```
Comment (htdvisser) [inline pkg/applicationserver/applicationserver_test.go]: This doesn't look quite right. We shouldn't be indenting YAML with tabs just because it happens to be in a Go file.

File: pkg/basicstation/cups/server_test.go [hunk 6]
```diff
@@ -138,17 +138,17 @@ func (m *mockGatewayClient) UpdateAPIKey(ctx context.Context, in *ttnpb.UpdateGa
...
+	"cupsUri": "https://thethingsnetwork.org:443",
+	"tcUri": "",
+	"cupsCredCrc": 1398343300,
+	"tcCredCrc": 0,
+	"station": "2.0.0(minihub/debug) 2018-12-06 09:30:35",
+	"model": "minihub",
+	"package": "2.0.0",
+	"keys": [
+		392840017
+	]
```
Comment (htdvisser) [inline pkg/basicstation/cups/server_test.go]: This doesn't look quite right. We shouldn't be indenting JSON with tabs just because it happens to be in a Go file.

File: pkg/webui/components/button/index.js [hunk 7]
```diff
@@ -154,49 +154,49 @@ const commonPropTypes = {
   /** The message to be displayed within the button. */
   message: PropTypes.message,
   /**
-   * A flag specifying whether the `danger` styling should applied to the
-   * button.
-   */
+  * A flag specifying whether the `danger` styling should applied to the
+  * button.
+  */
```
Comment (htdvisser) [inline pkg/webui/components/button/index.js]: I don't know how prettier would feel about this.

File: doc/data/api/ttn.lorawan.v3/enums.yml (hunk 4 above)
Comment (htdvisser) [reply doc/data/api/ttn.lorawan.v3/enums.yml]: @rvolosatovs you can cherry-pick add87c594aebe3a507b38e39d33b240583faaa49 for new generated data

**Comment by johanstokking** [comment]
Need input from @kschiffer @bafonins @pgalic96 @mjamescompton to hear how these JavaScript files should be formatted and validated.

Note that next up is a CI check that checks the format; one missing space and your PR doesn't get a green merge button

File: pkg/webui/components/button/index.js (hunk 7 above)
Comment (kschiffer) [reply pkg/webui/components/button/index.js]: Indeed. This is not common JSDoc styling either.

**Comment by kschiffer** [comment]
> Need input from [**@kschiffer**](https://github.com/kschiffer) [**@bafonins**](https://github.com/bafonins) [**@pgalic96**](https://github.com/pgalic96) [**@mjamescompton**](https://github.com/mjamescompton) to hear how these JavaScript files should be formatted and validated.

We use JSPrettier to streamline JS code format. It's currently not part of CI (I think that's because we had some clashes with other formatting rules earlier, cc @bafonins ?) but we all have plugins installed in our IDEs that format automatically on save.

**Comment by johanstokking** [comment]
> It's currently not part of CI

[It will be](https://github.com/TheThingsNetwork/lorawan-stack/pull/2731/files#diff-7f8a77db58bf3a17bac334c0f82afef5R63-R67), so please advise @rvolosatovs on next steps here

**Comment by kschiffer** [comment]
`mage js:fmt` works, but it seems like it would clash with the editorconfig as noted above. The editor config should leave JSDoc untouched, then it should be no problem.

**Comment by bafonins** [comment]
> It's currently not part of CI 

It is. It runs within the `js:lint` target as it is integrated into `eslint` and `prettier` runs as a `eslint` rule. There is no reason to make it as a separate target, since our setup also resolves some inconsistencies between `eslint` and `prettier`.

Also, `prettier` by default checks for `.editorconfig` and uses options that do not conflict with settings from `prettierrc.yml`. It seems that there is difference how `prettier + eslint` and `eclint` format comment blocks.
 
A quick fix for this can be changing `.editorconfig` to leave formatting blocks to `prettier`:

```diff
 insert_final_newline = true
 trim_trailing_whitespace = true
 charset = utf-8
 
+[*.js]
+block_comment_start = /*
+block_comment = *
+block_comment_end = */
 
 [*.go]
 indent_style = tab
 
```

**Comment by rvolosatovs** [comment]
@bafonins can you (partially) address https://github.com/TheThingsNetwork/lorawan-stack/issues/2723 ?

**Comment by johanstokking** [comment]
@rvolosatovs what is the status here?

**Comment by rvolosatovs** [comment]
I have higher priority things to work on, but this is almost done.
I'm happy to assign someone else to work on this.

File: doc/data/api/ttn.lorawan.v3/enums.yml (hunk 4 above)
Comment (rvolosatovs) [reply doc/data/api/ttn.lorawan.v3/enums.yml]: Is there still something to be cherry-picked here?

**Review by kschiffer — APPROVED** [review]

**Review by htdvisser — APPROVED** [review]
