### PR TITLE
Fix go vet warnings

### LINKED ISSUE #3808: Go 1.16 "go vet" Issues
#### Summary

...

#### Steps to Reproduce

```bash
$ go vet ./...
```

#### What do you see now?

- [x] `# go.thethings.network/lorawan-stack/v3/pkg/webui` - #3904 

    ```
    pkg/webui/template.go:50:2: struct field tag `name:-` not compatible with reflect.StructTag.Get:bad syntax for struct tag value
    ```

- [x] `go.thethings.network/lorawan-stack/v3/pkg/applicationserver/io/grpc_test`
    ```
    pkg/applicationserver/io/grpc/grpc_test.go:116:6: call to (*T).Fatalf from a non-test goroutine
    pkg/applicationserver/io/grpc/grpc_test.go:119:6: call to (*T).FailNow from a non-test goroutine
    ```

- [x] `go.thethings.network/lorawan-stack/v3/pkg/gatewayserver/io/grpc_test`
    ```
    pkg/gatewayserver/io/grpc/grpc_test.go:132:6: call to (*T).Fatalf from a non-test goroutine
    pkg/gatewayserver/io/grpc/grpc_test.go:135:6: call to (*T).FailNow from a non-test goroutine
    pkg/gatewayserver/io/grpc/grpc_test.go:198:5: call to (*T).Fatalf from a non-test goroutine
    ```

- [x] `go.thethings.network/lorawan-stack/v3/pkg/gatewayserver_test`
    ```
    pkg/gatewayserver/gatewayserver_test.go:791:10: call to (*T).Fatalf from a non-test goroutine
    pkg/gatewayserver/gatewayserver_test.go:880:9: call to (*T).Fatalf from a non-test goroutine
    pkg/gatewayserver/gatewayserver_test.go:936:6: call to (*T).Fatalf from a non-test goroutine
    ```

- [x] `go.thethings.network/lorawan-stack/v3/pkg/errors_test` - #3910
    ```
    pkg/errors/errors_test.go:97:7: the cancel function returned by context.WithDeadline should be called, not discarded, to avoid a context leak
    ```

- [ ] `go.thethings.network/lorawan-stack/v3/pkg/gatewayserver/io/ws_test`
    ```
    pkg/gatewayserver/io/ws/ws_test.go:312:6: call to (*T).Fatalf from a non-test goroutine
    pkg/gatewayserver/io/ws/ws_test.go:370:6: call to (*T).Fatalf from a non-test goroutine
    pkg/gatewayserver/io/ws/ws_test.go:415:7: call to (*T).Fatalf from a non-test goroutine
    pkg/gatewayserver/io/ws/ws_test.go:676:6: call to (*T).Fatalf from a non-test goroutine
    pkg/gatewayserver/io/ws/ws_test.go:1013:7: call to (*T).Fatalf from a non-test goroutine
    pkg/gatewayserver/io/ws/ws_test.go:1330:7: call to (*T).Fatalf from a non-test goroutine
    ```

Note: probably not all of these are related to Go 1.16.

#### What do you want to see instead?

No issues

#### Environment

Current v3.11 branch (basically v3.11.0)

Go 1.16

### PR DESCRIPTION
**Pull request by adriansmares**
#### Summary

Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/3808

#### Changes

- Call `Fatalf` from the main goroutine

### CODE REVIEW

File: pkg/gatewayserver/io/ws/ws_test.go [hunk 1]
```diff
@@ -364,12 +374,16 @@ func TestDiscover(t *testing.T) {
 				t.Fatalf("Failed to write message: %v", err)
 			}
 
+			var wg sync.WaitGroup
+			wg.Add(1)
 			go func() {
-				_, _, err := conn.ReadMessage()
-				if err == nil {
```
Comment (adriansmares) [inline pkg/gatewayserver/io/ws/ws_test.go:369]: This assertion was actually wrong. `err` is supposed to be `nil` here, while the body (the 2nd parameter) will contain the error in JSON. This assertion generally passed because the connection is closed using the `defer`.

**Review by johanstokking — APPROVED** [review]
LGTM

**Review by KrishnaIyer — APPROVED** [review]
