### PR TITLE
Support maximum EIRP and duty-cycle from frequency plan sub-bands and band fixes

### LINKED ISSUE #300: Sub-band overrides in frequency plans
**Summary:** 

Allow overrides in frequency plans for sub-bands.

**Why do we need this?**

To adjust duty-cycle and maximum EIRP per sub-band in frequency plans, overriding the sub-band values defined in the band.

**What is already there? What do you see now?**

Current behavior is using the sub-band's maximum EIRP, otherwise the band's default. The frequency plan's maximum EIRP acts as a ceiling, but is for all frequencies.

Duty cycles are currently only defined in the sub-bands of the band definitions.

**What is missing? What do you want to see?**

Have an EIRP ceiling and duty-cycles for specific frequencies (i.e. sub-bands) in the frequency plans.

**How do you propose to implement this?**

Add a new section of frequency plans, like in the band definition, that override the duty-cycle and maximum EIRP. If these values are present, these are used; it wouldn't act as a ceiling.

The frequency plan's maximum EIRP can, however, for simplicity, still act as a ceiling.

**What can you do yourself and what do you need help with?**

Can do, can also review.

### PR DESCRIPTION
**Pull request by johanstokking**
#### Summary

Closes #300
References https://github.com/TheThingsNetwork/lorawan-frequency-plans/pull/10
References https://github.com/TheThingsNetwork/lorawan-frequency-plans/pull/11
References https://github.com/TheThingsNetwork/lorawan-frequency-plans/pull/13

#### Changes

- Support maximum EIRP value from frequency plans sub-bands.
- Support duty-cycle value from frequency plans sub-bands.
- Correct `AU_915_928` maximum EIRP value to 30 dBm in 915.0 – 928.0 MHz (was 16.15 dBm).
- Correct `US_902_928` maximum EIRP value to 23.15 dBm in 902.3 – 914.9 MHz (was 32.15 dBm) and 28.15 dBm in 923.3 – 927.5 MHz (was 32.15 dBm). This aligns with US915 Hybrid Mode.
- Correct `AS_923` maximum EIRP value to 16 dBm in 923.0 – 923.5 MHz (was 16.15 dBm).

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, database and configuration, according to the stability commitments in `README.md`.
- [x] Testing: The changes are covered with unit tests. The changes are tested manually as well.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/frequencyplans/frequencyplans.go [hunk 1]
```diff
@@ -28,6 +28,33 @@ import (
...
+type SubBandParameters struct {
+	MinFrequency uint64 `yaml:"min-frequency,omitempty"`
+	MaxFrequency uint64 `yaml:"max-frequency,omitempty"`
+	// DutyCycle is a fraction. A value of 0 is interpreted as 1, i.e. no duty-cycle limitation.
+	DutyCycle float32  `yaml:"duty-cycle,omitempty"`
+	MaxEIRP   *float32 `yaml:"max-eirp,omitempty"`
+}
+
+// Clone returns a cloned SubBandParameters.
+func (sb *SubBandParameters) Clone() *SubBandParameters {
```
Comment (htdvisser) [inline pkg/frequencyplans/frequencyplans.go]: According to Coveralls we're not testing that this actually works...
