### PR TITLE
Fix application/gateway deletion in console

### LINKED ISSUE #1128: Fix infinite loading after deleting entity
#### Summary

Console freezes and show the loading screen after deleting an entity.
Screenshot 2019-08-08 at 10 00 12

#### Steps to Reproduce

1. Create a new gateway
2. Go the the general settings and delete it

#### What do you see now?

The user sees the loading screen

#### What do you want to see instead?

The user should be navigated to the entity list screen

#### Environment

browser (console)

#### How do you propose to implement this?

The issue is caused by the `withRequest` hoc. Most probably some changes needed there.

#### Can you do this yourself and submit a Pull Request?

Yes

### PR DESCRIPTION
**Pull request by bafonins**
#### Summary

Closes #1128 

#### Changes

- Redirect to lists after successful deletion

### CODE REVIEW

File: pkg/webui/console/views/application-general-settings/index.js [hunk 1]
```diff
@@ -54,10 +57,14 @@ const validationSchema = Yup.object().shape({
...
 }),
-{
-  updateApplication: attachPromise(updateApplication),
-  deleteApplication: attachPromise(deleteApplication),
-})
+dispatch => ({
+  ...bindActionCreators({
+    updateApplication: attachPromise(updateApplication),
+    deleteApplication: attachPromise(deleteApplication),
+
```
Comment (kschiffer) [inline pkg/webui/console/views/application-general-settings/index.js]: Unnecessary newline.
