### PR TITLE
cli: Include missing enum values in help text

### LINKED ISSUE #2340: Missing allowed enum values for some cli fields
#### Summary

Some cli fields only show numeric allowed values, but they also accept enum values.

#### Steps to Reproduce

For example, for some RxDelay values:

```
$ ttn-lw-cli dev update --help
       --mac-state.desired-parameters.rx1-delay string 0|1|10|11|12|13|14|15|2|3|4|5|6|7|8|9

# works
$ ttn-lw-cli dev update $app $dev --mac-state.desired-parameters.rx1-delay RX_DELAY_1
```

#### What do you see now?

Only numeric values for said fields (e.g. `0|1|2|3|...`)
#### What do you want to see instead?

All allowed values (including `RX_DELAY_0|....`)

#### Environment

3.7.0

#### How do you propose to implement this?

List all possible enum values

#### Can you do this yourself and submit a Pull Request?

yes

### PR DESCRIPTION
**Pull request by neoaggelos**
#### Summary

Closes #2340

#### Changes

- Add missing enum values in help text. (If enum type implements stringer, then add both values, not only the one returned from the stringer)

#### Notes for Reviewers

- Did a quick check with entities other than end devices, no flags seem to be affected.
- Tested `--lorawan-version`, `--lorawan-mac-version`, `--mac-state.desired-parameters.rx1-delay`
- Help text now shows all enum values for all device fields. Please verify that I have not missed anything

#### Checklist

- [X] Scope: The referenced issue is addressed, there are no unrelated changes.
- [X] Compatibility: The changes are backwards compatible with existing API, database and configuration, according to the stability commitments in `README.md`.
- [X] Testing: The changes are covered with unit tests. The changes are tested manually as well.
- [X] Documentation: Relevant documentation is added or updated.
- [X] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [X] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: cmd/ttn-lw-cli/internal/util/flags.go [hunk 1]
```diff
@@ -177,15 +177,13 @@ func enumValues(t reflect.Type) []string {
 		valueMap := make(map[string]int32)
 		implementsStringer := t.Implements(reflect.TypeOf((*fmt.Stringer)(nil)).Elem())
 		for s, v := range proto.EnumValueMap(fmt.Sprintf("ttn.lorawan.v3.%s", t.Name())) {
+			valueMap[s] = v
 			if implementsStringer {
 				// If the enum implements Stringer, then the String might be different than the official name.
 				rv := reflect.New(t).Elem()
 				rv.SetInt(int64(v))
 				s := rv.Interface().(fmt.Stringer).String()
 				valueMap[s] = v
```
Comment (rvolosatovs) [inline cmd/ttn-lw-cli/internal/util/flags.go:186]:
```suggestion
```

Comment (rvolosatovs) [inline cmd/ttn-lw-cli/internal/util/flags.go:186]:
```suggestion
				valueMap[rv.Interface().(fmt.Stringer).String()] = v
```
