### PR TITLE
Fix broken components in storybook

### LINKED ISSUE #2693: Fix component stories
#### Summary
A couple of component stories are currently crashing and should be fixed.

#### Steps to Reproduce
The following stories have issues:

- Icons
- List
- Status
  - With Label
  - Without Pulse

#### What do you see now?
Crashing / buggy stories

#### What do you want to see instead?
All stories functioning properly

#### How do you propose to test this?
Via storybook

#### Can you do this yourself and submit a Pull Request?
@pgalic96

### PR DESCRIPTION
**Pull request by pgalic96**
#### Summary

Closes #2693 

#### Changes

- Change array generation method in `List` component as the previous one was not generating items correctly
- Add `Message` component to `Status` label, this should be fixed for all components by adding internationalization (https://github.com/TheThingsNetwork/lorawan-stack/issues/603)
- Wrap the icon elements with a top level `div` to fix `Icon` story
- Fix proptype warning for `List`

#### Testing

Check storybook

##### Regressions

None

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md`. The target branch is set to `master` if the changes are fully compatible with existing API, database, configuration and CLI.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/webui/components/status/story.js [hunk 1]
```diff
@@ -15,16 +15,22 @@
...
 
 const containerStyle = {
-  width: '100px',
+  width: '120px',
   display: 'flex',
   alignItems: 'center',
   justifyContent: 'space-between',
 }
 
+const m = defineMessages({
```
Comment (bafonins) [inline pkg/webui/components/status/story.js:29]: There is no reason to define custom translated messages just for storybook. If the `<Status />` component does not accept raw strings, it is a bug and should fixed.

File: pkg/webui/components/list/index.js [hunk 2]
```diff
@@ -34,7 +34,9 @@ class List extends React.PureComponent {
     emptyMessageValues: PropTypes.shape({}),
     footer: PropTypes.node,
     header: PropTypes.node,
-    items: PropTypes.arrayOf(PropTypes.shape({})),
+    items: PropTypes.arrayOf(
+      PropTypes.oneOfType(PropTypes.shape({}), PropTypes.string, PropTypes.number),
```
Comment (bafonins) [inline pkg/webui/components/list/index.js:38]:
```suggestion
      PropTypes.oneOfType(PropTypes.shape({}), PropTypes.string),
```

File: pkg/webui/components/icon/story.js [hunk 3]
```diff
@@ -44,6 +44,15 @@ display value of the wrapping \`<span />\`in your local scoped css. The
 positioning will differ slightly, so the nudge props can be used to fine-tune
 the appearance.`
 
+const iconElement = icons.map(function(icon) {
```
Comment (bafonins) [inline pkg/webui/components/icon/story.js:47]:
```suggestion
const iconElements = icons.map(icon => {
```

File: pkg/webui/components/status/story.js (hunk 1 above)
Comment (pgalic96) [reply pkg/webui/components/status/story.js]: yep there was an issue with calling `intl.formatMessage` with a string as a parameter instead of a message, now this case is handled correctly.

File: pkg/webui/components/list/index.js (hunk 2 above)
Comment (bafonins) [reply pkg/webui/components/list/index.js]: actually, this should be array
```js
    items: PropTypes.arrayOf(
      PropTypes.oneOfType([PropTypes.shape({}), PropTypes.string]),
```

File: pkg/webui/components/status/story.js (hunk 1 above)
Comment (bafonins) [reply pkg/webui/components/status/story.js]: 👌
