### PR TITLE
Generate local session key ID if interop JS didn't

### LINKED ISSUE #1928: Bad payload decryption after a new join when using external JS
#### Summary
When a device joins with external JS for the 2nd time or more the payload is not decrypted correctly, it seems that session keys used by the LNS are wrong

#### Steps to Reproduce
1. Create a device using[ Semtech's join server](https://www.loracloud.com)
2. Join network
3. Send a payload => In MQTT uplink, payload is ok
4. Reset the device
5. Join the netwok
6. Send a payload => In MQTT uplink, payload is not ok

Reproduced in self hosted v3.5.0 and TTI v3.5.1-rc1

#### What do you want to see instead?
Device payload decrypted correctly each time

#### Can you do this yourself and submit a Pull Request?
No

### PR DESCRIPTION
**Pull request by johanstokking**
#### Summary

Fix #1928

#### Changes

- According to BI 1.0, either `AppSKey`, or `SessionKeyID`, or both are sent in `JoinAns`
- If `SessionKeyID` is not sent, we still need to have one for AS to detect session changes. We cannot reliably use `DevAddr` for that (as it may return to an old one while the AS wasn't up)
- We are now, in the interop client, generating a `SessionKeyID`. This is prepended with an identifier
- AS uses this identifier to not try to get the `AppSKey` from the interop JS

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, database and configuration, according to the stability commitments in `README.md`.
- [x] Testing: The changes are covered with unit tests. The changes are tested manually as well.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/interop/client.go [hunk 1]
```diff
@@ -285,10 +293,22 @@ func (cl joinServerHTTPClient) HandleJoinRequest(ctx context.Context, netID type
 	if req.SelectedMACVersion.Compare(ttnpb.MAC_V1_1) <= 0 {
 		fNwkSIntKey = interopAns.NwkSKey
 	}
+
+	sessionKeyID := []byte(interopAns.SessionKeyID)
+	if len(sessionKeyID) == 0 {
+		log.FromContext(ctx).Debug("Interop join-accept does not contain session key ID, use random ID")
```
Comment (rvolosatovs) [inline pkg/interop/client.go]:
```suggestion
		log.FromContext(ctx).Debug("Interop join-accept does not contain session key ID, generate an ID")
```
