### PR TITLE
Fix/5083 application rights

### LINKED ISSUE #5083: Improve application rights handling in the Console
#### Summary

If you add application collaborator without `RIGHT_APPLICATION_TRAFFIC_READ`, login as collaborator user and request rights for this application `RIGHT_APPLICATION_TRAFFIC_READ` is present.

<details>
<summary>Payloads</summary>

request when adding collaborator
```
// note: No `RIGHT_APPLICATION_TRAFFIC_READ` right
{
  "collaborator": {
    "ids": {
      "user_ids": {
        "user_id": "test-user"
      }
    },
    "rights": [
			"RIGHT_APPLICATION_DELETE",
			"RIGHT_APPLICATION_DEVICES_READ_KEYS",
			"RIGHT_APPLICATION_DEVICES_READ",
			"RIGHT_APPLICATION_DEVICES_WRITE_KEYS",
			"RIGHT_APPLICATION_DEVICES_WRITE",
			"RIGHT_APPLICATION_INFO",
			"RIGHT_APPLICATION_LINK",
			"RIGHT_APPLICATION_SETTINGS_API_KEYS",
			"RIGHT_APPLICATION_SETTINGS_BASIC",
			"RIGHT_APPLICATION_SETTINGS_COLLABORATORS",
			"RIGHT_APPLICATION_SETTINGS_PACKAGES",
			"RIGHT_APPLICATION_TRAFFIC_DOWN_WRITE",
			"RIGHT_APPLICATION_TRAFFIC_UP_WRITE"
    ]
  }
}
```

response when  fetching collaborator rights
```
// note: `RIGHT_APPLICATION_TRAFFIC_READ` is present.
{
  "rights": [
		"RIGHT_APPLICATION_DELETE",
		"RIGHT_APPLICATION_DEVICES_READ_KEYS",
		"RIGHT_APPLICATION_DEVICES_READ"
		"RIGHT_APPLICATION_DEVICES_WRITE_KEYS",
		"RIGHT_APPLICATION_DEVICES_WRITE",
		"RIGHT_APPLICATION_INFO",
		"RIGHT_APPLICATION_LINK",
		"RIGHT_APPLICATION_SETTINGS_API_KEYS",
		"RIGHT_APPLICATION_SETTINGS_BASIC",
		"RIGHT_APPLICATION_SETTINGS_COLLABORATORS",
		"RIGHT_APPLICATION_SETTINGS_PACKAGES",
		"RIGHT_APPLICATION_TRAFFIC_DOWN_WRITE",
		"RIGHT_APPLICATION_TRAFFIC_READ", // <-----
		"RIGHT_APPLICATION_TRAFFIC_UP_WRITE",
  ]
}
```

</details>

#### Why do we need this?

Better UX since some users might think that when `Read application traffic (uplink and downlink)` is not selected, collaborators wont be able to observe application events, which is not true as long as `Link as Application to a Network Server for traffic exchange, i.e. read uplink and write downlink` is selected.

#### What is already there? What do you see now?

The stack implies certain rights https://github.com/TheThingsNetwork/lorawan-stack/blob/ff220a3188426b8cdc70613910f98fb6a2d73fdf/pkg/ttnpb/rights.go#L113-L118 based on rights selection.
There is no obvious way for the user to be notified about this functionality in the console.

#### What is missing? What do you want to see?

Improved application rights selection in the Console.

#### Can you do this yourself and submit a Pull Request?

@kschiffer @ryaplots

### PR DESCRIPTION
**Pull request by ryaplots**
#### Summary

Closes #5083 

#### Changes

- Add field description to application rights group

Screenshot 2022-03-14 at 11 29 46

#### Testing

cypress and manually

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/webui/components/checkbox/checkbox.js [hunk 1]
```diff
@@ -157,25 +160,28 @@ class Checkbox extends React.PureComponent {
...
+              aria-describedby={rest['aria-describedby']}
+              aria-invalid={rest['aria-invalid']}
+              {...checkboxProps}
+            />
+            <span className={style.checkmark} />
+          </span>
+          {label && <Message className={style.label} content={label} />}
+          {children}
+        </label>
+        {fieldDescription && <Message className={style.description} content={fieldDescription} />}
```
Comment (kschiffer) [inline pkg/webui/components/checkbox/checkbox.js]: Please use the `children` prop to display the description message, which already gives us an all-purpose way to render nodes within the checkbox.

Three reasons:

*   We have been using passed messages in the past but it turned out to be not a good solution because:
    *   It's hard to pass message values (we have only a wonky workaround for that)
    *   It's hard to pass individual styling for the message
*   The prop would only serve an edge-case
*   The desired functionality can be achieved with existing props

Generally, try to consider a cost/utility ratio when deciding to add a prop or extend component functionality. Often, it cannot be avoided to extend a component but sometimes it can.

**Review by kschiffer — CHANGES_REQUESTED** [review]
See my remark regarding the new prop in the checkbox component.

File: pkg/webui/components/checkbox/checkbox.styl [hunk 2]
```diff
@@ -107,3 +107,4 @@
 
 .label
   padding-left: $cs.xs
+
```
Comment (kschiffer) [inline pkg/webui/components/checkbox/checkbox.styl]:
```suggestion
```

File: pkg/webui/console/components/rights-group/index.js [hunk 3]
```diff
@@ -243,6 +246,7 @@ class RightsGroup extends React.Component {
         name={right}
         disabled={outOfOwnScopeIndividualRights.includes(right)}
         label={{ id: `enum:${right}` }}
+        children={<Message className={style.description} content={m[`${right}_DESCRIPTION`]} />}
```
Comment (kschiffer) [inline pkg/webui/console/components/rights-group/index.js]:
```suggestion
        children={<Message className={style.description} component="div" content={m[`${right}_DESCRIPTION`]} />}
```

File: pkg/webui/console/components/rights-group/rights-group.styl [hunk 4]
```diff
@@ -22,6 +22,10 @@
 .right-label
   span::first-letter
     text-transform: uppercase
+  flex-wrap: wrap
 
 .grant-type
   margin-bottom: $cs.s
+
+.description
+  color: $tc-subtle-gray
```
Comment (kschiffer) [inline pkg/webui/console/components/rights-group/rights-group.styl:31]:
```suggestion
  color: $tc-subtle-gray
  width: 100%
```
Otherwise, short descriptions will be rendered on the same line.

**Review by kschiffer — APPROVED** [review]
See my remaining changes.
