### PR TITLE
Fix handling of FCnt resets and 32-bit FCnt rollovers

### LINKED ISSUE #3728: Frame Counter Resets setting has no effect (Store error)
#### Summary

I registered an ABP device on the V3 TTN console. Frame Counter Resets was selected.
image

I used a Things Uno runnong the SendABP example sketch.

The first message (counter 0) was not received on the live feed. From counter 1 and on the data was visible.

Then I reset the Things Uno and it started transmitting from frame counter 0. The data was not received on the console, until the frame counter increased past the previous value at which I reset the device.

It therefore seems like the Frame Counter Resets setting does not work.

#### Steps to Reproduce

1. Register an ABP device
2. Send data and see how the frame counter increases
3. Restart the device
4. See that no data is received until frame counter increases past the previous maximum value

#### What do you see now?

Data is lost!!

And on the gateway feed I see "Cluster failed to handle message: Store error"
Screenshot from 2021-02-02 09-20-36

#### What do you want to see instead?

I want my ABP devices to work, even if they got reset at some point.

#### Environment

v3.11.0-rc1

#### How do you propose to implement this?

...

#### How do you propose to test this?

...

#### Can you do this yourself and submit a Pull Request?

No

### PR DESCRIPTION
**Pull request by rvolosatovs**
#### Summary

Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/3728
Refs https://github.com/TheThingsNetwork/lorawan-stack/pull/3743

#### Changes

- Fix msgpack encoding of sessions
- Fix FCnt check on reset for devices with 32-bit frame counters
- Migrate sessions created on 3.11 snapshot to new format

#### Testing

Unit tests, integration testing
```sh
ses=$(cli dev get test-app2 test-dev-c --session)
dev_addr=$(echo "${ses}" | jq -r '.session.dev_addr')
f_nwk_s_int_key=$(echo "${ses}" | jq -r '.session.keys.f_nwk_s_int_key.key')
echo "${ses}" | jq
cli simulate gateway-uplink --lorawan-phy-version "1.0.3-a" --lorawan-version "1.0.3" --gateway-id test-gtw --dev-addr "${dev_addr}" --f_nwk_s_int_key "${f_nwk_s_int_key}" --f_cnt 0x42
cli simulate gateway-uplink --lorawan-phy-version "1.0.3-a" --lorawan-version "1.0.3" --gateway-id test-gtw --dev-addr "${dev_addr}" --f_nwk_s_int_key "${f_nwk_s_int_key}" --f_cnt "${1:-"0x02"}"
```

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Comment by KrishnaIyer** [comment]
@rvolosatovs: This only affects `v3.11` and doesn't need a backport right?

**Comment by rvolosatovs** [comment]
yes

File: pkg/networkserver/redis/registry.go [hunk 1]
```diff
@@ -15,7 +15,7 @@
 package redis
 
 import (
-	"bytes"
+	// "bytes"
```
Comment (htdvisser) [inline pkg/networkserver/redis/registry.go]: This doesn't look quite right

File: pkg/networkserver/redis/registry.go [hunk 2]
```diff
@@ -152,26 +115,153 @@ func (r *DeviceRegistry) GetByEUI(ctx context.Context, joinEUI, devEUI types.EUI
 }
 
 type uplinkMatchSession struct {
-	LoRaWANVersion    ttnpb.MACVersion
```
Comment (htdvisser) [inline pkg/networkserver/redis/registry.go:155]: Any specific reason for re-ordering the fields here (and below)?

**Review by htdvisser — COMMENTED** [review]
Not sure why GitHub decided to request code-owner review on a draft PR. Only quickly glanced over it.

File: pkg/networkserver/redis/registry.go (hunk 2 above)
Comment (rvolosatovs) [reply pkg/networkserver/redis/registry.go:155]: Yes, this takes less space

**Review by htdvisser — APPROVED** [review]
Looks okay to me. We're definitely going to need to verify that this all works in a new rc, so let's get that going as soon as this is merged.

**Review by adriansmares — APPROVED** [review]

**Review by johanstokking — APPROVED** [review]
