### PR TITLE
Fix validation and proptype errors in location form

### LINKED ISSUE #1574: Validation errors on copy-pasted location values
#### Summary

When I copy-paste a location value into the Latitude/Longitude of the gateway location, the console gives me (client side) validation errors.

#### Steps to Reproduce

1. Go to your gateway
2. Go to **Location**
3. Copy latitude `52.39528339` and longitude `4.87489745`
4. **Save Changes**

#### What do you see now?

Screenshot 2019-11-11 at 10 50 17

#### What do you want to see instead?

The console should not complain.

#### Environment

v3.2.4, Firefox 70

### PR DESCRIPTION
**Pull request by pgalic96**
#### Summary

Closes #1574

#### Changes

- Cast input type number into floats to avoid proptype errors (and possible other errors?)
- Add `step` to form to fix issues with form input in Firefox

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, database and configuration, according to the stability commitments in `README.md`.
- [x] Testing: The changes are covered with unit tests. The changes are tested manually as well.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/webui/components/location-form/index.js [hunk 1]
```diff
@@ -80,8 +80,14 @@ class LocationForm extends Component {
 
     this.setState({ error: '' })
 
+    const intValues = {
+      latitude: parseInt(values.latitude),
+      longitude: parseInt(values.longitude),
+      altitude: parseInt(values.altitude),
```
Comment (kschiffer) [inline pkg/webui/components/location-form/index.js]: This cannot work. Location values are floats, not ints, so you'd loose the decimals. Moreover, the correct spot to fix this is in the input component itself, by checking whether the input type is `number` and automatically parsing the value in that case.
