### PR TITLE
Remove leading space from safe inspector copy value

### LINKED ISSUE #1235: C-style array copy spacing
#### Summary

C-style array copy spacing and copy braces improvements

#### Steps to Reproduce

1. Select the `< >` button near EUIs or keys
2. Click copy

#### What do you see now?

The clipboard contains, for example: ` 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08`

Notice the space at the start (and not at the end)

#### What do you want to see instead?

No spacing

#### How do you propose to implement this?

No idea, is probably quite simple

#### Can you do this yourself and submit a Pull Request?

Can review

@kschiffer please adjust milestone or assignment

### PR DESCRIPTION
**Pull request by kschiffer**
#### Summary
Closes #1235 
References #1086 

#### Changes
- Remove leading whitespace in the copied value of the safe inspector (when in c-style mode)
- Fix proptypes

#### Notes for Reviewers
Just putting this in-between as it was an easy fix…

cc @johanstokking

### CODE REVIEW

File: pkg/webui/components/safe-inspector/index.js [hunk 1]
```diff
@@ -150,7 +180,7 @@ export class SafeInspector extends Component {
       const chunks = chunkArray(data.toUpperCase().split(''), 2)
       if (!byteStyle) {
         const orderedChunks = msb ? chunks : chunks.reverse()
-        formattedData = display = `${orderedChunks.map(chunk => ` 0x${chunk.join('')}`)}`
+        formattedData = display = `${orderedChunks.map(chunk => `0x${chunk.join('')}`).join(', ')}`
```
Comment (bafonins) [inline pkg/webui/components/safe-inspector/index.js]:
```suggestion
        formattedData = display = orderedChunks.map(chunk => `0x${chunk.join('')}`).join(', ')
```
