### PR TITLE
Fix header issue in storybook

### LINKED ISSUE #646: Header component broken in Storybook
#### Summary
The `<Header />` component does not work anymore in storybooks and displays an error.

#### Steps to Reproduce
1. Open storybook
2. Open `Header` entry
3. See an error

#### What do you see now?
Following error:
```
Cannot read property 'user_id' of undefined
    TypeError: Cannot read property 'user_id' of undefined
    at Header (http://localhost:9001/static/iframe.bundle.js:144921:22)
    at mountIndeterminateComponent (http://localhost:9001/static/iframe.bundle.js:104664:13)
    at beginWork (http://localhost:9001/static/iframe.bundle.js:105164:16)
    at performUnitOfWork (http://localhost:9001/static/iframe.bundle.js:107921:12)
    at workLoop (http://localhost:9001/static/iframe.bundle.js:107961:24)
    at renderRoot (http://localhost:9001/static/iframe.bundle.js:108047:7)
    at performWorkOnRoot (http://localhost:9001/static/iframe.bundle.js:108938:7)
    at performWork (http://localhost:9001/static/iframe.bundle.js:108850:7)
    at performSyncWork (http://localhost:9001/static/iframe.bundle.js:108824:3)
    at requestWork (http://localhost:9001/static/iframe.bundle.js:108693:5)
```

#### What do you want to see instead?
No error.

#### Environment
Storybook in browser

#### How do you propose to implement this?
Likely forgot to stub a proper `user` value. @pgalic96 can you investigate this?

#### Can you do this yourself and submit a Pull Request?
Good follow up issue for you @pgalic96

### PR DESCRIPTION
**Pull request by pgalic96**
#### Summary

Closes #646 
Add `user_id` to `user` stub such that `Header` component renders in the storybook.
...

#### Changes

- add `user_id` to the `user` object
- cleanup the `<Header />` props, rename the `link` prop to `path`

### CODE REVIEW

**Comment by bafonins** [comment]
1. `console: Add user_id to user stub` -> `util: Add user_id to user stub`
2. Please resolve other `PropTypes` issues shown in the console:
```
Warning: Failed prop type: The prop `dropdownItems[0].path` is marked as required in `Header`, but its value is `undefined`.
    in Header checkPropTypes.js:19
Warning: Failed prop type: Invalid prop `userId` of type `number` supplied to `ProfileDropdown`, expected `string`.
    in ProfileDropdown (created by Header)
    in Header
    in div (created by Story)
    in div (created by Story)
    in Story
    in div
    in Unknown
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Connect(ConnectedRouter))
    in Connect(ConnectedRouter)
    in IntlProvider
    in Provider
```

File: pkg/webui/components/header/story.js [hunk 1]
```diff
@@ -21,6 +21,9 @@ import Header from '.'
 
 const user = {
   name: 'kschiffer',
+  ids: {
+    user_id: 123456789,
```
Comment (bafonins) [inline pkg/webui/components/header/story.js]:
```suggestion
    user_id: 'something readable here`,
```

**Comment by kschiffer** [comment]
PS.: make sure to just delete parts of the PR template that you are not using.
