### PR TITLE
Optimize Redis application uplink queue

### LINKED ISSUE #1598: AS links capped at 10 per CPU
#### Summary

#1524 introduced blocking `XREADGROUP` per each AS-NS link, but did not account for the fact that default limit of connections in Redis library we're using is capped at `10*runtime.NumCPU()`

#### Steps to Reproduce

1. Start stack
2. Link more than `10*runtime.NumCPU()` applications and not generate any uplinks

#### What do you see now?

`redis: connection pool timeout`

#### What do you want to see instead?

Successful execution

#### Environment

`v3.2.5`

#### How do you propose to implement this?

Not sure, polling is one possible fix, but seems dirty.
We should probably shard the uplinks.

#### Can you do this yourself and submit a Pull Request?

yes

### PR DESCRIPTION
**Pull request by rvolosatovs**
#### Summary

Closes #1598 

#### Changes

- Use a channel to block for new uplinks instead of TCP connection.

#### Notes for Reviewers

This implementation only works when there's 1 NS in the cluster and/or they're properly sharded, i.e. only NS holding link to application A should be generating uplinks for application A.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, database and configuration, according to the stability commitments in `README.md`.
- [x] Testing: The changes are covered with unit tests. The changes are tested manually as well.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/networkserver/redis/application_uplink_queue.go [hunk 1]
```diff
@@ -82,119 +89,62 @@ var (
...
-		}
-	}()
-
-	_, err = q.Redis.XGroupCreateMkStream(upStream, q.Group, "0").Result()
-	if err != nil && !ttnredis.IsConsumerGroupExistsErr(err) {
-		return ttnredis.ConvertError(err)
+	upCh := make(chan *ttnpb.ApplicationUp, 1)
+	_, ok := q.subscriptions.LoadOrStore(uid, upCh)
+	if ok {
+		panic(fmt.Sprintf("duplicate subscription for application %s", uid))
```
Comment (htdvisser) [inline pkg/networkserver/redis/application_uplink_queue.go]: This should error, not panic. `ApplicationUplinkQueue.Subscribe` is called by the implementation of the `LinkApplication` RPC, which will be called by an (external) Application Server.

Situation: When an Application Server restarts because of a crash, the old application link may not have been canceled yet (the TCP connection may not have been closed cleanly) when the new instance calls LinkApplication, that causes a `panic` 💥

Comment (rvolosatovs) [reply pkg/networkserver/redis/application_uplink_queue.go]: The previous link is always closed before a new one is opened - https://github.com/TheThingsNetwork/lorawan-stack/blob/d6724d1cfb463b4096207e829cbbeb2e6daafe33/pkg/networkserver/grpc_asns.go#L85-L91
This is only reachable when there's a bug in NS implementation
