### PR TITLE
Use a thread safe `sync.Map` to store rights

### LINKED ISSUE #5534: Ttn-lw-cli applications subscribe HANG
#### Summary
When I execute **ttn-lw-cli events --gateway_id [_whatever_]**
the cli will (as expected) run until the access token expires and returns to the caller.

When I’m not authenicated I can just do **ttn-lw-cli login** to get a new access token.
That all works fine :smiley:

However, when I execute **ttn-lw-cli applications subscribe --application-id [_whatever_]**
the cli (unexpectedly) will not return after the access token has expired :frowning:

#### Steps to Reproduce
The symptom I see is that I get the desired application output data while the access token is valid but no clue that the token has expired.
Visually it is as if the device had stopped sending data to the application, but it has been broadcasting fine, as witnessed by the gateway events.

I can use **--log.level debug** to get an indication of when the token will expire, along the lines of
`DEBUG Using access token (valid until 8:06AM)`

… but I would expect the **ttn-lw-cli** to actually terminate at 8:06AM and not just hang!

#### What do you see now?
I feel ths behaviour is inconsistent with **ttn-lw-cli events** which sympathetically returns when the token expires.

#### What do you want to see instead?
If I have a script wrapping **ttn-lw-cli** I don't want it to hang and never return.
Once the access token has expired there is no further data retuned from the subscription.
However this data stream stops silently :frowning:

#### Environment
The Things Network Command-line Interface: ttn-lw-cli
Version:             3.19.2
Build date:          2022-05-25T07:14:30Z
Git commit:          2dfab4a75
Go version:          go1.18.2
OS/Arch:             windows/amd64

...

#### How do you propose to implement this?
I'm not in a position to fix it myself.
I currently have a workaround that has another process that monitors the script running **ttn-lw-cli**
When the token has expired I  kill the hung  **ttn-lw-cli**
I determine the expiry timestamp based on scanning the debug output

...

#### How do you propose to test this?
It should be simple to determine if the ttn-lw-cli unblocks after (typically) 1 hour allowing the wrapper script to continue.
All being well I would not need for another process to kill **ttn-lw-cli**

...

#### Can you do this yourself and submit a Pull Request?
I'm not in a position to fix it myself.

### PR DESCRIPTION
**Pull request by happyRip**
#### Summary

References #5534 

#### Changes

- Use `sync.Map` to store rights (instead of `map[string]*ttnpb.Rights`)

#### Testing

- Added unit tests for `rights.Map`

##### Regressions

Using `rights.Map` requires to use it's interface instead of relying on a native `map`.

#### Notes for Reviewers

nil

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/auth/rights/rights.go [hunk 1]
```diff
@@ -17,106 +17,132 @@ package rights
 
 import (
 	"context"
+	"sync"
 
 	"go.thethings.network/lorawan-stack/v3/pkg/ttnpb"
 )
 
+// RightsMap ...
+type RightsMap struct {
```
Comment (adriansmares) [inline pkg/auth/rights/rights.go]: Consider renaming to `Map`.

File: pkg/auth/rights/rights.go [hunk 2]
```diff
@@ -17,106 +17,132 @@ package rights
...
+	syncMap *sync.Map
+}
+
+// NewRightsMap ...
+func NewRightsMap(uid string, rights *ttnpb.Rights) RightsMap {
```
Comment (adriansmares) [inline pkg/auth/rights/rights.go]: Consider taking the old `map[string]*ttnpb.Rights` as an argument - then the updated sites will be better.

File: pkg/joinserver/grpc_deviceregistry_test.go [hunk 3]
```diff
@@ -720,14 +695,13 @@ func TestDeviceRegistrySet(t *testing.T) {
...
-					ApplicationRights: map[string]*ttnpb.Rights{
-						unique.ID(test.Context(), &ttnpb.ApplicationIdentifiers{
-							ApplicationId: registeredApplicationID,
-						}): ttnpb.RightsFrom(
+					ApplicationRights: rights.NewRightsMap(
+						unique.ID(test.Context(), &ttnpb.ApplicationIdentifiers{ApplicationId: registeredApplicationID}),
+						ttnpb.RightsFrom(
 							ttnpb.Right_RIGHT_APPLICATION_DEVICES_WRITE,
-							ttnpb.Right_RIGHT_APPLICATION_DEVICES_WRITE_KEYS,
+							ttnpb.Right_RIGHT_APPLICATION_DEVICES_READ_KEYS,
```
Comment (adriansmares) [inline pkg/joinserver/grpc_deviceregistry_test.go]: The test fails because you changed the right here.

File: pkg/auth/rights/rights.go [hunk 4]
```diff
@@ -17,106 +17,132 @@ package rights
...
 import (
 	"context"
+	"sync"
 
 	"go.thethings.network/lorawan-stack/v3/pkg/ttnpb"
 )
 
+// RightsMap ...
+type RightsMap struct {
+	syncMap *sync.Map
```
Comment (adriansmares) [inline pkg/auth/rights/rights.go]: Instead of making `syncMap` a pointer, make `NewContext` and `FromContext` carry the `*Rights`

File: pkg/auth/rights/rights.go (hunk 1 above)
Comment (happyRip) [reply pkg/auth/rights/rights.go]: Renamed to `Map`

File: pkg/auth/rights/rights.go (hunk 2 above)
Comment (happyRip) [reply pkg/auth/rights/rights.go]: Fixed

File: pkg/joinserver/grpc_deviceregistry_test.go (hunk 3 above)
Comment (happyRip) [reply pkg/joinserver/grpc_deviceregistry_test.go]: Fixed

File: pkg/auth/rights/rights.go (hunk 4 above)
Comment (happyRip) [reply pkg/auth/rights/rights.go]: Fixed https://github.com/TheThingsNetwork/lorawan-stack/pull/5887/commits/a9f7db7b915b193cddabf450fd57c84a2d05e886

**Review by adriansmares — APPROVED** [review]

**Review by KrishnaIyer — APPROVED** [review]
Code owned LGTM

File: pkg/auth/rights/rights.go [hunk 5]
```diff
@@ -17,122 +17,145 @@ package rights
...
-	ApplicationRights  map[string]*ttnpb.Rights
-	ClientRights       map[string]*ttnpb.Rights
-	GatewayRights      map[string]*ttnpb.Rights
-	OrganizationRights map[string]*ttnpb.Rights
-	UserRights         map[string]*ttnpb.Rights
+	ApplicationRights  Map
+	ClientRights       Map
+	GatewayRights      Map
+	OrganizationRights Map
+	UserRights         Map
```
Comment (johanstokking) [inline pkg/auth/rights/rights.go:68]: Is there a reason to store this by value and not by reference?

File: pkg/auth/rights/rights_test.go [hunk 6]
```diff
@@ -19,6 +19,7 @@ import (
 
 	"github.com/smartystreets/assertions"
 	"github.com/smartystreets/assertions/should"
+
```
Comment (johanstokking) [inline pkg/auth/rights/rights_test.go:22]: Remove empty line

File: pkg/auth/rights/rights.go (hunk 5 above)
Comment (adriansmares) [reply pkg/auth/rights/rights.go:68]: In order for the zero value (`&Rights{}`) to not require any additional initialization in places like `setApplicationRights`, `setClientRights` and so forth, which would race the initialization. 

Alternatively, we can have a factory function that takes these individual `*Map` and we expose only an interface, if that seems more appropriate to you.

File: pkg/auth/rights/rights_test.go (hunk 6 above)
Comment (happyRip) [reply pkg/auth/rights/rights_test.go:22]: Fixed

File: pkg/auth/rights/rights.go (hunk 5 above)
Comment (johanstokking) [reply pkg/auth/rights/rights.go:68]: OK, I see

**Review by johanstokking — APPROVED** [review]
