### PR TITLE
Check frontend stream status before emiting stats message

### LINKED ISSUE #6160: UDP frontend concurrency issues
### Summary

The UDP frontend of the Gateway Server is designed to operate even in situations in which the push UDP flow is connected to one Gateway Server instance, while the pull flow is connected to another Gateway Server instance.

This functionality works and we do see in the wild uplinks received on one instance, while the corresponding downlink is sent via another instance which holds the identifiers claim. With that being said, there are some UX issues:

1. The same gateway is counted twice when the flows are connected to separate Gateway Server instances. This happens because each flow counts as a connection in the Gateway Server.
2. If for some reason both flows start by being connected to the same instance, but later on split (due to loss of downlink path since UDP packets were lost), the original instance will continue to push statistics for the flow which is no longer connected.

The following situation is possible:
1. Connect both flows to a Gateway Server instance.
2. The gateway sends some uplinks and receives some downlinks.
3. One flow (lets say the pull) expires.
4. The flow reconnects to another instance.
5. Both instances now push downlink statistics, because the original one had some traffic, so its connection state is not clean.

The same situation may occur for the uplink flow disconnecting.

### Steps to Reproduce

1. Be terribly unlucky.
2. Have the steps described above happen.

### Current Result

The two instances fight over the gateway stats in Redis. The downlink counter and timestamps go back and forth between a stale value and the real value. The gateway is also counted twice in the metrics.

### Expected Result

The downlink counter and timestamps should be correct, and we should not count gateways twice.

### Relevant Logs

```shell
N/A.
```

### URL

_No response_

### Deployment

The Things Stack Enterprise (self-hosted)

### The Things Stack Version

3.25.0

### Client Name and Version

_No response_

### Other Information

_No response_

### Proposed Fix

Frontends (the UDP frontend really) are aware of the staleness of their flows. This information should be made available to the underlying `io.Connection`, such that the connection can avoid overwriting the counters and timestamps.

### Contributing

- [X] I can help by doing more research.
- [X] I can help by implementing a fix after the proposal above is approved.
- [X] I can help by testing the fix before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

### PR DESCRIPTION
**Pull request by adriansmares**
#### Summary

Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/6160

#### Changes

- Add a simple stream states mechanism which allows GS frontends to be queried if a stream is still active.
- Fix a race condition in the rate limiting UDP frontend.

#### Testing

Local testing.

##### Regressions

This functionality affects only stats book keeping, without affecting the hot path behavior.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/gatewayserver/io/stream_state.go [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+
+// MessageStream is a message stream.
+type MessageStream uint32
+
+const (
+	UplinkStream   MessageStream = 0 // UplinkStream is the uplink message stream.
+	DownlinkStream MessageStream = 1 // DownlinkStream is the downlink message stream.
+	TxAckStream    MessageStream = 2 // TxAckStream is the transmission acknowledgment stream.
+	StatusStream   MessageStream = 3 // StatusStream is the status message stream.
+	RTTStream      MessageStream = 4 // RTTStream is the round-trip times stream.
```
Comment (johanstokking) [inline pkg/gatewayserver/io/stream_state.go]: nit;

```suggestion
	UplinkStream   MessageStream = iota // UplinkStream is the uplink message stream.
	DownlinkStream  // DownlinkStream is the downlink message stream.
	TxAckStream     // TxAckStream is the transmission acknowledgment stream.
	StatusStream    // StatusStream is the status message stream.
	RTTStream       // RTTStream is the round-trip times stream.
```

needs some spacing

**Review by johanstokking — APPROVED** [review]
