### PR TITLE
Fix session keys nil dereference

### LINKED ISSUE #3053: nil pointer dereference in 3.9.0 applicationserver
#### Summary

TTN stack 3.9.0 is currently crash-looping with a nil pointer dereference.

#### Steps to Reproduce

1. Start the Stack.

#### What do you see now?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x18d2aba]
goroutine 124 [running]:
go.thethings.network/lorawan-stack/v3/pkg/applicationserver.(*ApplicationServer).decryptDownlinkMessage(0xc000843a20, 0x2774260, 0xc000d68c90, 0xc0007baec0, 0x1b, 0xc000581e38, 0x8, 0x0, 0xc000581e40, 0xc000581e48, ...)
	/Users/veg/devel/lorawan-stack-backend/pkg/applicationserver/applicationserver.go:1029 +0x18a
go.thethings.network/lorawan-stack/v3/pkg/applicationserver.(*ApplicationServer).handleUp(0xc000843a20, 0x2774260, 0xc000d68c30, 0xc000227300, 0xc000646200, 0x5f2eda2b, 0xa92c0f0, 0x3b4e166d88bc6)
	/Users/veg/devel/lorawan-stack-backend/pkg/applicationserver/applicationserver.go:540 +0x637
go.thethings.network/lorawan-stack/v3/pkg/applicationserver.(*link).sendUp(0xc000646200, 0x2774260, 0xc000470b10, 0xc000227300, 0xc000825d28, 0xc000646200, 0x2792d40)
	/Users/veg/devel/lorawan-stack-backend/pkg/applicationserver/linking.go:348 +0x2c6
go.thethings.network/lorawan-stack/v3/pkg/applicationserver.(*ApplicationServer).link(0xc000843a20, 0x2774260, 0xc000470870, 0xc000945300, 0x8, 0x0, 0xc00094c4c0, 0x0, 0x0)
	/Users/veg/devel/lorawan-stack-backend/pkg/applicationserver/linking.go:258 +0x9bc
go.thethings.network/lorawan-stack/v3/pkg/applicationserver.(*ApplicationServer).startLinkTask.func1(0x2774260, 0xc000470870, 0x39b0920, 0x0)
	/Users/veg/devel/lorawan-stack-backend/pkg/applicationserver/linking.go:63 +0x229
go.thethings.network/lorawan-stack/v3/pkg/component.(*Component).StartTask.func1(0xc0004708a0, 0x2774260, 0xc000470870, 0x279e120, 0xc00094c0c0, 0x2, 0x38e0cd0, 0x3, 0x3, 0x3fb999999999999a)
	/Users/veg/devel/lorawan-stack-backend/pkg/component/tasks.go:82 +0x84
created by go.thethings.network/lorawan-stack/v3/pkg/component.(*Component).StartTask
	/Users/veg/devel/lorawan-stack-backend/pkg/component/tasks.go:77 +0x150
```
#### What do you want to see instead?

No crash

#### Environment

Version 3.9.0 running in Kubernetes
a handful of Laird gateways connecting via basicstation and 3 end devices (xdot based). It suddenly started happening after I upgraded to 3.9.0 from 3.8.7.

#### How do you propose to implement this?

There appears to be no check for a non-existent session in applicationserver.go:

line 1022:
```
var session *ttnpb.Session
	switch {
	case dev.Session != nil && bytes.Equal(dev.Session.SessionKeyID, msg.SessionKeyID):
		session = dev.Session
	case dev.PendingSession != nil && bytes.Equal(dev.PendingSession.SessionKeyID, msg.SessionKeyID):
		session = dev.PendingSession
	}
	if session.GetAppSKey() == nil {
		return errNoAppSKey.New()
	}
```

My naive fix, based on not understanding what could cause this is:
```
        if session == nil || session.GetAppSKey() == nil {
```

#### How do you propose to test this?

Works On My Machine 

#### Can you do this yourself and submit a Pull Request?

Yes. But only if you think it's a good idea and I haven't missed the point entirely.

### PR DESCRIPTION
**Pull request by adriansmares**
#### Summary

Closes #3053

#### Changes

- Check if the `session` is `nil`, since the `SessionKeys` are actually an embedded member of the session.

#### Testing

Unit testing.

##### Regressions

The intent of the `if` stays the same, no regressions should occur.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/applicationserver/applicationserver.go [hunk 1]
```diff
@@ -1026,7 +1026,7 @@ func (as *ApplicationServer) decryptDownlinkMessage(ctx context.Context, ids ttn
 	case dev.PendingSession != nil && bytes.Equal(dev.PendingSession.SessionKeyID, msg.SessionKeyID):
 		session = dev.PendingSession
 	}
-	if session.GetAppSKey() == nil {
+	if session == nil || session.GetAppSKey() == nil {
```
Comment (KrishnaIyer) [inline pkg/applicationserver/applicationserver.go]: Would it be better to add a `default` to the `Switch` and exit the function with a `errSessionNotFound`?

**Review by KrishnaIyer — APPROVED** [review]
🚀
