### PR TITLE
Fix switch camera

### LINKED ISSUE #6529: Switch camera button during device onboarding via mobile doesn't work
### Summary

Switch camera button during device onboarding via mobile doesn't work.
Ref: https://github.com/TheThingsNetwork/lorawan-stack/pull/6500

### Steps to Reproduce

See https://github.com/TheThingsIndustries/lorawan-stack-support/issues/991#issuecomment-1710017134. 
I have also tested this with an iPhone 12 Pro with Safari and Firefox.

### Current Result

The switch camera button doesn't do anything visible on clicks.

### Expected Result

The button should cycle through the cameras. 
Since this is used by users to onboard devices, we need the users to be able to use the rear camera of their mobile phones. 
The good thing is that I have consistently seen that it always shows the primary (rear) camera. 
If we can somehow guarantee that this works, we don't even need to cycle I think.

### Relevant Logs

```shell
See https://github.com/TheThingsIndustries/lorawan-stack-support/issues/991#issuecomment-1710017134
```

### URL

_No response_

### Deployment

The Things Stack Open Source (self-hosted)

### The Things Stack Version

3.27.2

### Client Name and Version

```shell
iPhone Pro with Firefox and Safari.
```

### Other Information

_No response_

### Proposed Fix

_No response_

### Contributing

- [ ] I can help by doing more research.
- [ ] I can help by implementing a fix after the proposal above is approved.
- [X] I can help by testing the fix before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

### PR DESCRIPTION
**Pull request by ryaplots**
#### Summary

References #6529 

#### Changes

- Use a state for video mode

https://github.com/TheThingsNetwork/lorawan-stack/assets/56658938/9711301c-4915-4219-bfe6-2ff4d1361edf

#### Testing

1. Log in the console on a mobile device
2. Go to register end device
3. Click on scan end device QR code
4. See the switch button at the bottom of the video
5. Click and see the camera changing

#### Notes for Reviewers

Not using `stream` for conditions because at some point in time it is an empty object, which prevents comparing it's contents and makes it unreliable for the switch.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] The steps/process to test this feature are clearly explained including testing for regressions.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Comment by mjamescompton** [comment]
Is the clicking allow each time because of your set up or do you have to do that per camera?

**Comment by ryaplots** [comment]
> Is the clicking allow each time because of your set up or do you have to do that per camera?

I think it's my setup

**Comment by mjamescompton** [comment]
I have a feeling its every time you run `await navigator.mediaDevices.getUserMedia({` it resets the the user permissions.

**Comment by ryaplots** [comment]
> I have a feeling its every time you run `await navigator.mediaDevices.getUserMedia({` it resets the the user permissions.

Might be. Let me test.

**Comment by kschiffer** [comment]
Cool! Can we put the button on top of the camera stream instead? Right now it's causing this black bar at the bottom.
Also, can we fix the missing margin between the two "Cancel" and "Apply" button?

File: pkg/webui/components/qr/input/video/index.js [hunk 1]
```diff
@@ -76,30 +78,28 @@ const Video = props => {
   }, [devices, setCapture, setError, stream])
 
   const switchStream = useCallback(async () => {
-    if (stream === { facingMode: 'environment' }) {
+    if (videoMode.facingMode === 'environment') {
```
Comment (mjamescompton) [inline pkg/webui/components/qr/input/video/index.js]: device: iPhone14 Pro
browser: safari

`videeMode.faceMode` === `{ exact: "environment" }`

There is no condition for this so the switch camera button does nothing.

File: pkg/webui/components/qr/input/video/index.js [hunk 2]
```diff
@@ -135,23 +135,25 @@ const Video = props => {
...
+  return (
     <>
-      <video
-        autoPlay
-        playsInline
-        ref={videoRef}
-        className={style.video}
-        data-test-id="webcam-feed"
-      />
       {cameras.length > 1 && isMobile && (
```
Comment (mjamescompton) [inline pkg/webui/components/qr/input/video/index.js]: `isMobile` I don't think this is needed.

Comment (mjamescompton) [reply pkg/webui/components/qr/input/video/index.js]: `cameras.length` does not have a value when you first open the modal, you must close and re-open the model for the switch camera button to should. 

It might be better to always show the button and disable it if the device.length is 1 or less

**Review by mjamescompton — CHANGES_REQUESTED** [review]
Could not get the switch to work on either iPhone 14 or Samsung Galaxy A10

Screenshot 2023-10-13 at 16 09 12

Nothing happens on the iPhone and above happens on the samsumg on chrome when I click the button

**Review by kschiffer — APPROVED** [review]
LGTM, though haven't tested.

**Review by mjamescompton — CHANGES_REQUESTED** [review]
Ok, 

Iphone 14 pro - chrome  and safari - testing 

- switch camera button still does not show on first render of the modal
- switching the camera works once to go from back camera to front 
- but clicking the button again does nothing

I'm thinking we should put a component in between two we currently have. This one would specifically handle requesting the stream etc and includes the switching button, then we re-render the a component <Video stream="xxx">  because the `cameras.length` does not seem to cause a re render to show the button. The button could also always show but greyed out until the camera length is updated .

**Review by mjamescompton — APPROVED** [review]
Still broken but going ahead anyway.

I don't have an android phone to test, but I believe the switch button not rendering will be there as well, so I don't think anyone will see it anyway
