### PR TITLE
Fix pausing of event streams in Console

### LINKED ISSUE #3324: Fix event selection in the Console
#### Summary

selected-event

https://github.com/TheThingsNetwork/lorawan-stack/pull/3301 - does not solve the issue.

#### Steps to Reproduce

1. Open events page for apps/devices/gateways
2. Wait for some events to arrive
3. Pause events stream
4. Click on different events in the events list until selected event is not highlighted

Another issue:

1. Open events page for any entity
2. Clear events list
3. Click on the clear synthetic event until it stops closing the side panel

#### What do you see now?

Selected event is not highlighted in the events list

#### What do you want to see instead?

Selected event properly highlighted.

#### Environment

v3.10, staging

#### How do you propose to implement this?

@kschiffer 

#### How do you propose to test this?

See reproduction steps

#### Can you do this yourself and submit a Pull Request?

no

### PR DESCRIPTION
**Pull request by kschiffer**
#### Summary
This PR changes the logic of event pausing to pause event ingestion on store level rather than component level. This means that the Console will not save up events that arrived during the pause anymore.

Closes #3324 

image

#### Changes
- Extend store logic to allow for pausing ingestion of new events when the stream is paused
- Remove `shouldUpdate` type logic for the event component
- Add respective synthetic events for pausing and resuming the event stream
- Update event containers to pass down new action dispatches and selected `pause` prop
- Adjust the styling of the pause button a bit to make the paused state more noticeable

#### Testing

Manual testing.

##### Regressions

This might cause issues wrt correct event display during paused and resumed state

#### Notes for Reviewers
This will not interrupt the stream connection itself but only interrupt the adding of new events to the store. The event connection needs to persist e.g. in order to detect heartbeat events for end devices.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/webui/console/store/index.js [hunk 1]
```diff
@@ -29,7 +29,17 @@ import requestPromiseMiddleware from './middleware/request-promise-middleware'
 import logics from './middleware/logics'
 
 const composeEnhancers = (dev && window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__) || compose
-let middlewares = [requestPromiseMiddleware, createLogicMiddleware(logics)]
+
+const userTimingMiddleware = () => next => action => {
```
Comment (bafonins) [inline pkg/webui/console/store/index.js]: Do we need this in master?

Comment (kschiffer) [reply pkg/webui/console/store/index.js]: Oh, this slipped through from performance debugging. Will remove.

**Review by bafonins — APPROVED** [review]
