### PR TITLE
Limit event views in the Console to 2000 events per stream

### LINKED ISSUE #2887: Data views slow down and freeze after receiving many events
#### Summary
The data views of the console freeze after receiving a lot of events.

#### Steps to Reproduce
1. Go to the data view for an entity that receives a lot of events
2. Wait for some time while observing incoming events (waiting time is relative to the event frequency)
3. Observe the app becoming slow
4. Observe the app eventually freezing completely

#### What do you see now?
Freezing data views

#### What do you want to see instead?
Data views being stable regardless of the amount of events received

#### Environment
v3.5.8 and older

#### How do you propose to implement this?
The problem is likely caused by the redux store being filled considerably when the console is subscribed to an event source. Especially since the packet broker update, it will receive a lot of data per event which easily sucks up memory. My ideas to fix this are:
- Introduce a maximum amount of messages that are stored (rest being truncated)
- Discard event data for old events
- Experiment with storing event data in the browsers `localStorage` instead of in the redux store. We could then only reference the event data in the redux store. This is assumption-based buy maybe the `localStorage` can handle large amounts of data better.

@bafonins what do you think?

#### How do you propose to test this?
Manual testing.

#### Can you do this yourself and submit a Pull Request?
Yes.

### PR DESCRIPTION
**Pull request by kschiffer**
#### Summary
This PR is a forgotten followup from #3330. It limits the number of events per stream to 2000 in the Console, to prevent memory and performance issues in the event views.

image

Closes #2887 

#### Changes
- Set a hard limit for events to 2000, after that old limits will be truncated
- Add some logic and styles to communicate truncated events

#### Testing

Manual testing on the staging environment

##### Regressions

This touches store logic for events, so it could introduce arbitrary issues with event ingestion and display in the Console.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/webui/console/components/events/index.js [hunk 1]
```diff
@@ -32,81 +33,91 @@ import { getEventId } from './utils'
...
-    [focus],
-  )
+const Events = React.memo(
+  ({ events, scoped, paused, onClear, onPauseToggle, entityId, truncated }) => {
+    const [focus, setFocus] = useState({ eventId: undefined, visible: false })
+    const onPause = useCallback(() => onPauseToggle(paused), [onPauseToggle, paused])
+    const handleRowClick = useCallback(
+      eventId => {
+        if (eventId !== focus.eventId) {
+          setFocus({ eventId, visible: eventId })
```
Comment (bafonins) [inline pkg/webui/console/components/events/index.js:44]:
```suggestion
          setFocus({ eventId, visible: true })
```

**Review by bafonins — APPROVED** [review]
