### PR TITLE
Webhook templates improvements

### LINKED ISSUE #17: Make template fields optional
#### Summary

I want to make a template field optional. But a red asterisk is added to the right of the field name.

image

And when I try to save while leaving it empty

image

#### Environment
- **Webhook template:** new under development
- **The Things Stack version:** v3.11.1

#### Steps to Reproduce

1. Create a webhook template with one field and load the template.

#### What do you see now?

The field is required.

#### What do you want to see instead?

Allow leaving the field blank.

#### How do you propose to implement this?

Add an optional property to the field definition.

#### Can you do this yourself and submit a Pull Request?

No

### LINKED ISSUE #18: Default value ignored
#### Summary

I have a default value defined in the template:
```
fields:
  - id: experiment
    name: Experiment Name (optional)
    description: If you are testing (new device, balloon flights, etc) and do not want your data to appear on the main map, please specify an experiment name.
    secret: false
    default-value: "test"
```

But on the console the field is not filled in with the default value:

image

#### Environment
- **Webhook template:** new
- **The Things Stack version:** v3.11.1

#### Steps to Reproduce

1. Add a field to the webhook template
2. Add a default value
3. Reload console / restart stack

#### What do you see now?

Field is not pre-filled with default value

#### What do you want to see instead?

The field should be pre-filled with the default value

#### How do you propose to implement this?

Fix the bug

#### Can you do this yourself and submit a Pull Request?

No

### LINKED ISSUE #20: Only uplink-message endpoint added
#### Summary

In my-template.yaml I have:
```
paths:
  uplink-message: /uplink-message
  join-accept: /join-accept
  location-solved: /location-solved
```

But when the webhook is added, only the uplink-message endpoint was added:
image

#### Environment
- **Webhook template:** new under development
- **The Things Stack version:** v3.11.2

#### Steps to Reproduce

1. Create a template that adds more than just the uplink-message enpoints.
2. Create a webhook from the tempalte.
3. Look at which endpoints are active.

#### What do you see now?

Only uplink-message is added.

#### What do you want to see instead?

All defined endpoints in the template should be added.

#### How do you propose to implement this?

Fix the bug.

#### Can you do this yourself and submit a Pull Request?

No

### PR DESCRIPTION
**Pull request by adriansmares**
#### Summary

Closes https://github.com/TheThingsNetwork/lorawan-webhook-templates/issues/20
Closes https://github.com/TheThingsNetwork/lorawan-webhook-templates/issues/18
Closes https://github.com/TheThingsNetwork/lorawan-webhook-templates/issues/17
 
#### Changes

- Retrieve all webhook template fields
  - This fixes https://github.com/TheThingsNetwork/lorawan-webhook-templates/issues/20, as fields such as `service_data` and `join_accept` were not retrieved, and as such considered to be empty (and non instantiated).
- Use the field default value, instead of always using `''`
- Add `optional` tag to template fields. It can be used to remove the `required` tag of the webhook template fields.
  - A follow up on this is that empty headers, after instantiation, are no longer made part of the final webhook. This behavior ensures that templates don't create uneditable webhooks (as headers require values).

#### Testing

I've checked out the template repository in `./lorawan-webhook-templates` and used the `--as.webhooks.templates.directory` configuration parameter to serve the templates locally.

Afterwards I've just reproduced the bugs using the descriptions in the issues (you can edit the TTN Mapper template to toy with these issues).

##### Regressions

This changes the webhook template form generation and instantiation algorithm. Both changes have been tested.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

CC @nejraselimovic , @jpmeijers

### CODE REVIEW

**Comment by jpmeijers** [comment]
Optional field, and field default value tested, and work as expected.

Additional endpoints are also added to created webhook.

Note: I only tested the template. I did not test the actual integration with a real device.

**Review by htdvisser — APPROVED** [review]

**Review by kschiffer — APPROVED** [review]

File: pkg/webui/console/components/webhook-template-form/index.js [hunk 1]
```diff
@@ -147,24 +150,29 @@ export default class WebhookTemplateForm extends Component {
...
-        {
-          webhook_id: Yup.string()
-            .matches(webhookIdRegexp, Yup.passValues(sharedMessages.validateIdFormat))
-            .min(2, Yup.passValues(sharedMessages.validateTooShort))
-            .max(25, Yup.passValues(sharedMessages.validateTooLong))
-            .required(sharedMessages.validateRequired),
-        },
-      ),
+      ...fields
+        .filter(field => !field.optional)
```
Comment (bafonins) [inline pkg/webui/console/components/webhook-template-form/index.js]: Not sure we should filter out optional fields. Can we still add those to the validation schema but without the `.required` validation? Something like this:

```js
[field.id]: field.optional ? Yup.string() : Yup.string().required(sharedMessages.validateRequired)
```

**Review by bafonins — APPROVED** [review]

**Review by johanstokking — APPROVED** [review]
Code owned files (API + AS) LGTM. @bafonins' comment seems sane

**Review by asmulko — APPROVED** [review]
