### PR TITLE
Fix JS AAS usage

### LINKED ISSUE #3408: Application activation settings
#### Summary

Application activation settings don't work correctly.

#### Steps to Reproduce

Configure application server settings

#### What do you see now?

1. A panic when setting the activation settings [1]
2. The KEK seems to be mandatory
3. The KEK is used to wrap the network session keys too

[1]

```
error cause should not be set if nil
goroutine 301 [running]:
[...]
go.thethings.network/lorawan-stack/v3/pkg/errors.Definition.WithCause(0x4cdcfae, 0xe, 0x36f7207, 0xa, 0x370d018, 0x12, 0x509eba0, 0x0, 0x0, 0xc0009f0960, ...)
	/Users/johan/dev/src/lorawan-stack/pkg/errors/causes.go:47 +0x17e
go.thethings.network/lorawan-stack/v3/pkg/joinserver.applicationActivationSettingsRegistryServer.Set.func1(0x0, 0xc000a64750, 0xc000000005, 0x3b07560, 0xc000a64750, 0x3b8c060, 0xc001417200)
	/Users/johan/dev/src/lorawan-stack/pkg/joinserver/grpc_application_activation_settings_registry.go:87 +0x265
```

Please don't try to save vertical space with this kind of code. It's really not worth the instability it may cause.

#### What do you want to see instead?

1. No panic
2. The KEK is optional
3. The KEK, if set, is only used to wrap the AppSKey

#### Environment

`v3.10.rc2`

#### How do you propose to implement this?

For 1 and 2, here's my proposal:

```diff
diff --git a/pkg/joinserver/grpc_application_activation_settings_registry.go b/pkg/joinserver/grpc_application_activation_settings_registry.go
index 7b4d61bf6..7bb2214c9 100644
--- a/pkg/joinserver/grpc_application_activation_settings_registry.go
+++ b/pkg/joinserver/grpc_application_activation_settings_registry.go
@@ -58,13 +58,19 @@ func (srv applicationActivationSettingsRegistryServer) Set(ctx context.Context,
 	if len(req.FieldMask.Paths) == 0 {
 		return nil, errInvalidFieldMask.WithCause(errNoPaths)
 	}
+
+	if ttnpb.HasAnyField(req.FieldMask.Paths, "key.kek") && req.ApplicationActivationSettings.KEK.GetKey().IsZero() {
+		return nil, errInvalidFieldValue.WithAttributes("field", "kek.key")
+	}
+
 	if err := rights.RequireApplication(ctx, req.ApplicationIdentifiers, ttnpb.RIGHT_APPLICATION_DEVICES_READ_KEYS, ttnpb.RIGHT_APPLICATION_DEVICES_WRITE_KEYS); err != nil {
 		return nil, err
 	}
+
 	sets := req.FieldMask.Paths
 	reqKEK := req.ApplicationActivationSettings.KEK
-	if k := reqKEK.GetKey(); !k.IsZero() && ttnpb.HasAnyField(sets, "kek.key") {
-		kek, err := cryptoutil.WrapAES128Key(ctx, *k, srv.kekLabel, srv.JS.KeyVault)
+	if ttnpb.HasAnyField(sets, "kek.key") {
+		kek, err := cryptoutil.WrapAES128Key(ctx, *req.ApplicationActivationSettings.KEK.Key, srv.kekLabel, srv.JS.KeyVault)
 		if err != nil {
 			return nil, errWrapKey.WithCause(err)
 		}
@@ -76,22 +82,8 @@ func (srv applicationActivationSettingsRegistryServer) Set(ctx context.Context,
 		)
 	}
 	v, err := srv.JS.applicationActivationSettings.SetByID(ctx, req.ApplicationIdentifiers, req.FieldMask.Paths, func(stored *ttnpb.ApplicationActivationSettings) (*ttnpb.ApplicationActivationSettings, []string, error) {
-		if stored == nil {
-			if err := ttnpb.RequireFields(req.FieldMask.Paths,
-				"kek_label",
-			); err != nil {
-				return nil, nil, errInvalidFieldMask.WithCause(err)
-			}
-			if !ttnpb.HasAnyField(req.FieldMask.Paths, "kek.key") ||
-				!ttnpb.HasAnyField(req.FieldMask.Paths, "kek.encrypted_key") && !ttnpb.HasAnyField(req.FieldMask.Paths, "kek.kek_label") {
-				return nil, nil, errInvalidFieldMask.WithCause(ttnpb.RequireFields(req.FieldMask.Paths, "kek.key"))
-			}
-		}
 		return &req.ApplicationActivationSettings, sets, nil
 	})
-	if errors.IsNotFound(err) {
-		return nil, errApplicationActivationSettingsNotFound.WithCause(err)
-	}
 	if err != nil {
 		return nil, err
 	}
diff --git a/pkg/joinserver/grpc_application_activation_settings_registry_test.go b/pkg/joinserver/grpc_application_activation_settings_registry_test.go
index 757b0b691..441934b64 100644
--- a/pkg/joinserver/grpc_application_activation_settings_registry_test.go
+++ b/pkg/joinserver/grpc_application_activation_settings_registry_test.go
@@ -414,21 +414,6 @@ func TestApplicationActivationSettingRegistryServer(t *testing.T) {
 		CreatePaths    []string
 		GetSettings    *ttnpb.ApplicationActivationSettings
 	}{
-		{
-			Name: "KEK encrypted at rest",
-			CreateSettings: &ttnpb.ApplicationActivationSettings{
-				KEKLabel: sessionKEKLabel,
-				KEK:      jsKEKEnvelopeWrapped,
-			},
-			CreatePaths: []string{
-				"kek",
-				"kek_label",
-			},
-			GetSettings: &ttnpb.ApplicationActivationSettings{
-				KEKLabel: sessionKEKLabel,
-				KEK:      jsKEKEnvelopeUnwrapped,
-			},
-		},
 		{
 			Name: "KEK sent plaintext",
 			CreateSettings: &ttnpb.ApplicationActivationSettings{
```

For 3, the AppSKey is wrapped with the end device's AS KEK (if set), otherwise the KEK specified in the application activation settings (if set), otherwise the key vault's default label is used (i.e. by component address). For NwkSKeys, only the last behavior is used.

#### How do you propose to test this?

Unit tests and integration testing, preferably with CLI support (#3401)

#### Can you do this yourself and submit a Pull Request?

Can review

### PR DESCRIPTION
**Pull request by johanstokking**
#### Summary

Closes #3408

#### Changes

- Do not require AAS KEK to be specified; fixes request validation panic along the way
- Do not use AAS KEK for NS keys

#### Testing

Unit testing, doing integration testing now

##### Regressions

NS depending on wrong behavior, i.e. NwkSKey wrapped with AAS KEK, will break, but this is considered a bugfix.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/joinserver/grpc_application_activation_settings_registry.go [hunk 1]
```diff
@@ -76,22 +82,8 @@ func (srv applicationActivationSettingsRegistryServer) Set(ctx context.Context,
 		)
 	}
 	v, err := srv.JS.applicationActivationSettings.SetByID(ctx, req.ApplicationIdentifiers, req.FieldMask.Paths, func(stored *ttnpb.ApplicationActivationSettings) (*ttnpb.ApplicationActivationSettings, []string, error) {
-		if stored == nil {
-			if err := ttnpb.RequireFields(req.FieldMask.Paths,
-				"kek_label",
```
Comment (rvolosatovs) [inline pkg/joinserver/grpc_application_activation_settings_registry.go:81]: `KEKLabel` was marked as required field in original issue, did that requirement change?

File: pkg/joinserver/grpc_application_activation_settings_registry.go [hunk 2]
```diff
@@ -76,22 +82,8 @@ func (srv applicationActivationSettingsRegistryServer) Set(ctx context.Context,
...
-			); err != nil {
-				return nil, nil, errInvalidFieldMask.WithCause(err)
-			}
-			if !ttnpb.HasAnyField(req.FieldMask.Paths, "kek.key") ||
```
Comment (rvolosatovs) [inline pkg/joinserver/grpc_application_activation_settings_registry.go:85]: `KEK` was marked as required in original issue, did that requirement change?

File: pkg/joinserver/grpc_application_activation_settings_registry.go [hunk 3]
```diff
@@ -76,22 +82,8 @@ func (srv applicationActivationSettingsRegistryServer) Set(ctx context.Context,
...
-				!ttnpb.HasAnyField(req.FieldMask.Paths, "kek.encrypted_key") && !ttnpb.HasAnyField(req.FieldMask.Paths, "kek.kek_label") {
-				return nil, nil, errInvalidFieldMask.WithCause(ttnpb.RequireFields(req.FieldMask.Paths, "kek.key"))
-			}
-		}
 		return &req.ApplicationActivationSettings, sets, nil
 	})
-	if errors.IsNotFound(err) {
```
Comment (rvolosatovs) [inline pkg/joinserver/grpc_application_activation_settings_registry.go:92]: Without this, users get direct error from the (probably Redis) registry, it's nicer to wrap it, why change this?

**Review by rvolosatovs — APPROVED** [review]

File: pkg/joinserver/grpc_application_activation_settings_registry.go (hunk 2 above)
Comment (johanstokking) [reply pkg/joinserver/grpc_application_activation_settings_registry.go:85]: See above

File: pkg/joinserver/joinserver.go [hunk 4]
```diff
@@ -320,10 +320,21 @@ func (js *JoinServer) HandleJoin(ctx context.Context, req *ttnpb.JoinRequest) (r
 		},
 		func(ctx context.Context, dev *ttnpb.EndDevice) (*ttnpb.EndDevice, []string, error) {
 			if dn, ok := auth.X509DNFromContext(ctx); ok {
-				if dev.NetID == nil {
+				netID := dev.NetID
+				if netID == nil {
+					appSettings, err := js.applicationActivationSettings.GetByID(ctx, dev.ApplicationIdentifiers, []string{
```
Comment (rvolosatovs) [inline pkg/joinserver/joinserver.go]: it would be great if only 1 call to the registry would be required, because currently the call on L515 can be executed as well, even though we already have enough data

File: pkg/joinserver/grpc_application_activation_settings_registry.go (hunk 1 above)
Comment (johanstokking) [reply pkg/joinserver/grpc_application_activation_settings_registry.go:81]: It's not marked required, but it's also not marked explicitly optional in [the original issue](https://github.com/TheThingsIndustries/lorawan-stack/issues/2322). However, it does say "[...] multiple KEKs per application; at most one is fine", implying that it's optional. Anyway, it's optional now: users can also specify the default NetID only.

**Review by rvolosatovs — APPROVED** [review]
