### PR TITLE
Fix sentry error descriptions

### LINKED ISSUE #2849: Improve sentry error fingerprints for frontend errors
#### Summary
We currently see a lot of sentry errors being grouped in an unhelpful way. We need to use better fingerprints to ensure that grouped events actually account for the same type of error.

#### Steps to Reproduce
See sentry issues like these: https://sentry.io/organizations/the-things-industries/issues/1739012974/events/d441eb3ca15d4897be4be5a8bdce8b6b/?project=2682566&referrer=github_integration

Going through the individual error events, it can be seen that all the errors are grouped on the grounds of being logged as: `Non-Error exception captured with keys: code, details, message`
However, a lot of different backend errors can ultimately result in this error message. See also: https://github.com/TheThingsNetwork/lorawan-stack/issues/2824#issuecomment-654559983

#### What do you see now?
Sentry events being grouped in an unhelpful way.

#### What do you want to see instead?
Sentry events being grouped correctly.

#### Environment
v3.8.5

#### How do you propose to implement this?
I've found [this article](https://blog.sentry.io/2019/01/17/debug-tough-front-end-errors-sentry-clues) which has some helpful suggestions.

We should also make sure that we wrap the backend error into a proper `Error()` constructor.

#### How do you propose to test this?
Manually.

#### Can you do this yourself and submit a Pull Request?
@pgalic96

### PR DESCRIPTION
**Pull request by pgalic96**
#### Summary

Closes #2849 

An example of an error event: https://sentry.io/organizations/the-things-industries/issues/1772980065/?project=2732897&query=is%3Aunresolved

#### Changes

- Add grouping of error events by error id, if one is present
- Wrap errors with `Error` object and add error id as description, or generic description if error id is not present

#### Testing

- Tested manually

##### Regressions

- Sentry logging

#### Notes for Reviewers

@kschiffer This might look ugly, but I don't see other way of doing it until we are absolutely sure that everything we get from backend is in the same format (meaning that sometimes errors don't have message, details, etc.)

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md`. The target branch is set to `master` if the changes are fully compatible with existing API, database, configuration and CLI.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/webui/console/store/middleware/logics/lib.js [hunk 1]
```diff
@@ -89,7 +94,20 @@ const createRequestLogic = function(
         } else {
           // Otherwise, dispatch the fail action and report it to Sentry.
           if (isUnknown(e) || isInvalidArgumentError(e)) {
```
Comment (kschiffer) [inline pkg/webui/console/store/middleware/logics/lib.js:96]: What was actually the reason for distinguishing invalid argument errors?

File: pkg/webui/console/store/middleware/logics/lib.js [hunk 2]
```diff
@@ -89,7 +94,20 @@ const createRequestLogic = function(
...
-            Sentry.captureException(failAction(e))
+            Sentry.withScope(scope => {
+              scope.setExtras(e)
+              if (e.message) {
+                scope.setFingerprint(getBackendErrorId(e))
+                Sentry.captureException(new Error(getBackendErrorId(e)))
+              } else if (e.payload && e.payload.message) {
```
Comment (kschiffer) [inline pkg/webui/console/store/middleware/logics/lib.js:102]: When does that happen that a fail action is thrown? That seems odd to me, the `process()` function should dispatch API actions that should fail with backend error objects or request errors. Only the request logic itself here is wrapping the error into the fail action.

File: pkg/webui/lib/components/error-view.js [hunk 3]
```diff
@@ -39,8 +40,14 @@ class ErrorView extends React.Component {
...
-      scope.setExtras(errorInfo)
-      Sentry.captureException(error)
+      scope.setExtras(error)
+      if (error.message) {
+        const errorId = getBackendErrorId(error)
+        scope.setFingerprint([errorId])
+        Sentry.captureException(new Error(errorId))
+      } else {
+        Sentry.captureException(error)
+      }
```
Comment (kschiffer) [inline pkg/webui/lib/components/error-view.js:50]: Better to use our error utils here to distinguish the error `isBackend` and `isFrontend`.

You might also consider making a new util `getErrorFingerprint(error)` which basically does all of the above and we can maintain it in one place.

File: pkg/webui/console/store/middleware/logics/lib.js (hunk 2 above)
Comment (pgalic96) [reply pkg/webui/console/store/middleware/logics/lib.js:102]: sentry.io/organizations/the-things-industries/issues/1739001198/?project=2682566&query=is%3Aunresolved  check this

File: pkg/webui/console/store/middleware/logics/lib.js (hunk 1 above)
Comment (pgalic96) [reply pkg/webui/console/store/middleware/logics/lib.js:96]: the reason is that there is a lot of errors that are part of the regular flow, `404` for example always occurs when creating new gateways which haven't been connected. We don't want this to consume our sentry subscription.

File: pkg/webui/console/store/middleware/logics/lib.js (hunk 2 above)
Comment (pgalic96) [reply pkg/webui/console/store/middleware/logics/lib.js:102]: https://sentry.io/organizations/the-things-industries/issues/1739001198/events/024287ed737f4e8590651102b6c97653/?project=2682566

Why `isBackend` is false for this error? It has all the attributes that `isBackend` checks, but it still goes into this condition `isUnknown || isInvalidArgumentError`. This and many other errors mean that we cant just ignore `isUnknown`, but the problem is that the request errors and unrecognized backend errors are mixed there, meaning Sentry will have a hard time distinguishing between them.

**Comment by pgalic96** [comment]
So, while looking at the error events I came to some conclusions:

- We don't need (or shouldn't at least) separate utility for getting the error fingerprint. The error fingerprint should be derived for the backend errors, since these errors have a nice `message` property from which we can extract the fingerprint using `getBackendErrorId`. Frontend errors get caught by a built-in error catcher
- In error view it is enough to catch the backend errors, as the frontend errors that crash the console will get caught by default

File: pkg/webui/console/store/middleware/logics/lib.js (hunk 1 above)
Comment (kschiffer) [reply pkg/webui/console/store/middleware/logics/lib.js]: I get that for 404s, but invalid argument is not a 404?

File: pkg/webui/console/store/middleware/logics/lib.js (hunk 2 above)
Comment (kschiffer) [reply pkg/webui/console/store/middleware/logics/lib.js]: So what's the conclusion? Can you check where we wrongfully throw the whole action instead of just the error payload? We need an issue to fix that.

File: pkg/webui/console/store/middleware/logics/lib.js (hunk 1 above)
Comment (pgalic96) [reply pkg/webui/console/store/middleware/logics/lib.js]: yeah I think we decided that `invalidArgumentError` is the one that is not part of any regular flow, so it is good to report it to Sentry. The rest of the errors (404, 401, 403...) is not reported to Sentry.

File: pkg/webui/console/store/middleware/logics/lib.js (hunk 2 above)
Comment (pgalic96) [reply pkg/webui/console/store/middleware/logics/lib.js]: Yes we did it here, I wrapped the exception with `failAction` and reported it like that to Sentry. That is fixed now.
