### PR TITLE
Fix errors in events

### LINKED ISSUE #502: Error payload in events does not get published correctly
**Summary:** 

Error payload in events does not get published correctly

**Steps to Reproduce:** 

1. Spin up the stack
2. Subscribe to gateway events, i.e. `ttn-lw-cli events subscribe --gateway-id ...`
3. Start sending ABP uplink traffic with a random session, i.e. anything not existing

**What do you see now?**

The `gs.up.drop` event payload ends after `"data":`, see for example;

```js
{
  "name": "gs.up.drop",
  "time": "2019-04-08T15:16:43.563891502Z",
  "identifiers": [
    {
      "gateway_ids": {
        "gateway_id": "<snip>",
        "eui": "<snip>"
      }
    }
  ],
  "data":
{
  "name": "gs.up.receive",
   ...
```

**What do you want to see instead?**

The error as it gets published.

**Environment:**

`v3.0.0`

**How do you propose to implement this?**

Not sure. I something goes wrong here:

https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.0.0/pkg/events/events.go#L169-L174

What goes wrong for sure is that we're locally declaring `err` there and setting that as the output of the marshaling. But that doesn't set the outer error. So any errors L171 or L173 are discarded.

**Can you do this yourself and submit a Pull Request?**

I can review

### PR DESCRIPTION
**Pull request by htdvisser**
**Summary:**

This PR fixes #502 by using `ttnpb.ErrorDetailsToProto` instead of the statuspb. Additionally it skips marshaling empty maps.

### CODE REVIEW

File: pkg/events/events.go [hunk 1]
```diff
@@ -168,7 +168,7 @@ func Proto(e Event) (*ttnpb.Event, error) {
 			pb.Data, err = types.MarshalAny(protoMessage)
 		} else if err, ok := evt.data.(error); ok {
 			if ttnErr, ok := errors.From(err); ok {
-				pb.Data, err = types.MarshalAny(ttnErr.GRPCStatus().Proto())
+				pb.Data, err = types.MarshalAny(ttnpb.ErrorDetailsToProto(ttnErr))
```
Comment (johanstokking) [inline pkg/events/events.go]: This still sets the `err` that is locally redefined on L169. So either check-return this `err` on L175 or rename `err` on L169

Comment (johanstokking) [reply pkg/events/events.go]: Note that this is also why we saw a half message printed; the error wasn't caught but we used a dirty buffer
