### PR TITLE
Extend IS blacklist

### LINKED ISSUE #419: Blacklist console routes entries
**Summary:** 

It is possible to create an entity with the `add` as an identifier. This causes issues in console routing, since we use `/console/<entity-id>/add`  for the entity add page and hence the entity is not reachable.

**Steps to Reproduce:** 

1. Create a new application with `id = add`
2. Navigate to `/console/applications/add`
3. See the Add Application page instead of the Application Overview page for the `add` application. 

**What do you see now?**

The Add Application page

**What do you want to see instead?**

The Application Overview page

**Environment:**

is, browser

**How do you propose to implement this?**

Extend the blacklist 

**Can you do this yourself and submit a Pull Request?**

Fix the issue

### PR DESCRIPTION
**Pull request by bafonins**
**Summary:**

Closes #419 

Screenshot 2019-04-01 at 11 21 56

**Changes:**

- Extend IS blacklist with entries from https://github.com/shouldbee/reserved-usernames/blob/master/reserved-usernames.json
- Fix `<Form />` error to field mapping
- Extend the Application Add form with the `blacklist_id` error

**Notes for Reviewers:**

@htdvisser please check the blacklist extension
@kschiffer please check the console related changes

**Release Notes: _(optional)_**

- Block `add`, `edit`, `device`, `devices`, `end_device`, `end_devices`, `collaborator`, `collaborators` identifiers

### CODE REVIEW

**Comment by bafonins** [comment]
@htdvisser also, what about `api-key`, `api-keys` ?

**Comment by bafonins** [comment]
@htdvisser updated

File: pkg/identityserver/blacklist/builtin.go [hunk 1]
```diff
@@ -15,148 +15,678 @@
...
+	"tools",
+	"top",
+	"topic",
+	"topics",
+	"tos",
+	"tour",
+	"translations",
+	"trends",
+	"tti",
+	"ttn",
```
Comment (htdvisser) [inline pkg/identityserver/blacklist/builtin.go]: Let's add `ttn-lw-cli` and `ttn-lw-stack`.

File: pkg/identityserver/blacklist/builtin.go [hunk 2]
```diff
@@ -15,148 +15,678 @@
...
 	"localhost",
+	"log",
+	"log-in",
+	"log-out",
+	"log_in",
+	"log_out",
+	"login",
+	"logout",
+	"logs",
+	"m",
```
Comment (htdvisser) [inline pkg/identityserver/blacklist/builtin.go]: Let's also add `lorawan`, `lora`, `lorawan-stack`

File: pkg/identityserver/blacklist/builtin.go [hunk 3]
```diff
@@ -15,148 +15,678 @@
...
+	"follow",
+	"followers",
+	"following",
+	"forgot",
+	"form",
 	"forum",
 	"forums",
+	"founder",
+	"free",
+	"friend",
```
Comment (htdvisser) [inline pkg/identityserver/blacklist/builtin.go]: Let's also add `frequency-plan`/`frequency-plans`

File: pkg/identityserver/blacklist/builtin.go [hunk 4]
```diff
@@ -15,148 +15,678 @@
...
 	"alerts",
+	"all",
 	"alpha",
+	"analysis",
 	"analytics",
+	"android",
+	"anon",
+	"anonymous",
+	"api",
 	"app",
```
Comment (htdvisser) [inline pkg/identityserver/blacklist/builtin.go]: Lets' also add `api-key`/`api-keys`

File: pkg/identityserver/blacklist/builtin.go (hunk 2 above)
Comment (johanstokking) [reply pkg/identityserver/blacklist/builtin.go]: `m` is too short anyway

File: pkg/identityserver/blacklist/builtin.go [hunk 5]
```diff
@@ -15,148 +15,678 @@
...
+	"changelog",
+	"chat",
+	"check",
+	"checking",
+	"checkout",
+	"cli",
 	"client",
+	"cliente",
 	"clients",
+	"code",
```
Comment (KrishnaIyer) [inline pkg/identityserver/blacklist/builtin.go]: Please add `cluster`

File: pkg/identityserver/blacklist/builtin.go [hunk 6]
```diff
@@ -15,148 +15,678 @@
...
+	"owners",
+	"page",
+	"pager",
+	"pages",
+	"panel",
+	"partners",
+	"password",
+	"payment",
+	"perl",
+	"phone",
```
Comment (KrishnaIyer) [inline pkg/identityserver/blacklist/builtin.go]: `peer`/`peers`?

File: pkg/identityserver/blacklist/builtin.go [hunk 7]
```diff
@@ -15,148 +15,678 @@
...
+	"msg",
+	"msn",
+	"music",
+	"musicas",
+	"mx",
+	"my",
+	"myself",
+	"mysql",
+	"name",
+	"named",
```
Comment (KrishnaIyer) [inline pkg/identityserver/blacklist/builtin.go]: `namespace`

File: pkg/identityserver/blacklist/builtin.go [hunk 8]
```diff
@@ -15,148 +15,678 @@
...
+	"python",
+	"query",
+	"random",
+	"ranking",
+	"read",
+	"readme",
+	"recent",
+	"recruit",
+	"recruitment",
+	"register",
```
Comment (KrishnaIyer) [inline pkg/identityserver/blacklist/builtin.go]: `redirect`, `redirect_uri`

File: pkg/identityserver/blacklist/builtin.go [hunk 9]
```diff
@@ -15,148 +15,678 @@
...
+	"testing",
+	"tests",
+	"theme",
+	"themes",
+	"thethings",
+	"things",
+	"this",
+	"thread",
+	"threads",
+	"tmp",
```
Comment (KrishnaIyer) [inline pkg/identityserver/blacklist/builtin.go]: `tls`

File: pkg/identityserver/blacklist/builtin.go [hunk 10]
```diff
@@ -15,148 +15,678 @@
...
+	"contactus",
+	"contest",
+	"contribute",
+	"corp",
+	"create",
+	"css",
 	"customers",
+	"dashboard",
+	"data",
+	"db",
```
Comment (johanstokking) [inline pkg/identityserver/blacklist/builtin.go]: Won't pass length check

File: pkg/identityserver/blacklist/builtin.go [hunk 11]
```diff
@@ -15,148 +15,678 @@
...
+	"editor",
+	"editors",
+	"edu",
+	"education",
+	"email",
+	"employment",
+	"empty",
+	"end",
+	"end_device",
+	"end_devices",
```
Comment (johanstokking) [inline pkg/identityserver/blacklist/builtin.go]: Underscores not relevant; change to dashes

File: pkg/identityserver/blacklist/builtin.go [hunk 12]
```diff
@@ -15,148 +15,687 @@
...
+	"xfn",
+	"xml",
+	"xmpp",
+	"xpg",
+	"xxx",
+	"yaml",
+	"year",
+	"yml",
+	"you",
+	"yourdomain",
```
Comment (johanstokking) [inline pkg/identityserver/blacklist/builtin.go]: Also add `yourapp`, `yourapplication`, `yourdevice`, `yourorganization`

(for use in examples)

File: pkg/identityserver/blacklist/builtin.go [hunk 13]
```diff
@@ -15,148 +15,687 @@
...
+	"test",
+	"test1",
+	"test2",
+	"test3",
+	"teste",
+	"testing",
+	"tests",
+	"theme",
+	"themes",
+	"thethings",
```
Comment (johanstokking) [inline pkg/identityserver/blacklist/builtin.go]: `thethingsnetwork`
`thethingsindustries`
`thethingsproducts`

(also dashes variants)

File: pkg/identityserver/blacklist/builtin.go [hunk 14]
```diff
@@ -15,148 +15,687 @@
...
+	"ga",
+	"gadget",
+	"gadgets",
+	"game",
+	"games",
 	"gateway",
+	"gatewayagent",
 	"gateways",
+	"gatewayserver",
+	"get",
```
Comment (johanstokking) [inline pkg/identityserver/blacklist/builtin.go]: `genericnode`
`generic-node`

File: pkg/identityserver/blacklist/builtin.go (hunk 12 above)
Comment (htdvisser) [reply pkg/identityserver/blacklist/builtin.go]: Also with `your-`...

And then probably also with `example` prefix instead of `your`

File: pkg/identityserver/blacklist/builtin.go [hunk 15]
```diff
@@ -15,148 +15,687 @@
...
+	"ftp",
+	"ga",
+	"gadget",
+	"gadgets",
+	"game",
+	"games",
 	"gateway",
+	"gatewayagent",
 	"gateways",
+	"gatewayserver",
```
Comment (adriansmares) [inline pkg/identityserver/blacklist/builtin.go]: "gcs", "gatewayconfigurationserver", "gateway-configuration-server"

File: pkg/identityserver/blacklist/builtin.go (hunk 13 above)
Comment (adriansmares) [inline pkg/identityserver/blacklist/builtin.go]: "thethingsgateway", "the-things-gateway"

**Comment by bafonins** [comment]
> We don't need to add things with one or two characters as they won't pass length check
Then will remove all ttn related entries like `ns`, `as`, etc

File: pkg/identityserver/blacklist/builtin.go (hunk 15 above)
Comment (adriansmares) [reply pkg/identityserver/blacklist/builtin.go]: And also "gatewayconfserver"
