### PR TITLE
Fix cli version caching issues

### LINKED ISSUE #5735: New patch version available 3.21.1
### Summary

Running ttn-lw-cli version 3.21.1 for the commands tried I get 

`INFO New patch version available {"current": "3.21.0", "docs_url": "https://www.thethingsindustries.com/docs/getting-started/upgrading/", "latest": "3.21.1"}`

### Steps to Reproduce

1. authenticate by logging in with ttn-lw-cli
2. check the version of ttn-lw-cli
3. execute a command and note output gives an INFO about upgrading to 3.21.1

### Current Result

>ttn-lw-cli version
The Things Network Command-line Interface: ttn-lw-cli
Version:             3.21.1
Build date:          2022-08-24T16:05:59Z
Git commit:          6cf0efd63
Go version:          go1.18.5
OS/Arch:             windows/amd64

Now any command, this is just an example:

```
>echo 40F2BD9E00004B01020827471A8F517ACC133C4750A05974FB70E0E5B02637539B07BE60 | ttn-lw-cli lorawan decode --input-format hex
WARN    No AppSKey provided, skipping application payload decryption
{
  "message": {
    "m_hdr": {
      "m_type": "UNCONFIRMED_UP"
    },
    "mic": "mwe+YA==",
    "mac_payload": {
      "f_hdr": {
        "dev_addr": "009EBDF2",
        "f_ctrl": {},
        "f_cnt": 331
      },
      "f_port": 2,
      "frm_payload": "CCdHGo9ReswTPEdQoFl0+3Dg5bAmN1M="
    }
  }
}
INFO    New patch version available     {"current": "3.21.0", "docs_url": "https://www.thethingsindustries.com/docs/getting-started/upgrading/", "latest": "3.21.1"}
```

### Expected Result

I do not expect to see the INFO inviting me to upgrade to 3.21.1

### Relevant Logs

_No response_

### URL

_No response_

### Deployment

The Things Stack Community Edition

### The Things Stack Version

3.21.1

### Client Name and Version

```shell
The Things Network Command-line Interface: ttn-lw-cli
Version:             3.21.1
Build date:          2022-08-24T16:05:59Z
Git commit:          6cf0efd63
Go version:          go1.18.5
OS/Arch:             windows/amd64
```

### Other Information

_No response_

### Proposed Fix

Looks like a version check should be corrected

### Contributing

- [ ] I can help by doing more research.
- [ ] I can help by implementing a fix after the proposal above is approved.
- [ ] I can help by testing the fix before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

### PR DESCRIPTION
**Pull request by happyRip**
#### Summary

Closes #5735 

#### Changes

- Check if cached version matches current version

#### Testing

Tested locally:
1. checkout `v3.21` → new version `v3.22.0` available
1. checkout `v3.22` → new version `v3.22.0` available
1. checkout `v3.21` → new version `v3.22.0` available
1. checkout `fix/5735-version-caching` → no new version warn

##### Regressions

n/a

#### Notes for Reviewers

Version check times out if `versionCheckTimeout` stays at **500ms**, increasing to **1000ms** gives enough time, but might be not ideal.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: cmd/ttn-lw-cli/commands/root.go [hunk 1]
```diff
@@ -56,7 +56,7 @@ var (
 	inputDecoder io.Decoder
 
 	versionUpdate       chan pkgversion.Update
-	versionCheckTimeout = 500 * time.Millisecond
+	versionCheckTimeout = 1000 * time.Millisecond
```
Comment (adriansmares) [inline cmd/ttn-lw-cli/commands/root.go]: At this point you can just use `time.Second`.

File: cmd/ttn-lw-stack/commands/root.go [hunk 2]
```diff
@@ -46,7 +46,7 @@ var (
 	config = new(Config)
 
 	versionUpdate       chan pkgversion.Update
-	versionCheckTimeout = 500 * time.Millisecond
+	versionCheckTimeout = 1000 * time.Millisecond
```
Comment (adriansmares) [inline cmd/ttn-lw-stack/commands/root.go]: Same as above.

File: pkg/version/remote.go [hunk 3]
```diff
@@ -210,14 +210,16 @@ func saveCheck(result *Update) error {
...
-	cachedCheck, err := cachedCheck()
-	if err == nil && cachedCheck.Timestamp.Add(versionCheckCacheTTL).After(time.Now()) {
-		return cachedCheck.Result, nil
-	}
 	current, err := semver.Parse(strings.TrimPrefix(TTN, "v"))
 	if err != nil {
 		return nil, err
 	}
+	cachedCheck, err := cachedCheck()
+	if err == nil && cachedCheck.Timestamp.Add(versionCheckCacheTTL).After(time.Now()) {
```
Comment (adriansmares) [inline pkg/version/remote.go]: Join the `ifs`.

**Review by adriansmares — APPROVED** [review]
