### PR TITLE
Fail downlink based on GS errors, fix retry logic

### LINKED ISSUE #631: Fail downlink based on GS errors
#### Summary

NS should fail absolute timed downlink that's too late to schedule.

#### Why do we need this?

So that a queued downlink item that can never be scheduled anymore by a GS does not keep halting the downlink flow until the queue is reset.

#### What is already there? What do you see now?

Currently, when you schedule a downlink message with an absolute time in the past or too soon in the future for any GS to schedule, the downlink task fails. However, the downlink item stays first in the queue, so it gets retried and keep failing until the queue is replaced with an item that can be scheduled.

GS now returns an `Aborted` error with error details per downlink path and Rx window that was specified. The error details code can be:

- `ResourceExhausted`: no more resources available, i.e. scheduling conflict
- `FailedPrecondition`: this is not going to work, i.e. too late – this is what should cause failure
- `Unavailable`: try again later, i.e. no clock sync; NS may retry later on this downlink path when there is clock sync (i.e. once there's uplink)
- `Aborted`: try another downlink path, i.e. this gateway doesn't have absolute time

#### What is missing? What do you want to see?

Based on errors returned by GS, NS should decide to fail the downlink and inform AS about that. Basically, when NS sees `FailedPrecondition` on all scheduling attempts, it can fail the downlink.

#### How do you propose to implement this?

NS should decide whether to fail the downlink based on GS error details codes. Suggesting the following;

- If all attempts are either `ResourceExhausted`, `FailedPrecondition`, `Aborted`, fail the downlink
- If any attempt is something else (i.e. `Unavailable`), try again later, like now

#### Can you do this yourself and submit a Pull Request?

If the proposed solution is acceptable for @rvolosatovs, then GS doesn't need a change. I'm open for suggestions that may involve specific GS errors.

### LINKED ISSUE #944: Only schedule ClassBC downlink for class B/C
#### Summary

Only schedule ClassBC downlink for class B/C

#### Why do we need this?

To be compliant with the behavior users expect

#### What is already there? What do you see now?

If zero `class_b_c` is set, the downlink may be scheduled as Class A

#### What is missing? What do you want to see?

If any `class_b_c` is set, the downlink should only be scheduled as Class B/C in Rx2

#### How do you propose to implement this?

Check if `classBC` is set instead of checking individual fields

#### Can you do this yourself and submit a Pull Request?

yes

### PR DESCRIPTION
**Pull request by rvolosatovs**
#### Summary

Closes #631
Closes #944 

#### Changes

- Only retry Class C downlink slots, which can be retried
- Fail downlinks based on GS errors
- Fix unscheduled valid application downlink being removed from the queue, if it is updated

### CODE REVIEW

File: pkg/networkserver/downlink.go [hunk 1]
```diff
@@ -573,17 +571,49 @@ type scheduledDownlink struct {
...
+	gtwErrs := make([]error, 0, len(errs))
+	allGatewayErrors := true
+	for _, gsErr := range errs {
+		ttnGSErr, ok := errors.From(gsErr)
+		if !ok {
+			allGatewayErrors = false
+			continue
+		}
+		for _, d := range ttnGSErr.Details() {
+			gtwErr, ok := d.(error)
```
Comment (johanstokking) [inline pkg/networkserver/downlink.go]: In which case does this cast fail?

Comment (rvolosatovs) [reply pkg/networkserver/downlink.go]: No clue, details are not type checked - they're just `interface{}` (https://github.com/TheThingsNetwork/lorawan-stack/blob/8102bd25586153ce41207714555402277ee84fbd/pkg/errors/details.go#L33-L56), so there are no guarantees on the type. Better safe than sorry.
@htdvisser any comment on how is this supposed to be used?

Comment (johanstokking) [reply pkg/networkserver/downlink.go]: But isn't the details than a `ttnpb` type? Or (also) an `error`?

Comment (rvolosatovs) [reply pkg/networkserver/downlink.go]: According to https://github.com/TheThingsNetwork/lorawan-stack/blob/8102bd25586153ce41207714555402277ee84fbd/pkg/errors/details.go#L47
it's
> Usually structs from ttnpb or google.golang.org/genproto/googleapis/rpc/errdetails.

so there's no guarantee

@htdvisser can we refactor these to use `error` instead of `interface{}`?

Comment (htdvisser) [reply pkg/networkserver/downlink.go]: Error details wraps existing gRPC API. There is absolutely no guarantee that any of these actually implement the `error` interface. The details is just a list of proto messages. When we send errors over gRPC they contain a single `ttnpb.ErrorDetails` that carries ttn-lw-stack specific details of the error like the error namespace and name. This could be extended with gRPC (googleapis) error details such as field violation details, debug info, localized messages, retry info, etc. but I think we'll use our own protos instead.

Considering that `WithDetails` is currently only used in two places in master (and incorrectly by the looks of it) I think it may be better to completely remove the `Details` funcs from the `errors` package until we can actually use it correctly.

Comment (johanstokking) [reply pkg/networkserver/downlink.go]: How would that work? These can come from any valid API implementation, right? I think we need proper type assertion.

My comment is mostly about directly type casting to `error`, which I don't think is going to work, but not sure.

**Comment by htdvisser** [comment]
blocked on #967

**Comment by rvolosatovs** [comment]
The build fails since the changes from #995 are not present, otherwise this is ready for review. Once #995 is merged, I will rebase to fix CI.

**Comment by rvolosatovs** [comment]
unable to merge without @johanstokking approval. @htdvisser can you merge this?
