### PR TITLE
Redirect user when accessToken not found

### LINKED ISSUE #426: Redirect user back to login page when an invalid token is detected
**Summary:** 
The console should make sure the user is being sent back to the login screen once his token has expired or invalidated, as well as clearing all user data. This already happens on initial load, but since the console is a single page app, an invalid token can cause trouble at any point after the initial page load.

**Steps to Reproduce:** 
1. Log into the console
2. Open another console tab
3. Logout in one tab
4. In the other tab, try to perform any action that will trigger an API request (eg. list applications)
5. The requested action will result in an error

**What do you see now?**
The console stopping to work properly

**What do you want to see instead?**
The console redirecting the user back to the login page, once it notices that it can no longer obtain a valid token.

**Environment:**
Browser.

**How do you propose to implement this?**
We currently use the `with-auth.js` wrapper component to check whether the store has a `user` object. If the object is not present, and the tree is wrapped around the `<withAuth />`-component, he/she will be redirected to the login page via react router. We could make use of this logic by clearing the user store, once the token cannot be retrieved anymore.
One issue here would be that the store will still hold all (potentially sensitive) data associated with the user.
Alternatively, we could simply trigger a hard page reload, which would also result in a redirect to the login page, since the console would not be able to get the user data.
Another question to solve is where to make the token check and where to trigger the corresponding redirect/reload logic.

**Can you do this yourself and submit a Pull Request?**
I can do this, once we agreed on a way to go.

cc @bafonins

### PR DESCRIPTION
**Pull request by pgalic96**
#### Summary

Closes #426 

#### Changes

- ~~Add check in `requestLogic` that makes an api request to the token and in case of an error dispatches a `logoutSuccess` action that clears the user store~~
- Add unauthenticated error handling in `createRequestLogic` wrapper
- Updated `isUnauthenticated` error such that it recognizes `401` error (@kschiffer )
- Add additional check in `events.js`where `createRequestLogic` is not used

### CODE REVIEW

**Comment by kschiffer** [comment]
This is not quite what I had in mind. You could simply in the logic middleware, check whether the `process()` throws an error that evaluates to `401 Unauthorized` and then dispatch the logout action. Your approach would redundantly query the token endpoint on every request.

The error returned from the backend in these cases looks like this:
```json
{  
  "code":2,
  "message":"error:pkg/errors/web:http (HTTP error: code=401, message=You are not logged in)",
  "details":[  
    {  
      "@type":"type.googleapis.com/ttn.lorawan.v3.ErrorDetails",
      "namespace":"pkg/errors/web",
      "name":"http",
      "message_format":"HTTP error: {message}",
      "attributes":{  
        "message":"code=401, message=You are not logged in"
      }
    }
  ]
}
```
It's a bit unfortunate that it has the code: 2 (Unknown), and also no `http_code` attribute.

**Comment by kschiffer** [comment]
See my branch [fix/token-invalid-redirect](https://github.com/TheThingsNetwork/lorawan-stack/tree/fix/token-invalid-redirect) for a PoC.

File: pkg/webui/lib/errors/utils.js [hunk 1]
```diff
@@ -117,7 +117,7 @@ export const isPermissionDeniedError = error => (
  * `false` otherwise.
  */
 export const isUnauthenticatedError = error => (
-  grpcStatusCode(error) === 16
+  grpcStatusCode(error) === 16 || (isBackend(error) && error.details[0].attributes.message === 'code=401, message=You are not logged in')
```
Comment (kschiffer) [inline pkg/webui/lib/errors/utils.js]:
```suggestion
  grpcStatusCode(error) === 16 
  || (isBackend(error) && error.details[0].attributes.message === 'code=401, message=You are not logged in')
```
