### PR TITLE
Fix end device wizard values reset 

### LINKED ISSUE #3372: Fix end device wizard values reset
#### Summary

Currently, it is not possible to reset/overwrite most of the fields in the end device wizard.

#### Steps to Reproduce

1. Open the basic settings step
2. Fill in the end device name
3. Go to the next step
4. Go back to the basic settings step
5. Remove the end device name
6. Finish the rest of the wizard steps and submit
7. See that name from (2) is still present in the request payload

#### What do you see now?

Most of the field of the end device wizard cannot be reset

#### What do you want to see instead?

The end device (and the wizard component in general) should use the latest values of each step.

#### Environment

v3.10

#### How do you propose to implement this?

Keep track of values for every step in the wizard

#### How do you propose to test this?

See reproduction steps

#### Can you do this yourself and submit a Pull Request?

yes

### PR DESCRIPTION
**Pull request by bafonins**
#### Summary

Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/3372

#### Changes

- Keep track of values for each step separately.
- Clean up wizard related components.

#### Testing

See reproduction steps in the issue and https://github.com/TheThingsNetwork/lorawan-stack/pull/3065#issuecomment-705144996

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/webui/components/wizard/wizard.js [hunk 1]
```diff
@@ -32,14 +34,19 @@ const reducer = (state, action) => {
         steps: action.steps,
       }
     case GO_TO_STEP:
+      const { snapshots: oldSnapshots, currentStep: oldStep } = state
```
Comment (kschiffer) [inline pkg/webui/components/wizard/wizard.js:37]: It would be good to use some inline commenting to explain the mechanics here. It's not easy to grasp on first glance.

**Review by kschiffer — APPROVED** [review]
