### PR TITLE
Gateway onboarding API keys

### LINKED ISSUE #5767: Gateway onboarding API key creation does not save the API keys
### Summary

The API keys created by the gateway onboarding process (LNS/CUPS) are not actually used - the calls are just awaited.

### Steps to Reproduce

1. Onboard gateway.
2. During onboarding, check 'Require authenticated connection'.
3. Check the API key boxes.

### Current Result

1. The API keys are created, but not returned anywhere:

https://github.com/TheThingsNetwork/lorawan-stack/blob/fb2240493507b6b011f724d77c913b98c2707909/pkg/webui/console/containers/gateway-onboarding-form/index.js#L90-L95

### Expected Result

1. The LNS key needs to be saved as `lbs_lns_secret.value`.
2. The LNS key needs to be made available as a file download. The file contents have to be `Authorization: Bearer {key}\r\n`, and the file should be named `tc.key`.
3. The CUPS key needs to be made available as a file download. The file contents have to be `Authorization: Bearer {key}\r\n`, and the file should be named `cups.key`.

### Relevant Logs

_No response_

### URL

_No response_

### Deployment

The Things Stack Cloud

### The Things Stack Version

4.21.2

### Client Name and Version

_No response_

### Other Information

_No response_

### Proposed Fix

_No response_

### Contributing

- [X] I can help by doing more research.
- [ ] I can help by implementing a fix after the proposal above is approved.
- [X] I can help by testing the fix before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

### PR DESCRIPTION
**Pull request by ryaplots**
#### Summary

Closes #5767

#### Changes

- Add `lbs_lns_secret.value` to form values
- Create modal, that opens after the gateway as been successfully created to download the LNS and CUPS api keys.

Screenshot 2022-09-08 at 12 35 38

#### Testing

e2e and manually

##### Regressions

-

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

File: pkg/webui/console/components/gateway-api-keys-modal/index.js [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+})
+
+const GatewayApiKeysModal = ({ modalVisible, lnsKey, cupsKey, downloadLns, downloadCups }) => (
+  <PortalledModal
+    visible={modalVisible}
+    title={m.modalTitle}
+    approval={false}
+    buttonMessage={m.buttonMessage}
+  >
+    <div className={style.div}>
```
Comment (kschiffer) [inline pkg/webui/console/components/gateway-api-keys-modal/index.js]: 1. `div` is not an appropriate class name for a `div`
2. Instead of wrapping everything, just allow a `className` prop to be passed to the `<PortalledModal />`/`<Modal />`

File: pkg/webui/console/components/gateway-api-keys-modal/index.js [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+        <div className={style.row}>
+          <Message component="h4" content={m.cupsKey} />
+          <Button
+            type="button"
+            message={m.downloadButton}
+            onClick={downloadCups}
+            icon="file_download"
+          />
+        </div>
+      )}
```
Comment (kschiffer) [inline pkg/webui/console/components/gateway-api-keys-modal/index.js]:
```suggestion
  <ButtonGroup>
      {lnsKey && (
          <Button
            type="button"
            message={m.downloadButton}
            onClick={downloadLns}
            icon="file_download"
          />
      )}
      {cupsKey && (
          <Button
            type="button"
            message={m.downloadButton}
            onClick={downloadCups}
            icon="file_download"
          />
      )}
  </ButtonGroup>
```
Use `Download LNS key` and `Download CUPS key` as button titles.

File: pkg/webui/console/components/gateway-api-keys-modal/index.js [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+
+import style from './gateway-api-key-modal.styl'
+
+const m = defineMessages({
+  modalTitle: 'Gateway API keys',
+  buttonMessage: 'Go to gateway',
+  grantedRights: 'Granted rights',
+  description: `<b>Your Gateway has been created successfully.</b>{lineBreak}Below are the API keys.{lineBreak}
+  Note: After proceeding to the gateway, the API keys will not be accessible for download anymore.
+  Make sure to download and store them.`,
```
Comment (kschiffer) [inline pkg/webui/console/components/gateway-api-keys-modal/index.js]:
```suggestion
  description: `Your Gateway and API keys have been created successfully.`
```

Move this line `Note: After proceeding to the gateway, the API keys will not be accessible for download anymore. Make sure to download and store them.` after the buttons.

File: pkg/webui/console/components/gateway-api-keys-modal/index.js [hunk 4]
```diff
@@ -0,0 +1,92 @@
...
+import Button from '@ttn-lw/components/button'
+
+import Message from '@ttn-lw/lib/components/message'
+
+import PropTypes from '@ttn-lw/lib/prop-types'
+
+import style from './gateway-api-key-modal.styl'
+
+const m = defineMessages({
+  modalTitle: 'Gateway API keys',
```
Comment (kschiffer) [inline pkg/webui/console/components/gateway-api-keys-modal/index.js]:
```suggestion
  modalTitle: 'Download gateway API keys',
```

File: pkg/webui/console/components/gateway-api-keys-modal/index.js [hunk 5]
```diff
@@ -0,0 +1,92 @@
...
+  buttonMessage: 'Go to gateway',
```
Comment (kschiffer) [inline pkg/webui/console/components/gateway-api-keys-modal/index.js]:
```suggestion
  buttonMessage: 'I have downloaded the keys',
```

File: pkg/webui/console/components/gateway-api-keys-modal/index.js [hunk 6]
```diff
@@ -0,0 +1,92 @@
...
+  grantedRights: 'Granted rights',
```
Comment (kschiffer) [inline pkg/webui/console/components/gateway-api-keys-modal/index.js]:
```suggestion
```
This is not used.

File: pkg/webui/console/components/gateway-api-keys-modal/index.js [hunk 7]
```diff
@@ -0,0 +1,92 @@
...
+  description: `<b>Your Gateway has been created successfully.</b>{lineBreak}Below are the API keys.{lineBreak}
+  Note: After proceeding to the gateway, the API keys will not be accessible for download anymore.
+  Make sure to download and store them.`,
+  lnsKey: 'LNS key:',
+  downloadButton: 'Download',
+  cupsKey: 'CUPS key:',
```
Comment (kschiffer) [inline pkg/webui/console/components/gateway-api-keys-modal/index.js]:
```suggestion
```
You can remove these with my other comment below.

File: pkg/webui/console/components/gateway-api-keys-modal/index.js [hunk 8]
```diff
@@ -0,0 +1,92 @@
...
+  <PortalledModal
+    visible={modalVisible}
+    title={m.modalTitle}
+    approval={false}
+    buttonMessage={m.buttonMessage}
+  >
+    <div className={style.div}>
+      <Message
+        content={m.description}
+        values={{ b: str => <b>{str}</b>, lineBreak: <br /> }}
```
Comment (kschiffer) [inline pkg/webui/console/components/gateway-api-keys-modal/index.js]:
```suggestion
```
See my suggestion about changing the description message.

File: pkg/webui/console/containers/gateway-onboarding-form/index.js [hunk 9]
```diff
@@ -86,37 +92,64 @@ const GatewayOnboardingForm = props => {
...
+          const generatedCupsKey = await generateCUPSApiKey(gatewayId)
+          setCupsKey(generatedCupsKey)
         }
         if (_create_api_key_lns) {
-          await generateLNSApiKey(gatewayId)
+          const generatedLnsKey = await generateLNSApiKey(gatewayId)
+          cleanValues.lbs_lns_secret = { value: generatedLnsKey }
+          setLnsKey(generatedLnsKey)
         }
+        await dispatch(attachPromise(createGateway(ownerId, cleanValues, isUserOwner)))
```
Comment (kschiffer) [inline pkg/webui/console/containers/gateway-onboarding-form/index.js]: You cannot create the gateway last. This will make the API key requests fail because the gateway does not exist yet.

File: pkg/webui/console/containers/gateway-onboarding-form/index.js [hunk 10]
```diff
@@ -86,37 +92,64 @@ const GatewayOnboardingForm = props => {
...
         onSuccess(gatewayId)
+        setModalVisible(cupsKey || lnsKey)
```
Comment (kschiffer) [inline pkg/webui/console/containers/gateway-onboarding-form/index.js]: If you call `onSuccess(gatewayId)` here, then the site will already redirect and the modal will not be shown. You have to defer the success handler to after the modal has been resolved (that is, only when the modal is shown).

**Review by kschiffer — CHANGES_REQUESTED** [review]

File: pkg/webui/console/containers/gateway-onboarding-form/index.js [hunk 11]
```diff
@@ -84,39 +91,70 @@ const GatewayOnboardingForm = props => {
...
-      error={error}
-      onSubmit={handleSubmit}
-      initialValues={initialValues}
-      hiddenFields={['gateway_server_address', 'enforce_duty_cycle', 'schedule_anytime_delay']}
-      validationSchema={validationSchema}
-      validateAgainstCleanedValues
-    >
-      <GatewayProvisioningFormSection userId={userId} />
-    </Form>
+    <React.Fragment>
```
Comment (mjamescompton) [inline pkg/webui/console/containers/gateway-onboarding-form/index.js]: Use `<></>` instead of `<React.Fragment>`

File: pkg/webui/console/containers/gateway-onboarding-form/index.js [hunk 12]
```diff
@@ -84,39 +91,70 @@ const GatewayOnboardingForm = props => {
...
+      <GatewayApiKeysModal
```
Comment (mjamescompton) [inline pkg/webui/console/containers/gateway-onboarding-form/index.js:143]: Cancel and I have downloaded both send us to onSucess. Just remove the cancel button from the model

**Review by mjamescompton — CHANGES_REQUESTED** [review]

**Comment by mjamescompton** [comment]
@ryaplots @kschiffer Could we extend this component to include multiple api keys?

pkg/webui/console/components/api-key-modal/index.js

**Comment by kschiffer** [comment]
I think this is somewhat of a special case where you actually need to download the API keys as a file, hence I believe making a small one-off custom modal is OK here.

@ryaplots please also add a small e2e for this as well and please also take care that this gets properly merged into enterprise. Thanks!

File: pkg/webui/console/containers/gateway-onboarding-form/index.js (hunk 12 above)
Comment (ryaplots) [reply pkg/webui/console/containers/gateway-onboarding-form/index.js:143]: Could you clarify this comment?

File: pkg/webui/console/components/gateway-api-keys-modal/index.js [hunk 13]
```diff
@@ -0,0 +1,89 @@
...
+
+import PropTypes from '@ttn-lw/lib/prop-types'
+
+import style from './gateway-api-key-modal.styl'
+
+const m = defineMessages({
+  modalTitle: 'Download gateway API keys',
+  buttonMessage: 'I have downloaded the keys',
+  description:
+    'Note: After proceeding to the gateway, the API keys will not be accessible for download anymore. Make sure to download and store them.',
```
Comment (kschiffer) [inline pkg/webui/console/components/gateway-api-keys-modal/index.js]:
```suggestion
    'Note: After closing this window, these API keys will not be accessible for download anymore. Please make sure to download and store them now.',
```

Sorry but have to reword this a bit more.

File: pkg/webui/console/components/gateway-api-keys-modal/index.js [hunk 14]
```diff
@@ -0,0 +1,89 @@
...
+    )}
+    {cupsKey && (
+      <Button
+        className={style.downloadButton}
+        type="button"
+        message={m.downloadCups}
+        onClick={downloadCups}
+        icon="file_download"
+      />
+    )}
```
Comment (kschiffer) [inline pkg/webui/console/components/gateway-api-keys-modal/index.js]:
```suggestion
    <ButtonGroup>
    {lnsKey && (
      <Button
        className={style.downloadButton}
        type="button"
        message={m.downloadLns}
        onClick={downloadLns}
        icon="file_download"
      />
    )}
    {cupsKey && (
      <Button
        className={style.downloadButton}
        type="button"
        message={m.downloadCups}
        onClick={downloadCups}
        icon="file_download"
      />
    )}
    </ButtonGroup>
```

File: pkg/webui/console/components/gateway-api-keys-modal/gateway-api-key-modal.styl [hunk 15]
```diff
@@ -0,0 +1,24 @@
...
+
+.gateway-api-key-modal
+    display: flex
+    flex-direction: column
+    h4
+    margin-top: 0
+
+.download-button
+    width: fit-content
+    margin-top: 1rem
```
Comment (kschiffer) [inline pkg/webui/console/components/gateway-api-keys-modal/gateway-api-key-modal.styl]:
```suggestion
```

File: pkg/webui/console/components/gateway-api-keys-modal/index.js [hunk 16]
```diff
@@ -0,0 +1,89 @@
...
+const GatewayApiKeysModal = ({
+  modalVisible,
+  modalApprove,
+  lnsKey,
+  cupsKey,
+  downloadLns,
+  downloadCups,
+}) => (
+  <PortalledModal
+    className={style.gatewayApiKeyModal}
```
Comment (kschiffer) [inline pkg/webui/console/components/gateway-api-keys-modal/index.js:46]: This class is not being applied here, since it is only applied when using the `message` prop. From what I can see, it is not required anyway.

File: pkg/webui/console/components/gateway-api-keys-modal/gateway-api-key-modal.styl [hunk 17]
```diff
@@ -0,0 +1,24 @@
...
+// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+// See the License for the specific language governing permissions and
+// limitations under the License.
+
+
+.gateway-api-key-modal
+    display: flex
+    flex-direction: column
+    h4
+    margin-top: 0
```
Comment (kschiffer) [inline pkg/webui/console/components/gateway-api-keys-modal/gateway-api-key-modal.styl]: I think you can remove this file altogether.

**Review by kschiffer — CHANGES_REQUESTED** [review]

File: pkg/webui/console/components/gateway-api-keys-modal/index.js (hunk 16 above)
Comment (ryaplots) [reply pkg/webui/console/components/gateway-api-keys-modal/index.js:46]: I think it is being applied after all, because if I remove it he styling gets all messed up:

Screenshot 2022-09-08 at 12 34 43

Comment (kschiffer) [reply pkg/webui/console/components/gateway-api-keys-modal/index.js:46]: Oh ok, sorry about that then.

**Review by kschiffer — APPROVED** [review]

**Review by mjamescompton — APPROVED** [review]
